### ISSUE TITLE
DNS fails for .local files when aiodns is also installed

### ISSUE THREAD

**Issue by ColinRobbins** [aio-libs/aiohttp#10111]
### Describe the bug

Home Assistant uses aiohttp with aiodns.
The HA Overkiz integration has stopped working in 2024.11.
The issue has been logged in HA https://github.com/home-assistant/core/issues/132318 and traced to the use of aiodns.

The library https://github.com/iMicknl/python-overkiz-api has a test script.   
The test works fine when aiodns is not installed, but fails when aiodsn is installed.

The URL that fails to resolve is https://gateway-0403-xxxx-7195.local:8443.

If I downgrade to aiohttp version 3.10.3 the DNS resolution work as expected.

### To Reproduce

Run the Overkiz integration in HA, with a local server.

### Expected behavior

The DNS name should resolve correctly.

### Logs/tracebacks

```python-traceback
See  https://github.com/home-assistant/core/issues/132318
```

### Python Version

```console
$ python --version
3.12

Issue also occurs with 3.13.
```

### aiohttp Version

```console
$ python -m pip show aiohttp
3.11.9
```

### multidict Version

```console
$ python -m pip show multidict
6.1.0
```

### propcache Version

```console
$ python -m pip show propcache
0.2.0
```

### yarl Version

```console
$ python -m pip show yarl
1.18.0
```

### OS

Ubunto Linux

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by bdraco** [comment]
HA has used `aiodns` way before 2024.11  

I don't think thats the cause.

**Comment by ColinRobbins** [comment]
But the evndence suggests it is a change in how aiohttp works with it in some way.
It all works fine with 3.10.3, but breaks with 3.11.9

**Comment by Dreamsorcerer** [comment]
I think we started using aiohappyeyeballs in 3.11, so more likely that's the change which makes the difference. Not sure how that plays with aiodns.

**Comment by ColinRobbins** [comment]
I'm not familiar with these packages.   
Are there any local tests I can do try and narrow down the issue?

**Comment by bdraco** [comment]
> I think we started using aiohappyeyeballs in 3.11, so more likely that's the change which makes the difference. Not sure how that plays with aiodns.

aiohappyeyeballs was 3.10 so I don't think that is related

**Comment by bdraco** [comment]
> But the evidence suggests it is a change in how aiohttp works with it in some way. It all works fine with 3.10.3, but breaks with 3.11.9

That's helpful to narrow the window, but , but its really not enough to go on to figure out whats going wrong. 

We need some sample code (ie small reproducer) that is expected to work but now fails.

**Comment by ColinRobbins** [comment]
Here is some code that will reproduce the error without the need for any local hardware.

```
mport asyncio
import time
import aiohttp

from pyoverkiz.client import OverkizClient
from pyoverkiz.const import SUPPORTED_SERVERS, OverkizServer
from pyoverkiz.enums import Server

LOCAL_GATEWAY = "gateway-0403-XXXX-7195.local" # or use the IP address of your gateway

async def main() -> None:
    token = "" # you can set the token here for testing purposes, to re-use an earlier generated token

    # Local Connection
    session = aiohttp.ClientSession(
        connector=aiohttp.TCPConnector(verify_ssl=True))

    async with OverkizClient(
        username="", password="", token=token, session=session, verify_ssl=True, server=OverkizServer(
            name="Somfy TaHoma (local)",
            endpoint=f"https://{LOCAL_GATEWAY}:8443/enduser-mobile-web/1/enduserAPI/",
            manufacturer="Somfy",
            configuration_url=None,
        )
    ) as client:
        await client.login()

asyncio.run(main())
```

If you run this WITH the aiodns package installed, you get the error...
```
iohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host gateway-0403-xxxx-7195.local:8443 ssl:<ssl.SSLContext object at 0x7961589a1b50> [Could not contact DNS servers]
```
which in an exact reproduction of the error in HA / pyoverkiz test code.

if you run this WITHOUT the aiodns package installed, you get the error...
```
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host gateway-0403-xxxx-7195.local:8443 ssl:<ssl.SSLContext object at 0x71b65b1d88d0> [Name or service not known]
```
This is "good" in the test sense as the DNS call is attempting a lookup and failing.

**Comment by bdraco** [comment]
We need a minimal reproducer that doesn't use any external libraries. It should only use aiohttp.

**Comment by bdraco** [comment]
Also you mentioned downgrading to 3.10.3 solves the problem. Its unclear if you mean that 3.10.4 is where the problem was introduced. It would be helpful to know the first version that you can reproduce the problem with.

**Comment by ColinRobbins** [comment]
Here is some code without the library dependency...
```import asyncio
import time
import aiohttp

LOCAL_GATEWAY = "gateway-0403-5459-7195.local" 

async def main() -> None:
    token = "" # you can set the token here for testing purposes, to re-use an earlier generated token

    # Local Connection
    session = aiohttp.ClientSession(
        connector=aiohttp.TCPConnector(verify_ssl=True))

    async with session.post(
        f"https://{LOCAL_GATEWAY}:8443/xx/",
        data="",
        headers="",
        ssl=False,
    ) as response:
        print ("Made it")

asyncio.run(main())
```
This generates the error...
```
Traceback (most recent call last):
  File "/home/colin/github/python-overkiz-api/venv/lib/python3.12/site-packages/aiohttp/resolver.py", line 103, in resolve
    resp = await self._resolver.getaddrinfo(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aiodns.error.DNSError: (11, 'Could not contact DNS servers')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/colin/github/python-overkiz-api/venv/lib/python3.12/site-packages/aiohttp/connector.py", line 1348, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/github/python-overkiz-api/venv/lib/python3.12/site-packages/aiohttp/connector.py", line 989, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/github/python-overkiz-api/venv/lib/python3.12/site-packages/aiohttp/connector.py", line 1020, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/github/python-overkiz-api/venv/lib/python3.12/site-packages/aiohttp/resolver.py", line 112, in resolve
    raise OSError(None, msg) from exc
OSError: [Errno None] Could not contact DNS servers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/colin/github/python-overkiz-api/aiotest.py", line 22, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/colin/github/python-overkiz-api/aiotest.py", line 14, in main
    async with session.post(
  File "/home/colin/github/python-overkiz-api/venv/lib/python3.12/site-packages/aiohttp/client.py", line 1423, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/home/colin/github/python-overkiz-api/venv/lib/python3.12/site-packages/aiohttp/client.py", line 701, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/github/python-overkiz-api/venv/lib/python3.12/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/github/python-overkiz-api/venv/lib/python3.12/site-packages/aiohttp/connector.py", line 1052, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colin/github/python-overkiz-api/venv/lib/python3.12/site-packages/aiohttp/connector.py", line 1354, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host gateway-0403-5459-7195.local:8443 ssl:False [Could not contact DNS servers]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x70fae729b650>

```
Under 3.10 the DNS all resolves fine, and it makes contact with the host
Under 3.11.9 without aiodns, it all works fine and makes contact with the host
Under 3.11.9 with aiodns I get the error above

In terms of test code, I sadly don't have a way I can find of simulating the server.

I tried running a noddy server on my local machine using ncat...
```
while true ; do ncat -v -l -p 8443 -c 'echo "HTTP/1.1 200 OK\n\n $(date)"'; done
```
and then change the test code to
```
LOCAL_GATEWAY = "xxx.local" 
```
then it works as expected.

So it seems to me that the call from aiodns to `getaddrinfo` is getting an unexpected response, and logging it as a DNS error.   Its not clear if it is trying to contact the server or not.

I don't know enough about getaddinfo to progress any further.

**Comment by bdraco** [comment]
> Under 3.10 the DNS all resolves fine, and it makes contact with the host

Would you please clarify if [3.10.10](https://github.com/aio-libs/aiohttp/releases/tag/v3.10.10) works as expected?

I'm guessing the problem was introduced in 3.11.x based on your comments but I'm not clear if 3.10.3 is the only working version in 3.10.x or not.

**Comment by ColinRobbins** [comment]
Good point.   I've cycled through multiple combinations of aiohttp and aiodns verisons.

The aiohttp version does NOT seem to matter after all - I should have tried that earlier.  Sorry

The error occurs when upgrading from aiodns 3.1.0 to 3.2.0, irrespective of the aiohttp version.

**Comment by ColinRobbins** [comment]
I note aiodns 3.2 added support for `getaddrinfo`, and its `getaddrinfo` that is failing.
I'll raise an issue in aiodsn.

**Comment by bdraco** [comment]
There isn't anything significant changed that would affect resolution between 3.1.0 and 3.2.0 https://github.com/aio-libs/aiodns/compare/v3.1.0...v3.2.0 as it mostly adds some new methods.

Does the installed version of [`pycares`](https://github.com/saghul/pycares) or [`c-areas` ](https://c-ares.org/) affect the ability to reproduce the issue?

**Comment by bdraco** [comment]
I just tried the following and was able to get an mdns `.local` name to resolve in a Home Assistant container with `aiodns`

```
homeassistant:/config/issue_10111# cat dns_test.py 
import aiodns
import asyncio
import socket


async def main():
    resolver = aiodns.DNSResolver()
    try:
        result = await resolver.query("drivewaygate.local.", "A")
        print(result)
    except aiodns.error.DNSError as e:
        print(e)
    try:
        result = await resolver.gethostbyname("drivewaygate.local.", socket.AF_INET)
        print(result)
    except aiodns.error.DNSError as e:
        print(e)
    try:
        result = await resolver.getaddrinfo("drivewaygate.local.", 0, socket.AF_INET)
        print(result)
    except aiodns.error.DNSError as e:
        print(e)


asyncio.run(main())
homeassistant:/config/issue_10111# python3 dns_test.py 
[<ares_query_a_result> host=192.168.212.44, ttl=60]
<ares_host_result> name=drivewaygate.local, aliases=[], addresses=['192.168.212.44']
<ares_addrinfo_result> cnames=[], nodes=[<ares_addrinfo_node_result> ttl=60, flags=0, family=2, socktype=0, protocol=0, addr=(b'192.168.212.44', 2)]
```

```
homeassistant:/config/issue_10111# pip3 show aiodns
Name: aiodns
Version: 3.2.0
Summary: Simple DNS resolver for asyncio
Home-page: https://github.com/saghul/aiodns
Author: Saúl Ibarra Corretgé
Author-email: s@saghul.net
License: MIT
Location: /usr/local/lib/python3.13/site-packages
Requires: pycares
Required-by: aiodiscover, easyenergy, forecast-solar, homeassistant, pyjvcprojector, radios, slixmpp, vulcan-api
homeassistant:/config/issue_10111# pip3 show pycares
Name: pycares
Version: 4.5.0
Summary: Python interface for c-ares
Home-page: http://github.com/saghul/pycares
Author: Saúl Ibarra Corretgé
Author-email: s@saghul.net
License: MIT
Location: /usr/local/lib/python3.13/site-packages
Requires: cffi
Required-by: aiodns
```

**Comment by ColinRobbins** [comment]
> There isn't anything significant changed that would affect resolution between 3.1.0 and 3.2.0 [aio-libs/aiodns@v3.1.0...v3.2.0](https://github.com/aio-libs/aiodns/compare/v3.1.0...v3.2.0) as it mostly adds some new methods.

The aiodns release note says added support for `getaddrinfo`, and its `getaddrinfo` that is failing!   That seems significant.

I've spent all day on this, and need to take a break now, I can investigate [pycares](https://github.com/saghul/pycares) or [c-areas](https://c-ares.org/) another day if the change to `getaddrinfo` can be ruled out.

**Comment by ColinRobbins** [comment]
As per my report above, it also worked for me with a simple ncat  server running on xxx.local as well.
However, when connecting to gateway-0403-XXXX-7195.local  the getaddrinfo is failing under aiodns 3.2, but OK on 3.1.

Its not clear to me what getaddrinfo does.   Is it actually contacting the host - is the response in someway unexpected?

**Comment by bdraco** [comment]
I'm also able to resolve an mdns .local name using the aiohttp `AsyncResolver`. Example below:

```
homeassistant:/config/issue_10111# python3 aiohttp_dns_test.py 
[{'hostname': 'drivewaygate.local.', 'host': '192.168.212.44', 'port': 80, 'family': <AddressFamily.AF_INET: 2>, 'proto': 0, 'flags': <AddressInfo.AI_NUMERICHOST|AI_NUMERICSERV: 1028>}]
homeassistant:/config/issue_10111# cat aiohttp_dns_test.py 
from aiohttp import AsyncResolver
import asyncio


async def aiohttp_test():
    resolver = AsyncResolver()
    host = await resolver.resolve('drivewaygate.local.', 80)
    print(host)

asyncio.run(aiohttp_test())

homeassistant:/config/issue_10111# python3 aiohttp_dns_test.py 
[{'hostname': 'drivewaygate.local.', 'host': '192.168.212.44', 'port': 80, 'family': <AddressFamily.AF_INET: 2>, 'proto': 0, 'flags': <AddressInfo.AI_NUMERICHOST|AI_NUMERICSERV: 1028>}]
homeassistant:/config/issue_10111# pip3 show aiohttp
Name: aiohttp
Version: 3.11.10.dev0
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache-2.0
Location: /usr/local/lib/python3.13/site-packages
Requires: aiohappyeyeballs, aiosignal, attrs, frozenlist, multidict, propcache, yarl
Required-by: accuweather, adax, Adax-local, adguardhome, advantage-air, AEMET-OpenData, afsapi, agent-py, aio-geojson-geonetnz-quakes, aio-geojson-geonetnz-volcano, aio-geojson-nsw-rfs-incidents, aio-geojson-usgs-earthquakes, aio-georss-client, aio_geojson_client, aio_geojson_generic_client, aioairq, aioairzone, aioairzone-cloud, aioambient, aioaquacell, aioaseko, aioautomower, aioazuredevops, aiobotocore, aiocomelit, aiodukeenergy, aioeafm, aioeagle, aioecowitt, aioelectricitymaps, aioemonitor, aioflo, aiogithubapi, aioguardian, aioharmony, aiohasupervisor, aiohttp-cors, aiohttp-fast-zlib, aiohttp-retry, aiohttp-sse-client2, aiohttp_socks, aiohue, aiolivisi, aiolookin, aiolyric, aiomealie, aiomodernforms, aiomusiccast, aionanoleaf, aionotion, aiooncue, aioopenexchangerates, aiopegelonline, aiopurpleair, aiopvapi, aiopvpc, aiopyarr, aioqsw, aiorecollect, aioresponses, aioridwell, aioruckus, aioshelly, aioskybell, aioslimproto, aiosolaredge, AIOSomecomfort, aiosteamist, aiostreammagic, aioswitcher, aiosyncthing, aiotankerkoenig, aiotedee, aiotractive, aiounifi, aiovodafone, aiowaqi, aiowatttime, aiowithings, aioymaps, airgradient, airly, airthings_cloud, alpha-vantage, anova-wifi, apple_weatherkit, apsystems-ez1, asmog, async_upnp_client, asyncarve, asyncpysupla, asyncsleepiq, autarco, authcaptureproxy, ayla_iot_unofficial, blebox_uniapi, blinkpy, bond-async, bring-api, brunt, connect_box, crownstone-cloud, crownstone-sse, deebot-client, demetriek, devialet, dio-chacon-wifi-api, directv, DoorBirdPy, easyenergy, electrickiwi-api, elgato, eliqonline, elvia, emulated-roku, energyzero, enturclient, env_canada, epson-projector, esphome-dashboard-api, eternalegypt, evohome-async, faadelays, firebase-messaging, fivem-api, foobot-async, forecast-solar, freebox-api, freenub, fyta_cli, gcal_sync, geniushub-client, geocachingapi, gios, go2rtc-client, goalzero, google_nest_sdm, google_photos_library_api, goslide-api, gotailwind, greeneye-monitor, gridnet, hass-nabucasa, here_routing, here_transit, hko, hole, homeassistant, homematicip, imgw_pib, incomfort-client, intellifire4py, jsonrpc-async, jsonrpc-websocket, kaiterra-async-client, knocki, konnected, lacrosse_view, laundrify-aio, linear-garage-door, london-tube-status, loqedAPI, mac-vendor-lookup, matrix-nio, mbddns, meater-python, microBeesPy, mill-local, millheater, moehlenhoff-alpha2, monarchmoney, monzopy, motioneye-client, mozart_api, music_assistant_client, mutesync, mypermobil, myuplink, nettigo_air_monitor, nexia, nextcord, nextdns, nice-go, nyt_games, odp-amsterdam, omnilogic, open-garage, open-meteo, opensensemap-api, openwebifpy, opower, ourgroceries, ovoenergy, p1monitor, panasonic-viera, peco, plexauth, plexwebsocket, plugwise, poolsense, ProgettiHWSW, pvo, py-aosmith, py-ccm15, py-melissa-climate, py-synologydsm-api, py_nightscout, pyaftership, pyairnow, pyairvisual, pyasuswrt, pyatag, pyatmo, pyatv, pyaussiebb, pyblu, pybravia, pycfdns, pyControl4, pydaikin, pydeconz, pydelijn, pydrawise, pydroid-ipcam, pyebox, pyeconet, pyefergy, pyElectra, pyemoncms, pyeverlights, pyevilgenius, pyfido, pyforked-daapd, PyFronius, pygti, pyhaversion, pyhiveapi, pyinsteon, pyintesishome, pyipma, pyipp, pyiqvia, pyiskra, pyisy, pykaleidescape, pykmtronic, pykodi, pykoplenti, pylaunches, pylibrespot-java, pylitterbot, PyLoadAPI, pymelcloud, PyMetEireann, PyMetno, PyNINA, pynordpool, pynws, pyoctoprintapi, pyopenuv, pyopenweathermap, pyosoenergyapi, pyoverkiz, pypalazzetti, pypoint, pyprosegur, pyps4-2ndscreen, pyrisco, pyrituals, pyrympro, pysabnzbd, pysensibo, pyseventeentrack, pyskyqhub, pysma, pysmartthings, pysmlight, pyspcwebgw, pysqueezebox, pysuezV2, pyswitchbee, PySwitchbot, PySyncThru, pytautulli, python-awair, python-bsblan, python-family-hub-local, python-homeassistant-analytics, python-homewizard-energy, python-izone, python-juicenet, python-kasa, python-matter-server, python-mystrom, python-otbr-api, python-roborock, python-smarttub, python-songpal, python-technove, python_linkplay, python_opendata_transport, python_opensky, pyTibber, pytile, pytomorrowio, pytouchlinesl, pytraccar, pytrafikverket, pyuptimerobot, pyversasense, pyvizio, pyvolumio, pywmspro, pyxeoma, radios, regenmaschine, renault-api, reolink_aio, ring-doorbell, rokuecp, romy, rtsp-to-webrtc, sense_energy, sharkiq, simplefin4py, simplepush, simplisafe-python, sisyphus_control, slackclient, smart_meter_texas, snitun, solarlog_cli, solax, sonos-websocket, spotifyaio, starline, stookwijzer, subarulink, surepy, switchbot_api, systembridgeconnector, tailscale, tesla-wall-connector, tesla_fleet_api, tesla_powerwall, teslajsonpy, teslemetry_stream, thinqconnect, toonapi, tp-connected, tplink_omada_client, ttls, twentemilieu, twitchAPI, uasiren, uiprotect, unifi-discovery, universal-silabs-flasher, vallox_websocket_api, vehicle, volkszaehler, volvooncall, vulcan-api, weatherflow4py, webmin-xmlrpc, whirlpool_sixth_sense, wled, xbox-webapi, xiaomi-ble, yalexs, yolink-api, youtubeaio, zamg, zigpy, zwave-js-server-python
homeassistant:/config/issue_10111# pip3 show aiodns
Name: aiodns
Version: 3.2.0
Summary: Simple DNS resolver for asyncio
Home-page: https://github.com/saghul/aiodns
Author: Saúl Ibarra Corretgé
Author-email: s@saghul.net
License: MIT
Location: /usr/local/lib/python3.13/site-packages
Requires: pycares
Required-by: aiodiscover, easyenergy, forecast-solar, homeassistant, pyjvcprojector, radios, slixmpp, vulcan-api
```

**Comment by bdraco** [comment]
> Its not clear to me what getaddrinfo does. Is it actually contacting the host - is the response in someway unexpected?

`getaddrinfo` is a standard library call for resolving a name

https://en.wikipedia.org/wiki/Getaddrinfo
https://man7.org/linux/man-pages/man3/getaddrinfo.3.html

**Comment by bdraco** [comment]
https://github.com/home-assistant/core/issues/132318#issuecomment-2520192227

```
Traceback (most recent call last):
  File "/home/colin/github/Home-Assistant-Core/venv/lib/python3.12/site-packages/aiohttp/resolver.py", line 103, in resolve
    resp = await self._resolver.getaddrinfo(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aiodns.error.DNSError: (11, 'Could not contact DNS servers')
```

This implies the problem is a local configuration issue.

**Comment by ColinRobbins** [comment]
I agree this implies a DNS issue, but it works fine for aiodns 3.1, and the issue is occuring on two different local computers, including one running an unmodified HA OS.   And there are several people reporting the issue.

**Comment by bdraco** [comment]
If you have aiodns 3.1.0 installed, aiohttp won't use the `AsyncResolver` and will fallback to the `ThreadedResolver` because it will be missing the `getaddrinfo` method it needs. https://github.com/aio-libs/aiohttp/blob/703ce6172f55e959cc7a0c2dd7a4fe7170e0590e/aiohttp/resolver.py#L13

But that doesn't explain why `ThreadedResolver` would work differently since it also uses `getaddrinfo` https://github.com/aio-libs/aiohttp/blob/703ce6172f55e959cc7a0c2dd7a4fe7170e0590e/aiohttp/resolver.py#L36

**Comment by ColinRobbins** [comment]
Is this an mDNS issue? 
The address that is failing is not configured in DNS anywhere, it a server that has announced itself to the network.

**Comment by bdraco** [comment]
> Is this an mDNS issue?

Almost certainly as `.local` domains are almost always going to be mDNS

**Comment by ColinRobbins** [comment]
I don’t really understand the details of mDNS, but doesn’t it reply on getting a response from server - which will be need to be asynchronous in some way.
Is it possible the new threaded approach is not getting these responses, so throwing an error.

**Comment by bdraco** [comment]
> I don’t really understand the details of mDNS, but doesn’t it reply on getting a response from server - which will be need to be asynchronous in some way. Is it possible the new async, as opposed to threaded approach is not getting these responses, so throwing an error.

Can you try the examples I posted above in your Home Assistant container?

https://github.com/aio-libs/aiohttp/issues/10111#issuecomment-2521340185
https://github.com/aio-libs/aiohttp/issues/10111#issuecomment-2521350509

Replace `drivewaygate.local.` with the name you expect to be able to resolve
