### ISSUE TITLE
Client connection raises "EOF occurred in violation of protocol (_ssl.c:600)".

### ISSUE THREAD

**Issue by dpdani** [aio-libs/aiohttp#1046]
## Long story short

Was testing SSL on aiohttp, but client raises exception (server doesn't show error).
## Expected behaviour

The request should run fine without errors and the client should get "Hello World" as response.
## Actual behaviour

While the server is running in another process and no errors seem to be occurring, the client raises an exception while trying to connect.
The server doesn't show any incoming requests.
Also tried to make a request to the server using the `requests` package, but repeats the same behaviour.
The exact same code used without SSL (server doesn't have `--use-https` parameter and client request starting with `'http://...'`) doesn't raise any error and produces expected behaviour.

Exception traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/connector.py", line 607, in _create_connection
    local_addr=self._local_addr)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 643, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 666, in _create_connection_transport
    yield from waiter
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    return self.result()  # May raise too.
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 802, in _on_handshake
    self._sock.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:600)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/connector.py", line 321, in connect
    yield from self._create_connection(req)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/connector.py", line 630, in _create_connection
    (req.host, req.port, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 8] Can not connect to localhost:8080 [EOF occurred in violation of protocol (_ssl.c:600)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "aiohttp_client_study.py", line 40, in <module>
    got = asyncio.get_event_loop().run_until_complete(fetch(session, sys.argv[1]))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "aiohttp_client_study.py", line 13, in fetch
    response = yield from session.get(url)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/client.py", line 527, in __iter__
    resp = yield from self._coro
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/client.py", line 186, in _request
    conn = yield from self._connector.connect(req)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/connector.py", line 331, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 8] Cannot connect to host localhost:8080 ssl:True [Can not connect to localhost:8080 [EOF occurred in violation of protocol (_ssl.c:600)]]
```
### server.py

``` python
import json
import ssl
from asyncio import coroutine
import os
import sys
from aiohttp import web


app = web.Application()


@coroutine
def hello(request):
    print("Request: {}".format(request))
    return web.Response(body=b"Hello World!")

@coroutine
def do_some_json(request):
    print("Request: {}".format(request))
    resp = json.dumps({
        'request': request.host,
        'information': 'spam'
    }).encode('utf-8')
    return web.Response(body=resp)

app.router.add_route('GET', '/', hello)
app.router.add_route('GET', '/asd/', do_some_json)

if '--use-https' in sys.argv:
    sslcontext = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
    sslcontext.verify_mode = ssl.CERT_REQUIRED
    sslcontext.check_hostname = True
    sslcontext.load_verify_locations(os.path.join(os.getcwd(), "certs",
        "comodorsacertificationauthority.crt"))
else:
    sslcontext = None

web.run_app(app, host='localhost', port=8080, ssl_context=sslcontext, shutdown_timeout=10.0)
```
### client.py

``` python
import json
import sys
import asyncio
import aiohttp
import ssl
import os
from pprint import pprint
from asyncio import coroutine


@coroutine
def fetch(session, url):
    response = yield from session.get(url)
    try:
        status = response.status
        text = yield from response.text()
        try:
            text = json.loads(text)
        except: pass
    finally:
        if sys.exc_info()[0] is not None:
            # on exceptions, close the connection altogether
            response.close()
        else:
            yield from response.release()
    return status, text


if sys.argv[1].startswith('https'):
    sslcontext = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
    sslcontext.verify_mode = ssl.CERT_REQUIRED
    sslcontext.check_hostname = True
    sslcontext.load_verify_locations(os.path.join(os.getcwd(), "certs",
        "comodorsacertificationauthority.crt"))
else:
    sslcontext = None
conn = aiohttp.TCPConnector(ssl_context=sslcontext, verify_ssl=True)
with aiohttp.ClientSession(connector=conn) as session:
    got = asyncio.get_event_loop().run_until_complete(fetch(session, sys.argv[1]))
    print("GOT (status = {}): ".format(got[0]))
    pprint(got[1])
```

Run server: `python3 server.py --use-https`
Perform client request: `python3 client.py https://localhost:8080/`
Using `requests` package: `requests.get("https://localhost:8080/", verify="/home/dparmeggiani/tBB/certs/ca.crt")`
## Environment

aiohttp version: `0.22.2`
Python version: `3.4.3`
Running on Ubuntu: `15.04`
OpenSSL version (as return by `ssl.OPENSSL_VERSION`): `OpenSSL 1.0.1f 6 Jan 2014`

**Comment by asvetlov** [comment]
Obviously your server ssl conetext is wrong.
Use [ssl.create_default_context](https://docs.python.org/3/library/ssl.html#ssl.create_default_context) with proper `purpose`for constructing well-formed context.
It's not trivial operation actually.

**Comment by dpdani** [comment]
Here's the code that creates the ssl context now:

``` python
sslcontext = ssl.create_default_context(ssl.Purpose.SERVER_AUTH,
        capath=os.path.join(os.getcwd(), "certs", "comodorsacertificationauthority.crt")
)
```

Now, instead of giving the above exception it results in an handshake failure.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/connector.py", line 607, in _create_connection
    local_addr=self._local_addr)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 643, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 666, in _create_connection_transport
    yield from waiter
  File "/usr/lib/python3.4/asyncio/futures.py", line 386, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 287, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 802, in _on_handshake
    self._sock.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:600)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/connector.py", line 321, in connect
    yield from self._create_connection(req)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/connector.py", line 630, in _create_connection
    (req.host, req.port, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 1] Can not connect to localhost:8080 [[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:600)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "aiohttp_client_study.py", line 42, in <module>
    got = asyncio.get_event_loop().run_until_complete(fetch(session, sys.argv[1]))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 234, in _step
    result = coro.throw(exc)
  File "aiohttp_client_study.py", line 13, in fetch
    response = yield from session.get(url)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/client.py", line 527, in __iter__
    resp = yield from self._coro
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/client.py", line 186, in _request
    conn = yield from self._connector.connect(req)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/connector.py", line 331, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 1] Cannot connect to host localhost:8080 ssl:True [Can not connect to localhost:8080 [[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:600)]]
```

**Comment by asvetlov** [comment]
For server side context it should be `ssl.Purpose.CLIENT_AUTH`!

**Comment by dpdani** [comment]
It is `CLIENT_AUTH` on server side.

**Comment by dpdani** [comment]
@asvetlov Do you have any ideas why the handshake fails?

**Comment by asvetlov** [comment]
It should work.
Maybe I'll find a time for writing a demo/docs for demonstrating how to create ssl contexts properly.
If handshake fails on client side even with `requests` usage -- the problem definitely inside a server ssl context object.

**Comment by dpdani** [comment]
After some online searching, its seems that my self-signed certificate wasn't acceptable for the handshake to happen.
At this point I'm disabling host name checking in the sslcontext, until I can fix the certificates.
Thanks for your time @asvetlov :)

Anyway I have to say that I did get an error while first trying with checking disabled (`Can not connect to localhost:8080 [The operation did not complete (read) (_ssl.c:600)]`). It later disappeared without any code changes. I guess it was a temporary socket reading error.
