### ISSUE TITLE
Heizenbug in test_client_session

### ISSUE THREAD

**Issue by kxepal** [aio-libs/aiohttp#1153]
```
tests/test_client_session.py ................................exception calling callback for <Future at 0x7f59d6fcb198 state=finished returned list>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib64/python3.5/asyncio/futures.py", line 442, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib64/python3.5/asyncio/base_events.py", line 532, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "/usr/lib64/python3.5/asyncio/base_events.py", line 506, in _call_soon
    self._check_closed()
  File "/usr/lib64/python3.5/asyncio/base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed.
```

Could be rarely reproduced for Python 3.5 after dozens runs. I was lucky to hit it with broken travis build, but after several hours to localize it I failed ):

**Comment by asvetlov** [comment]
Perhaps we should add an extra loop iteration before loop closing.

**Comment by kxepal** [comment]
I feel lucky. It's `test_request_ctx_manager_props`. 100% hit.

**Comment by fafhrd91** [comment]
@kxepal is this still the case? i can not reproduce on 3.5.2 with repeat count 1000

**Comment by kxepal** [comment]
Probably too old for now. I'll reopen if I meet it again.
