### ISSUE TITLE
bad certificate error with ssl_verify=False

### ISSUE THREAD

**Issue by AndreLouisCaron** [aio-libs/aiohttp#1158]
I'm trying to use aiohttp to communicate with a Docker daemon, and I'm getting errors when trying to establish the HTTPS connection.  I'm using docker-machine on OSX, so I'm communicating over TCP to the daemon that uses a self-signed certificate.

I'm using the `aiohttp.TCPConnector`'s `verify_ssl=False` option to disable certificate validation.  This is temporary, I intend to validate the certificate eventually.

However, I'm still getting an "sslv3 alert bad certificate" error.

Here is my code:

``` python
# -*- coding: utf-8 -*-


import asyncio
import aiohttp
import collections
import os

from urllib.parse import urljoin


Container = collections.namedtuple('Container', [
    'id_',
    'names',
])

async def main():
    """."""

    # Choose UNIX or TCP, depending on ``DOCKER_HOST``.
    #
    # TODO: supply the certificate (at least for docker-machine)?
    docker_host = os.environ.get('DOCKER_HOST')
    if docker_host:
        connector = aiohttp.TCPConnector(verify_ssl=False)
        base_url = 'https://' + docker_host[6:]
    else:
        connector = aiohttp.UNIXConnector(path='/var/run/docker.sock')
        base_url = 'http://docker'

    # Debug logs.
    print('BASE URL:', base_url)
    print('CONNECTOR:', connector.verify_ssl)

    # Initialize the HTTP client.
    async with aiohttp.ClientSession(connector=connector) as session:
        async with session.get(urljoin(base_url, '/containers/json')) as rep:
            assert rep.status == 200
            listing = rep.json()
        listing = [
            Container(
                id_=container['Id'],
                names=frozenset(container['Names']),
            )
            for container in listing
        ]
        print('LISTING:', listing)


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

Here is the full stack trace: 

```
(py35)$ python stats.py
BASE URL: https://192.168.99.100:2376
CONNECTOR: False
Traceback (most recent call last):
  File ".tox/py35/lib/python3.5/site-packages/aiohttp/connector.py", line 581, in _create_connection
    local_addr=self._local_addr)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 669, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 692, in _create_connection_transport
    yield from waiter
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 385, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 288, in _wakeup
    value = future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/sslproto.py", line 486, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/sslproto.py", line 200, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:646)
```

Is this expected?  Can you share any tips as to how I should proceed?

Thanks!

**Comment by AndreLouisCaron** [comment]
Note that I've also tried setting the `aiohttp.TCPConnector`'s `capath` argument to where `DOCKER_CERT_PATH` points, which triggers a different error:

```
Traceback (most recent call last):
  File ".tox/py35/lib/python3.5/site-packages/aiohttp/connector.py", line 607, in _create_connection
    local_addr=self._local_addr)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 669, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 692, in _create_connection_transport
    yield from waiter
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 385, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 288, in _wakeup
    value = future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/sslproto.py", line 486, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/sslproto.py", line 200, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:646)
```

Any suggestions?

Thanks!

**Comment by asvetlov** [comment]
aiohttp does nothing magical with SSL.
It just uses standard python calls.
Thus if ssl module blames that certificate is wrong -- it's probably true.
Or you construct `ssl.SSLContext` incorrectly.

**Comment by AndreLouisCaron** [comment]
Yes, I'm pretty sure I'm doing something wrong with the `ssl.SSLContext`, but I was hoping you might be able to give me a few pointers.

I'm 100% sure the certificates are fine because they are used successfully by `docker`, `docker-compose` and a separate script that I wrote using [docker-py](https://github.com/docker/docker-py).  I'll take a deeper look into docker-py's source to see if I can figure out how they do it.

However, I would still expect to be able to communicate with the Docker daemon when using `TCPConnector(verify_ssl=False)`, but that doesn't work either (I get the "bad certificate" error).  Is that expected?

**Comment by asvetlov** [comment]
`verify_ssl=False` option disables certification check but still requires a valid ssl protocol support.

**Comment by AndreLouisCaron** [comment]
I don't have a clear issue with `aiohttp` and I was mostly coming to ask for help, so I'll close this.

**Comment by joaomortani** [comment]
Hi, I have same problem with verify_ssl. 

I used verify_ssl but don`t worked. 
`connector = aiohttp.TCPConnector(verify_ssl=False)`

This error : 
`aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
`

Can help me?

**Comment by fafhrd91** [comment]
@joaomortani can you make connection with urllib?

**Comment by joaomortani** [comment]
I i dont use urlib, sorry i`m beginner on python, can you send me one example? 

`connector = aiohttp.TCPConnector(verify_ssl=False)
async with aiohttp.request('POST',
                               url,
                               data=parameters,
                               connector=connector)`


Call: `curl -X POST https://127.0.0.1:5001/auth`

Error:
`File "aiohttp/_http_parser.pyx", line 269, in aiohttp._http_parser.HttpParser.feed_data (aiohttp/_http_parser.c:4257)
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method`

**Comment by fafhrd91** [comment]
does `curl` work?

**Comment by joaomortani** [comment]
No.

**Comment by fafhrd91** [comment]
well, at this point it is not related to python. you need to get proper certificate for server, then you can load it into SSLContect, then you can use this sslcontext with TCPConnector

**Comment by joaomortani** [comment]
I verify if i called HTTP and not HTTPS on curl it work.
`curl -X POST http://127.0.0.1:5001/auth - HTTP` 

Thank for your help.
