### ISSUE TITLE
Error when terminating script

### ISSUE THREAD

**Issue by gabrielgradinaru** [aio-libs/aiohttp#1163]
Error when terminating script with  SystemExit, sys.exit(), exit(), quit()...

To reproduce, run the following code:

``` python
import aiohttp
class SimpleClass:
    def __init__(self):
        self.session = aiohttp.ClientSession()
    def __del__(self):
        self.session.close()
obj = SimpleClass()
raise SystemExit
```

We get the following error:

``` python
Exception ignored in: <bound method SimpleClass.__del__ of <__main__.SimpleClass object at 0x7f2cd303b2b0>>
Traceback (most recent call last):
  File "test.py", line 6, in __del__
  File "/home/gaby/.local/lib/python3.5/site-packages/aiohttp/client.py", line 430, in close
  File "/home/gaby/.local/lib/python3.5/site-packages/aiohttp/connector.py", line 233, in close
AttributeError: 'NoneType' object has no attribute 'create_future'
Exception ignored in: <bound method ClientSession.__del__ of <aiohttp.client.ClientSession object at 0x7f2cd303b358>>
Traceback (most recent call last):
  File "/home/gaby/.local/lib/python3.5/site-packages/aiohttp/client.py", line 84, in __del__
  File "/home/gaby/.local/lib/python3.5/site-packages/aiohttp/client.py", line 430, in close
  File "/home/gaby/.local/lib/python3.5/site-packages/aiohttp/connector.py", line 233, in close
AttributeError: 'NoneType' object has no attribute 'create_future'
```

Environment: python3.5 and aiohttp==0.22.5

**Comment by asvetlov** [comment]
aiohttp depends on asyncio loop.
You shouldn't rely on `__del__` but make graceful shutdown and close the loop after.
Also `ClientSession.close()` is a coroutine, it means the `session.close()` call is not allowed from regular functions but should be used as `await session.close()`.

**Comment by gabrielgradinaru** [comment]
Thank you for your answer.
It seems that is not a real issue and will close it.
