### ISSUE TITLE
Handle all concurrent.futures._base.TimeoutError and throw a aiohttp.errors.TimeoutError instead.

### ISSUE THREAD

**Issue by AraHaan** [aio-libs/aiohttp#1207]
## Long story short

This is better to explain with the full Traceback:

``` py
Ignoring exception caused at _resolve_edit_method_code:
Traceback (most recent call last):
  File "E:\Users\Elsword\Desktop\DecoraterBot\Async\\resources\Dependencies\DecoraterBotCore\Ignore.py", line 630, in resolve_edit_method_code
    yield from DBLogs.send_edit_logs(client, before, after)
  File "E:\Users\Elsword\Desktop\DecoraterBot\Async\\resources\Dependencies\DecoraterBotCore\BotLogs.py", line 523, in send_edit_logs
    yield from self.bot.send_edit_logs_code(client, before, after)
  File "E:\Users\Elsword\Desktop\DecoraterBot\Async\\resources\Dependencies\DecoraterBotCore\BotLogs.py", line 263, in send_edit_logs_code
    yield from client.send_message(discord.Object(id='153055192873566208'), sendeditlogs)
  File "discord\client.py", line 834, in send_message
  File "discord\http.py", line 105, in request
  File "E:\Users\Elsword\Desktop\DecoraterBot\Async\\resources\Dependencies\win32-deps\3.5\aiohttp\client.py", line 555, in __iter__
    resp = yield from self._coro
  File "E:\Users\Elsword\Desktop\DecoraterBot\Async\\resources\Dependencies\win32-deps\3.5\aiohttp\client.py", line 198, in _request
    conn = yield from self._connector.connect(req)
  File "async_timeout\__init__.py", line 44, in __exit__
concurrent.futures._base.TimeoutError
```
## Expected behaviour

To Throw a `aiohttp.errors.TimeoutError` instead of a `concurrent.futures._base.TimeoutError` on
`File "aiohttp\client.py", line 198, in _request
    conn = yield from self._connector.connect(req)`
## Actual behaviour

Line 198 thows a `concurrent.futures._base.TimeoutError` making it hard to handle if you do not want to import `concurrent` just to handle the exceptions from it.
## Steps to reproduce

Something that used to exist but does not anymore so when it tries to connect for x time it throws this.
## Your environment

Windows 7 Ultimate x64
Python 3.5.2 (embedded) (I Insalled aiohttp (latest 1.0.2) with a installed version but use the embedded one because I can 😛)

**Comment by asvetlov** [comment]
Nothing to fix: `asyncio.TimeoutError` and `aiohttp.errors.TimeoutError` are both aliases for `concurrent.futures._base.TimeoutError`.

**Comment by hustshawn** [comment]
So how to solve the issue?

**Comment by asvetlov** [comment]
You should catch `asyncio.TimeoutError`

**Comment by EFF** [comment]
I can confirm on python 3.6 and aiohttp latest, the error doesn't get caught with `except asyncio.TimeoutError` as exception handling ..

**Comment by asvetlov** [comment]
@EFF I don't follow, what error is not caught?
Latest aiohttp has no `aiohttp.errors` module.

**Comment by EFF** [comment]
@asvetlov You're totally right I wasn't on latest. Thanks for the quick answer, sorry for the inconvenience.
