### ISSUE TITLE
Cythonized applications don't work

### ISSUE THREAD

**Issue by s0undt3ch** [aio-libs/aiohttp#1464]
## Long story short

If you cythonize your application it won't work

## Expected behaviour

I expected it to work just as the non compiled version does.

## Actual behaviour

We have _issues_

## Steps to reproduce

Consider the following app code, `/tmp/test.pyx`:
```python
import asyncio
from aiohttp import web


@asyncio.coroutine
def handler(request):
    return web.Response(body=b'OK')


@asyncio.coroutine
def middleware_factory(app, handler):

    @asyncio.coroutine
    def middleware(request):
        resp = yield from handler(request)
        assert 200 == resp.status
        resp.set_status(201)
        resp.text = resp.text + '[MIDDLEWARE]'
        return resp
    return middleware

loop = asyncio.get_event_loop()
app = web.Application(loop=loop)
app.middlewares.append(middleware_factory)
app.router.add_route('GET', '/', handler)
app_handler = app.make_handler()
server = loop.create_server(app_handler, 'localhost', 8080)
loop.run_until_complete(server)
loop.run_forever()
```
When running it under python:
```
$ python /tmp/test.pyx &
$ curl http://localhost:8080 
OK[MIDDLEWARE]
```
When running it under cython:
```
$ python -c 'import os; import pyximport; pyximport.install(); os.chdir("/tmp"); import test_cy' &
$ curl http://localhost:8080
<html>
  <head>
    <title>500 Internal Server Error</title>
  </head>
  <body>
    <h1>500 Internal Server Error</h1>
    Server got itself in trouble
  </body>
</html>
```
And the traceback:
```
Error handling request
Traceback (most recent call last):
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.5.2-features-aiohttp/lib/python3.5/site-packages/aiohttp/server.py", line 265, in start
    yield from self.handle_request(message, payload)
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.5.2-features-aiohttp/lib/python3.5/site-packages/aiohttp/web.py", line 101, in handle_request
    match_info.handler, type(resp), self._middlewares)
AttributeError: 'RequestHandler' object has no attribute '_middlewares'
```

If we use the python +3.5 syntax the same happens.

## Your environment
* Python 3.5.2
* Cython 0.25.1
* aiohttp 1.1.6

**Comment by asvetlov** [comment]
1. aiohttp never supported blind cythonization
2. Why do you want to compile a code which you don't own? Do you use cythonized stdlib? Does it work well?

**Comment by s0undt3ch** [comment]
So, that bad `_middlwares` reference, seems to [fixed](https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/web.py#L253-L258) now.

1. I'm cythonizing my own application which uses non cythonized aiohttp
2. I'm not compiling code which is not mine.

If I locally fix the middlwares reference(although I'm using the latest stable version not the master branch), the traceback is different:
```
Traceback (most recent call last):
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.5.2-features-aiohttp/lib/python3.5/site-packages/aiohttp/server.py", line 265, in start
    yield from self.handle_request(message, payload)
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.5.2-features-aiohttp/lib/python3.5/site-packages/aiohttp/web.py", line 101, in handle_request
    match_info.handler, type(resp), [middleware for middleware in app.middlewares
AssertionError: Handler <function handler at 0x7f0b424cad08> should return response instance, got <class 'generator'> [middlewares [<function middleware_factory at 0x7f0b3d3af598>]]
```

**Comment by asvetlov** [comment]
Try to use `async def`/`await` in your code

**Comment by s0undt3ch** [comment]
Same outcome

**Comment by s0undt3ch** [comment]
Now using aiohttp from master branch
```python
import asyncio
from aiohttp import web


async def handler(request):
    return web.Response(body=b'OK')


async def middleware_factory(app, handler):

    async def middleware(request):
        resp = await handler(request)
        assert 200 == resp.status
        resp.set_status(201)
        resp.text = resp.text + '[MIDDLEWARE]'
        return resp
    return middleware

loop = asyncio.get_event_loop()
app = web.Application(loop=loop)

app.middlewares.append(middleware_factory)
app.router.add_route('GET', '/', handler)
app_handler = app.make_handler()
server = loop.create_server(app_handler, 'localhost', 8080)
loop.run_until_complete(server)
loop.run_forever()
```

```
$ python -c 'import os; import pyximport; pyximport.install(); os.chdir("/tmp"); import test_cy' &
$ curl http://localhost:8080
<html><head><title>500 Internal Server Error</title></head><body><h1>500 Internal Server Error</h1>Server got itself in trouble</body></html>
```

And the traceback:
```
Traceback (most recent call last):
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.5.2-features-aiohttp/lib/python3.5/site-packages/aiohttp/web_server.py", line 61, in handle_request
    resp = yield from self._handler(request)
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.5.2-features-aiohttp/lib/python3.5/site-packages/aiohttp/web.py", line 257, in _handle
    [middleware for middleware in app.middlewares
AssertionError: Handler <function handler at 0x7f7283cebd08> should return response instance, got <class 'generator'> [middlewares [<function middleware_factory at 0x7f727eb95c80>]]
```

**Comment by s0undt3ch** [comment]
Actually, let me update the above traceback(using 3.5 async def/await syntax)(I ran the wrong file above):
```
Traceback (most recent call last):
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.5.2-features-aiohttp/lib/python3.5/site-packages/aiohttp/web_server.py", line 61, in handle_request
    resp = yield from self._handler(request)
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.5.2-features-aiohttp/lib/python3.5/site-packages/aiohttp/web.py", line 250, in _handle
    handler = yield from factory(app, handler)
TypeError: 'coroutine' object is not iterable
```

**Comment by s0undt3ch** [comment]
And if I make aiohttp's `_handle` use the 3.5 syntax(yes that's not the fix you still want to support <3.5):
```
Traceback (most recent call last):
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.5.2-features-aiohttp/lib/python3.5/site-packages/aiohttp/web_server.py", line 61, in handle_request
    resp = yield from self._handler(request)
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.5.2-features-aiohttp/lib/python3.5/site-packages/aiohttp/web.py", line 251, in _handle
    resp = await handler(request)
  File "test_cy.pyx", line 12, in middleware (/home/vampas/.pyxbld/temp.linux-x86_64-3.5/pyrex/test_cy.c:1372)
    resp = await handler(request)
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.5.2-features-aiohttp/lib/python3.5/site-packages/aiohttp/web_urldispatcher.py", line 113, in handler_wrapper
    result = yield from result
TypeError: 'coroutine' object is not iterable
/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.5.2-features-aiohttp/lib/python3.5/site-packages/aiohttp/web_server.py:83: RuntimeWarning: coroutine 'handler' was never awaited
  exc_info=exc)
```

**Comment by s0undt3ch** [comment]
However! If also make the `web_urldispatcher.py`, in `handler_wrapper` use the 3.5 syntax...
```
$ python /tmp/test.pyx &
$ curl http://localhost:8080 
OK[MIDDLEWARE]
```

**Comment by s0undt3ch** [comment]
Ok.

By now, my conclusion is that cythonized code doesn't play well with asyncio using pre 3.5 syntax.

The solution would be to migrate aiohttp and all it's external libs(3rd-party)  to python 3.5 syntax(not doable), or, open a bug on cython to see what can be done.

**Comment by asvetlov** [comment]
aiohttp should stick with Python 3.4 for a while, at least up to next summer

**Comment by s0undt3ch** [comment]
Yes, sounds reasonable.
