### ISSUE TITLE
client must follow to exact url path from `Location` on redirect

### ISSUE THREAD

**Issue by estin** [aio-libs/aiohttp#1466]
## Long story short

When I upgrade from `aiohttp==0.22.5` to `aiohttp==1.1.5` found that redirects follow to wrong `Location`

My closed PR about this https://github.com/KeepSafe/aiohttp/pull/1423 

I will try to describe problem again )

## Expected behaviour

Client must follow to the exact url path from `Location`

When server redirect to `http://localhost:8080/target?next=http%3A//example.com/` aiohttp client must fetch exact url `http://localhost:8080/target?next=http%3A//example.com/`

## Actual behaviour

When server redirect to `http://localhost:8080/target?next=http%3A//example.com/` aiohttp client fetch wrong url `http://localhost:8080/target?next=http://example.com/`

## Steps to reproduce

server.py
```python
import sys
import logging
import asyncio
import aiohttp


REDIRECT_URL = 'http://localhost:8080/target?next=http%3A//example.com/'  # noqa


async def redirect(request):
    return web.Response(
        status=302,
        headers={
            'location': REDIRECT_URL,
        },
    )


async def target(request):
    return web.Response(status=200)


if __name__ == '__main__':
    import yarl
    from aiohttp import web

    print("aiohttp:", aiohttp.__version__)
    print("yarl:", yarl.__version__)

    logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
    logger = logging.getLogger(__name__)

    loop = asyncio.get_event_loop()

    app = web.Application()
    app.router.add_get('/', redirect)
    app.router.add_get('/target', target)

    web.run_app(
        app, access_log=logger, access_log_format='aiohttp server access: %r',
    )
```

client.py
```python
import asyncio
import aiohttp

REDIRECT_URL = 'http://localhost:8080/target?next=http%3A//example.com/'  # noqa

async def request(loop, url):
    async with aiohttp.ClientSession(loop=loop) as session:
        async with session.get(url) as response:
            print(url, response.status, response.url)
            assert str(response.url_obj) == REDIRECT_URL, '{} != {}'.format(
                str(response.url_obj), REDIRECT_URL,
            )


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(request(loop, 'http://localhost:8080/')) 
```

Start server 
```bash
$ python server.py &
```

Check aiohttp client behavior on redirect
```bash
$ python client.py
INFO:__main__:aiohttp server access: GET / HTTP/1.1
INFO:__main__:aiohttp server access: GET /target?next=http://example.com/ HTTP/1.1
http://localhost:8080/ 200 http://localhost:8080/target?next=http://example.com/
Traceback (most recent call last):
  File "client.py", line 17, in <module>
    loop.run_until_complete(request(loop, 'http://localhost:8080/'))
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "client.py", line 11, in request
    response.url_obj, REDIRECT_URL,
AssertionError: http://localhost:8080/target?next=http://example.com/ != http://localhost:8080/target?next=http%3A//example.com/
```

`curl` fetch exact url from `Location` 
```bash
$ curl -v -L http://localhost:8080/ 2>&1 | egrep '(GET|Location)'
> GET / HTTP/1.1
INFO:__main__:aiohttp server access: GET / HTTP/1.1
< Location: http://localhost:8080/target?next=http%3A//example.com/
> GET /target?next=http%3A//example.com/ HTTP/1.1
INFO:__main__:aiohttp server access: GET /target?next=http%3A//example.com/ HTTP/1.1
```

`wget` fetch exact url too
```bash
$ wget -q http://localhost:8080/
INFO:__main__:aiohttp server access: GET / HTTP/1.1
INFO:__main__:aiohttp server access: GET /target?next=http%3A//example.com/ HTTP/1.
```

`requests` fetch exact url too
```bash
$ python -c"import requests; assert requests.get('http://localhost:8080/').url == 'http://localhost:8080/target?next=http%3A//example.com/'"
INFO:__main__:aiohttp server access: GET / HTTP/1.1
INFO:__main__:aiohttp server access: GET /target?next=http%3A//example.com/ HTTP/1.1
```

## Your environment
```
aiohttp: 1.1.6
yarl: 0.8.1
```

**Comment by asvetlov** [comment]
Why do you prefer denormalized form?

**Comment by estin** [comment]
> Why do you prefer denormalized form?

Not me. Server want exact url path. I think this is some sort check logic on server.

My abstract case
```
> GET /path1
< 302
< Locaiton:  /path2?next=http%3A//domain/path1

> GET /path2?next=http%3A//domain/path1
< 200

> GET /path2?next=http://domain/path1
< 404
```

This diff is fix for my case
```diff
diff --git a/aiohttp/client.py b/aiohttp/client.py
index 6c5d029..394a237 100644
--- a/aiohttp/client.py
+++ b/aiohttp/client.py
@@ -212,7 +212,7 @@ class ClientSession:
                                        "a redirect [{0.status}] status "
                                        "but response lacks a Location "
                                        "or URI HTTP header".format(resp))
-                r_url = URL(r_url)
+                r_url = URL(r_url, encoded=True)

                 scheme = r_url.scheme
                 if scheme not in ('http', 'https', ''):
```

**Comment by estin** [comment]
Browsers also works as I expect - by exact url path

```
GET / HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8,ru;q=0.6
```

```
HTTP/1.1 302 Found
Location: http://localhost:8080/target?next=http%3A//example.com/
Content-Type: application/octet-stream
Content-Length: 0
Date: Fri, 09 Dec 2016 10:10:08 GMT
Server: Python/3.5 aiohttp/1.2.0a0
```

```
GET /target?next=http%3A//example.com/ HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8,ru;q=0.6
```

**Comment by asvetlov** [comment]
Otherwise speaking your ragged web server doesn't process percent encoding correctly.
Maybe better to fix server first?

**Comment by estin** [comment]
No. Server was not under my control.
And `server.py` defined only to show client behavior.

In other ways may be client must trust to server response and  `Location` content?
And follow to it without any changes?

**Comment by asvetlov** [comment]
Technically server might response with `Location: https://en.wikipedia.org/wiki/Special:Search?search=Питон` thus client **must** encode non-allowed charachers (Russian glyphs in this case).

Also it *could* decode allowed chars, it's 100% correct behaviour specified by RFC 3986.
For `Location` header I might suggest skipping *decoding* operation but encoding should be processed anyway.

P.S.
If you'll take a look on https://tools.ietf.org/html/rfc3986.html#page-49 ABNF you'll see that `:` (as well as `?/@`) is allowed character in *query* part of URL.

**Comment by estin** [comment]
As I understand this issue actual only for me and that server with incorrect encoding.

P.S. Why browsers, `curl` and others work as expected?

**Comment by asvetlov** [comment]
They might want to support old standards and broken servers as good as they can.
In case of `requests` I believe it's just an implementation detail -- the library uses regexp for requoting and don't care about unquoting rarely used symbols.

We could add a flag to `yarl` for not *unquoting allowed symbols* but I personally not very interesting in writing a patch myself. Also not sure if this flag should be applied by default.
