### ISSUE TITLE
aiohttp get stuck on too much requests on the same route

### ISSUE THREAD

**Issue by Marco-Sulla** [aio-libs/aiohttp#1529]
## Long story short

I have an app that uses aiohttp as server. I noticed that if I refresh the main page multiple times, sometimes I get this error:

```
2017-01-05 14:29:42,348 - In web_server.py line 83, ERROR: Error handling request
Traceback (most recent call last):
  File "/home/marco/webwams_pyenv/lib/python3.5/site-packages/aiohttp/web_server.py", line 61, in handle_request
    resp = yield from self._handler(request)
  File "/home/marco/webwams_pyenv/lib/python3.5/site-packages/aiohttp/web.py", line 249, in _handle
    resp = yield from handler(request)
  File "/home/marco/webwams_pyenv/lib/python3.5/site-packages/aiohttp/web_urldispatcher.py", line 486, in _handle
    ret = yield from self._file_sender.send(request, filepath)
  File "/home/marco/webwams_pyenv/lib/python3.5/site-packages/aiohttp/file_sender.py", line 201, in send
    yield from self._sendfile(request, resp, f, count)
  File "/home/marco/webwams_pyenv/lib/python3.5/site-packages/aiohttp/file_sender.py", line 108, in _sendfile_system
    yield from fut
  File "uvloop/future.pyx", line 230, in __iter__ (uvloop/loop.c:103945)
  File "uvloop/future.pyx", line 432, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:107104)
  File "uvloop/future.pyx", line 96, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:102292)
concurrent.futures._base.CancelledError
```

The page is not served on client. Furthermore, after a while, the app will segfault:

```
python: src/unix/core.c:878: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.
Aborted (core dumped)
```

I'm using aiohttp 1.2.0 on CentOS 6.5

**Comment by fafhrd91** [comment]
Could you test it with defaul event loop

**Comment by fafhrd91** [comment]
@1st1 ^^^

**Comment by 1st1** [comment]
> Could you test it with defaul event loop

Right, @MarcoSulla, please try it with the default asyncio event loop. It would also help if you could test on Python 3.6 (it has different Future implementation), and if you could upload a script to reproduce this bug.

**Comment by fafhrd91** [comment]
@MarcoSulla any updates?

**Comment by fafhrd91** [comment]
will re-open if will get more info
