### ISSUE TITLE
AttributeError when keepalive timeout exceeded

### ISSUE THREAD

**Issue by danfairs** [aio-libs/aiohttp#1687]
## Long story short

First off - not sure if this is an `aiohttp` bug or a `gunicorn` bug - happy to raise in the latter if necessary.

I run a simple flask service (just returns a string) using `gunicorn` and `aiohttp` with the `gaiohttp` worker type and make a request using a browser (which sends a keep-alive header), and I've configured an access log, then I see error tracebacks in the console which look like they're caused by an incompatible logging call from `handle_error` in `aiohttp/server.py` into `gunicorn`'s `_gaiohttp.py` worker module.

This does not occur if no keepalive header is in place, or if you fire requests quickly enough that the keepalive timeout isn't hit (2 seconds by default).

## Expected behaviour

When a keepalive timeout happens, it should pass silently.

## Actual behaviour

I'm seeing tracebacks like this:

```
(unrest) boatman:KBSvc dan$ gunicorn -k gaiohttp kbsvc.app --access-logfile=-
[2017-02-27 15:18:23 +0000] [49697] [INFO] Starting gunicorn 19.6.0
[2017-02-27 15:18:23 +0000] [49697] [INFO] Listening at: http://127.0.0.1:8000 (49697)
[2017-02-27 15:18:23 +0000] [49697] [INFO] Using worker: gaiohttp
[2017-02-27 15:18:23 +0000] [49700] [INFO] Booting worker with pid: 49700
127.0.0.1 - - [27/Feb/2017:15:18:27 +0000] "GET /healthz HTTP/1.1" 200 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
Task exception was never retrieved
future: <Task finished coro=<ServerHttpProtocol.start() done, defined at /Users/dan/Envs/unrest/lib/python3.6/site-packages/aiohttp/server.py:225> exception=AttributeError("'NoneType' object has no attribute 'get'",)>
Traceback (most recent call last):
  File "/Users/dan/Envs/unrest/lib/python3.6/site-packages/aiohttp/server.py", line 254, in start
    message = yield from httpstream.read()
  File "/Users/dan/Envs/unrest/lib/python3.6/site-packages/aiohttp/helpers.py", line 765, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dan/Envs/unrest/lib/python3.6/site-packages/aiohttp/server.py", line 311, in start
    yield from self.handle_error(504, message)
  File "/Users/dan/Envs/unrest/lib/python3.6/site-packages/aiohttp/server.py", line 378, in handle_error
    self.log_access(message, None, response, self._loop.time() - now)
  File "/Users/dan/Envs/unrest/lib/python3.6/site-packages/gunicorn/workers/_gaiohttp.py", line 24, in log_access
    self.logger.access(response, request, environ, datetime.timedelta(0, 0, time))
  File "/Users/dan/Envs/unrest/lib/python3.6/site-packages/gunicorn/glogging.py", line 320, in access
    request_time))
  File "/Users/dan/Envs/unrest/lib/python3.6/site-packages/gunicorn/glogging.py", line 267, in atoms
    'h': environ.get('REMOTE_ADDR', '-'),
AttributeError: 'NoneType' object has no attribute 'get'
```

## Steps to reproduce

Running a simple flask app that returns a string with a gunicorn invocation like this:

gunicorn -k gaiohttp kbsvc.app --access-logfile=-

## Your environment

Running versions:

aiohttp==1.3.3
gunicorn==19.6.0

Running Python 3.6.0, error occurs both on OS X and Linux. 

I can put together a docker image that demonstrates the issue if need be.

**Comment by fafhrd91** [comment]
technically `gaiohttp` worker is deprecated and `aiohttp.wsgi` as well.
you can try `GunicornWebWorker` from 1.3 branch

I will try to push update gunicorn and deprecate gaiohttp.
also we dropped wsgi in aiohttp 2.0

**Comment by danfairs** [comment]
Great, thanks - didn't know those were deprecated. Did I miss that in the docs?

My services have moved around a bit and I actually no longer have an async worker serving browser requests (so it's not an urgent thing for me) but I'll try to test the 1.3 branch over the next week or so.

**Comment by fafhrd91** [comment]
I do not think this is actionable. here is gunicorn's PR https://github.com/benoitc/gunicorn/pull/1418
