### ISSUE TITLE
default_exception_handler Exception in callback FileSender._sendfile_cb(<Future cancelled>, 12, 11, 27360, 172674, <_UnixSelecto...e debug=False>, True)

### ISSUE THREAD

**Issue by wencan** [aio-libs/aiohttp#1848]
debian 9
python 3
aiohttp 1.3.3

    ERROR [2017-04-27 11:04:41,468] base_events.py:1259#default_exception_handler Exception in callback FileSender._sendfile_cb(<Future cancelled>, 12, 11, 27360, 172674, <_UnixSelecto...e debug=False>, True)
    handle: <Handle FileSender._sendfile_cb(<Future cancelled>, 12, 11, 27360, 172674, <_UnixSelecto...e debug=False>, True)>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
        self._callback(*self._args)
      File "/usr/local/lib/python3.6/site-packages/aiohttp/file_sender.py", line 25, in _sendfile_cb
        loop.remove_writer(out_fd)
      File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 351, in remove_writer
        self._ensure_fd_no_transport(fd)
      File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 258, in _ensure_fd_no_transport
        fd, transport))
    RuntimeError: File descriptor 12 is used by transport <_SelectorSocketTransport fd=12 read=polling write=<polling, bufsize=0>>

and:

    ERROR [2017-04-27 11:14:24,018] base_events.py:1259#default_exception_handler Exception in callback FileSender._sendfile_cb(<Future cancelled>, 12, 11, 27512, 54508, <_UnixSelecto...e debug=False>, True)
    handle: <Handle FileSender._sendfile_cb(<Future cancelled>, 12, 11, 27512, 54508, <_UnixSelecto...e debug=False>, True)>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
        self._callback(*self._args)
      File "/usr/local/lib/python3.6/site-packages/aiohttp/file_sender.py", line 25, in _sendfile_cb
        loop.remove_writer(out_fd)
      File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 351, in remove_writer
        self._ensure_fd_no_transport(fd)
      File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 258, in _ensure_fd_no_transport
        fd, transport))
    RuntimeError: File descriptor 12 is used by transport <_SelectorSocketTransport fd=12 read=polling write=<polling, bufsize=0>>
    ERROR [2017-04-27 11:14:24,019] base_events.py:1259#default_exception_handler Exception in callback FileSender._sendfile_cb(<Future cancelled>, 12, 11, 27512, 54508, <_UnixSelecto...e debug=False>, True)
    handle: <Handle FileSender._sendfile_cb(<Future cancelled>, 12, 11, 27512, 54508, <_UnixSelecto...e debug=False>, True)>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
        self._callback(*self._args)
      File "/usr/local/lib/python3.6/site-packages/aiohttp/file_sender.py", line 25, in _sendfile_cb
        loop.remove_writer(out_fd)
      File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 351, in remove_writer
        self._ensure_fd_no_transport(fd)
      File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 258, in _ensure_fd_no_transport
        fd, transport))
    RuntimeError: File descriptor 12 is used by transport <_SelectorSocketTransport fd=12 read=polling write=<polling, bufsize=0>>
    ERROR [2017-04-27 11:14:24,019] base_events.py:1259#default_exception_handler Exception in callback FileSender._sendfile_cb(<Future cancelled>, 12, 11, 27512, 54508, <_UnixSelecto...e debug=False>, True)
    handle: <Handle FileSender._sendfile_cb(<Future cancelled>, 12, 11, 27512, 54508, <_UnixSelecto...e debug=False>, True)>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
        self._callback(*self._args)
      File "/usr/local/lib/python3.6/site-packages/aiohttp/file_sender.py", line 25, in _sendfile_cb
        loop.remove_writer(out_fd)
      File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 351, in remove_writer
        self._ensure_fd_no_transport(fd)
      File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 258, in _ensure_fd_no_transport
        fd, transport))
    RuntimeError: File descriptor 12 is used by transport <_SelectorSocketTransport fd=12 read=polling write=<polling, bufsize=0>>

**Comment by fafhrd91** [comment]
This should be fixed in 2.0
