### ISSUE TITLE
[Investigation] Leaking of timeout task cancellation

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiohttp#1904]
In one of our applications we use aiobotocore, which layers on top of aiohttp.  I have S3 worker processes that have ~50 aiobotocore tasks working in parallel (`head_object`, `get_object`, etc).

I've noticed w/in the last month that I started getting spurious `CancelledError`s from aiohttp.  I've done some debugging and it seems there's something broken with how the `CeilTimeout` works in `ClientSession._request`.  In my particular scenario the call structure looks like:

```
outer_task
    aiobotocore_method
       while num_retries:
           try:
                aiohttp request
           except (TimeoutError, ClientConnectionError):
               await asyncio.sleep(NUM)
```

so you can see aiobotocore will catch the timeout errors then sleep for a few seconds before trying the aiohttp call again.  The issue I'm seeing is that aiohttp is inadvertently cancelling the sleep.  The following shows who's cancelling the Task:

```
Task cancel traceback:
...
  File "/Users/amohr/dev/weather/python/fbn/asyncio/mp_worker_pool.py", line 219, in _main
    self._loop.run_until_complete(self._job_enqueuer())
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 375, in run_until_complete
    self.run_forever()
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 1312, in _run_once
    handle._run()
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.5/site-packages/async_timeout/__init__.py", line 53, in _cancel_task
    self._cancelled = self._task.cancel()
```

so it's definitely asyncio's task cancelling proc.  And the following shows who's cancelling the sleep future:
```
Future cancel traceback:
...
  File "/Users/amohr/dev/weather/python/fbn/asyncio/mp_worker_pool.py", line 219, in _main
    self._loop.run_until_complete(self._job_enqueuer())
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 375, in run_until_complete
    self.run_forever()
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 1312, in _run_once
    handle._run()
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    self._step(exc)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 270, in _step
    if self._fut_waiter.cancel():
```

Resulting the the following outer Cancellation Exception:
```
Traceback (most recent call last):
  File "/Users/amohr/dev/weather/python/fbn/asyncio/mp_worker_pool.py", line 134, in _process_job
    try: result = await method(*args, **kwargs)
  File "/Users/amohr/dev/weather/python/fbn/asyncio/s3.py", line 119, in wrapped_func
    response = await attr(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/aiobotocore/client.py", line 79, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python3.5/site-packages/aiobotocore/endpoint.py", line 205, in _send_request
    exception)):
  File "/usr/local/lib/python3.5/site-packages/aiobotocore/endpoint.py", line 246, in _needs_retry
    yield from asyncio.sleep(handler_response, loop=self._loop)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 521, in sleep
    return (yield from future)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 367, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 301, in _wakeup
    future.result()
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 272, in result
    raise CancelledError
concurrent.futures._base.CancelledError
```

So we know the `timeout._cancel_task` was called before the `timeout.__exit__` because `timeout.__exit__` clears out `self._task`.  I'm not sure what happened in the `__exit__` though.

Curious if you have any ideas.

**Comment by fafhrd91** [comment]
could be this #1879

**Comment by fafhrd91** [comment]
you can try ab8efa4231041d86de2684af50793c0810382c33 commit

**Comment by thehesiod** [comment]
dang, u the man, so fast :)  Will try, thanks!

**Comment by thehesiod** [comment]
looks like a winner!

**Comment by thehesiod** [comment]
now just anxiously awaiting release  with it :)

**Comment by fafhrd91** [comment]
I am busy with different project, but I'll try to release new version by the end of weekend
