### ISSUE TITLE
aiohttp.client_exceptions.ClientResponseError: 400, message='400, message='data received after completed connection: close message''

### ISSUE THREAD

**Issue by wencan** [aio-libs/aiohttp#1905]
aiohttp: 2.0.7
debian: 8.7
python: 3.6

```
ERROR [2017-05-19 14:31:37,688] web_protocol.py:358#log_exception Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 417, in start
    resp = yield from self._request_handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web.py", line 289, in _handle
    resp = yield from handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp_session/__init__.py", line 129, in middleware
    response = yield from handler(request)
  File "./app/error.py", line 40, in middleware_handler
    return await handler(request)
  File "./app/routes/proxy.py", line 52, in proxy_handler
    async with session.request(method, url, params=request.query, headers=headers, data=body)as response:
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 626, in __aenter__
    self._resp = yield from self._coro
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 235, in _request
    yield from resp.start(conn, read_until_eof)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 528, in start
    (message, payload) = yield from self._protocol.read()
  File "/usr/local/lib/python3.6/site-packages/aiohttp/streams.py", line 489, in read
    yield from self._waiter
aiohttp.client_exceptions.ClientResponseError: 400, message='400, message='data received after completed connection: close message''
```

**Comment by asvetlov** [comment]
Sorry, your trace back is not helpful without code snippet for reprouting the issue

**Comment by wencan** [comment]
@asvetlov 
```
with async_timeout.timeout(60):
    async with aiohttp.ClientSession() as session:
        log.info("proxy {}: {}{}".format(method, url, '?{}'.format(request.query_string) if request.query_string else ''))
        async with session.request(method, url, params=request.query, headers=headers, data=body)as response:
            status = response.status
            reason = response.reason
            headers = response.headers
            headers = dict(headers)
            if 'Transfer-Encoding' in headers:
                headers.pop('Transfer-Encoding')
            body = await response.read()
            return Response(status=status, reason=reason, headers=headers, body=body)
```

**Comment by samuelcolvin** [comment]
I'm afraid there's not enough information here to diagnose the problem, I think the problem is with `body` as passed to request. Happy to look more if you can provide a full working example of the problem.
