### ISSUE TITLE
Server say "Unhandled exception CancelledError" after send date

### ISSUE THREAD

**Issue by tonal** [aio-libs/aiohttp#2073]
## Long story short
Error in log after send date
```
Traceback (most recent call last):
  File "/opt/img_lib/venv/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 435, in start
    yield from resp.write_eof()
  File "/opt/img_lib/venv/lib/python3.6/site-packages/aiohttp/web_response.py", line 583, in write_eof
    yield from super().write_eof(body)
  File "/opt/img_lib/venv/lib/python3.6/site-packages/aiohttp/web_response.py", line 420, in write_eof
    yield from self._payload_writer.write_eof(data)
  File "/opt/img_lib/venv/lib/python3.6/site-packages/aiohttp/http_writer.py", line 282, in write_eof
    yield from self.drain(True)
  File "/opt/img_lib/venv/lib/python3.6/site-packages/aiohttp/http_writer.py", line 295, in drain
    yield from self._stream.drain()
  File "/opt/img_lib/venv/lib/python3.6/site-packages/aiohttp/http_writer.py", line 128, in drain
    yield from self._protocol._drain_helper()
  File "/opt/pyenv/versions/3.6.1/lib/python3.6/asyncio/streams.py", line 211, in _drain_helper
    yield from waiter
concurrent.futures._base.CancelledError
```
## Expected behaviour

I do not wait CancelledError here

## Actual behaviour

My server processes 10 - 30 requests per second.
The error appears every 5 to 10 minutes.

## Steps to reproduce

I do not known how to reproduce

## Your environment

aiohttp 2.2.3
python 3.6.1
ubuntu 12.04 & 14.04

**Comment by asvetlov** [comment]
You don't expect web handler cancellation but the handler is cancelled if connection to client is lost (or closed by peer, it doesn't matter).
Quite not clean to me: are you talking about incorrect behavior or just annoying log message?

**Comment by fafhrd91** [comment]
I think this is web_protocol problem. we need to catch CancelledError for write_eof()

**Comment by asvetlov** [comment]
+1

**Comment by tonal** [comment]
I have not noticed any incorrect behavior so far.
Only errors in the log

**Comment by asvetlov** [comment]
Got it

**Comment by fafhrd91** [comment]
fixed in master
