### ISSUE TITLE
Client deadlocks when having received long read() then EOF before new request

### ISSUE THREAD

**Issue by manuco** [aio-libs/aiohttp#2217]
## Long story short

When :
- the program creates a request wich returns a big content ;
- the OS `read` syscall returns with long buffer (containing a response) ;
- the program fetches the response but not its content (`response.status == 200` but no `response.text()` or something else) ;
- the program creates a new request...

## Expected behaviour

The program gets its second response (and the first one is of course not discarded).

## Actual behaviour

The call to `session.get()` deadlocks until it timeouts. 

## Steps to reproduce

Run the following program. It creates a simplistic server that serves big enough content to trigger the bug. The server is not part of the bug.

It also contains the problematic client calls that lead to the timeout. I'm using aiohttp server and localhost because this combination enables the OS to push a big read. (as an aside, the real sent content is a rather big generated PNG image)

```python
import asyncio
import aiohttp
import aiohttp.web


@asyncio.coroutine
def main_client(loop):
	session = aiohttp.ClientSession()
	a = yield from session.get("http://localhost:8742/plop")
	print("A:", a.status)

	# don't release 'a' for now

	b = yield from session.get("http://localhost:8742/bla") # deadlocks here
	# following code is never called
	print("B:", b.status)

	yield from b.release()
	yield from a.release()
	session.close()


@asyncio.coroutine
def handler(request):
	# see aiohttp.streams.DEFAULT_LIMIT for the "magic value" of 2 ** 16
	# this works
	#return aiohttp.web.Response(body="Z" * ((2 ** 16) * 2))

	# this does not work
	return aiohttp.web.Response(body="Z" * ((2 ** 16) * 2 + 1))

@asyncio.coroutine
def main_server(loop):
	global server
	server = aiohttp.web.Server(handler)
	yield from loop.create_server(server, "0.0.0.0", 8742)


# case preparation : craft a server with big writes
loop = asyncio.get_event_loop()
loop.run_until_complete(main_server(loop))

# execution of the client
loop.run_until_complete(main_client(loop))

# garbage collecting
loop.run_until_complete(server.shutdown(10))
```

## Details

The problem is due to two events :
- data received fills the buffer up (`aiohttp.streams.FlowControlStreamReader.feed_data()` and its super call), triggering a pause on the protocol.
- the reach of the end of the reponse triggers a `StreamReader.feed_eof()` which causes the protocol to be returned to the pool of the session while response data is still in the associated `FlowControlStreamReader` buffer.

I think that the protocol shouldn't be returned to the pool before `release()` is *explicitly* called on the response, letting the program choose when the connection can be reused. I see the commit 321550e1b5b759b7e09a66cfe3ebc9b1e16c94e6 that tries to release the connection earlier, but reached EOF doesn't mean that the FlowControlStreamReader buffer is ready again to be used.

## Your environment

Python 3.4.2, aiohttp 2.1.0
Python 3.5.3, aiohttp 2.3.0a0

**Comment by scranen** [comment]
Issue still stands, and seems to be what is preventing us from adopting aiohttp in our data processing pipelines.

Same example, rewritten for Python 3.6+ and aiohttp 3.5.2:
```python
import asyncio
import aiohttp
import aiohttp.web


async def main_client():
    async with aiohttp.ClientSession(read_timeout=10) as session:
        a = await session.get("http://localhost:8742/plop")
        print("A:", a.status)

        b = await session.get("http://localhost:8742/bla")  # deadlocks here
        # following code is never called
        print("B:", b.status)


async def handler(request):
    # see aiohttp.streams.DEFAULT_LIMIT for the "magic value" of 2 ** 16
    # this works
    # return aiohttp.web.Response(body="Z" * ((2 ** 16) * 2))

    # this does not work
    return aiohttp.web.Response(body="Z" * ((2 ** 16) * 2 + 1))


async def main():
    server = aiohttp.web.Server(handler)
    await asyncio.get_event_loop().create_server(server, "0.0.0.0", 8742)
    await asyncio.gather(main_client(), server.shutdown(10))


if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```

**Comment by andr-c** [comment]
To reproduce the problem reliably, one can modify the test and send more requests like this:
```python
async def main_client():
    async with aiohttp.ClientSession(read_timeout=10) as session:
        for i in range(100):
            print(i)
            a = await session.get("http://localhost:8742/plop")
            print("A:", a.status)

            b = await session.get("http://localhost:8742/bla")  # deadlocks here
            # following code is never called
            print("B:", b.status)
```
This bug makes aiohttp unsuitable for use in high load environments.
On my box it times out on 2nd iteration. Resizing msgs to (2 ** 16) * 2) makes it passing again.

Is there better workaround/fix than padding all reponses to be x DEFAULT_LIMIT ?

**Comment by bdraco** [comment]
Is this still reproducible with 3.11?

**Comment by Dreamsorcerer** [comment]
With aiohttp 3.7 I get this on the second loop:
```
Traceback (most recent call last):
  File "/home/s/Desktop/test.py", line 34, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/s/Desktop/test.py", line 30, in main
    await asyncio.gather(main_client(), server.shutdown(10))
  File "/home/s/Desktop/test.py", line 10, in main_client
    a = await session.get("http://localhost:8742/plop")
  File "/usr/lib/python3/dist-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/lib/python3/dist-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/usr/lib/python3/dist-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

Which I think is related to the response getting garbage collected. If you change the code to use `async with` (i.e. the recommended way), there is no issue.

Complete code:
```
import asyncio
import aiohttp
import aiohttp.web


async def main_client():
    async with aiohttp.ClientSession(read_timeout=10) as session:
        for i in range(100):
            print(i)
            a = await session.get("http://localhost:8742/plop")
            print("A:", a.status)

            b = await session.get("http://localhost:8742/bla")  # deadlocks here
            # following code is never called
            print("B:", b.status)


async def handler(request):
    # see aiohttp.streams.DEFAULT_LIMIT for the "magic value" of 2 ** 16
    # this works
    # return aiohttp.web.Response(body="Z" * ((2 ** 16) * 2))

    # this does not work
    return aiohttp.web.Response(body="Z" * ((2 ** 16) * 2 + 1))


async def main():
    server = aiohttp.web.Server(handler)
    await asyncio.get_event_loop().create_server(server, "0.0.0.0", 8742)
    await asyncio.gather(main_client(), server.shutdown(10))


if __name__ == '__main__':
    asyncio.run(main())
```

**Comment by bdraco** [comment]
> With aiohttp 3.7 I get this on the second loop:

Does this happen on 3.11 as well?

**Comment by bdraco** [comment]
I wonder if this is the same issue as #10169
