### ISSUE TITLE
Cannot use upstr with CIMultiDict

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#244]
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/mock.py", line 1136, in patched
    return func(_args, *_keywargs)
  File "/Users/nikolay/dev/account-api/venv/src/aiohttp/tests/test_web_response.py", line 176, in test_compression
    headers=CIMultiDict({hdrs.ACCEPT_ENCODING: 'gzip, deflate'}))
  File "aiohttp/_multidict.pyx", line 200, in aiohttp._multidict.MultiDict.__init__ (aiohttp/_multidict.c:5126)
    self._extend(args, kwargs, self.__class__.**name**, 1)
  File "aiohttp/_multidict.pyx", line 213, in aiohttp._multidict.MultiDict._extend (aiohttp/_multidict.c:5399)
    key, value = item
nose.proxy.TypeError: Expected str, got upstr

**Comment by asvetlov** [comment]
Did you added a new test to the suite?
If yes please make a branch with failing test.

It's unlikely that we have the different behavior on Linux and MacOSX.

I suspect I've missed some edge case in multidict implementation.

**Comment by fafhrd91** [comment]
added "multidict-error" branch

**Comment by asvetlov** [comment]
Got it, working on fix

**Comment by asvetlov** [comment]
Fixed
