### ISSUE TITLE
CancelledError are not handled correctly even with aiojobs

### ISSUE THREAD

**Issue by larryclean** [aio-libs/aiohttp#2466]
## Long story short

We are running a internet mobile app which has around 100,000 users accessing each day . Probably，the web server received 3,000 hits per second. 
Since all the user access should be realtime mode . We use aiohttp framework to handle all of them.
Every sec, the error log records around 5,6 cancellederrors which confused us very much . We can not figure out the real cause why so many cancellederrors are threw . 
After several rounds of discussion in GitHub , we got to know the version of aiohttp 2.3.0 has resolved this common problem by using aiojobs to reduce the number of cancellederror occured.
But after 2.3.0 implemented ， nothing has been changed. the number of cancellederror still remains same. 

The error will cause the saving to the redis failed , while errors accumulated in certain amount , all the operations to redis will be responsed "error" . 

It suffers. and we hope to have a good solution to cater it to get rid of all the cancellederror.

## Expected behaviour

No cancellederror occurs.
or Cancellederror will not impact the application status . 

## Actual behaviour

Too many cancellederror lead the redis malfunction. 

## Steps to reproduce

Sorry, This problem only occurs in live environment , while we set up test environment on localhost or test server , it's hard to reproduce the same error.

## Your environment
Server Side:
centos 7.2 (OS)
python3.6.2 
aiohttp 2.3.0 
aioredis0.33
aiomysql0.0.9
sqlachemy1.1.12
python-socketio (last version)

Client Side：
socketio.js 1.2

**Comment by larryclean** [comment]
Error Log Example:
```python
[2017-11-06 11:45:34][ERROR][Traceback (most recent call last):
  File "/home/wwwroot/ykrealtime/venv36/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 19, in poll
    self.server.ping_timeout)]
  File "/usr/local/python36/lib/python3.6/asyncio/tasks.py", line 351, in wait_for
    yield from waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wwwroot/ykrealtime/rtgame/middleware.py", line 34, in middleware_handler
    response = await handler(request)
  File "/home/wwwroot/ykrealtime/venv36/lib/python3.6/site-packages/engineio/asyncio_server.py", line 138, in handle_request
    b64)
  File "/home/wwwroot/ykrealtime/venv36/lib/python3.6/site-packages/engineio/asyncio_server.py", line 253, in _handle_connect
    return self._ok(await s.poll(), headers=headers, b64=b64)
  File "/home/wwwroot/ykrealtime/venv36/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 22, in poll
    raise exceptions.QueueEmpty()
engineio.exceptions.QueueEmpty
][middleware.py][59]
```

**Comment by larryclean** [comment]
Code Example:
aiojobs decorator
```python
def use_aiojob(app):
    def decorator(func):
        @functools.wraps(func)
        async def wrapper(*args, **kw):
            scheduler = app['siojobs']
            job = await scheduler.spawn(func(*args, **kw))
            return await job.wait()
        return wrapper
    return decorator
```

socket.io disconnect event
```python
    @sio.on('disconnect')
    @use_aiojob(app)
    async def disconnect(sid):
        await factory.leave_room(sid)
        rooms = sio.rooms(sid)
        for room in rooms:
            sio.leave_room(sid, room)
        await sio.eio.disconnect(sid)
```
factory leave_room
```python
    async def leave_room(self, sid):
          try:
            data, user, sid_user_hall_room_list = await self.user_logic.leave_room(sid, self.check_sid_valid, self.port)
            if sid_user_hall_room_list:
                return None
            if data:
                hall = data.get('hall')
                room = data.get('room')
                user_id = data.get('user_id')
                if int(room) > 0:
                    online = await self.game_logic.leave_game(hall, room, user_id)
                    if online:
                        await self.sio.emit("update_game", online, room=str(hall) + "_" + str(room))
               await self.sio.emit("notice", {
                    "type": "message",
                    "message": user.get("user_name", "") + "退出房间"
                }, room=str(hall) + "_" + str(room))
            await self.user_logic.delete_sid(sid, self.port)
        except RTException as e:
            print(e.error)
```

user_logic leave_room

```python
    async def leave_room(self, sid, handle=None, port=0):
        try:

            temp_user_sid = None
            redis = await self.get_redis()
            key = REDIS_KEY['RT_SID_HALL_ROOM'].format(sid)
            result = await redis.hgetall(key)
            user_info = dict()
            if result:
               ……
                if not temp_user_sid:
                    await redis.srem(REDIS_KEY['RT_USER_HALL'].format(result.get('hall'), result.get('room')),
                                     REDIS_KEY['RT_USER'].format(result.get('user_id')))
                if not sid_list:
                    user_info['online_status'] = 0
                    await redis.hset(REDIS_KEY['RT_USER'].format(result.get('user_id')), 'online_status', 0)
                    match = await redis.hgetall(
                        REDIS_KEY['RT_HASH_MATCH_HIS'].format(result.get('hall', 1), result.get('user_id')))
                    if match:
                        await redis.zrem(match.get('list_key'), match.get('rule_key'))
                        await redis.srem(
                            REDIS_KEY['RT_MATCH_SET_USER'].format(result.get('hall', 1), result.get('user_id')),
                            match.get('rule_key'))
                        await redis.delete(
                            REDIS_KEY['RT_HASH_MATCH_HIS'].format(result.get('hall', 1), result.get('user_id')))
            return result, user_info, temp_user_sid
        except Exception as e:
            error_log.error(traceback.format_exc())
            raise RTException(e)
```

gamelogic.leave_room
```python
    async def leave_game(self, hall, room, user_id):
        try:
            redis = await self.get_redis()
           ……
            game = await self._calc_game_time(game_key, game, save_flag)
            if int(game.get('offlineTime', -1)) > -1:
                if int(game.get("blackId")) == int(user_id) and int(game.get('curColor')) == 1:
                    game['isStop'] = 1
                elif int(game.get('whiteId')) == int(user_id) and int(game.get('curColor')) == -1:
                    game['isStop'] = 1
                await redis.hmset_dict(game_key, game)

            return self.__foramt_game_status(game)
        except Exception as e:
            raise RTException(e)
```
To simplify it , most of the redis operations were deleted. 
We hope this issue can be addressed and resolved asap ....

**Comment by asvetlov** [comment]
Handler cancellation is inherent `aiohttp` feature -- that's how TCP network is working.
http://aiohttp.readthedocs.io/en/stable/web.html#web-handler-cancellation
`aiojobs` allows to spawn a new task for handling activities like saving a data to DB regardless peer connection closing.
What is your problem?
Do you lose data?
Or just see a cancellation record in your logs?
Anyway you should raise an issue in [`aiojobs`](/aio-libs/aiojobs/issues/new) bugtracker, not here.

**Comment by hellysmile** [comment]
@larry-dev there is similar lib to aiojobs, which STRICTLY do no allow cancel https://github.com/wikibusiness/async_lru , try to take a look on it

**Comment by hellysmile** [comment]
Related actual aiojobs issue https://github.com/aio-libs/aiojobs/issues/25
