### ISSUE TITLE
request.remote should work on closed transport

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2474]
Regression, should be fixed on 2.3 branch also.

```
aiohttp/pytest_plugin.py:119: RuntimeError
-------------------------------------------------- Captured stderr call --------------------------------------------------
Error handling request
Traceback (most recent call last):
  File "/home/andrew/projects/aiohttp/aiohttp/web_protocol.py", line 414, in start
    resp = await self._request_handler(request)
  File "/home/andrew/projects/aiohttp/aiohttp/web.py", line 309, in _handle
    resp = await handler(request)
  File "/home/andrew/projects/aiohttp/tests/test_client_ws_functional.py", line 759, in handler
    await ws.receive_bytes()
  File "/home/andrew/projects/aiohttp/aiohttp/web_ws.py", line 326, in receive_bytes
    msg.data))
TypeError: Received message 8:1000 is not bytes
Error in logging
Traceback (most recent call last):
  File "/home/andrew/projects/aiohttp/aiohttp/helpers.py", line 510, in __get__
    return inst._cache[self.name]
KeyError: 'remote'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrew/projects/aiohttp/aiohttp/helpers.py", line 477, in log
    for key, value in fmt_info:
  File "/home/andrew/projects/aiohttp/aiohttp/helpers.py", line 469, in <genexpr>
    for key, method in self._methods)
  File "/home/andrew/projects/aiohttp/aiohttp/helpers.py", line 429, in _format_a
    ip = request.remote
  File "/home/andrew/projects/aiohttp/aiohttp/helpers.py", line 512, in __get__
    val = self.wrapped(inst)
  File "/home/andrew/projects/aiohttp/aiohttp/web_request.py", line 318, in remote
    peername = self.transport.get_extra_info('peername')
AttributeError: 'NoneType' object has no attribute 'get_extra_info'
```

**Comment by asvetlov** [comment]
Fixed by 397c0427c
