### ISSUE TITLE
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method

### ISSUE THREAD

**Issue by wpbloger** [aio-libs/aiohttp#2632]
I want to make a bot in a telegram.
I'm using the materials in this article: https://habrahabr.ru/post/322078/
I do as it says there, I create a client and a server, and I do a webhook that would send telegrams to the server.
But the following error is received (apparently when a request comes from the telegram):
```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 271, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 295, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
```
The code I finally use:
```
import asyncio
import aiohttp
from aiohttp import web
import json

class Api:
	URL = 'https://api.telegram.org/bot%s/%s'

	def __init__(self, token, loop):
		self._token = token
		self._loop = loop

	async def _request(self, method, message):
		headers = {
			'Content-Type': 'application/json'
		}
		async with aiohttp.ClientSession(loop=self._loop) as session:
			async with session.post(self.URL % (self._token, method),
									data=json.dumps(message),
									headers=headers) as resp:
				try:
					assert resp.status == 200
				except:
					pass

	async def sendMessage(self, chatId, text):
		message = {
			'chat_id': chatId,
			'text': text
		}
		await self._request('sendMessage', message)


class Conversation(Api):
	def __init__(self, token, loop):
		super().__init__(token, loop)

	async def _handler(self, message):
		pass

	async def handler(self, request):
		message = await request.json()
		asyncio.ensure_future(self._handler(message['message']))
		return aiohttp.web.Response(status=200)


class EchoConversation(Conversation):
	def __init__(self, token, loop):
		super().__init__(token, loop)

	async def _handler(self, message):
		await self.sendMessage(message['chat']['id'],
							   message['text'])

async def init_app(loop):
	echobot = EchoConversation('*********', loop)
	
	app = web.Application(loop=loop, middlewares=[])
	app.router.add_post('/api_bot', echobot.handler)
	return app

if __name__ == '__main__':
	loop = asyncio.get_event_loop()
	try:
		
		app = loop.run_until_complete(init_app(loop))
		web.run_app(app, host='0.0.0.0', port=8443)
	except Exception as e:
		print('Error create server: %r' % e)
	finally:
		pass
	loop.close()
```
Python 3.6.1
aiohttp 2.3.7
Ubuntu 12.04.5 LTS

Is it like an error in the library, or am I doing something wrong?

**Comment by asvetlov** [comment]
What HTTP method is not accepted?

**Comment by wpbloger** [comment]
I send any POST request:
`curl -X POST -d @pass.txt -H "Content-Type: application/json" "https://site.ru:8443/api_bot"`
and I get an error on the server:
```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 271, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 295, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
```

**Comment by asvetlov** [comment]
I'm asking not about request to telegram but what HTTP method cannot be processed by aiohttp.

**Comment by wpbloger** [comment]
I understood you.
I wrote about this, above in my answer.
I run the server on the port 8443, then I assign the route api_bot and I set the handler.
I start the server, it works in anticipation of incoming requests.
Further I from the local machine do request to the server on this port, a method the POST.
And as a result on the server there is such error about which I wrote above.

**Comment by asvetlov** [comment]
You server starts HTTP serving on port 8443 (`web.run_app(app, host='0.0.0.0', port=8443)`).
But you are trying to connect using HTTPS protocol by CURL.

Obviously it doesn't work.
Closing the issue.
