### ISSUE TITLE
AssertionError releted to subapp and add_route()

### ISSUE THREAD

**Issue by maxkezhang** [aio-libs/aiohttp#2705]
## Long story short
When I use `subapp` and subapp's `add_route` method, I encounter a strange error:
```Python
python3 wsgi.py
Traceback (most recent call last):
  File "wsgi.py", line 1, in <module>
    from service import app, web, loop
  File "/home/humbert/dev/asynccnu/szkc_service/service/__init__.py", line 20, in <module>
    app = create_app()
  File "/home/humbert/dev/asynccnu/szkc_service/service/__init__.py", line 15, in create_app
    from .api import api
  File "/home/humbert/dev/asynccnu/szkc_service/service/api.py", line 65, in <module>
    api.router.add_route('GET', '/szkc/grade/', grade_all_api, name='szkc_grade_api')
  File "/home/humbert/dev/asynccnu/szkc_service/venv/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 905, in add_route
    expect_handler=expect_handler)
  File "/home/humbert/dev/asynccnu/szkc_service/venv/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 301, in add_route
    expect_handler=expect_handler)
  File "/home/humbert/dev/asynccnu/szkc_service/venv/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 702, in __init__
    resource=resource)
  File "/home/humbert/dev/asynccnu/szkc_service/venv/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 124, in __init__
    assert callable(handler), handler
AssertionError: None
```

I check my code and find that, the `POST` route can be added to the `api` app, but two `GET` apis can't.
Here's part of my code:
my `api.py`
```Python
import ...
api = web.Application()

async def login_api(request):
    code
@require_login
async def getinfo1(request, arg1, arg2):
    code
@require_login
async def getinfo2(request, arg1, arg2):
    code

api.router.add_route('POST', '/login/', login_api, name='login_api')
api.router.add_route('GET', '/grade/', getinfo1_api, name='getinfo1_api')
api.router.add_route('GET', '/table/', getinfo2_api, name='getinfo2_api')
```
my `__init__.py` which initialize the `app` and add subapp `api` to it
```Python
import ...
def create_app():
    code
app = create_app()
loop = asyncio.get_event_loop()
from .api import api
app.add_subapp('/api/', api)
```
And When I run my `wsgi.py`, it just throw that error and i don't know what's wrong with my code.

## Expected behaviour

The app can run normally

## Actual behaviour

Throw those error

## Steps to reproduce
[Here's my code repo](https://github.com/asynccnu/szkc_service)
## Your environment
OS: Ubuntu16.04
Python: Python 3.6.3
aiohttp server: 2.3.10

**Comment by webknjaz** [comment]
@Humbertzhang un-tab this line https://github.com/asynccnu/szkc_service/blob/master/service/decorator.py#L25
