### ISSUE TITLE
asyncio.sleep() raise RuntimeError  exception in AioHTTPTestCase.

### ISSUE THREAD

**Issue by asleea88** [aio-libs/aiohttp#2706]
## Long story short

```
# test_utils.py

 def setup_test_loop(loop_factory=asyncio.new_event_loop):
    """Create and return an asyncio.BaseEventLoop
    instance.
    The caller should also call teardown_test_loop,
    once they are done with the loop.
    """
    loop = loop_factory()
    asyncio.set_event_loop(None)   
    if sys.platform != "win32":
        policy = asyncio.get_event_loop_policy()
        watcher = asyncio.SafeChildWatcher()
        watcher.attach_loop(loop)
        with contextlib.suppress(NotImplementedError):
            policy.set_child_watcher(watcher)
    return loop                                 
```
The `setup_test_loop()` method looks to clear `main loop` as `None` and return `new loop` while not setting the `new loop` as `main loop` by calling `set_event_loop(loop)`.

Then I have run into an issue about the above setting when I called `asyncio.sleep()` in my `aiohttp Application` with `AioHTTPTestCase`.

Because `asyncio.sleep()` still try to access `main loop` by calling `get_event_loop()` regardless of a loop over which the `Application `is run.

For example,

```
# main.py

import asyncio
from aiohttp import web

async def background_task():
    await asyncio.sleep(5)

async def start_up_test(app):
    app.loop.create_task(background_task())

def get_application(bg_tasks=[]):
    app = web.Application()
    app.on_startup.append(start_up_test)
    return app
```
---
```
# main_test.py

import main
from aiohttp import test_utils

class TestMain(test_utils.AioHTTPTestCase):

    async def get_application(self):
        return main.get_application()

    @test_utils.unittest_run_loop
    async def test_main(self):
        pass
```
---
```
$ python -m unittest main_test
Task exception was never retrieved
future: <Task finished coro=<background_task() done, defined at /home/sangmin/workspace/main.py:78> exception=RuntimeError("There is no current event loop in thread 'MainThread'.",)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/sangmin/workspace/main.py", line 79, in background_task
    await asyncio.sleep(5)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 510, in sleep
    loop = events.get_event_loop()
  File "/usr/lib/python3.5/asyncio/events.py", line 632, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/usr/lib/python3.5/asyncio/events.py", line 578, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.
.
----------------------------------------------------------------------
Ran 1 test in 0.021s

OK
```

As you can see in the `Trace`, `asyncio.sleep()` still try to access `main loop` though it is run over `test loop`, raising `RuntimeError` exception. 

## Expected behaviour

Set a `new loop` as the `main loop` before returning  the `new loop`. by calling `asyncio.set_event_loop(loop)` or something.

## Actual behaviour

Just clear the `main loop`, leaving it empty. It results in `RuntimeError` when `asyncio` method try to call `get_event_loop()`

## Steps to reproduce

Refer the above example.

## Your environment

Ubuntu 16.04
Python 3.5.2 
aiohttp 2.3.9  (server)

**Comment by asvetlov** [comment]
Upgrade Python to 3.5.3 at least otherwise your code is still potentially buggy regardless of global loop initialization
