### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by wuyazi** [aio-libs/aiohttp#2796]
I want to fetch args from request by request method like flask instead of request.match_info.
```
@app.route('/post/<int:post_id>')
def show_post(post_id):
    # show the post with the given id, the id is an integer
    return 'Post %d' % post_id
```
so, i build a BaseApi class to change the request method:
```
import functools

from aiohttp import web
from aiohttp import hdrs


def _embed_params(func):
    """
    embed params from match_info
    """
    @functools.wraps(func)
    def new_func(self, *args, **kwargs):
        kwargs.update(self.request.match_info)
        return func(self, *args, **kwargs)
    return new_func


class BaseApi(web.View):

    def __new__(cls, request):
        if request.method in hdrs.METH_ALL:
            method = request.method.lower()
            if hasattr(cls, method):
                # embed params from match_info
                embed_method = _embed_params(getattr(cls, method))
                setattr(cls, method, embed_method)
        return super(BaseApi, cls).__new__(cls)

    def output(self, data):
        return web.Response(text=data)
```
so, i can write a View class like this, i can fetch `name` from request method args
```
from aioview.validate import validate_params
from aioview.validate import StringValidator
from aioview.validate import EmailValidator
from aioview.api import BaseApi


class UserApi(BaseApi):

    get_params = {
        "email": EmailValidator(required=True, null=False),
        "ref": StringValidator(required=True, null=False),
    }

    @validate_params(get_params)
    async def get(self, name, params=None):
        text = "Hello, " + name
        return self.output(text)
```
it can works.
But, when i do http load test use siege, it raise a Exception
```
siege -c 100 -r 5 http://127.0.0.1:8080/user/asdfsfd\?email\=asdf@qq.com\&ref\=asdasdfasdf
```
the exception is:
```
Error handling request
Traceback (most recent call last):
  File "/Users/wuyazi/.virtualenvs/aiohttp/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 381, in start
    resp = await self._request_handler(request)
  File "/Users/wuyazi/.virtualenvs/aiohttp/lib/python3.6/site-packages/aiohttp/web_app.py", line 310, in _handle
    resp = await handler(request)
  File "/Users/wuyazi/.virtualenvs/aiohttp/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/Users/wuyazi/italki/mississippi/src/middlewares/error.py", line 10, in middleware_handler
    response = await handler(request)
  File "/Users/wuyazi/.virtualenvs/aiohttp/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 741, in _iter
    resp = await method()
  File "/Users/wuyazi/italki/mississippi/src/apis/base.py", line 15, in new_func
    return func(*args, **kwargs)
  File "/Users/wuyazi/italki/mississippi/src/apis/base.py", line 15, in new_func
    return func(*args, **kwargs)
  File "/Users/wuyazi/italki/mississippi/src/apis/base.py", line 15, in new_func
    return func(*args, **kwargs)
  [Previous line repeated 489 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```
the code in https://github.com/wuyazi/aioview

**Comment by asvetlov** [comment]
As I see the recursion is inside your code, not in aiohttp. 
`new_func` recursively calls itself.

Closing the issue.

**Comment by wuyazi** [comment]
@asvetlov 
yes, i think so,
but i do not know how to fix it.
can you tell me?

**Comment by asvetlov** [comment]
Don't modify *class* attributes on creation of view *instance* in `__new__`, every next view instantiation wraps decorated method again and again.
