### ISSUE TITLE
Random crash occurs

### ISSUE THREAD

**Issue by mennovanhout** [aio-libs/aiohttp#2907]
## Long story short

Random aiohttp crashes

## Expected behaviour

That there wouldn't be an error.

## Actual behaviour

It crashes after a random amount of time.

## Steps to reproduce

aiohttp server:
```
from aiohttp import web
import socketio

sio = socketio.AsyncServer()
app = web.Application()
sio.attach(app)

connections = { }

# On client connect
@sio.on('connect')
def connect(sid, environ):
    print("New connection ", "(" + sid + ")")

# On client disconnect
@sio.on('disconnect')
def disconnect(sid):
    print('Disconnected ', "(" + sid + ")")

# Say Hi to eachother
@sio.on('hello')
def hello(sid, data):
    connections[sid] = data
    print("hello ", "I am " + data + " with sid: " + sid)

if __name__ == '__main__':
    web.run_app(app)
```

The crash:
```
Traceback (most recent call last):   
File "C:\...\lib\site-packages\aiohttp\web_protocol.py", line 381, in start
resp = await self._request_handler(request)   
File "C:\...\lib\site-packages\aiohttp\web_app.py", line 322, in _handle
    resp = await handler(request)   
File "C:\...\lib\site-packages\engineio\asyncio_server.py", line 146, in handle_request
    packets = await socket.handle_get_request(environ)   
File "C:\...\lib\site-packages\engineio\asyncio_socket.py", line 76, in handle_get_request
    return await getattr(self, '_upgrade_' + transport)(environ)   
File "C:\...\lib\site-packages\engineio\asyncio_socket.py", line 118, in _upgrade_websocket
    return await ws(environ)   
File "C:\...\lib\site-packages\engineio\async_aiohttp.py", line 96, in __call__
    await self.handler(self)   
File "C:\...\lib\site-packages\engineio\asyncio_socket.py", line 138, in _websocket_handler
    pkt = await ws.wait()   
File "C:\...\lib\site-packages\engineio\async_aiohttp.py", line 116, in wait
    raise IOError()
OSError
```

## Your environment

Working with visual studio 2017
Installed:
- Python
- Aiohttp
- python-socketio

**Comment by thomaszdxsn** [comment]
Look like not cause by `aiohttp`, but throw error by wrapper package。see:

```python
...
File "C:\...\lib\site-packages\engineio\async_aiohttp.py", line 116, in wait
    raise IOError()
```

You need issue on [engineio](https://github.com/miguelgrinberg/python-engineio)

**Comment by asvetlov** [comment]
Agree with @thomaszdxsn 
Closing the issue

**Comment by UGxMvH** [comment]
Hi there,

Is it possible to return a boolean wherever it is realy shared or canceled.

Also is it posible to return a string or something to know on which
platform it is shared.

Greetings,
Menno

2018-04-09 0:32 GMT+02:00 Andrew Svetlov <notifications@github.com>:

**Comment by asvetlov** [comment]
Sorry, I don't follow.

**Comment by UGxMvH** [comment]
We use the function NativeShare.share(ARGUMENTS);

It would be nice to have some feedback whether it is actually shared or not
and on which platform

2018-04-11 12:28 GMT+02:00 Andrew Svetlov <notifications@github.com>:

**Comment by asvetlov** [comment]
Please file an issue in socketio bugtracker.
aiohttp has not `NativeShare` at all, your question is out of the library scope.
