### ISSUE TITLE
WebSocket.send_str corroutine

### ISSUE THREAD

**Issue by ikit** [aio-libs/aiohttp#2974]
Hi, it's more a question than an issue.

I'm using the method send_str() method of WebSocket. But today I updated aiohttp to the version 3.0 and this method is now a coroutine. 

As I'm using websockets almost everywhere in my code to notify the clients, it's hard to convert all my code into coroutine.
And I need help to fix it in the best way.

### Code version 1 (before version 3.0)
below the method that i'm calling "almost everywhere":
```python
def rest_notify_all(data):
    data = local_path_to_pub_url(data)
    msg = json.dumps(data)
    for ws in WebsocketHandler.socket_list:
        ws[0].send_str(msg)
```

calling this method cause the following exception
```python
<CoroWrapper WebSocketResponse.send_str() running at /usr/local/lib/python3.6/site-packages/aiohttp/web_ws.py:250, created at /usr/local/lib/python3.6/asyncio/coroutines.py:85> was never yielded from
Coroutine object created at (most recent call last, truncated to 10 last lines):
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_app.py", line 322, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.6/site-packages/aiohttp_session/__init__.py", line 132, in factory
    response = await handler(request)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/var/regovar_app/api_rest/rest.py", line 233, in get
    core.notify_all(msg)
  File "/var/regovar_app/api_rest/rest.py", line 130, in rest_notify_all
    ws[0].send_str(msg)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 85, in debug_wrapper
    return CoroWrapper(gen, None)
```

### Code version 2
So I tryed to use the `run_until_complete` method
```python
def rest_notify_all(data):
    data = local_path_to_pub_url(data)
    msg = json.dumps(data)
    for ws in WebsocketHandler.socket_list:
        asyncio.get_event_loop().run_until_complete(ws[0].send_str(msg))
```
But I got this error in some cases
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 381, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_app.py", line 322, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.6/site-packages/aiohttp_session/__init__.py", line 132, in factory
    response = await handler(request)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/var/regovar_app/api_rest/rest.py", line 233, in get
    core.notify_all(msg)
  File "/var/regovar_app/api_rest/rest.py", line 130, in rest_notify_all
    run_until_complete(ws[0].send_str(msg))
  File "/var/regovar_app/core/framework/common.py", line 49, in run_until_complete
    asyncio.get_event_loop().run_until_complete(future)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 455, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 409, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```

### Code version 3
So I tryied this way
```python
def rest_notify_all(data):
    data = local_path_to_pub_url(data)
    msg = json.dumps(data)
    for ws in WebsocketHandler.socket_list:
        asyncio.run_coroutine_threadsafe(ws[0].send_str(msg), asyncio.get_event_loop())
```
But another error when I'm calling notify all from another thread (using `asynchio.run_in_executor`)
```python
Future exception was never retrieved
future: <Future finished exception=RuntimeError("There is no current event loop in thread 'ThreadPoolExecutor-4_0'.",) created at /usr/local/lib/python3.6/asyncio/base_events.py:276>
source_traceback: Object created at (most recent call last):
  File "regovar.py", line 35, in <module>
    web.run_app(app, host=HOST, port=PORT)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web.py", line 117, in run_app
    loop.run_forever()
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1424, in _run_once
    handle._run()
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 126, in send
    return self.gen.send(value)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 381, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_app.py", line 322, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.6/site-packages/aiohttp_session/__init__.py", line 132, in factory
    response = await handler(request)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/var/regovar_app/api_rest/rest.py", line 114, in wrapped
    return await f(self, request)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/var/regovar_app/api_rest/handlers/sample_handler.py", line 114, in import_from_file
    samples = await core.samples.import_from_file(file_id, ref_id)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/var/regovar_app/core/managers/sample_manager.py", line 91, in import_from_file
    result = await importer.import_data(file_id, reference_id=reference_id)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/var/regovar_app/core/managers/imports/vcf_manager.py", line 763, in import_data
    run_async(self.import_delegate, file_id, vcf_reader, reference_id, db_ref_suffix, vcf_metadata, samples)
  File "/var/regovar_app/core/framework/common.py", line 61, in run_async
    asyncio.get_event_loop().run_in_executor(None, future, *args)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 639, in run_in_executor
    return futures.wrap_future(executor.submit(func, *args), loop=self)
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 428, in wrap_future
    new_future = loop.create_future()
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 276, in create_future
    return futures.Future(loop=self)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/regovar_app/core/managers/imports/vcf_manager.py", line 638, in import_delegate
    core.notify_all({"action": "import_vcf_processing", "data" : {"reference_id": reference_id, "file_id" : file_id, "status" : "loading", "progress": progress, "samples": [ {"id" : samples[sname]["id"], "name" : sname} for sname in samples]}})
  File "/var/regovar_app/api_rest/rest.py", line 130, in rest_notify_all
    run_until_complete(ws[0].send_str(msg))
  File "/var/regovar_app/core/framework/common.py", line 49, in run_until_complete
    asyncio.run_coroutine_threadsafe(future, asyncio.get_event_loop())
  File "/usr/local/lib/python3.6/asyncio/events.py", line 694, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/usr/local/lib/python3.6/asyncio/events.py", line 602, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-4_0'.

```

### My questions
1. Why `send_str` is now a coroutine ? 
2. How it's suppose to be used, did you have some example ?
3. In my case, as I'm using websocket everywhere, sometime in multithread, etc, do you have any idea how to fix my code ? Will have I to change all my code as coroutine or do you thinks that there is a "workaround" that will allow me to call the send_str method without changing the signature of  `def notify_all(...)` ?

**Comment by asvetlov** [comment]
Suppose you produce a data for websocket very often.
Suppose the connection to websocket peer is slow.
If `send_str()` is not a coroutine the method call doesn't wait for actual data sending but stores the data into an internal buffer.
Shortly it leads to out-of-memory error.

Since `send_str()` is a coroutine -- call it from other coroutine as `await ws.send_str(data)`.

You need two `notify_all()` versions: one for async code and another for usage from other threads.
`run_until_complete()` cannot be called from a coroutine.
`get_event_loop()` returns a current thread's loop. not the global system one.

You cannot use bare `run_coroutine_threadsafe()` exactly for the same reason as `send_str()` is not a non-blocking function. To avoid potential memory error you need to wait for returned future.

**Comment by ikit** [comment]
thanks for your answer,

I'm not sure to understand what you means by "To avoid potential memory error you need to wait for returned future". The only way I know to wait the returned of a coroutine, is to call `get_event_loop().run_until_complete(...)`

So I created 2 methods:
```python
def rest_notify_all(data)
    data = local_path_to_pub_url(data)
    msg = json.dumps(data)
    loop = asyncio.new_event_loop()
    for ws in WebsocketHandler.socket_list:
        loop.run_until_complete(ws[0].send_str(msg))
    loop.close()

async def rest_notify_all_co(data)
    data = local_path_to_pub_url(data)
    msg = json.dumps(data)
    for ws in WebsocketHandler.socket_list:
        await ws[0].send_str(msg)
``` 
`rest_notify_all` to be called from thread when I use `asyncio.get_event_loop().run_in_executor` by example
and `rest_notify_all_co` for async code. 

Regarding `rest_notify_all`, is it the good way to do (creating a new event loop) ?

**Comment by asvetlov** [comment]
It doesn't work, you need to use not a new event loop but the loop used to serve aiohttp application.

**Comment by ikit** [comment]
ok, thanks for your support :+1:  

```python
main_loop = asyncio.get_event_loop()
...
def rest_notify_all(data)
    data = local_path_to_pub_url(data)
    msg = json.dumps(data)
    for ws in WebsocketHandler.socket_list:
        asyncio.run_coroutine_threadsafe(ws[0].send_str(msg), main_loop)
```
