### ISSUE TITLE
Useless exception

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#305]
`form.add_field('name', 'текст', content_type='text/plain; charset: asadasdadkoi8-r')`

for this got i receive exception like "Can not write request body"
can we make it more clear?

**Comment by kxepal** [comment]
I believe we can. Will take a look.

**Comment by fafhrd91** [comment]
Thanks

**Comment by fafhrd91** [comment]
@kxepal should we close this issue

**Comment by kxepal** [comment]
Not yet. I have a plan, but no time ): Thanks for ping.

**Comment by fafhrd91** [comment]
@kxepal another ping

**Comment by kxepal** [comment]
Reproduced with the foillowing traceback:
```
Traceback (most recent call last):
  File "/home/kxepal/projects/aio-libs/aiohttp/aiohttp/client_reqrep.py", line 361, in write_bytes
    result = stream.send(value)
  File "/home/kxepal/projects/aio-libs/aiohttp/aiohttp/helpers.py", line 192, in _gen_form_data
    part = self._writer.append(value, headers)
  File "/home/kxepal/projects/aio-libs/aiohttp/aiohttp/multipart.py", line 950, in append
    self.parts.append(self.part_writer_cls(obj, headers))
  File "/home/kxepal/projects/aio-libs/aiohttp/aiohttp/multipart.py", line 677, in __init__
    self._fill_headers_with_defaults()
  File "/home/kxepal/projects/aio-libs/aiohttp/aiohttp/multipart.py", line 708, in _fill_headers_with_defaults
    content_length = self._guess_content_length(self.obj)
  File "/home/kxepal/projects/aio-libs/aiohttp/aiohttp/multipart.py", line 723, in _guess_content_length
    return len(obj.encode(charset))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 14, in <module>
    asyncio.get_event_loop().run_until_complete(test())
  File "/usr/lib64/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "test.py", line 10, in test
    async with session.post("https://google.com", data=form) as response:
  File "/home/kxepal/projects/aio-libs/aiohttp/aiohttp/client.py", line 540, in __aenter__
    self._resp = yield from self._coro
  File "/home/kxepal/projects/aio-libs/aiohttp/aiohttp/client.py", line 181, in _request
    yield from resp.start(conn, read_until_eof)
  File "/home/kxepal/projects/aio-libs/aiohttp/aiohttp/client_reqrep.py", line 614, in start
    message = yield from httpstream.read()
  File "/home/kxepal/projects/aio-libs/aiohttp/aiohttp/streams.py", line 644, in read
    result = yield from super().read()
  File "/home/kxepal/projects/aio-libs/aiohttp/aiohttp/streams.py", line 475, in read
    yield from self._waiter
  File "/usr/lib64/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
aiohttp.errors.ClientRequestError: Can not write request body for https://google.com
```

The first exception is about serialization, second is about the failed request. So, for me it's a bit confusing, but it's possible to find out what the problem source.

To fix this completely will require to rewrite a bit FormData in the way, at least to always add a data to internal multipart writer whenever form will be send as multipart or not. But this may produce false negative exceptions when some of data will be good for urlencode, but not for multipart defaults. No specific case for this, just a theory.

In the end, the issue here is like the same as if you pass generator as a request data: you'll get exception in the middle of request with more or less similar result.

Should I improve FormData to catch this case or we'll leave things as is?

**Comment by fafhrd91** [comment]
i would prefer to have proper exception message. right now it is not clear what data is wrong.
but it is up to you.

**Comment by fafhrd91** [comment]
now we throw ValueError 

```
ValueError: Can not serialize value type: <class 'str'>
 headers: {'Content-Type': 'text/plain; charset=asadasdadkoi8-r'}
 value: 'текст'
```
