### ISSUE TITLE
TimeoutError: Proper way to read chunk wise?

### ISSUE THREAD

**Issue by livioso** [aio-libs/aiohttp#3067]
## Long story short

- When fetching files chunk-wise, we get `TimeoutError` - dependent on hardware (processing power, chunk size) sooner or later. E.g. On a MBP 2017, Python 3.65 + aiohttp 3.3 while reading a 10GB file chunk wise at 512KB per `read`. On an embedded Linux w/ limited processing power + 512 bytes chunk size much earlier (e.g. 512Bytes / 80MB file).
- See https://github.com/rauc/rauc-hawkbit/pull/8. Which chunk size makes sense? Can we just catch it and retry reading or is this a bad idea?
- Same happens with using `read_chunk` - what's the proper way to read chunk wise?

## Expected behaviour

- No `TimeoutError` exception

## Actual behaviour

```
Traceback (most recent call last):
  File "aiohttp-rauc-hawkbit.py", line 30, in <module>
    loop.run_until_complete(main())
  File "/usr/local/opt/asdf/installs/python/3.6.5/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "aiohttp-rauc-hawkbit.py", line 22, in main
    await fetch(session, 'https://speed.hetzner.de/10GB.bin')
  File "/usr/local/opt/asdf/installs/python/3.6.5/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "aiohttp-rauc-hawkbit.py", line 8, in fetch
    chunk = await response.content.read(512000)
  File "/usr/local/opt/asdf/installs/python/3.6.5/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/Users/livioso/.local/share/virtualenvs/third-party-api-experiments-pge9BDZy/lib/python3.6/site-packages/aiohttp/streams.py", line 319, in read
    await self._wait('read')
  File "/usr/local/opt/asdf/installs/python/3.6.5/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/Users/livioso/.local/share/virtualenvs/third-party-api-experiments-pge9BDZy/lib/python3.6/site-packages/aiohttp/streams.py", line 250, in _wait
    await waiter
  File "/Users/livioso/.local/share/virtualenvs/third-party-api-experiments-pge9BDZy/lib/python3.6/site-packages/aiohttp/helpers.py", line 671, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
```

- I think `read` eventually times out since `feed_data` is not able to feed data i time and the timeout is reached (is the timeout too conservative?).

## Steps to reproduce

```
import aiohttp
import asyncio


async def fetch(session, url):
    async with session.get(url) as response:
        while True:
            chunk = await response.content.read(512000)

            # a) same issue, eventually breaks
            # chunk, _ = await response.content.readchunk()

            # b) no effect
            # asyncio.sleep(0.001)

            if not chunk:
                break


async def main():
    async with aiohttp.ClientSession() as session:
        await fetch(session, 'https://speed.hetzner.de/10GB.bin')
        # await fetch(session, 'http://localhost:2280/huge.zip')
        # await fetch(session, 'http://localhost:2280/segin-rootfs-update-02.raucb')
        # await fetch(session, 'https://speed.hetzner.de/100MB.bin')
        print('Success')

loop = asyncio.get_event_loop()
loop.set_debug(True)
loop.run_until_complete(main())
```

## Your environment

- Python 3.6.5
- aiohttp 3.3 (latest)

**Comment by asvetlov** [comment]
There is no "good chunk size" for everything.
Maybe you need to configure timeouts?
https://docs.aiohttp.org/en/stable/client_quickstart.html#timeouts and https://docs.aiohttp.org/en/stable/client_reference.html#clienttimeout can provide more info.

**Comment by Bastian-Krause** [comment]
So any download taking longer than 5 minutes will run in this default timeout? What's the reasoning behind this?

**Comment by asvetlov** [comment]
It is a tradeoff.
Infinite HTTP request is a pain, it looks like hang. 
aiohttp provides flexible timeout configuration, use it.

**Comment by livioso** [comment]
^ Regarding my example: That's actually what happens; it times out after 5 minutes... (unfortunately the stack trace is the same as in https://github.com/rauc/rauc-hawkbit/pull/8 so I got confused). :-/
