### ISSUE TITLE
Client timeouts when raise_for_status is used with connection limit

### ISSUE THREAD

**Issue by pauleikis** [aio-libs/aiohttp#3112]
## Long story short

When using connection limit in TCPConnector and `raise_for_status=True`, when exception is thrown the connection cannot be reused and further requests raise `asyncio.TimeoutError`.

## Expected behaviour

After the exception is raised, the connection is cleaned up and can be reused

## Steps to reproduce

```python
import asyncio
import aiohttp
import aiohttp.web


async def working_client(loop):
    print("START WORKING")
    timeout = aiohttp.ClientTimeout(total=3)  # is not relevant to the test case, just to show error faster
    tcp_connector = aiohttp.TCPConnector(limit=1)
    async with aiohttp.ClientSession(connector=tcp_connector, timeout=timeout) as session:
        for _ in range(2):
            try:
                async with session.get("http://localhost:8742/plop") as response:
                    print((await response.read())[:50], '...')
                    response.raise_for_status()
            except aiohttp.ClientResponseError as e:
                print("RETRYING FOR status =", e.status)
    print("END WORKING")


async def not_working_client(loop):
    print("START NOT WORKING")
    timeout = aiohttp.ClientTimeout(total=3)  # is not relevant to the test case, just to show error faster
    tcp_connector = aiohttp.TCPConnector(limit=1)
    async with aiohttp.ClientSession(connector=tcp_connector, timeout=timeout, raise_for_status=True) as session:
        for _ in range(2):
            try:
                async with session.get("http://localhost:8742/plop") as response:
                    print(await response.read())
            except aiohttp.ClientResponseError as e:
                print("RETRYING FOR status =", e.status)
    print("END NOT WORKING")


r404 = False


@asyncio.coroutine
def handler(request):
    global r404
    r404 = not r404
    if r404:
        return aiohttp.web.Response(status=404, body="A" * 200_000)  # this needs to be big, cannot reproduce bug with small body

    return aiohttp.web.Response(body="OK")


@asyncio.coroutine
def main_server(loop):
    global server
    server = aiohttp.web.Server(handler)
    yield from loop.create_server(server, "0.0.0.0", 8742)


# case preparation : craft a server with big writes
loop = asyncio.get_event_loop()
loop.run_until_complete(main_server(loop))

# execution of the client
loop.run_until_complete(working_client(loop))
loop.run_until_complete(not_working_client(loop))

# garbage collecting
loop.run_until_complete(server.shutdown(10))
```

```
START WORKING
b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' ...
RETRYING FOR status = 404
b'OK' ...
END WORKING
START NOT WORKING
RETRYING FOR status = 404
Traceback (most recent call last):
  File "raise.py", line 61, in <module>
    loop.run_until_complete(not_working_client(loop))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "raise.py", line 28, in not_working_client
    async with session.get("http://localhost:8742/plop") as response:
  File "/Users/psileikis/projects/tsunami/.venv/lib/python3.6/site-packages/aiohttp/client.py", line 843, in __aenter__
    self._resp = await self._coro
  File "/Users/psileikis/projects/tsunami/.venv/lib/python3.6/site-packages/aiohttp/client.py", line 387, in _request
    await resp.start(conn)
  File "/Users/psileikis/projects/tsunami/.venv/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 761, in start
    self._continue = None
  File "/Users/psileikis/projects/tsunami/.venv/lib/python3.6/site-packages/aiohttp/helpers.py", line 677, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
```
## Your environment

     aiohttp==3.3.2
     Mac OS 10.13.5, but the bug first surfaced on centos-release-7-5.1804.el7.centos.2.x86_64 so it should be widespread
     
     This is related to aiohttp client only.

**Comment by pauleikis** [comment]
As it depends on the response length, it might be related to #2217

**Comment by Dreamsorcerer** [comment]
Seems to work on current releases (probably something fixed with releasing connections):
```
START WORKING
b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' ...
RETRYING FOR status = 404
b'OK' ...
END WORKING
START NOT WORKING
RETRYING FOR status = 404
b'OK'
END NOT WORKING
```
