### ISSUE TITLE
aiohttp.http_exceptions.BadStatusLine: 0 exception for any request to Apache/Django-Rest-Framework

### ISSUE THREAD

**Issue by dmarkey** [aio-libs/aiohttp#3121]
## Long story short

An exception is raised while trying to interact with an internal Apache/Django-Rest-Framework web service (using aiohttp as a client)

## Expected behaviour

GET/POST works correctly

(It works fine with requests, curl and httpie)

## Actual behaviour

An exception is raised

## Steps to reproduce

Unfortunately this is an internal service and I will only be able to reproduce

## Your environment

Python 3.6 client on Arch linux, aiohttp 3.3.2
Exception:
```Traceback (most recent call last):
  File "/home/dmarkey/src/proj/venv/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 748, in start
    message, payload = await self._protocol.read()
  File "/usr/lib64/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/home/dmarkey/src/proj/venv/lib/python3.6/site-packages/aiohttp/streams.py", line 533, in read
    await self._waiter
  File "/home/dmarkey/src/proj/venv/lib/python3.6/site-packages/aiohttp/client_proto.py", line 195, in data_received
    messages, upgraded, tail = self._parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 297, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid constant string'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "aio_http_request.py", line 17, in <module>
    loop.run_until_complete(test())
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "aio_http_request.py", line 10, in test
    async with aiohttp.request("post", url, json={"some": "value"}, headers=headers) as resp:
  File "/usr/lib64/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/home/dmarkey/src/proj/venv/lib/python3.6/site-packages/aiohttp/client.py", line 872, in __aenter__
    self._resp = await self._coro
  File "/usr/lib64/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/home/dmarkey/src/proj/venv/lib/python3.6/site-packages/aiohttp/client.py", line 387, in _request
    await resp.start(conn)
  File "/usr/lib64/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/home/dmarkey/src/proj/venv/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 753, in start
    message=exc.message, headers=exc.headers) from exc
aiohttp.client_exceptions.ClientResponseError: 400, message='invalid constant string'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fed0def42e8>
source_traceback: Object created at (most recent call last):
  File "aio_http_request.py", line 17, in <module>
    loop.run_until_complete(test())
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 455, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 1424, in _run_once
    handle._run()
  File "/usr/lib64/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "aio_http_request.py", line 10, in test
    async with aiohttp.request("post", url, json={"some": "value"}, headers=headers) as resp:
  File "/home/dmarkey/src/proj/venv/lib/python3.6/site-packages/aiohttp/client.py", line 938, in request
    connector=connector, connector_owner=connector_owner)
```
Script:
```
import aiohttp
import asyncio


async def test():
    url = "http://internalservice/v1.0/oauth/token/"
    headers = {
        'Authorization': "Basic <redacted>"}
    async with aiohttp.request("post", url, json={"some": "value"}, headers=headers) as resp:
        print(resp.status)
        print(await resp.text())


loop = asyncio.get_event_loop()

loop.run_until_complete(test())

```

With AIOHTTP_NO_EXTENSIONS=1:

```
Traceback (most recent call last):
  File "/home/dmarkey/src/proj/venv/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 748, in start
    message, payload = await self._protocol.read()
  File "/usr/lib64/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/home/dmarkey/src/proj/venv/lib/python3.6/site-packages/aiohttp/streams.py", line 533, in read
    await self._waiter
  File "/home/dmarkey/src/proj/venv/lib/python3.6/site-packages/aiohttp/client_proto.py", line 195, in data_received
    messages, upgraded, tail = self._parser.feed_data(data)
  File "/home/dmarkey/src/proj/venv/lib/python3.6/site-packages/aiohttp/http_parser.py", line 142, in feed_data
    msg = self.parse_message(self._lines)
  File "/home/dmarkey/src/proj/venv/lib/python3.6/site-packages/aiohttp/http_parser.py", line 414, in parse_message
    raise BadStatusLine(line) from None
aiohttp.http_exceptions.BadStatusLine: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "new_file.py", line 17, in <module>
    loop.run_until_complete(test())
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "new_file.py", line 10, in test
    async with aiohttp.request("post", url, json={"some": "value"}, headers=headers) as resp:
  File "/usr/lib64/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/home/dmarkey/src/proj/venv/lib/python3.6/site-packages/aiohttp/client.py", line 872, in __aenter__
    self._resp = await self._coro
  File "/usr/lib64/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/home/dmarkey/src/proj/venv/lib/python3.6/site-packages/aiohttp/client.py", line 387, in _request
    await resp.start(conn)
  File "/usr/lib64/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/home/dmarkey/src/proj/venv/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 753, in start
    message=exc.message, headers=exc.headers) from exc
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f63e1c87358>
source_traceback: Object created at (most recent call last):
  File "new_file.py", line 17, in <module>
    loop.run_until_complete(test())
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 455, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 1424, in _run_once
    handle._run()
  File "/usr/lib64/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "new_file.py", line 10, in test
    async with aiohttp.request("post", url, json={"some": "value"}, headers=headers) as resp:
  File "/home/dmarkey/src/proj/venv/lib/python3.6/site-packages/aiohttp/client.py", line 938, in request
    connector=connector, connector_owner=connector_owner)

**Comment by asvetlov** [comment]
Optimized C parser cannot process HTTP message from the peer.
Most likely it is a sign of incorrect HTTP headers or something like this.
You can try to switch to pure python parser by setting `AIOHTTP_NO_EXTENSIONS` env var.

Upd.
Aaah, you did it already.
Sorry, I cannot provide more help without looking at the server response.
But if the response cannot be parsed by C and Python HTTP parsers (they have independent implementations) -- something is wrong with your server.

**Comment by Dreamsorcerer** [comment]
Closing as this is very old and the server response was never provided (it's probably expected behaviour, as the output suggests the server sent '0' as the status line, which would be totally useless).
