### ISSUE TITLE
logging.exception(HTTPException) does not print underlying chained exception

### ISSUE THREAD

**Issue by ArthurKantor** [aio-libs/aiohttp#3167]
## Long story short

Example of badness:
```python
import logging
from aiohttp import web_exceptions   

def f():
  try:
        raise Exception('hi mom')
  except Exception as e:
        raise web_exceptions.HTTPBadRequest(reason='chaining an exception from hi mom')

try:    
    f() 
except Exception as e:   
    logging.exception(e) 
```
outputs
```
ERROR:root:chaining an exception from hi mom
Traceback (most recent call last):
  File "<ipython-input-4-6ec4e29d6e22>", line 11, in <module>
    f()
  File "<ipython-input-4-6ec4e29d6e22>", line 8, in f
    raise web_exceptions.HTTPBadRequest(reason='chaining an exception from hi mom')
aiohttp.web_exceptions.HTTPBadRequest: chaining an exception from hi mom
```
This probably has to do with `HTTPException` deriving from `Response`
## Expected behaviour
It would be nice to also see the underlying exceptions...
```python
def g():
    try:
        raise Exception('hi mom2')
    except Exception as e:
        raise ValueError('chaining a normal exception from hi mom2')
try:    
    g() 
except Exception as e:  
    logging.exception(e)
```
which outputs 
```
ERROR:root:chaining a normal exception from hi mom2
Traceback (most recent call last):
  File "<ipython-input-6-2590806aa1fb>", line 3, in g
    raise Exception('hi mom2')
Exception: hi mom2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<ipython-input-6-2590806aa1fb>", line 7, in <module>
    g()
  File "<ipython-input-6-2590806aa1fb>", line 5, in g
    raise ValueError('chaining a normal exception from hi mom2')
ValueError: chaining a normal exception from hi mom2
```

## Your environment

aiohttp 3.3.2
python 3.7

**Comment by asvetlov** [comment]
Fixed by #3098
Will be available in the next release
