### ISSUE TITLE
error in virtualenv - python3.4 and django

### ISSUE THREAD

**Issue by aztrock** [aio-libs/aiohttp#317]
Traceback (most recent call last):
  File "/opt/datacelco/lib/python3.4/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/opt/datacelco/src/aiohttp/aiohttp/worker.py", line 28, in init_process
    super().init_process()
  File "/opt/datacelco/lib/python3.4/site-packages/gunicorn/workers/base.py", line 120, in init_process
    self.run()
  File "/opt/datacelco/src/aiohttp/aiohttp/worker.py", line 34, in run
    self.loop.run_until_complete(self._runner)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 268, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 236, in _step
    result = next(coro)
  File "/opt/datacelco/src/aiohttp/aiohttp/worker.py", line 80, in _run
    handler = self.make_handler(self.wsgi, *sock.cfg_addr)
  File "/opt/datacelco/src/aiohttp/aiohttp/worker.py", line 46, in make_handler
    return app.make_handler(
AttributeError: 'WSGIHandler' object has no attribute 'make_handler'

**Comment by fafhrd91** [comment]
what version of gunicorn and aiohttp do you use?

**Comment by mkhndrsn** [comment]
I'm getting the same error. I'm using gunicorn 19.3.0, aiohttp 0.15.1 and django 1.7 and python 3.4

Here is the full stacktrace:

```
Traceback (most recent call last):
  File "/website/.virtualenv/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    self.cfg.pre_fork(self, worker)
  File "/website/.virtualenv/lib/python3.4/site-packages/aiohttp/worker.py", line 28, in init_process
    super().init_process()
  File "/website/.virtualenv/lib/python3.4/site-packages/gunicorn/workers/base.py", line 112, in init_process
    util.close_on_exec(self.tmp.fileno())
  File "/website/.virtualenv/lib/python3.4/site-packages/aiohttp/worker.py", line 34, in run
    self.loop.run_until_complete(self._runner)
  File "/usr/local/lib/python3.4/asyncio/base_events.py", line 208, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.4/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/local/lib/python3.4/asyncio/tasks.py", line 283, in _step
    result = next(coro)
  File "/website/.virtualenv/lib/python3.4/site-packages/aiohttp/worker.py", line 80, in _run
    handler = self.make_handler(self.wsgi, *sock.cfg_addr)
  File "/website/.virtualenv/lib/python3.4/site-packages/aiohttp/worker.py", line 46, in make_handler
    return app.make_handler(
  File "/website/.virtualenv/lib/python3.4/site-packages/newrelic-2.32.0.28/newrelic/common/object_wrapper.py", line 50, in __getattr__
    return _ObjectProxy.__getattr__(self, name)
AttributeError: 'WSGIHandler' object has no attribute 'make_handler'
```

**Comment by aztrock** [comment]
same version gunicorn 19.3

**Comment by fafhrd91** [comment]
aiohttp/worker.py does not support wsgi applications. Also it is not possible to run django app with aiohttp, but it might be with aiohttp-wsgi https://github.com/etianen/aiohttp-wsgi

**Comment by mkhndrsn** [comment]
That works. Thanks @fafhrd91
