### ISSUE TITLE
aiohttp can't crawl any website 

### ISSUE THREAD

**Issue by xiantang** [aio-libs/aiohttp#3179]
```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<Downloader.worker() done, defined at /home/didi/repertory/mini_scrapy/mini_scrapy/Markdown/domo_aio.py:44> exception=ClientConnectorError(-3, 'Temporary failure in name resolution')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 813, in _create_direct_connection
    hosts = yield from self._resolve_host(req.url.raw_host, req.port)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 718, in _resolve_host
    yield from self._throttle_dns_events[key].wait()
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 813, in _create_direct_connection
    hosts = yield from self._resolve_host(req.url.raw_host, req.port)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 718, in _resolve_host
    yield from self._throttle_dns_events[key].wait()
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 813, in _create_direct_connection
    hosts = yield from self._resolve_host(req.url.raw_host, req.port)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 727, in _resolve_host
    loop=self._loop)
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/resolver.py", line 31, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/didi/repertory/mini_scrapy/mini_scrapy/Markdown/domo_aio.py", line 51, in worker
    content=await self.download(link)
  File "/home/didi/repertory/mini_scrapy/mini_scrapy/Markdown/domo_aio.py", line 36, in download
    async with self.client.get(url) as response:
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 690, in __aenter__
    self._resp = yield from self._coro
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 267, in _request
    conn = yield from self._connector.connect(req)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 402, in connect
    proto = yield from self._create_connection(req)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 749, in _create_connection
    _, proto = yield from self._create_direct_connection(req)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 817, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.amazon.com:443 ssl:True [Temporary failure in name resolution]
```
i use so much website to take replace of `amazon`, and this expection will raise again and again. i don't know what happen. i used to use this yesterday

**Comment by xiantang** [comment]
maybe my ssl was wrong....

**Comment by asvetlov** [comment]
No idea what fails on your box.
I am and many others use aiohttp without such issues.
Check for `socket.getaddrinfo()` execution may help you to pin the bug.

**Comment by webknjaz** [comment]
> maybe my ssl was wrong....
> Temporary failure in name resolution

Fix your DNS.
