### ISSUE TITLE
Allowing a middleware to handle OPTIONS calls by aiohttp-cors signals

### ISSUE THREAD

**Issue by bmamouri** [aio-libs/aiohttp#3228]
## Long story short

Inside my authentication middleware, I want to give the control to `aiohttp-cors` signal to handle CORS request. I created [an issue](https://github.com/aio-libs/aiohttp-cors/issues/193) inside that repository. Please accept my apologies for creating similar issues, but I am not sure which project is more appropriate for my question.

I want to know what is the correct way to deal with OPTIONS calls that should be handled by aiohttp-cors signals in middlewares:

```
@middleware
async def auth_middleware(request, handler):
    if isinstance(request.match_info.route, SystemRoute):  # eg. 404
        return await handler(request)

    if request.method == hdrs.METH_OPTIONS:
        return await handler(request)

    try:
        request['claims'] = await authenticate(request)
    except ValueError as e:
        raise HTTPUnauthorized(PayloadErrors(e.args[0]))

    return await handler(request)
```

## Expected behaviour

Respond with correct CORS headers supplied by aiohttp-cors.

## Actual behaviour

```
Unhandled exception
Traceback (most recent call last):
  File "/python3.7/site-packages/aiohttp/web_protocol.py", line 398, in start
    await resp.prepare(request)
  File "/python3.7/site-packages/aiohttp/web_response.py", line 299, in prepare
    await request._prepare_hook(self)
  File "/python3.7/site-packages/aiohttp/web_request.py", line 686, in _prepare_hook
    await app.on_response_prepare.send(self, response)
  File "/python3.7/site-packages/aiohttp/signals.py", line 35, in send
    await receiver(*args, **kwargs)
  File "/python3.7/site-packages/aiohttp_cors/cors_config.py", line 171, in _on_response_prepare
    assert hdrs.ACCESS_CONTROL_ALLOW_ORIGIN not in response.headers
AssertionError
Unhandled exception
Traceback (most recent call last):
  File "/python3.7/site-packages/aiohttp/web_protocol.py", line 398, in start
    await resp.prepare(request)
  File "/python3.7/site-packages/aiohttp/web_response.py", line 299, in prepare
    await request._prepare_hook(self)
  File "/python3.7/site-packages/aiohttp/web_request.py", line 686, in _prepare_hook
    await app.on_response_prepare.send(self, response)
  File "/python3.7/site-packages/aiohttp/signals.py", line 35, in send
    await receiver(*args, **kwargs)
  File "/python3.7/site-packages/aiohttp_cors/cors_config.py", line 171, in _on_response_prepare
    assert hdrs.ACCESS_CONTROL_ALLOW_ORIGIN not in response.headers
AssertionError
```

## Steps to reproduce
N/A

## Your environment

Docker running on MacOS host

**Comment by samuelcolvin** [comment]
looks like this isn't an issue with aiohttp, best to stick to the issue on aiohttp-cors
