### ISSUE TITLE
aiohttp+gunicorn+DEBUG = A lot of error messages in logs

### ISSUE THREAD

**Issue by klen** [aio-libs/aiohttp#337]
For current version aiohttp I see a lot of exceptions in gunicorn logs when using DEBUG loglevel.

Small example:

```
aiohttp (0.15.2)
gunicorn (19.3.0)
```

`a.py`:

``` python
import asyncio
from aiohttp import web

@asyncio.coroutine
def hello(request):
    return web.Response(body=b"Hello, world")

app = web.Application()
app.router.add_route('GET', '/', hello)
```

Run:

``` sh
$ gunicorn a:app -k aiohttp.worker.GunicornWebWorker -b 0.0.0.0:5000 --log-level DEBUG
```

Output (any connection):

```
[2015-04-20 14:54:43 +0300] [71306] [DEBUG] Start keep-alive timer for 2 sec.
[2015-04-20 14:54:44 +0300] [71303] [DEBUG] 1 workers
[2015-04-20 14:54:45 +0300] [71303] [DEBUG] 1 workers
[2015-04-20 14:54:45 +0300] [71306] [ERROR] Ignored premature client disconnection.
Traceback (most recent call last):
  File "/Users/horneds/Dropbox/projects/zoo/m/.env/lib/python3.4/site-packages/aiohttp/server.py", line 237, in start
    message = yield from httpstream.read()
  File "/Users/horneds/Dropbox/projects/zoo/m/.env/lib/python3.4/site-packages/aiohttp/streams.py", line 501, in read
    result = yield from super().read()
  File "/Users/horneds/Dropbox/projects/zoo/m/.env/lib/python3.4/site-packages/aiohttp/streams.py", line 364, in read
    yield from self._waiter
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/futures.py", line 386, in __iter__
    yield self  # This tells Task to wait for completion.
concurrent.futures._base.CancelledError
[2015-04-20 14:54:45 +0300] [71306] [DEBUG] Ignored premature client disconnection.
```

Is it normal behaviour?

**Comment by fafhrd91** [comment]
thats right behavior, i'll reduce logging in next version
