### ISSUE TITLE
Fatal error on SSL transport

### ISSUE THREAD

**Issue by yjqiang** [aio-libs/aiohttp#3393]
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x114b81518>
transport: <_SelectorSocketTransport fd=132 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/383B28C1-6DCF-40D8-AB53-B5F7548B7F79/Pythonista3/Documents/site-packages-3/aiohttp/client.py", line 391, in _request
    await resp.start(conn)
  File "/private/var/mobile/Containers/Shared/AppGroup/383B28C1-6DCF-40D8-AB53-B5F7548B7F79/Pythonista3/Documents/site-packages-3/aiohttp/client_reqrep.py", line 770, in start
    self._continue = None
  File "/private/var/mobile/Containers/Shared/AppGroup/383B28C1-6DCF-40D8-AB53-B5F7548B7F79/Pythonista3/Documents/site-packages-3/aiohttp/helpers.py", line 673, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/containers/Bundle/Application/84DF3BDF-B442-41B6-93B3-AB45EDA9E5FC/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/sslproto.py", line 640, in _process_write_backlog
    ssldata = self._sslpipe.shutdown(self._finalize)
  File "/var/containers/Bundle/Application/84DF3BDF-B442-41B6-93B3-AB45EDA9E5FC/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/sslproto.py", line 156, in shutdown
    ssldata, appdata = self.feed_ssldata(b'')
  File "/var/containers/Bundle/Application/84DF3BDF-B442-41B6-93B3-AB45EDA9E5FC/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/sslproto.py", line 220, in feed_ssldata
    self._sslobj.unwrap()
  File "/var/containers/Bundle/Application/84DF3BDF-B442-41B6-93B3-AB45EDA9E5FC/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/ssl.py", line 692, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL] called a function you should not call (_ssl.c:2299)

**Comment by yjqiang** [comment]
I used “try” and tried handle this exception, but I can’ catch it.

**Comment by asvetlov** [comment]
What Python and aiohttp versions do yo use?

**Comment by yjqiang** [comment]
python 3.6.1 and aiohttp 3.4.4 by using pip

**Comment by asvetlov** [comment]
The problem not in aiohttp itself but in Python asyncio.
Try to upgrade to Python 3.7.1 -- it has several asyncio SSL fixes.
I don't know if these fixes are enough for your case though.

**Comment by asvetlov** [comment]
Yes, better to report on upstream.
Regarding #3202 -- let's briefly discuss your findings with closed issue status and decide what to do after that.

**Comment by yjqiang** [comment]
@asvetlov I wrote something in #3202  few minutes ago.

**Comment by yjqiang** [comment]
> Yes, better to report on upstream.
> Regarding #3202 -- let's briefly discuss your findings with closed issue status and decide what to do after that.

Did you read that? I think that's important.

**Comment by yjqiang** [comment]
https://bz.apache.org/bugzilla/show_bug.cgi?id=58956
I think maybe it was a bug in OpenSSL 1.0.2f. But I'd like to keep it open until I'm sure about this, which means I have to wait until Pythonista upgrades OpenSSL.

**Comment by asvetlov** [comment]
Let's close: nothing to do on aiohttp side.
SSL work is performed completely in standard `ssl` and `asyncio` modules.

**Comment by yjqiang** [comment]
> Let's close: nothing to do on aiohttp side.
> SSL work is performed completely in standard `ssl` and `asyncio` modules.

😂 Maybe you are right. Anyway, thanks a lot.
