### ISSUE TITLE
3.4.4 - invalid constant string when no response headers.

### ISSUE THREAD

**Issue by niemyjski** [aio-libs/aiohttp#3402]
I noticed that my request are failing and that no response headers are returned when this happens. If I go into chrome and click copy response headers it gives me `HTTP/0.9 200 OK`

```
Traceback (most recent call last):
  File "/Users/blake/Code/home-assistant-fork/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 757, in start
    message, payload = await self._protocol.read()
  File "/Users/blake/Code/home-assistant-fork/lib/python3.7/site-packages/aiohttp/streams.py", line 543, in read
    await self._waiter
  File "/Users/blake/Code/home-assistant-fork/lib/python3.7/site-packages/aiohttp/client_proto.py", line 195, in data_received
    messages, upgraded, tail = self._parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid constant string'
```

![image](https://user-images.githubusercontent.com/1020579/48796872-5d6e7580-ecc6-11e8-92cc-a2fa135e759e.png)

**Comment by niemyjski** [comment]
Is there any chance we can get a work around for this? There is nothing I can do about this web server it's on my local network and is out of my control.

**Comment by asvetlov** [comment]
Sorry, aiohttp cannot help you.
Build HTTP request data, send it through the socket, get back an answer and parse it.
Should be an easy exercise for HTTP 0.9, the protocol has a really simple structure.
