### ISSUE TITLE
client: GET request continues after cancelling the task

### ISSUE THREAD

**Issue by MShekow** [aio-libs/aiohttp#3426]
## Long story short

When I cancel a task which actually GETs a large file, I expect the transfer to truly stop once I called task.cancel().

## Expected behaviour

CancelledError is raised inside my co-routine - the ClientSession context manager and request context manager is left, so I expect the request to have truly finished.

## Actual behaviour

The transfer continues in the background.

## Steps to reproduce

```
import asyncio
import time
from contextlib import suppress
from threading import Thread

import aiohttp


async def request(url):
    async with aiohttp.ClientSession() as session:
        async with session.get(url) as resp:
            return await resp.text()


async def cancel_task():
    global task
    task.cancel()
    print("task.cancel() called")
    with suppress(asyncio.CancelledError):
        await task  # hangs forever ... it makes no difference if the last 3 lines of this method are not there
    print('done cancel_task()')


loop = None


def runner():
    global loop
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    loop.run_forever()


t = Thread(target=runner)
t.start()

time.sleep(0.5)

url = 'https://speed.hetzner.de/10GB.bin'
task = asyncio.run_coroutine_threadsafe(request(url), loop)
time.sleep(2)
print("Starting cancellation")
asyncio.run_coroutine_threadsafe(cancel_task(), loop)
time.sleep(5000)
```
Output:
```
Starting cancellation
task.cancel() called
```

## Your environment
Win10, Python 3.6.1, aiohttp 3.4.4

**Comment by asvetlov** [comment]
Could you rework the example to use the single event loop in the main thread (with a couple of tasks maybe)?

**Comment by MShekow** [comment]
Here is an example with just one thread. The same result happens. I'm not sure why "a couple of tasks" (in other words, a more complex example) would be more illustrative than a minimal example.
```
import asyncio
import time
from contextlib import suppress

import aiohttp


async def request(url):
    async with aiohttp.ClientSession() as session:
        async with session.get(url) as resp:
            return await resp.text()


async def cancel_task(task):
    await asyncio.sleep(5)
    task.cancel()
    print("task.cancel() called")
    with suppress(asyncio.CancelledError):
        await task  # hangs forever ... it makes no difference if the last 3 lines of this method are not there
    print('done cancel_task()')


loop = asyncio.get_event_loop()
url = 'https://speed.hetzner.de/10GB.bin'
task = asyncio.ensure_future(request(url))
asyncio.ensure_future(cancel_task(task))
loop.run_forever()
```
Note that if I replace `loop.run_forever()` with
```
try:
    loop.run_until_complete(task)
except asyncio.CancelledError:
    pass
print("done")
time.sleep(5)
```
Then the transfer truly stops (during the last 5 idle seconds of keeping the Python process alive), but this is simply a side effect of stopping the event loop. Replacing `time.sleep` with `loop.run_forever()` will cause the download to resume again in the background, without any task being active.

**Comment by khazhyk** [comment]
Simple reproducer

On windows, with aiohttp@master, and aiohttp 3.5.4, shows task continues to download (unmistakable, multiple Mbps...) even after exception raised
```py
import aiohttp
import asyncio

BIG_URL = "https://planet.openstreetmap.org/planet/full-history/history-latest.osm.bz2"

async def get_abort_file():
    async with aiohttp.ClientSession() as sess:
         async with sess.get(BIG_URL, timeout=30) as resp:
            raise Exception("Raising exception immediately...")


loop = asyncio.get_event_loop()


async def amain():
    try:
        await get_abort_file()
    except:
        pass

    await asyncio.sleep(999999)
loop.run_until_complete(amain())
```


Workaround I guess, if you have a `resp` object, `resp.connection.transport.abort()`


This also seems to work, albeit a bit clunky. I don't see anywhere else this is exposed in 3.5.4
```py
aiohttp.ClientSession(
            connector=aiohttp.TCPConnector(enable_cleanup_closed=True))
```

**Comment by jacobsvante** [comment]
Perhaps this deserves a separate issue, but I'll start here since it's the closest thing I could find in the issues page.

I'm experiencing this while `await resp.text()` is executing inside a task and I actively cancel via `Cmd-Z`. The stack trace I get is:
```
Traceback (most recent call last):
  File "./app/requests.py", line 56, in _make_request
    body = await response.text()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1009, in text
    await self.read()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 973, in read
    self._body = await self.content.read()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 358, in read
    block = await self.readany()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 380, in readany
    await self._wait('readany')
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 296, in _wait
    await waiter
concurrent.futures._base.CancelledError
```

**Comment by Dreamsorcerer** [comment]
https://github.com/aio-libs/aiohttp/issues/3426#issuecomment-457496102
Doesn't seem to reproduce for me on current versions. I'm assuming this is fixed.
