### ISSUE TITLE
BUG. ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify

### ISSUE THREAD

**Issue by ghost** [aio-libs/aiohttp#3502]
## Long story short

If assert is between function where I use ClientSession() -> this give error to me:
```
SSL error in data received  
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f27f8585ac8>  
transport: <_SelectorSocketTransport fd=38 read=polling write=<idle, bufsize=0>>  
Traceback (most recent call last):  
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2592)
```

## Expected behaviour

No errors, I am using try..catch

## Actual behaviour

Show me error message in console.

## Steps to reproduce

```python
import asyncio
from aiohttp import ClientSession, ClientTimeout


async def fun3(url):
    try:
        async with ClientSession(timeout=timeout) as s:
            async with s.get(url) as r:
                if r.status == 200:
                    return True
                else:
                    return False
    except:
        return False


async def fun1(session, url):
    try:
        async with session.get(url) as r:
            # Make assert here, special. And error displayed
            assert 'A77er1 9rr0r' in await r.text()

        return [True, url]
    except:
        return [False, '']


async def fun0(url):
    url = url if 'http' in url else 'http://' + url

    # If I remove this function - all good
    if await fun3(url):
        return

    async with ClientSession(timeout=timeout) as s:
        temp = await fun1(s, url)

        if temp[0]:
            print('Good')


async def main():
    tasks = []
    # I have many items, just add to simulate real behavior
    task = asyncio.create_task(
        fun0(
            'https://python.org'
        )
    )
    tasks.append(task)

    await asyncio.gather(*tasks)


if __name__ == "__main__":
    timeout = ClientTimeout(total=10)

    asyncio.run(main())

```

## Your environment
- [x] Ubuntu 18.04
- [x] Python 3.7.1
- [x] GCC 8.2.0

- [x] asyncio v3.4.3
- [x] aiohttp v3.5.1

**Comment by asvetlov** [comment]
A copy of #3477
