### ISSUE TITLE
aiohttp client closes files after sending

### ISSUE THREAD

**Issue by Rapptz** [aio-libs/aiohttp#3654]
## Long story short

`aiohttp` seems to close files after the request is over, meaning a file object cannot be reused once a request is sent.

## Expected behaviour

The file should not be closed and I can reuse my file objects following a `seek` call.

## Actual behaviour

`aiohttp` closes the file instead.

```
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    asyncio.get_event_loop().run_until_complete(run())
  File "...\Python36\lib\asyncio\base_events.py", line 466, in run_until_complete
    return future.result()
  File "test.py", line 27, in run
    b.seek(0)
ValueError: I/O operation on closed file.
```

## Steps to reproduce

```py
import asyncio
import io
import aiohttp

async def run():
    b = io.BytesIO(b'test')
    async with aiohttp.ClientSession() as sess:
        for _ in range(2):
            b.seek(0)
            async with sess.post('https://httpbin.org/post', data=b) as resp:
                print(await resp.text())

asyncio.get_event_loop().run_until_complete(run())
```

The equivalent `requests` code does not error:

```py
b = io.BytesIO(b'test')
for _ in range(2):
    b.seek(0)
    r = requests.post('https://httpbin.org/post', data=b)
    print(r.text)
```

## Your environment

aiohttp version: 3.5.4
Python version: 3.6.1
OS: Windows 8.1

**Comment by Rapptz** [comment]
I searched github earlier and didn't see the duplicate discussion in #1907 sorry.

If this is truly by design (and it seems to be) patching the close method to do nothing and then putting it back will work fine, e.g.

```py
async def run():
    b = io.BytesIO(b'test')
    original = b.close
    b.close = lambda: None
    try:
        async with aiohttp.ClientSession() as sess:
            for _ in range(2):
                b.seek(0)
                async with sess.post('https://httpbin.org/post', data=b) as resp:
                    print(await resp.text())
    finally:
        b.close = original
```

The reason I needed the file to stay open is because I wanted to retry requests if they failed.
