### ISSUE TITLE
Stderr spammed with ssl-related error messages

### ISSUE THREAD

**Issue by AMDmi3** [aio-libs/aiohttp#3675]
## Long story short

On SSL errors in connection, aiohttp issues messages to stderr. This doesn't seem to be correct behavior as these messages clobber actual application output, there's nothing useful can be done with them, and we have exceptions to actually handle the errors.

## Expected behaviour

No messages from aiohttp on stderr.

## Actual behaviour

A lot of messages even from a single request (output from the example program listed below):

```
SSL handshake failed on verifying the certificate
protocol: <asyncio.sslproto.SSLProtocol object at 0x802828cf8>
transport: <_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "/usr/local/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'geopandas.org'. (_ssl.c:1056)
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x802828cf8>
transport: <_SelectorSocketTransport closing fd=6 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'geopandas.org'. (_ssl.c:1056)
SSL handshake failed on verifying the certificate
protocol: <asyncio.sslproto.SSLProtocol object at 0x8028b90f0>
transport: <_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "/usr/local/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'geopandas.org'. (_ssl.c:1056)
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x8028b90f0>
transport: <_SelectorSocketTransport closing fd=6 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'geopandas.org'. (_ssl.c:1056)
```

## Steps to reproduce

Despite SSL exception is intercepted, stderr is still polluted by a lot of errors as listed above.

```python
import aiohttp
import asyncio

async def main():
    try:
        async with aiohttp.ClientSession() as sess:
            async with sess.head('https://geopandas.org/') as resp:
                print('ok',resp.status_code)
    except aiohttp.client_exceptions.ClientConnectorCertificateError:
        print('SSL error caught')

asyncio.run(main())
```

## Your environment

aiohttp 3.5.4 (client), FreeBSD 12.0 amd64, python 3.7, no proxy server

**Comment by webknjaz** [comment]
Are you sure that it's aiohttp and not asyncio dumping such logs?

**Comment by AMDmi3** [comment]
> Are you sure that it's aiohttp and not asyncio dumping such logs?

Oh, I'm not. Judging by the tracebacks it's likely the case, sorry for the noise then.

**Comment by webknjaz** [comment]
Well, just check that first and maybe try setting up the logging to better identify the log sources. I think @asvetlov fixed something like this a while back in CPython so maybe also try Python 3.8 dev/alpha release.

**Comment by Harmon758** [comment]
This is an issue with asyncio rather than aiohttp.
See https://bugs.python.org/issue34506 and https://stackoverflow.com/q/52012488/6191255.

**Comment by asvetlov** [comment]
Not the same but tightly coupled with #3535

**Comment by Harmon758** [comment]
This should now be fixed with https://github.com/python/cpython/pull/13548 in Python 3.8.0 (and with https://github.com/python/cpython/pull/13594 in Python 3.7.4). See https://bugs.python.org/issue37035.

**Comment by AMDmi3** [comment]
I'll confirm it - still waiting for 3.8.0 to appear in FreeBSD ports.

**Comment by AMDmi3** [comment]
Confirmed - with python 3.8 the problem is gone.
