### ISSUE TITLE
Error while setting client session timeout 

### ISSUE THREAD

**Issue by odysseusmax** [aio-libs/aiohttp#3692]
## Long story short

some errors are occuring while setting client session timeouts

## Expected behaviour

No errror should appear

## Actual behaviour

```Exception ignored in: <function ClientSession.__del__ at 0x7f887a9362f0>
Traceback (most recent call last):
   File "/app/.heroku/python/lib/python3.7/site-packages/aiohttp/client.py", line 283, in __del__
     if not self.closed:
  File "/app/.heroku/python/lib/python3.7/site-packages/aiohttp/client.py", line 899, in closed
     return self._connector is None or self._connector.closed
 AttributeError: _connector
 __init__() takes 1 positional argument but 2 were given
```
## Steps to reproduce

```
t = aiohttp.ClientTimeout(total=600)
    async with aiohttp.ClientSession(t) as session:
        async with session.get(url) as r:
```
## Your environment

aiohttp==4.0.0a0
python-3.7.3

**Comment by ghost** [comment]
Read about [ClientSession parametes](https://docs.aiohttp.org/en/stable/client_reference.html), you forget `timeout=` because first parameter is `connector=`
```python
t = aiohttp.ClientTimeout(total=600)

async with aiohttp.ClientSession(timeout=t) as session:
    async with session.get(url) as r:
```
