### ISSUE TITLE
Timeout Doesn't Work as expected

### ISSUE THREAD

**Issue by ajbeach2** [aio-libs/aiohttp#3782]
## Long story short

TimeoutError is thrown when it is not expected to

## Expected behaviour

No TimeoutError should occur 

## Actual behaviour

TimeoutErrors are being thrown

## Steps to reproduce
```python
# main.py
import aiohttp
import asyncio
import functools
import time

async def fetch(session, url):
    timeout = aiohttp.ClientTimeout(total=10)
    async with session.get(url, timeout=timeout) as resp:
        print("get url", url)
        await resp.read()

async def main(seconds):
    miliseconds = seconds * 1000
    async with aiohttp.ClientSession() as session:
        await fetch(session, 'http://deelay.me/{0}/https://www.python.org/'.format(miliseconds))
    time.sleep(2) 

loop = asyncio.get_event_loop()
loop.run_until_complete(
    asyncio.gather(
        main(4),
        main(3),
        main(3),
        main(3),
        main(3),
        main(3),
        main(1),
        main(4),
        main(1),
        main(1),
        main(1),
        main(1),
        main(1),
        main(3),
        main(1)
))
```
```
 ->python main.py 
get url http://deelay.me/1000/https://www.python.org/
get url http://deelay.me/1000/https://www.python.org/
get url http://deelay.me/1000/https://www.python.org/
get url http://deelay.me/1000/https://www.python.org/
get url http://deelay.me/1000/https://www.python.org/
get url http://deelay.me/1000/https://www.python.org/
get url http://deelay.me/1000/https://www.python.org/
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    main(1)
  File "/Users/ajbeach2/.pyenv/versions/3.6.8/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "main.py", line 15, in main
    await fetch(session, 'http://deelay.me/{0}/https://www.python.org/'.format(miliseconds))
  File "main.py", line 8, in fetch
    async with session.get(url, timeout=timeout) as resp:
  File "/Users/ajbeach2/.pyenv/versions/3.6.8/lib/python3.6/site-packages/aiohttp/client.py", line 843, in __aenter__
    self._resp = await self._coro
  File "/Users/ajbeach2/.pyenv/versions/3.6.8/lib/python3.6/site-packages/aiohttp/client.py", line 387, in _request
    await resp.start(conn)
  File "/Users/ajbeach2/.pyenv/versions/3.6.8/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 761, in start
    self._continue = None
  File "/Users/ajbeach2/.pyenv/versions/3.6.8/lib/python3.6/site-packages/aiohttp/helpers.py", line 677, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
```

## Your environment

python version Python 3.6.8
aiohttp-3.5.4

**Comment by asvetlov** [comment]
Is there any reason to use the blocking `time.sleep()` in your snippet?

**Comment by ajbeach2** [comment]
this code sample is derived from production code, and i am using time.sleep here as a placeholder for synchronous code (that is why i am not using asyncio.sleep).  Should we expected the timeout to work with a mix of async and sync? If not maybe this isn't a bug.

If i wrap the synchronous code in a executor the code doesn't throw any errors. 

```python
# main.py
import aiohttp
import asyncio
import functools
import time

async def fetch(session, url):
    timeout = aiohttp.ClientTimeout(total=10)
    async with session.get(url, timeout=timeout) as resp:
        print("get url", url)
        await resp.read()

async def main(seconds):
    miliseconds = seconds * 1000
    async with aiohttp.ClientSession() as session:
        await fetch(session, 'http://deelay.me/{0}/https://www.python.org/'.format(miliseconds))

    loop = asyncio.get_event_loop()
    loop.run_in_executor(None, time.sleep, 2)

loop = asyncio.get_event_loop()
loop.run_until_complete(
    asyncio.gather(
        main(4),
        main(3),
        main(3),
        main(3),
        main(3),
        main(3),
        main(1),
        main(4),
        main(1),
        main(1),
        main(1),
        main(1),
        main(1),
        main(3),
        main(1)
))
````

**Comment by asvetlov** [comment]
Running blocking code inside async function is a **very bad idea**.
It is true not only for aiohttp but for asyncio in general (and even for trio or curio).

**Comment by ajbeach2** [comment]
yeap. that seems to be the case. If this behavior is expected, than this issue can be closed.
