### ISSUE TITLE
ServerDisconnectedError on Python 3.8

### ISSUE THREAD

**Issue by burnnat** [aio-libs/aiohttp#3802]
## Long story short

I have some unit tests using TestClient/TestServer that pass in Python 3.5, 3.6, and 3.7, but result in a ServerDisconnectedError in Python 3.8. Even after removing everything other than the core aiohttp calls the problem remains which makes me wonder if this is a regression of some kind.
 
## Expected behaviour

This simple test should print "Success".

## Actual behaviour

A ServerDisconnectedError is encountered with the following stack trace:

    Traceback (most recent call last):
    File "test.py", line 17, in <module>
        asyncio.run(run())
    File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
        return loop.run_until_complete(main)
    File "/usr/lib/python3.8/asyncio/base_events.py", line 614, in run_until_complete
        return future.result()
    File "test.py", line 13, in run
        response = await client.get('/foo')
    File "/home/coder/screenly_ose/venv/py38/lib/python3.8/site-packages/aiohttp/test_utils.py", line 294, in request
        resp = await self._session.request(
    File "/home/coder/screenly_ose/venv/py38/lib/python3.8/site-packages/aiohttp/client.py", line 497, in _request
        await resp.start(conn)
    File "/home/coder/screenly_ose/venv/py38/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 844, in start
        message, payload = await self._protocol.read()  # type: ignore  # noqa
    File "/home/coder/screenly_ose/venv/py38/lib/python3.8/site-packages/aiohttp/streams.py", line 588, in read
        await self._waiter
    aiohttp.client_exceptions.ServerDisconnectedError: None

## Steps to reproduce

Here is the simplified test script I am running. I'm pretty much a novice when it comes to async handling in Python, so it's certainly possible I'm doing something wrong here. Let me know if that's the case.

    import asyncio
    from aiohttp import web
    from aiohttp import test_utils

    async def handle_request(request):
        return web.Response(text='Success')

    async def run():
        app = web.Application()
        app.router.add_route('GET', '/foo', handle_request)

        async with test_utils.TestClient(test_utils.TestServer(app)) as client:
            response = await client.get('/foo')
            body = await response.text()
            print(body)

    asyncio.run(run())

## Your environment

Ubuntu 16.04, Python 3.8.0a4, aiohttp 3.5.4

**Comment by asvetlov** [comment]
please check aiohttp master

**Comment by burnnat** [comment]
Ah good point, I tried against master and it appears to work fine. I guess I will wait for the next release then. Thanks for the quick response 👍
