### ISSUE TITLE
mjpeg streaming server says "ConnectionResetError: Cannot write to closing transport"

### ISSUE THREAD

**Issue by ghost** [aio-libs/aiohttp#3966]
I hacked together a little mjpeg server copied mostly from examples found around the internet.

It monitors a directory, and if the jpeg file in that directory changes, then it sends it on the stream to the browser.

So, to use this server, you make a directory (in the same dir that you are running the python program from):
mkdir -p previews/{dirtowatch}
replace "dirtowatch" in above line with some arbitrary text like "test"  - note below that you will put this same text on the URL as "dirtowatch" url param.

When a file named preview.jpeg **is put into the "test" directory that you created**, it gets streamed to the browser.

Put this in your browser: http://**address**:8080/?dirtowatch=test
Replace **address** with the address your Python program is running on.

Also put any jpeg file in **the python program directory** and name it placeholder.jpeg - this is what will be sent if there is no jpeg in the dirtowatch.

The overall idea is that you can replace the preview.jpeg with whatever jpeg image you want and it will be streamed to the browsers.

It seems to work fine.

EXCEPT it keeps giving errors, can anyone suggest what I am doing wrong?

```
Error handling request
Traceback (most recent call last):
  File "server_aiohttp.py", line 66, in handle_async_mjpeg_stream
    await write(img_bytes)
  File "server_aiohttp.py", line 39, in write
    len(img_bytes)), 'utf-8') + img_bytes + b'\r\n')
  File "/home/ubuntu/venv3.6/lib/python3.6/site-packages/aiohttp/web_response.py", line 423, in write
    await self._payload_writer.write(data)
  File "/home/ubuntu/venv3.6/lib/python3.6/site-packages/aiohttp/http_writer.py", line 101, in write
    self._write(chunk)
  File "/home/ubuntu/venv3.6/lib/python3.6/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/venv3.6/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "server_aiohttp.py", line 75, in handle_async_mjpeg_stream
    await response.write_eof()
  File "/home/ubuntu/venv3.6/lib/python3.6/site-packages/aiohttp/web_response.py", line 444, in write_eof
    await self._payload_writer.write_eof(data)
  File "/home/ubuntu/venv3.6/lib/python3.6/site-packages/aiohttp/http_writer.py", line 138, in write_eof
    self._write(chunk)
  File "/home/ubuntu/venv3.6/lib/python3.6/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
Unhandled exception
Traceback (most recent call last):
  File "/home/ubuntu/venv3.6/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 447, in start
    await resp.prepare(request)
  File "/home/ubuntu/venv3.6/lib/python3.6/site-packages/aiohttp/web_response.py", line 353, in prepare
    return await self._start(request)
  File "/home/ubuntu/venv3.6/lib/python3.6/site-packages/aiohttp/web_response.py", line 667, in _start
    return await super()._start(request)
  File "/home/ubuntu/venv3.6/lib/python3.6/site-packages/aiohttp/web_response.py", line 410, in _start
    await writer.write_headers(status_line, headers)
  File "/home/ubuntu/venv3.6/lib/python3.6/site-packages/aiohttp/http_writer.py", line 112, in write_headers
    self._write(buf)
  File "/home/ubuntu/venv3.6/lib/python3.6/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
```

Here is the source code.

```
import asyncio
from aiohttp import web
from asyncio import CancelledError
from uuid import uuid4
from aiohttp.web import StreamResponse
import os
import glob
import os, time

with open('placeholder.jpeg', mode='rb') as file:  # b is important -> binary
    placeholder_img_bytes = file.read()

async def handle_async_mjpeg_stream(request):
    """
    if the user specifies a dirtowatch url param
    then this monitors a directory of that name
    it checks a single preview jpeg file
    if that jpeg file changes then it sends it to the client
    """
    dirtowatch = request.rel_url.query.get('dirtowatch', None)
    if not dirtowatch:
        return web.HTTPNotFound()
    print(request.rel_url.query['dirtowatch'])
    response = web.StreamResponse()

    response.content_type = ('multipart/x-mixed-replace; '
                             'boundary=--jpegboundary')
    await response.prepare(request)

    async def write(img_bytes):
        """Write image to stream."""
        await response.write(bytes(
            '--jpegboundary\r\n'
            'Content-Type: image/jpeg\r\n'
            'Content-Length: {}\r\n\r\n'.format(
                len(img_bytes)), 'utf-8') + img_bytes + b'\r\n')

    last_image = None
    last_file_sent_modified_date = None
    try:
        while True:
            filename = f'previews/{dirtowatch}/preview.jpeg'
            # note that we check file modification date at nanosecond resolution
            this_file_modified_date = None
            try:
                this_file_modified_date = os.stat(filename).st_mtime_ns
                if last_file_sent_modified_date == this_file_modified_date:
                    # the file has not changed on the disk, wait and try again
                    print('-', end='', flush=True)
                    await asyncio.sleep(0.2) # 200ms/5fps
                    continue
                print('+', end='', flush=True)
                with open(filename, mode='rb') as file:  # b is important -> binary
                    img_bytes = file.read()
            except:
                img_bytes = placeholder_img_bytes
            if not img_bytes:
                # sometimes the file read will fail to read data
                # perhaps because a new file is bring copied in
                # we just ignore that by continuing
                continue
            if img_bytes is not None and img_bytes != last_image:
                await write(img_bytes)
                # Chrome seems to always ignore first picture,
                # print it twice.
                if last_image is None:
                    await write(img_bytes)
                last_image = img_bytes
                await response.drain()
            last_file_sent_modified_date = this_file_modified_date
    finally:
        await response.write_eof()

async def main():
    server = web.Server(handle_async_mjpeg_stream)
    runner = web.ServerRunner(server)
    await runner.setup()
    listen_address = '0.0.0.0'
    port = '8080'
    site = web.TCPSite(runner, listen_address, port)
    await site.start()
    print(f"======= MJPEG server on http://{listen_address}:8080/ ======")

    # pause here for very long time by serving HTTP requests and
    # waiting for keyboard interruption
    await asyncio.sleep(100*3600)

loop = asyncio.get_event_loop()

try:
    loop.run_until_complete(main())
except KeyboardInterrupt:
    pass
loop.close()

```

**Comment by asvetlov** [comment]
The error message is pretty clear: client closed connection, that's why server cannot write a chunk of response.

**Comment by socketpair** [comment]
@asvetlov what should I do (as a Aiohttp user) wher `ConnectionResetError` raised in `await response.prepare(request)` ?

If I do not use `StreamResponse`, accidental connection close by browser does not lead to the traceback.

So, obvious idea - is to handle exception, but what to do inside ?

```python
try:
    await response.prepare(request)
except ConnectionResetError:
    what to do here ? how to suppress traceback ? what to return from handler  or what to raise ?
```

**Comment by socketpair** [comment]
is  `return Response()` safe  on any stage ? even after sending some bytes ?

**Comment by socketpair** [comment]
see also #7590
