### ISSUE TITLE
Why I excepted Exception but alway raise ssl.SSLError: [SSL: WRONG_VERSION_NUMBER]

### ISSUE THREAD

**Issue by shmilylty** [aio-libs/aiohttp#3972]
## Long story short

![image](https://user-images.githubusercontent.com/24275308/62807481-0e07f800-bb28-11e9-8cde-02d9229c3d87.png)

## Expected behaviour

I want to except Exception.

## Actual behaviour

But not work,  alway raise ssl.SSLError: [SSL: WRONG_VERSION_NUMBER].

## Steps to reproduce
```bash
python test.py
```

```python
# test.py
import asyncio
import aiohttp


async def fetch(session, url):
	async with session.get(url, ssl=False) as response:
	    return await response.text()



async def main():
    conn = aiohttp.TCPConnector(ssl=False)
    async with aiohttp.ClientSession(connector=conn) as session:
        try:
            html = await fetch(session, 'https://guahao.com:80')
            print(html)
        except BaseException as e:
            print('excepted!!!')
            print(e.args)



loop = asyncio.get_event_loop()
loop.run_until_complete(main())

```

## Your environment
```bash
root@kali:~# uname -a
Linux kali 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux

root@kali:~# python3 -V
Python 3.7.3rc1

root@kali:~# pip3 show aiohttp
Name: aiohttp
Version: 3.5.4
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: /usr/local/lib/python3.7/dist-packages
Requires: async-timeout, yarl, chardet, multidict, attrs
Required-by: 
```

## Error detail
```bash
root@kali:~# python3 test.py 
SSL handshake failed
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f008bf8fc18>
transport: <_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1056)
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f008bf8fc18>
transport: <_SelectorSocketTransport closing fd=6 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1056)
excepted!!!
(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1056)')
```

**Comment by webknjaz** [comment]
I think it's a bug in asyncio itself that it dumps the traceback. Because `except` works, it's even visible in your log: there's results of your print statements.

**Comment by shmilylty** [comment]
Thx, So , Is there any way to make it not throw this exception?🙏

**Comment by webknjaz** [comment]
Don't make broken queries.

**Comment by shmilylty** [comment]
But I do need to do this kind of request detection.

**Comment by webknjaz** [comment]
I believe that's all you can do. Anyway, it's just some garbage in logs, everything else works.

**Comment by atemate** [comment]
I could not reproduce this on Python 3.7.4, aiohtttp 3.5.4:
```
$ uname -a
Linux archlinux 5.2.6-arch1-1-ARCH #1 SMP PREEMPT Sun Aug 4 14:58:49 UTC 2019 x86_64 GNU/Linux
```
note, variable `PYTHONASYNCIODEBUG` does not affect the problem as well:
```
$ PYTHONASYNCIODEBUG=1 python test-ssl-error.py 
excepted!!!
(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1076)')

$ PYTHONASYNCIODEBUG=0 python test-ssl-error.py 
excepted!!!
(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1076)')
```

**Comment by webknjaz** [comment]
@ayushkovskiy it's reproducible for me under the same Python version.

**Comment by shmilylty** [comment]
@ayushkovskiy Are u use same url (https://guahao.com:80)？

**Comment by asvetlov** [comment]
There are two things here: WRONG_VERSION_NUMBER itself and printing it by `loop.call_exception_handler()`

The former can be avoided by providing custom `SSLContext` that re-enables obsolete (and insecure) SSL protocol versions.
The later is fixed in upstream, see https://bugs.python.org/issue37035

**Comment by shmilylty** [comment]
@asvetlov Thank you very much, when will the WRONG_VERSION_NUMBER problem be fixed, and can you give me the sample code to use SSLContext to avoid this error?

**Comment by shmilylty** [comment]
I find this code in Issues, But it's for server，I just use aiohttp(is a client) to make a request.
```python
import ssl

from aiohttp import web

custom_context = ssl.create_default_context()
custom_context... # do things to it

web.run_app(..., ssl_context=custom_context, ...)
```

_Originally posted by @webknjaz in https://github.com/aio-libs/aiohttp/issues/3292#issuecomment-450571014_

**Comment by webknjaz** [comment]
@asvetlov is `WRONG_VERSION_NUMBER` happening because @shmilylty uses TLS to connect to port `80` which usually serves plain HTTP w/o transport layer encryption. Custom `SSLContext` won't help in this case because it's not an invalid version, the whole protocol is wrong.

```console
$ curl -L https://guahao.com/
[...HTML payload...]

$ curl https://guahao.com:80/   
curl: (35) SSL received a record that exceeded the maximum permissible length.

$ curl -k https://guahao.com:80/  # ignore invalid check
curl: (35) SSL received a record that exceeded the maximum permissible length.

$ openssl s_client -connect guahao.com:80
CONNECTED(00000003)
140675430856512:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:252:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 5 bytes and written 176 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1565966822
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```

**Comment by webknjaz** [comment]
@shmilylty you can pass `SSLContext` using `ssl=` arg of `TCPConnector` or `.request()`/`.get()` method (ref: https://docs.aiohttp.org/en/stable/client_reference.html#tcpconnector). But I don't believe that it'll help.

**Comment by shmilylty** [comment]
@webknjaz As you said, it doesn't work.😥

**Comment by webknjaz** [comment]
@shmilylty just keep using try/except.

**Comment by shmilylty** [comment]
@webknjaz This is my code：

```python
import asyncio
import aiohttp
import ssl


async def fetch(session, url):
	async with session.get(url) as response:
	    return await response.text()



async def main():
    custom_context = ssl.create_default_context()
    conn = aiohttp.TCPConnector(ssl=custom_context)
    async with aiohttp.ClientSession(connector=conn) as session:
        try:
            html = await fetch(session, 'https://guahao.com:80')
            print(html)
        except BaseException as e:
            print('excepted!!!')
            print(e.args)



loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

**Comment by webknjaz** [comment]
That's it

**Comment by shmilylty** [comment]
But it raise raise ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] 。。。

**Comment by webknjaz** [comment]
As it should.
