### ISSUE TITLE
Create Server with IPV6 +SocketIo

### ISSUE THREAD

**Issue by harshkoralwala** [aio-libs/aiohttp#4016]
Hello all,

I need a server with socket Io implementation. Where users in local connection can access my server.

I have nodeJs clients...

After research, I found a solution with the **socketio+aiohttp server.**

I got **success** in creating a server with host as "**localhost**".(which uses **ipv4**)

But I want to start the server with **IPV6** address.

How can I achieve that?

Refer below code

`
import socketio
from aiohttp import web
import ssl
import json

sio = socketio.AsyncServer(cors_allowed_origins="*",logger=True,json=json)
socketio.Server()
app = web.Application()
sio.attach(app)

@sio.event
async def connect(sid, environ):
    print('>>>> connect <<<<< ')
    print(sid)

@sio.event
def error(sid, data):
    print('>>>> error <<<<< ')

ctx = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
ctx.load_cert_chain('server.cert', 'server.key')
web.run_app(app, host='fe80::899d:6463:7c8c:5af2', port=2499, ssl_context=ctx)
web.run_app()

===========================================================================
When I run the above code I got an error on server console like 
`
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1062, in create_server
    sock.bind(sa)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "socketio/ipv6-socketio-https.py", line 92, in <module>
    web.run_app(app, host='fe80::899d:6463:7c8c:5af2', port=2499, ssl_context=ctx)
  File "/home/harsh/.local/lib/python3.6/site-packages/aiohttp/web.py", line 415, in run_app
    reuse_port=reuse_port))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/harsh/.local/lib/python3.6/site-packages/aiohttp/web.py", line 341, in _run_app
    await site.start()
  File "/home/harsh/.local/lib/python3.6/site-packages/aiohttp/web_runner.py", line 102, in start
    reuse_port=self._reuse_port)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1066, in create_server
    % (sa, err.strerror.lower()))
OSError: [Errno 22] error while attempting to bind on address ('fe80::899d:6463:7c8c:5af2', 2499, 0, 0): invalid argument`

===========================================================================
I changed line to...(added square brackets to IP address as per some surfing result)

> web.run_app(app, host='[fe80::899d:6463:7c8c:5af2]', port=2499, ssl_context=ctx)

I got an error like

`Traceback (most recent call last):
  File "socketio/ipv6-socketio-https.py", line 92, in <module>
    web.run_app(app, host='[fe80::899d:6463:7c8c:5af2]', port=2499, ssl_context=ctx)
  File "/home/harsh/.local/lib/python3.6/site-packages/aiohttp/web.py", line 415, in run_app
    reuse_port=reuse_port))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/harsh/.local/lib/python3.6/site-packages/aiohttp/web.py", line 341, in _run_app
    await site.start()
  File "/home/harsh/.local/lib/python3.6/site-packages/aiohttp/web_runner.py", line 102, in start
    reuse_port=self._reuse_port)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1030, in create_server
    infos = yield from tasks.gather(*fs, loop=self)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 979, in _create_server_getaddrinfo
    flags=flags, loop=self)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known`

===========================================================================

I got success with **creating ipv6 server and client on SAME system** like...

`web.run_app(app, host='::', port=2499, ssl_context=ctx)`

And on **node js Client** on **SAME system**...

`const socket = io('wss://[::]:2499', {
    reconnection: false,
    secure: true,
    transports: ['websocket'],
    rejectUnauthorized: false,
});` 

But other local user can not connect to this server .And also **i can not even start server** with **host as** actual **ipv6** address of my system...

So how can I create a server with ipv6 so other user in local connection can access my server?

My ipv6 looks like with **ifconfig** command on **linux** 

![ipv6](https://user-images.githubusercontent.com/33347464/63927356-2b671c80-ca6b-11e9-8f50-db14a09d048b.png)

Thanks in advance

**Comment by thomasschaeferm** [comment]
You have no real IPv6 addresses, just the link local addresses (fe80::...). Since the link local addresses are only unique for the link, you need to specify the interface(link) at the client site, the so called scope id (address%eth0 ; fe80:...%wlp2s0).
I am not sure if python support services for link local addresses. You should assign real IPv6-adresses to you computers, for testing purposes at least "unique local address" usually starting with fd00:....

**Comment by asvetlov** [comment]
From my understanding, the issue is out of aoihttp scope.
The library has nothing IPv6 specific (except handling IPv6 addresses in URLs maybe).
All the underground work is done by Python itself.
