### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by fangpenlin** [aio-libs/aiohttp#411]
```
Exception ignored in: Exception ignored in: <generator object start at 0x1038a6b88>
Traceback (most recent call last):
  File "/Users/victorlin/workspace/gofugue/event_hub/.env/lib/python3.4/site-packages/aiohttp/server.py", line 296, in start
    reader.unset_parser()
  File "/Users/victorlin/workspace/gofugue/event_hub/.env/lib/python3.4/site-packages/aiohttp/parsers.py", line 206, in unset_parser
    self._output.set_exception(self._eof_exc_class())
  File "/Users/victorlin/workspace/gofugue/event_hub/.env/lib/python3.4/site-packages/aiohttp/streams.py", line 335, in set_exception
    waiter.set_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/futures.py", line 353, in set_exception
    self._schedule_callbacks()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/futures.py", line 243, in _schedule_callbacks
    self._loop.call_soon(callback, self)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/base_events.py", line 427, in call_soon
    handle = self._call_soon(callback, args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/base_events.py", line 436, in _call_soon
    self._check_closed()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/base_events.py", line 265, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

When the app server closed with event loop, if there is still request connection alive (like keep alive request), the app server will generate event loop is closed error, as it tries to `unset_parser`, then it somehow calls closed event loop.

**Comment by fangpenlin** [comment]
hmmm, nvm, I think it's `app.finish` not called

**Comment by digitaldavenyc** [comment]
I'm showing a similar error, how is app.finish called?

**Comment by fafhrd91** [comment]
gunicorn worker calls `app.finish()`, otherwise you need to call it manually.

**Comment by digitaldavenyc** [comment]
Interesting... I'm using aiohttp for async http requests. I have a separate ticket open there. Is there any reason to call app.finish for requests? What is app in that case? That's not something I've used for aiohttp requests.
