### ISSUE TITLE
asyncio condition to stop server

### ISSUE THREAD

**Issue by mccartnm** [aio-libs/aiohttp#4152]
## Long story short
Using aiohttp, I would love to be able to create a condition variable that, once notified, you could shut down the app  gracefully.

So, given a basic webserver

```py
def server_in_thread(abort_condition):
    my_loop = asyncio.new_event_loop()
    app = web.Application(loop=my_loop)
    app.add_routes(...)
    web.run_app(app, abort_condition=abort_condition)


def main():
    abort_condition = asyncio.Condition()
    t = threading.Thread(target=server_in_thread, args=(abort_condition,))
    t.start()

    time.sleep(5.0) # Some indefinite time...

    # To quit, simply tap the condition
    with abort_condition:
        abort_condition.notify_all()
```

The trouble I'm having is related to the async loop and starting/stopping multiple servers on the fly. It's extremely hard to shut down the web server from another thread, justly so. I'm just curious if this could work?

```py
# https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web.py -> line ~365

    # ...
    if abort_condition:
        async with abort_condition:
            await abort_condition.wait()
    else:
        while True: # ... The same as it is currently.
```
I can make a PR for this if it makes sense. The only reason I'm not is because I'm somewhat new to this asyncio world and don't want to be presumptuous.

Thanks so much for your time!

**Comment by mccartnm** [comment]
[I tried the change](https://github.com/mccartnm/aiohttp/commit/fb99e3ec507ff84ee6a19f0c7f32e1393301935d) and it seems to work quite nicely. With a light touch of `asyncio.run_coroutine_threadsafe`, I'm avoiding the `GracefulExit` world and just let the app die once it's happy to do so.

```py
def server_in_thread(loop, condition):
    app = web.Application(loop=loop)
    app.add_routes(...)
    web.run_app(app, abort_condition=condition)

async def fire_abort(abort_condition):
    async with abort_condition:
        abort_condition.notify_all()

def main():
    loop = asyncio.new_event_loop()
    abort_condition = asyncio.Condition(loop=loop)
    t = threading.Thread(target=server_in_thread, args=(loop, abort_condition,))
    t.start()

    time.sleep(5.0) # Some indefinite time...

    future = asyncio.run_coroutine_threadsafe(
        fire_abort(abort_condition), loop
    )
    result = future.result()
```

Again, if this is something the community would want, I'm happy to do the PR legwork. I'm just really not sure if it's against the grain or anything. I come from a high multi-thread C++ world so my answer always tends to lean toward these kinds of mechanisms.

**Comment by asvetlov** [comment]
The proper solution is #2746

Unfortunately, nobody is volunteered to make it done.

**Comment by el07694** [comment]
I will try your code to test if it's works.

**Comment by el07694** [comment]
I got this error:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chris/Documents/papinhio-player/src/python+/main-window/../../python+/menu-3/radio-stations/import/test-connections.py", line 434, in server_in_thread
    web.run_app(app, access_log=None, host=lan_ip_address, port="8080", ssl_context=None, abort_condition=abort_condition)  
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/web.py", line 419, in run_app
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3'.

```

Code:

```
...
...
...
#a multiprocess run method
def run(self):
        try:
            
            global stop_stream_q
            threading.Thread(target=self.connect_to_icecast).start()
            self.to_emitter.send({"type":"test_results","http":self.http_connect_message,"ftp":self.ftp_login_message,"mysql":self.mysql_login_message,"radio":"ok","url":"http://"+self.lan_ip_address+":8080/"})
            #web.run_app(self.app, access_log=None, host=self.lan_ip_address, port="8080", ssl_context=None)
            self.abort_condition = asyncio.Condition()
            t = threading.Thread(target=self.server_in_thread, args=(self.abort_condition,self.lan_ip_address))
            t.start()
        except Exception as e:
            self.to_emitter.send({"type":"test_results","http":self.http_connect_message,"ftp":self.ftp_login_message,"mysql":self.mysql_login_message,"radio":str(e),"url":"http://"+self.lan_ip_address+":8080/"})

def server_in_thread(self,abort_condition,lan_ip_address):
        self.my_loop = asyncio.new_event_loop()
        app = web.Application(loop=self.my_loop)
        app.router.add_get("/", self.index)
        web.run_app(app, access_log=None, host=lan_ip_address, port="8080", ssl_context=None, abort_condition=abort_condition)  

def stop_aiohttp_server(self):
        future = asyncio.run_coroutine_threadsafe(self.fire_abort(self.abort_condition), self.loop)
        result = future.result()

async def fire_abort(self,abort_condition):
        async with abort_condition:
            abort_condition.notify_all()
        print("Aiohttp server closed")
```
```

and the terminate operation is called:
#self.aiohttp_server_child_process = PROCCESS_INSTANCE
self.aiohttp_server_child_process.stop_aiohttp_server()
```

I just copy [this file](https://raw.githubusercontent.com/mccartnm/aiohttp/fb99e3ec507ff84ee6a19f0c7f32e1393301935d/aiohttp/web.py) to `aiohttp.__file__` directory
