### ISSUE TITLE
Aiohttp: ModuleNotFoundError: No module named 'http.server'; 'http' is not a package

### ISSUE THREAD

**Issue by CodeM01** [aio-libs/aiohttp#4278]
## Long story short

I have pip installed aiohttp but I cannot get it working

## Expected behaviour

Not throw an error when I import it

## Actual behaviour

Its's throwing this error:

Traceback (most recent call last):
  File "C:\Users\\PycharmProjects\Project\http.py", line 1, in <module>
    import aiohttp
  File "C:\Users\\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\__init__.py", line 6, in <module>
    from .client import BaseConnector as BaseConnector
  File "C:\Users\\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\client.py", line 32, in <module>
    from . import hdrs, http, payload
  File "C:\Users\\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\http.py", line 1, in <module>
    import http.server
ModuleNotFoundError: No module named 'http.server'; 'http' is not a package
[Finished in 1.431s]

## Your environment

I am using the latest version of aiohttp and im on a windows operating system. I am using aiohttp for communicating with Discords server; a client

**Comment by webknjaz** [comment]
It's a common beginner mistake. Rename your module from `http.py` to `something_else.py`.

**Comment by webknjaz** [comment]
Next time, please consider posting "help" questions on Discourse (https://github.com/aio-libs/aiohttp/issues/4257), StackOverflow or mailing lists. This tracker is for bugs.

**Comment by CodeM01** [comment]
Thanks you for your swift response 😀
