### ISSUE TITLE
Unretrieved exceptions [socket.gaierror]

### ISSUE THREAD

**Issue by s0h3ck** [aio-libs/aiohttp#4330]
## Long story short

When fetching a list of URLs, they are exceptions that are not retrieved by `aiohttp`. The ones that I came across are `socket.gaierror`.

## Expected behaviour

No exceptions.

## Actual behaviour

```python-traceback
http://aaal.club a
http://aaal.club b
http://aaal.club c
Task exception was never retrieved
future: <Task finished coro=<TCPConnector._resolve_host() done, defined at /home/s0h3ck/.virtualenvs/example/lib/python3.7/site-packages/aiohttp/connector.py:774> exception=gaierror(-3, 'Temporary failure in name resolution')>
Traceback (most recent call last):
  File "/home/s0h3ck/.virtualenvs/example/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/home/s0h3ck/.virtualenvs/example/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 784, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib64/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

```

## Steps to reproduce

1. Grab the following piece of code:

```python
import argparse
import asyncio
import logging
import aiohttp
import sys
​
log = logging.getLogger("script")
​
​
async def get_url(session, url):
    try:
        async with session.get(url, timeout=5) as response:
            content = await response.content.read()
            content = content.decode(errors="ignore")
            for pattern in ["a", "b", "c"]:
                if pattern in content:
                    print(url, pattern)
    except Exception as error:
        log.error(error)
        return False
    else:
        return True
​
​
async def process(urls):
    sem = asyncio.Semaphore(10)
​
    async with aiohttp.ClientSession() as session:
        for url in urls:
            async with sem:
                await get_url(session, url)
​
​
if __name__ == "__main__":
    log.addHandler(logging.StreamHandler(stream=sys.stderr))
    log.setLevel(logging.INFO)
​
    parser = argparse.ArgumentParser()
    parser.add_argument("urls", type=argparse.FileType(mode="r"))
    args = parser.parse_args()
​
    urls = [line.strip() for line in args.urls.read().split("\n") if line.strip()]
    log.info(f"Found {len(urls)} urls")
​
    asyncio.run(process(urls))
```

2. Grab the list of urls: `curl -L -o urls.txt "https://drive.google.com/uc?export=download&id=16XKCJWKGHoTOOLh69Cjxn31HE2CmZd9w"`

3. Execute the script: `python fetcher.py urls.txt`

## Your environment

aiohttp==3.6.2
python 3.7

**Comment by asvetlov** [comment]
Thanks for the very good steps for the problem reproducing.
I see what you are talking on my laptop.

**Comment by buckle2000** [comment]
I came into the same problem in https://github.com/miguelgrinberg/python-socketio/issues/401.
