### ISSUE TITLE
 Exception Type: ValueError at /admin/ Exception Value: set_wakeup_fd only works in main thread

### ISSUE THREAD

**Issue by nima2000ir** [aio-libs/aiohttp#4487]
pardon my English
i have project that work god in django and mysql server but it dosnt work in apachi server
i think it cant connect to mysql

the error is

Environment:

Request Method: GET
Request URL: http://localhost/student/

Django Version: 3.0.2
Python Version: 3.8.0
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'student']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Template error:
In template c:\users\nima\envs\my_application\lib\site-packages\django\contrib\admin\templates\student\student_show.html, error at line 10
   set_wakeup_fd only works in main thread
   1 : <!DOCTYPE html>
   2 : <html>
   3 : <head>
   4 :     <title>Student_Show</title>
   5 : </head>
   6 : <body>
   7 : <h1>The Students Here at Dataflair</h1>
   8 : <div>
   9 :     <ul>
   10 :         {% for stud in student %} 
   11 :        <li>
   12 :          <h2>Name {{ stud.name }}</h2>
   13 :          <p> department {{ stud.department}}</p>
   14 :          <p> class {{ stud.stud_class}}</p>
   15 :        </li>
   16 :          {% endfor %}
   17 :     </ul>
   18 : </div>
   19 : </body>
   20 : </html>

Traceback (most recent call last):
  File "c:\users\nima\envs\my_application\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "c:\users\nima\envs\my_application\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "c:\users\nima\envs\my_application\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:/Users/nima/Documents/django/my_application\student\views.py", line 8, in student_show
    return render(request, 'student/student_show.html', {'student': student})
  File "c:\users\nima\envs\my_application\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\nima\envs\my_application\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "c:\users\nima\envs\my_application\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "c:\users\nima\envs\my_application\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "c:\users\nima\envs\my_application\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "c:\users\nima\envs\my_application\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "c:\users\nima\envs\my_application\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "c:\users\nima\envs\my_application\lib\site-packages\django\template\defaulttags.py", line 166, in render
    len_values = len(values)
  File "c:\users\nima\envs\my_application\lib\site-packages\django\db\models\query.py", line 258, in __len__
    self._fetch_all()
  File "c:\users\nima\envs\my_application\lib\site-packages\django\db\models\query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "c:\users\nima\envs\my_application\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "c:\users\nima\envs\my_application\lib\site-packages\django\db\models\sql\compiler.py", line 1142, in execute_sql
    cursor = self.connection.cursor()
  File "c:\users\nima\envs\my_application\lib\site-packages\django\utils\asyncio.py", line 19, in inner
    event_loop = asyncio.get_event_loop()
  File "c:\program files\python38\Lib\asyncio\events.py", line 636, in get_event_loop
    self.set_event_loop(self.new_event_loop())
  File "c:\program files\python38\Lib\asyncio\events.py", line 656, in new_event_loop
    return self._loop_factory()
  File "c:\program files\python38\Lib\asyncio\windows_events.py", line 310, in __init__
    super().__init__(proactor)
  File "c:\program files\python38\Lib\asyncio\proactor_events.py", line 633, in __init__
    signal.set_wakeup_fd(self_no)

Exception Type: ValueError at /student/
Exception Value: set_wakeup_fd only works in main thread

**Comment by webknjaz** [comment]
Hello, you use Django and this is a bug tracker for aiohttp which is in no way related to Django. Please, ask your question there.
https://github.com/django/django.
