### ISSUE TITLE
payload.read_chunk method never returns if locked by a semaphore

### ISSUE THREAD

**Issue by mykola-mokhnach** [aio-libs/aiohttp#4501]
## Long story short

We'd like to implement basic rate limiting features on the server side for file upload endpoint. The idea is to put the multipart form parsing under a semaphore to limit the count of simultaneous file uploads and avoid OOM errors (k8s is quite strict about it and kills the pod forcefully as soon as it runs out of the memory limit)

## Expected behaviour

The `read_chunk` method should not freeze if called from within a locked semaphore

## Actual behaviour

The caller code is frozen as soon as the semaphore is locked

## Steps to reproduce

```python

import asyncio
import aiofiles


SEMAPHORE = asyncio.Semaphore(1)

@web.middleware
async def rate_limit_middleware(request: web.Request, handler) -> web.Response:
    if request.path.find('/upload') < 0:
        # only limit file uploads
        return await handler(request)

    global SEMAPHORE
    async with SEMAPHORE:
        return await handler(request)


....

     self.app = web.Application(middlewares=[
            rate_limit_middleware,
     ]

....

    async def handle_upload(self, request: web.Request) -> web.Response:
          reader = await request.multipart()
          while True:
                part = await reader.next()
                if part is None:
                    break

                if part.name == 'payload':
                    log.debug(f'Writing the binary payload')
                    file_name = file_name or getattr(part, 'filename', '')
                    file_path = os.path.join(tmp_root, f'{uuid.uuid4()}.tmp')
                    try:
                        file_size = await write_payload_to_file(part, file_path,
                                                                max_size=Config.server.max_file_size)
                        log.info(f'Wrote the payload to a temporary file "{file_path}". '
                                 f'Payload size: {file_size} bytes')
                        if file_size < 1:
                            raise web.HTTPBadRequest(
                                reason=f'The size of the attached file is expected to be greater than zero, '
                                       f'got {file_size}')
                    except FileTooBigError as e:
                        log.warning(f'The attached file is too big: {e.actual_size} > {e.max_size}')
                        raise web.HTTPRequestEntityTooLarge(max_size=e.max_size, actual_size=e.actual_size)
....
async def write_payload_to_file(payload, dst_path: str, max_size: int = None) -> int:
    try:
        async with aiofiles.open(dst_path, mode='wb') as afp:
            size = 0
            while True:
                chunk = await payload.read_chunk(size=1 * MB)  # 8192 bytes by default
                if not chunk:
                    # Finish when no more chunks left
                    return size
                size += len(chunk)
                if max_size is not None and size > max_size:
                    raise FileTooBigError(max_size=max_size, actual_size=size)
                await afp.write(chunk)
    except Exception:
        if os.path.exists(dst_path):
            os.unlink(dst_path)
        raise

```

As soon as we start more than one simultaneous file upload, for example with curl, then the server freezes. Sending SIGINT to the main process uncovers the following stack trace:

```
Traceback (most recent call last):
  File "/opt/meta-parser/server/middlewares/errors.py", line 35, in error_middleware
    return await handler(request)
  File "/opt/meta-parser/server/server.py", line 564, in handle_upload
    max_size=Config.server.max_file_size)
  File "/opt/meta-parser/utils.py", line 41, in write_payload_to_file
    chunk = await payload.read_chunk(size=1 * MB)  # 8192 bytes by default
  File "/root/.local/share/virtualenvs/meta-parser-dhqRhYTW/lib/python3.7/site-packages/aiohttp/multipart.py", line 303, in read_chunk
    chunk = await self._read_chunk_from_stream(size)
  File "/root/.local/share/virtualenvs/meta-parser-dhqRhYTW/lib/python3.7/site-packages/aiohttp/multipart.py", line 332, in _read_chunk_from_stream
    chunk = await self._content.read(size)
  File "/root/.local/share/virtualenvs/meta-parser-dhqRhYTW/lib/python3.7/site-packages/aiohttp/streams.py", line 368, in read
    await self._wait('read')
  File "/root/.local/share/virtualenvs/meta-parser-dhqRhYTW/lib/python3.7/site-packages/aiohttp/streams.py", line 298, in _wait
    await waiter
```

The issue does not happen if the count of parallel upload is less than the count of allowed processes in the semaphore.

## Your environment

Docker container running in k8s env: `python:3.7.5-alpine`

Additionally installed packages: `curl unzip gcc libc-dev libffi-dev openssl-dev python3-dev libxml2-dev libxslt-dev` 

```
[packages]
aiohttp = "<4.0"
aiofiles = "<1.0"
```

**Comment by mykola-mokhnach** [comment]
I tried to workaround the issue by scheduling file payload parsing operation into a separate event loop, which is running in the other thread:

```python
import asyncio
from concurrent.futures import ThreadPoolExecutor, Executor

        self._pool = ThreadPoolExecutor(max_workers=1)

...

            loop = asyncio.new_event_loop()

            def f():
                asyncio.set_event_loop(loop)
                loop.run_forever()

            self._pool.submit(f)

            async def parse_payload():
                nonlocal file_name
                nonlocal file_path
                reader = await request.multipart()
                while True:
                    part = await reader.next()
                    if part is None:
                        break

                    if part.name == 'payload':
                        log.debug(f'Writing the binary payload')
                        file_name = file_name or getattr(part, 'filename', '')
                        file_path = os.path.join(tmp_root, f'{uuid.uuid4()}.tmp')
                        try:
                            file_size = await write_payload_to_file(part, file_path,
                                                                    max_size=Config.server.max_file_size)
                            log.info(f'Wrote the payload to a temporary file "{file_path}". '
                                     f'Payload size: {file_size} bytes')
                            if file_size < 1:
                                raise web.HTTPBadRequest(
                                    reason=f'The size of the attached file is expected to be greater than zero, '
                                           f'got {file_size}')
                        except FileTooBigError as e:
                            log.warning(f'The attached file is too big: {e.actual_size} > {e.max_size}')
                            raise web.HTTPRequestEntityTooLarge(max_size=e.max_size, actual_size=e.actual_size)
                    elif part.name == 'name':
                        ....

            asyncio.run_coroutine_threadsafe(parse_payload(), loop).result()
            loop.close()
....

```

Got the following exception as response (this time used `payload.read` instead of `read_chunk`):

```
  File "/opt/meta-parser/server/middlewares/errors.py", line 35, in error_middleware
    return await handler(request)
  File "/opt/meta-parser/server/server.py", line 594, in handle_upload
    asyncio.run_coroutine_threadsafe(parse_payload(), loop).result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/opt/meta-parser/server/server.py", line 566, in parse_payload
    part = await reader.next()
  File "/root/.local/share/virtualenvs/meta-parser-dhqRhYTW/lib/python3.7/site-packages/aiohttp/multipart.py", line 576, in next
    await self._read_until_first_boundary()
  File "/root/.local/share/virtualenvs/meta-parser-dhqRhYTW/lib/python3.7/site-packages/aiohttp/multipart.py", line 644, in _read_until_first_boundary
    chunk = await self._readline()
  File "/root/.local/share/virtualenvs/meta-parser-dhqRhYTW/lib/python3.7/site-packages/aiohttp/multipart.py", line 640, in _readline
    return await self._content.readline()
  File "/root/.local/share/virtualenvs/meta-parser-dhqRhYTW/lib/python3.7/site-packages/aiohttp/streams.py", line 328, in readline
    await self._wait('readline')
  File "/root/.local/share/virtualenvs/meta-parser-dhqRhYTW/lib/python3.7/site-packages/aiohttp/streams.py", line 298, in _wait
    await waiter
RuntimeError: Task <Task pending coro=<Server.handle_upload.<locals>.parse_payload() running at /opt/meta-parser/server/server.py:566> cb=[_chain_future.<locals>._call_set_state() at /usr/local/lib/python3.7/asyncio/futures.py:355]> got Future <Future pending> attached to a different loop
```

**Comment by Dreamsorcerer** [comment]
I couldn't reproduce this. If it's still an issue, please provide a complete reproducer.
