### ISSUE TITLE
aiohttp/aiobotocore hangs and raises timeout in case of 400 bad request with minio

### ISSUE THREAD

**Issue by anand870** [aio-libs/aiohttp#4579]
aiohttp/aiobotocore raises timeout error in case of 400 response with minio which botocore handles properly. All my testcases succeed except one in which i am trying to put object with invalid name in minio i.e '/testobj'.

💡 **To Reproduce**
```

import asyncio
import aiobotocore
from botocore.client import Config
import botocore.session

bucket = 'trash'
filename = '/testobj'
key = filename

def goboto():
    session = botocore.session.get_session()
    def handler(**kwargs):
        print("="*5+kwargs['event_name'])
        print(kwargs)
        print()
    session.register('response-received',handler,'1onreponse')
    session.register('before-send',handler,'1onrequest')
    client = session.create_client('s3',endpoint_url='http://localhost:9001',aws_access_key_id='minio',aws_secret_access_key='minio123',region_name='us-east-1')
    data = b'\x01'*1024
    #import pdb;pdb.set_trace()
    obj = client.put_object(Bucket='trash',Key='/testobj',Body=data)


async def go(loop):
    session = aiobotocore.get_session(loop=loop)
    def handler(**kwargs):
        print("="*5+kwargs['event_name'])
        print(kwargs)
        print()
    session.register('response-received',handler,'1onreponse')
    session.register('before-send',handler,'1onrequest')
    async with session.create_client('s3', region_name='us-east-1',
                                   aws_secret_access_key='minio123',
                                   aws_access_key_id='minio',
                                   endpoint_url = 'http://localhost:9001',
                                   config=Config(signature_version='s3v4')
                                   ) as client:
        # upload object to amazon s3
        data = b'\x01'*1024
        #import pdb;pdb.set_trace()
        resp = await client.put_object(Bucket=bucket,
                                            Key=key,
                                            Body=data)
        print(resp)


if __name__=="__main__":
    import logging
    import sys
    logger = logging.getLogger('1botocore.endpoint')
    logger.setLevel(logging.DEBUG)
    logger.addHandler(logging.StreamHandler(sys.stdout))
    logger.debug('test Started')

    #loop = asyncio.get_event_loop()
    #loop.run_until_complete(go(loop))
    goboto()

```

Add these steps below this comment: -->

💡 **Expected behavior**
aiohttp should should not raise timeout. Both botocore and aiobotocore sould behave similar.

**Behavior with botocore and minio**
```=====before-send.s3.PutObject
{'request': <AWSPreparedRequest stream_output=False, method=PUT, url=http://localhost:9001/trash//testobj, headers={'User-Agent': b'Botocore/1.13.14 Python/3.7.5 Linux/4.15.0-76-generic', 'Content-MD5': b'VKxYzB4nEaGj2IvOFbsVLQ==', 'Expect': b'100-continue', 'X-Amz-Date': b'20200215T180457Z', 'X-Amz-Content-SHA256': b'5a648d8015900d89664e00e125df179636301a2d8fa191c1aa2bd9358ea53a69', 'Authorization': b'AWS4-HMAC-SHA256 Credential=minio/20200215/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=7e6ca95fe2ac146409f36b56393018391e5d888b459a6367807c49c096e6d22c', 'Content-Length': '1024'}>, 'event_name': 'before-send.s3.PutObject'}

=====response-received.s3.PutObject
{'response_dict': {'headers': {'Accept-Ranges': 'bytes', 'Content-Length': '323', 'Content-Security-Policy': 'block-all-mixed-content', 'Content-Type': 'application/xml', 'Server': 'MinIO/RELEASE.2020-02-07T23-28-16Z', 'Vary': 'Origin', 'X-Amz-Request-Id': '15F3A587E4C2F5B5', 'X-Xss-Protection': '1; mode=block', 'Date': 'Sat, 15 Feb 2020 18:04:58 GMT'}, 'status_code': 400, 'context': {'operation_name': 'PutObject'}, 'body': b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>XMinioInvalidObjectName</Code><Message>Object name contains a leading slash.</Message><Key>/testobj</Key><BucketName>trash</BucketName><Resource>/trash//testobj</Resource><RequestId>15F3A587E4C2F5B5</RequestId><HostId>240585dc-43de-4f9d-bbc7-765e1d55b753</HostId></Error>'}, 'parsed_response': {'Error': {'Code': 'XMinioInvalidObjectName', 'Message': 'Object name contains a leading slash.', 'Key': '/testobj', 'BucketName': 'trash', 'Resource': '/trash//testobj'}, 'ResponseMetadata': {'RequestId': '15F3A587E4C2F5B5', 'HostId': '', 'HTTPStatusCode': 400, 'HTTPHeaders': {'accept-ranges': 'bytes', 'content-length': '323', 'content-security-policy': 'block-all-mixed-content', 'content-type': 'application/xml', 'server': 'MinIO/RELEASE.2020-02-07T23-28-16Z', 'vary': 'Origin', 'x-amz-request-id': '15F3A587E4C2F5B5', 'x-xss-protection': '1; mode=block', 'date': 'Sat, 15 Feb 2020 18:04:58 GMT'}}}, 'context': {'client_region': 'us-east-1', 'client_config': <botocore.config.Config object at 0x7ff13ad76510>, 'has_streaming_input': True, 'auth_type': None, 'signing': {'bucket': 'trash'}, 'timestamp': '20200215T180457Z'}, 'exception': None, 'event_name': 'response-received.s3.PutObject'}

Traceback (most recent call last):
  File "test.py", line 76, in <module>
    goboto()
  File "test.py", line 21, in goboto
    obj = client.put_object(Bucket='trash',Key='/testobj',Body=data)
  File "/home/rohit.anand/envs/fastapi/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/rohit.anand/envs/fastapi/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (XMinioInvalidObjectName) when calling the PutObject operation: Object name contains a leading slash.
```
**Behavior with aiobotocore and minio**
```
=====before-send.s3.PutObject
{'request': <AWSPreparedRequest stream_output=False, method=PUT, url=http://localhost:9001/trash//testobj, headers={'User-Agent': b'Botocore/1.13.14 Python/3.7.5 Linux/4.15.0-76-generic', 'Content-MD5': b'VKxYzB4nEaGj2IvOFbsVLQ==', 'Expect': b'100-continue', 'X-Amz-Date': b'20200215T181534Z', 'X-Amz-Content-SHA256': b'5a648d8015900d89664e00e125df179636301a2d8fa191c1aa2bd9358ea53a69', 'Authorization': b'AWS4-HMAC-SHA256 Credential=minio/20200215/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=5b7f05a7767b9bad5b703910ea6939fb807eed1bab266710396945d15293410c', 'Content-Length': '1024'}>, 'event_name': 'before-send.s3.PutObject'}

=====response-received.s3.PutObject
{'response_dict': None, 'parsed_response': None, 'context': {'client_region': 'us-east-1', 'client_config': <aiobotocore.config.AioConfig object at 0x7f6acccdb490>, 'has_streaming_input': True, 'auth_type': None, 'signing': {'bucket': 'trash'}, 'timestamp': '20200215T181534Z'}, 'exception': ServerTimeoutError('Timeout on reading data from socket'), 'event_name': 'response-received.s3.PutObject'}

=====before-send.s3.PutObject
{'request': <AWSPreparedRequest stream_output=False, method=PUT, url=http://localhost:9001/trash//testobj, headers={'User-Agent': b'Botocore/1.13.14 Python/3.7.5 Linux/4.15.0-76-generic', 'Content-MD5': b'VKxYzB4nEaGj2IvOFbsVLQ==', 'Expect': b'100-continue', 'X-Amz-Date': b'20200215T181635Z', 'X-Amz-Content-SHA256': b'5a648d8015900d89664e00e125df179636301a2d8fa191c1aa2bd9358ea53a69', 'Authorization': b'AWS4-HMAC-SHA256 Credential=minio/20200215/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=3a6a2ddaa7b0a8ea6f79d5948fe08e83ddc650c7826ef643d964b39d12aed54f', 'Content-Length': '1024'}>, 'event_name': 'before-send.s3.PutObject'}
.................
and has to be cancelled
```

**minio request log for aiobotocore**
```
16:56:56.533 [400 Bad Request] s3.PutObject localhost:9001/trash//testobj 172.20.0.1        1m0.032218s  ↑ 119 B ↓ 582 B
16:57:57.328 [400 Bad Request] s3.PutObject localhost:9001/trash//testobj 172.20.0.1        1m0.004064s  ↑ 119 B ↓ 582 B
16:58:58.382 [400 Bad Request] s3.PutObject localhost:9001/trash//testobj 172.20.0.1        1m0.053345s  ↑ 119 B ↓ 582 B
16:59:59.743 [400 Bad Request] s3.PutObject localhost:9001/trash//testobj 172.20.0.1        1m0.061754s  ↑ 119 B ↓ 582 B
17:01:06.333 [400 Bad Request] s3.PutObject localhost:9001/trash//testobj 172.20.0.1        1m0.002442s  ↑ 119 B ↓ 582 B
```

**minio request log for botocore**
```
16:55:03.558 [400 Bad Request] s3.PutObject localhost:9001/trash//testobj 172.20.0.1        1.00181s     ↑ 112 B ↓ 582 B
```

aiobotocore keeps on making request as aiohttp raises timeout error and hence multiple log for aiobotocore. botocore request duration is 1s where as aiobotocore request duration is 1 min
 
Tested with aiohttp (3.6.1 and 3,6.2)
python - 3.7.5
aiobotocore - 0.11.1
botocore - 1.13.14

**Docker Compose to set up minio**
```
version: "3.7"
services:
  minio:
    image: minio/minio:RELEASE.2020-02-07T23-28-16Z
    hostname: minio
    volumes:
      - minio-data:/export
    ports:
      - "9001:9000"
    networks:
      # On the internal you are exposed as minio1/2/3/4 by default
      rnd:
        aliases:
          - minio-cluster
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio==true
    command: server /export
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio-data:

networks:
  rnd:
    name: rnd-network
```
To View minio  logs, run on local
```
mc admin trace local
```

**Comment by Dreamsorcerer** [comment]
Is this still a problem? If so, would you be able to dig a bit further to investigate the cause?

**Comment by webknjaz** [comment]
Should this be transferred to the aiobotocore repo, though?

**Comment by webknjaz** [comment]
Ah, I see there's a duplicate over there already..
