### ISSUE TITLE
error while integrating sonar and influx with grafana

### ISSUE THREAD

**Issue by narayansinghjai** [aio-libs/aiohttp#4586]
count -----
1
begin export data...
Traceback (most recent call last):
  File "./sonar-client.py", line 110, in <module>
    ids = client.get_all_ids('/api/components/search?qualifiers=TRK')
  File "./sonar-client.py", line 34, in get_all_ids
    data = self._make_request(endpoint)
  File "./sonar-client.py", line 31, in _make_request
    return r.json()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by gvnirmal** [comment]
Even I am seeing the same error. Can someone get through this problem?

ubuntu@ip-172-31-47-199:~/sonarqube-exporter$ SONAR_USER=admin SONAR_PASSWORD=admin INFLUX_USER=admin INFLUX_PASSWORD=password INFLUX_DB=mydb /usr/bin/python3 sonar-client.py
Traceback (most recent call last):
  File "sonar-client.py", line 89, in <module>
    ids = client.get_all_ids('/api/components/search?qualifiers=TRK')
  File "sonar-client.py", line 30, in get_all_ids
    'id': component['id'],
KeyError: 'id'

**Comment by asvetlov** [comment]
Sorry, you are using the wrong project to report.
Please contact the author of sonar-client.py
