### ISSUE TITLE
response to json no exception

### ISSUE THREAD

**Issue by NiaNingXue** [aio-libs/aiohttp#464]
```
    while True:
        print('get_live_league_games: while True')
        start = time.clock()
        try:
            r = yield from aiohttp.request('GET', steam_urls['GetLiveLeagueGames'])
            print('yield from aiohttp.request')
            if r:
                res = yield from r.json()
            print('res = yield from r.json()')
        except BaseException:
            logging.warning('get_live_league_games:',BaseException)
            yield from asyncio.sleep(10)
            continue
```

it always stops at r.json() ,and no exception throwed.
the log just:
    get_live_league_games: while True
    try
    yield from aiohttp.request

**Comment by asvetlov** [comment]
@NiaNingXue sorry I don't follow
Does https://github.com/KeepSafe/aiohttp/blob/master/examples/client_json.py work for you?

**Comment by NiaNingXue** [comment]
```
source_traceback: Object created at (most recent call last):
  File "C:/Users/sunjinxue/PycharmProjects/Dota2/dota2liveleague.py", line 296, in <module>
    loop.run_forever()
  File "E:\Python34\lib\asyncio\base_events.py", line 276, in run_forever
    self._run_once()
  File "E:\Python34\lib\asyncio\base_events.py", line 1164, in _run_once
    handle._run()
  File "E:\Python34\lib\asyncio\events.py", line 120, in _run
    self._callback(*self._args)
  File "E:\Python34\lib\asyncio\tasks.py", line 292, in _wakeup
    self._step(value, None)
  File "E:\Python34\lib\asyncio\tasks.py", line 238, in _step
    result = next(coro)
  File "C:/Users/sunjinxue/PycharmProjects/Dota2/dota2liveleague.py", line 288, in init
    loop.create_task(get_live_league_games(loop))
Traceback (most recent call last):
  File "E:\Python34\lib\asyncio\selector_events.py", line 897, in _read_ready
    data = self._sock.recv(self.max_size)
  File "E:\Python34\lib\ssl.py", line 736, in recv
    return self.read(buflen)
  File "E:\Python34\lib\ssl.py", line 625, in read
    v = self._sslobj.read(len or 1024)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Python34\lib\asyncio\tasks.py", line 234, in _step
    result = coro.throw(exc)
  File "C:/Users/sunjinxue/PycharmProjects/Dota2/dota2liveleague.py", line 91, in get_live_league_games
    res = yield from r.json()
  File "E:\Python34\lib\site-packages\aiohttp\client_reqrep.py", line 692, in json
    yield from self.read()
  File "E:\Python34\lib\site-packages\aiohttp\client_reqrep.py", line 640, in read
    self._content = yield from self.content.read()
  File "E:\Python34\lib\site-packages\aiohttp\streams.py", line 398, in wrapper
    result = yield from func(self, *args, **kw)
  File "E:\Python34\lib\site-packages\aiohttp\streams.py", line 454, in read
    return (yield from super().read(n))
  File "E:\Python34\lib\site-packages\aiohttp\streams.py", line 174, in read
    block = yield from self.read(self._limit)
  File "E:\Python34\lib\site-packages\aiohttp\streams.py", line 398, in wrapper
    result = yield from func(self, *args, **kw)
  File "E:\Python34\lib\site-packages\aiohttp\streams.py", line 454, in read
    return (yield from super().read(n))
  File "E:\Python34\lib\site-packages\aiohttp\streams.py", line 187, in read
    yield from self._waiter
  File "E:\Python34\lib\asyncio\futures.py", line 386, in __iter__
    yield self  # This tells Task to wait for completion.
  File "E:\Python34\lib\asyncio\tasks.py", line 287, in _wakeup
    value = future.result()
  File "E:\Python34\lib\asyncio\futures.py", line 275, in result
    raise self._exception
aiohttp.errors.ServerDisconnectedError
```

i remove the try ..catch ,and it prints the above error

**Comment by asvetlov** [comment]
It's _HTTPS_ connection on Windows, right?
Windows doesn't support _https_ with proactor event loop until Python 3.5.
Selector-base event loop should work IIRC.

**Comment by NiaNingXue** [comment]
yeah,it's https on windows.but it doesn't always occur ,just sometimes throw the error

**Comment by asvetlov** [comment]
Well, if it happens time-to-time than your server occasionally rejects your request.
The best you can do in that situation is re-query the server.

**Comment by NiaNingXue** [comment]
ok,i will try ,thank you very much

**Comment by NiaNingXue** [comment]
@asvetlov  I reinstall the python 3.5 and still have the problem.http://stackoverflow.com/questions/31970740/python-aiohttp-request-stopped-but-raised-no-exception

**Comment by asvetlov** [comment]
Use `asyncio.wait_for()`

**Comment by ZYecho** [comment]
I use python 3.5 
`
async with session.get('http://www.zhihu.com') as r:
                json = await r.json()
`
the `json = await r.json()` always report **Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8** is there any bugs ?

**Comment by kxepal** [comment]
@ZYecho `text/html`  is definitely not right content type for JSON data. Much likely you received not JSON data, but some HTML page instead. If your server returns JSON with such content type, you should fix it in first place to return correct `application/json` instead.
