### ISSUE TITLE
how to config `max_field_size` on server side

### ISSUE THREAD

**Issue by bmbouter** [aio-libs/aiohttp#4657]
🐞 **Describe the bug**

I tried to configure `max_field_size` using the docs for make_handler. I understand it's deprecated, but I'm not sure what is replacing it.

💡 **To Reproduce**

Say you want to set it to 9000. I've tried two ways:

1. I tried adding it using the handler_args, and in my testing this still raises the exception when I submit a header larger than 8190 bytes (the default)

```
app = web.Application(handler_args={'max_line_size': 9000})
```

2. I also tried calling app.make_handler explicitly which completes but then my app.add_route calls fail complaining of a frozen router

Specifically I have: 

```
app = web.Application()
app.make_handler(max_line_size=9000)
```

Won't start and raises this exception:

```
[2020-03-23 22:55:06 +0000] [38721] [ERROR] Exception in gunicorn worker
Traceback (most recent call last):
  File "/usr/local/lib/pulp/lib64/python3.7/site-packages/aiohttp/worker.py", line 58, in run
    self.loop.run_until_complete(self._task)
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/usr/local/lib/pulp/lib64/python3.7/site-packages/aiohttp/worker.py", line 71, in _run
    app = await self.wsgi()
  File "/home/vagrant/devel/pulpcore/pulpcore/content/__init__.py", line 52, in server
    app.add_routes([web.get(settings.CONTENT_PATH_PREFIX, Handler().list_distributions)])
  File "/usr/local/lib/pulp/lib64/python3.7/site-packages/aiohttp/web_app.py", line 314, in add_routes
    self.router.add_routes(routes)
  File "/usr/local/lib/pulp/lib64/python3.7/site-packages/aiohttp/web_urldispatcher.py", line 1135, in add_routes
    route_def.register(self)
  File "/usr/local/lib/pulp/lib64/python3.7/site-packages/aiohttp/web_routedef.py", line 65, in register
    reg(self.path, self.handler, **self.kwargs)
  File "/usr/local/lib/pulp/lib64/python3.7/site-packages/aiohttp/web_urldispatcher.py", line 1084, in add_get
    resource = self.add_resource(path, name=name)
  File "/usr/local/lib/pulp/lib64/python3.7/site-packages/aiohttp/web_urldispatcher.py", line 1023, in add_resource
    self.register_resource(resource)
  File "/usr/local/lib/pulp/lib64/python3.7/site-packages/aiohttp/web_urldispatcher.py", line 992, in register_resource
    "Cannot register a resource into frozen router.")
RuntimeError: Cannot register a resource into frozen router.
```

💡 **Expected behavior**
I expect some reasonable documented way to configure max_line_size.

Python 3.7.6 on Fedora 31. I am using aiohttp==3.6.2

**Comment by webknjaz** [comment]
@bmbouter please try submitting a PR with tests where this'd fail (for the first case), this'd be a complete reproducer for us. The second method [is deprecated](https://github.com/aio-libs/aiohttp/blob/3.6/aiohttp/web_app.py#L377-L380) and is no longer present in master (the future 4.0). If you run your app with `python -Wd`, you'll see the deprecation warnings printed out to your console.

**Comment by bmbouter** [comment]
Yes I realize now I need to port to Application Runner, which I am doing right now actually. I don't believe this needs to be open.
