### ISSUE TITLE
'Fatal Python error: deallocating None' when requesting large number of URLs via proxy

### ISSUE THREAD

**Issue by callumapplsys** [aio-libs/aiohttp#4666]
🐞 **Describe the bug**

After making lots of subsequent HTTP requests (using a proxy server, in my case Squid 4.10) aiohttp client crashes Python with a fatal error: ```deallocating None```

💡 **To Reproduce**

To make it simpler, we've got a server called `binserve` which is also written using aiohttp server. If you make a HTTP `GET` request to /234 for example it will return a random binary string exactly 234 bytes in length (excluding the headers). This runs on a different machine in a different environment to isolate it from this issue; in other words any server should cause the same behaviour. Using that we make multiple requests using `random.randint(1,1000000)` to get a large sample.

Running the following code in our environment triggers the fatal error:
```python
import aiohttp
import asyncio
import random

BASE_SERVER = 'http://192.168.1.179:8080/'
PROXY = 'http://192.168.1.181:800/'

async def fetch(session, url):
    async with session.get(url, proxy=PROXY) as response:
        return await response.text()

async def main():
    async with aiohttp.ClientSession() as session:
        for i in range(120000):
            size = random.randint(1, 100000)
            resp = await fetch(session, BASE_SERVER + str(size))
            print(len(resp))

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

💡 **Expected behavior**

No fatal error, it should continue execution as normal.

📋 **Logs/tracebacks**

Python error:
```python
Fatal Python error: deallocating None

Current thread 0x00007fceaaa87700 (most recent call first):
  File "/usr/lib/python3.7/selectors.py", line 192 in get_key
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 287 in _add_writer
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 334 in add_writer
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 477 in _sock_connect
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 463 in sock_connect
  File "/usr/lib/python3.7/asyncio/base_events.py", line 946 in create_connection
  File "/usr/lib/python3.7/site-packages/aiohttp/connector.py", line 936 in _wrap_create_connection
  File "/usr/lib/python3.7/site-packages/aiohttp/connector.py", line 986 in _create_direct_connection
  File "/usr/lib/python3.7/site-packages/aiohttp/connector.py", line 1028 in _create_proxy_connection
  File "/usr/lib/python3.7/site-packages/aiohttp/connector.py", line 856 in _create_connection
  File "/usr/lib/python3.7/site-packages/aiohttp/connector.py", line 523 in connect
  File "/usr/lib/python3.7/site-packages/aiohttp/client.py", line 483 in _request
  File "/usr/lib/python3.7/site-packages/aiohttp/client.py", line 1012 in __aenter__
  File "rep.py", line 9 in fetch
  File "rep.py", line 16 in main
  File "/usr/lib/python3.7/asyncio/events.py", line 88 in _run
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1775 in _run_once
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539 in run_forever
  File "/usr/lib/python3.7/asyncio/base_events.py", line 571 in run_until_complete
  File "rep.py", line 21 in <module>
Aborted (core dumped)
```
From gdb:
```console
[New LWP 13699]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `appliance: downloader     '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007ff64eb733f8 in raise () from /lib64/libc.so.6
#0  0x00007ff64eb733f8 in raise () from /lib64/libc.so.6
#1  0x00007ff64eb74ffa in abort () from /lib64/libc.so.6
#2  0x00007ff64fbdb3d8 in fatal_error (prefix=prefix@entry=0x0, msg=msg@entry=0x7ff64fc57999 "deallocating None", status=status@entry=-1) at Python/pylifecycle.c:2179
#3  0x00007ff64fbdc273 in Py_FatalError (msg=msg@entry=0x7ff64fc57999 "deallocating None") at Python/pylifecycle.c:2189
#4  0x00007ff64fb34cf0 in none_dealloc (ignore=<optimized out>) at Objects/object.c:1548
#5  0x00007ff64fc3ca6a in buffered_flush_and_rewind_unlocked (self=self@entry=0x7ff6500c4a98) at ./Modules/_io/bufferedio.c:813
#6  0x00007ff64fc3ccac in buffered_flush (self=0x7ff6500c4a98, args=<optimized out>) at ./Modules/_io/bufferedio.c:837
#7  0x00007ff64fafcfe8 in _PyMethodDef_RawFastCallDict (method=<optimized out>, self=0x7ff6500c4a98, args=0x0, nargs=0, kwargs=<optimized out>) at Objects/call.c:482
#8  0x00007ff64fafd03d in _PyCFunction_FastCallDict (func=func@entry=0x7ff643b73dc8, args=<optimized out>, nargs=<optimized out>, kwargs=<optimized out>) at Objects/call.c:582
#9  0x00007ff64fafd1e0 in _PyObject_FastCallDict (callable=callable@entry=0x7ff643b73dc8, args=args@entry=0x0, nargs=nargs@entry=0, kwargs=kwargs@entry=0x0) at Objects/call.c:101
#10 0x00007ff64fafd516 in _PyObject_CallFunctionVa (callable=0x7ff643b73dc8, format=<optimized out>, va=<optimized out>, is_size_t=<optimized out>) at Objects/call.c:931
#11 0x00007ff64fafd751 in callmethod (callable=0x7ff643b73dc8, format=0x0, va=0x7ffefd2f6868, is_size_t=1) at Objects/call.c:1027
#12 0x00007ff64fafdc94 in _PyObject_CallMethodId_SizeT (obj=<optimized out>, name=name@entry=0x7ff64ff4b200 <PyId_flush>, format=format@entry=0x0) at Objects/call.c:1145
#13 0x00007ff64fc41799 in _io_TextIOWrapper_flush_impl (self=0x7ff6500ea630) at ./Modules/_io/textio.c:2915
#14 _io_TextIOWrapper_flush (self=0x7ff6500ea630, _unused_ignored=<optimized out>) at ./Modules/_io/clinic/textio.c.h:488
#15 0x00007ff64fafcfe8 in _PyMethodDef_RawFastCallDict (method=<optimized out>, self=0x7ff6500ea630, args=0x0, nargs=0, kwargs=<optimized out>) at Objects/call.c:482
#16 0x00007ff64fafd03d in _PyCFunction_FastCallDict (func=func@entry=0x7ff6493ef798, args=<optimized out>, nargs=<optimized out>, kwargs=<optimized out>) at Objects/call.c:582
#17 0x00007ff64fafd1e0 in _PyObject_FastCallDict (callable=callable@entry=0x7ff6493ef798, args=args@entry=0x0, nargs=nargs@entry=0, kwargs=kwargs@entry=0x0) at Objects/call.c:101
#18 0x00007ff64fafd516 in _PyObject_CallFunctionVa (callable=0x7ff6493ef798, format=<optimized out>, va=<optimized out>, is_size_t=<optimized out>) at Objects/call.c:931
#19 0x00007ff64fafd751 in callmethod (callable=0x7ff6493ef798, format=0x0, va=0x7ffefd2f6b08, is_size_t=0) at Objects/call.c:1027
#20 0x00007ff64fafda61 in _PyObject_CallMethodId (obj=obj@entry=0x7ff6500ea630, name=name@entry=0x7ff64ff19860 <PyId_flush>, format=format@entry=0x0) at Objects/call.c:1096
#21 0x00007ff64fbdb091 in flush_std_files () at Python/pylifecycle.c:1083
#22 0x00007ff64fbdb3ce in fatal_error (prefix=prefix@entry=0x0, msg=msg@entry=0x7ff64fc57999 "deallocating None", status=status@entry=-1) at Python/pylifecycle.c:2167
#23 0x00007ff64fbdc273 in Py_FatalError (msg=msg@entry=0x7ff64fc57999 "deallocating None") at Python/pylifecycle.c:2189
#24 0x00007ff64fb34cf0 in none_dealloc (ignore=<optimized out>) at Objects/object.c:1548
#25 0x00007ff64fb44388 in clear_slots (type=type@entry=0x1b40508, self=self@entry=0x7ff64472ee58) at Objects/typeobject.c:1073
#26 0x00007ff64fb452ca in subtype_dealloc (self=0x7ff64472ee58) at Objects/typeobject.c:1230
#27 0x00007ff64fb15aa7 in list_dealloc (op=0x7ff6493e50c8) at Objects/listobject.c:324
#28 0x00007ff64fb25c17 in insertdict (mp=mp@entry=0x7ff6493e3120, key=key@entry=0x7ff64cb382b0, hash=-2919758158610674453, value=value@entry=0x7ff643b74348) at Objects/dictobject.c:1076
#29 0x00007ff64fb281bf in PyDict_SetItem (op=0x7ff6493e3120, key=0x7ff64cb382b0, value=0x7ff643b74348) at Objects/dictobject.c:1463
#30 0x00007ff64fb2adab in _PyObjectDict_SetItem (tp=tp@entry=0x1b20f48, dictptr=<optimized out>, key=key@entry=0x7ff64cb382b0, value=value@entry=0x7ff643b74348) at Objects/dictobject.c:4333
#31 0x00007ff64fb36a46 in _PyObject_GenericSetAttrWithDict (obj=0x7ff6493e1588, name=0x7ff64cb382b0, value=<optimized out>, dict=dict@entry=0x0) at Objects/object.c:1357
#32 0x00007ff64fb36adb in PyObject_GenericSetAttr (obj=<optimized out>, name=<optimized out>, value=<optimized out>) at Objects/object.c:1379
#33 0x00007ff64fb35de2 in PyObject_SetAttr (v=v@entry=0x7ff6493e1588, name=<optimized out>, value=value@entry=0x7ff643b74348) at Objects/object.c:1016
#34 0x00007ff64fad768b in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:2015
#35 0x00007ff64fbb981c in PyEval_EvalFrameEx (f=f@entry=0x1ddb748, throwflag=throwflag@entry=0) at Python/ceval.c:547
#36 0x00007ff64fad3993 in function_code_fastcall (co=<optimized out>, args=<optimized out>, args@entry=0x7ff64941b948, nargs=1, globals=<optimized out>) at Objects/call.c:283
#37 0x00007ff64fafc3dc in _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x7ff64941b948, nargs=<optimized out>, kwnames=<optimized out>) at Objects/call.c:408
#38 0x00007ff64fada5f5 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at Python/ceval.c:4616
#39 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3110
#40 0x00007ff64fbb981c in PyEval_EvalFrameEx (f=f@entry=0x7ff64941b7c8, throwflag=throwflag@entry=0) at Python/ceval.c:547
#41 0x00007ff64fad3993 in function_code_fastcall (co=<optimized out>, args=<optimized out>, args@entry=0x7ff6447fd3b8, nargs=1, globals=<optimized out>) at Objects/call.c:283
#42 0x00007ff64fafc3dc in _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x7ff6447fd3b8, nargs=<optimized out>, kwnames=<optimized out>) at Objects/call.c:408
#43 0x00007ff64fada5f5 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at Python/ceval.c:4616
#44 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3110
#45 0x00007ff64fbb981c in PyEval_EvalFrameEx (f=f@entry=0x7ff6447fd230, throwflag=throwflag@entry=0) at Python/ceval.c:547
#46 0x00007ff64fad3993 in function_code_fastcall (co=<optimized out>, args=<optimized out>, args@entry=0x19a0fa8, nargs=2, globals=<optimized out>) at Objects/call.c:283
#47 0x00007ff64fafc3dc in _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x19a0fa8, nargs=<optimized out>, kwnames=<optimized out>) at Objects/call.c:408
#48 0x00007ff64fada5f5 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at Python/ceval.c:4616
#49 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3110
#50 0x00007ff64fbb981c in PyEval_EvalFrameEx (f=f@entry=0x19a0e28, throwflag=throwflag@entry=0) at Python/ceval.c:547
#51 0x00007ff64fad3993 in function_code_fastcall (co=<optimized out>, args=<optimized out>, args@entry=0x7ff6500efb70, nargs=0, globals=<optimized out>) at Objects/call.c:283
#52 0x00007ff64fafc3dc in _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x7ff6500efb70, nargs=<optimized out>, kwnames=<optimized out>) at Objects/call.c:408
#53 0x00007ff64fada33d in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at Python/ceval.c:4616
#54 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3124
#55 0x00007ff64fbb981c in PyEval_EvalFrameEx (f=f@entry=0x7ff6500ef9f8, throwflag=throwflag@entry=0) at Python/ceval.c:547
#56 0x00007ff64fbba298 in _PyEval_EvalCodeWithName (_co=_co@entry=0x7ff650012540, globals=globals@entry=0x7ff650043168, locals=locals@entry=0x7ff650043168, args=args@entry=0x0, argcount=argcount@entry=0, kwnames=kwnames@entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:3930
#57 0x00007ff64fbba3bd in PyEval_EvalCodeEx (_co=_co@entry=0x7ff650012540, globals=globals@entry=0x7ff650043168, locals=locals@entry=0x7ff650043168, args=args@entry=0x0, argcount=argcount@entry=0, kws=kws@entry=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:3959
#58 0x00007ff64fbba3ef in PyEval_EvalCode (co=co@entry=0x7ff650012540, globals=globals@entry=0x7ff650043168, locals=locals@entry=0x7ff650043168) at Python/ceval.c:524
#59 0x00007ff64fbe2bb9 in run_mod (mod=mod@entry=0x1999400, filename=filename@entry=0x7ff64ea977c8, globals=globals@entry=0x7ff650043168, locals=locals@entry=0x7ff650043168, flags=flags@entry=0x7ffefd2f794c, arena=arena@entry=0x7ff65013d0a8) at Python/pythonrun.c:1035
#60 0x00007ff64fbe4f36 in PyRun_FileExFlags (fp=fp@entry=0x1a1d300, filename_str=filename_str@entry=0x7ff65002fbb0 "/usr/bin/downloader", start=start@entry=257, globals=globals@entry=0x7ff650043168, locals=locals@entry=0x7ff650043168, closeit=closeit@entry=1, flags=0x7ffefd2f794c) at Python/pythonrun.c:988
#61 0x00007ff64fbe5098 in PyRun_SimpleFileExFlags (fp=fp@entry=0x1a1d300, filename=<optimized out>, filename@entry=0x7ff65002fbb0 "/usr/bin/downloader", closeit=closeit@entry=1, flags=flags@entry=0x7ffefd2f794c) at Python/pythonrun.c:429
#62 0x00007ff64fbe5539 in PyRun_AnyFileExFlags (fp=fp@entry=0x1a1d300, filename=0x7ff65002fbb0 "/usr/bin/downloader", closeit=closeit@entry=1, flags=flags@entry=0x7ffefd2f794c) at Python/pythonrun.c:84
#63 0x00007ff64fbfdf0d in pymain_run_file (p_cf=0x7ffefd2f794c, filename=0x193e540 L"/usr/bin/downloader", fp=0x1a1d300) at Modules/main.c:427
#64 pymain_run_filename (cf=0x7ffefd2f794c, pymain=0x7ffefd2f7a20) at Modules/main.c:1627
#65 pymain_run_python (pymain=0x7ffefd2f7a20) at Modules/main.c:2877
#66 pymain_main (pymain=pymain@entry=0x7ffefd2f7a20) at Modules/main.c:3038
#67 0x00007ff64fbfe15f in _Py_UnixMain (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:3073
#68 0x0000000000400759 in main (argc=<optimized out>, argv=<optimized out>) at ./Programs/python.c:15
```

📋 **Your version of the Python**

```console
$ python --version
Python 3.7.3
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.6.2
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: /usr/lib/python3.7/site-packages
Requires: attrs, yarl, chardet, multidict, async-timeout
```
```console
$ python -m pip show multidict
Name: multidict
Version: 4.7.5
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /usr/lib/python3.7/site-packages
Requires: 
```
```console
$ python -m pip show yarl
Name: yarl
Version: 1.4.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /usr/lib/python3.7/site-packages
Requires: idna, multidict
```

📋 **Additional context**

Linux 4.14.127, Slackware 14.2, Squid 4.10, Python 3.7.3, aiohttp 3.6.2

**Comment by webknjaz** [comment]
Hey @callumapplsys, thanks for the report! It'd be useful if you could submit a PR with pytest-based tests reproducing this behavior. Would you be able to do this?

**Comment by callumapplsys** [comment]
@webknjaz I'll have a go and see what happens. I'm not sure how the tests will handle a fatal Python error, as it causes the whole Python process to segfault with signal 6 SIGABRT.

**Comment by craiggowing** [comment]
After some experimentation I found I could reproduce this bug on many different environments and versions of Python, the common factor was when the multidict module was version 4.7.1. When multidict was updated to 4.7.6 the crash went away on all environments I tested it, so this bug report can possibly be closed if someone can reproduce these results.
