### ISSUE TITLE
Exception cannot be caught  

### ISSUE THREAD

**Issue by heroanswer** [aio-libs/aiohttp#4724]
🐞 **Describe the bug**

hello，friend，I have a little problem，My code cannot catch a specific exception
 this is my code:
```
# /usr/bin/env python
# -*- coding:utf-8 -*-
import aiohttp
from aiohttp import ClientSession
import asyncio
from socket import error as SocketError
import errno

async def send_request(sem, url):
    async with sem:
            async with ClientSession() as session:
                try:

                    async with session.get(f'http://127.0.0.1:80/{url}') as response:
                        r = await response.read()
                        print(r)
                        print(response.status)
                        response.close()

                except aiohttp.InvalidURL as e:
                    pass
                except aiohttp.ClientConnectorError as e:
                    pass
                except aiohttp.ClientOSError as e:
                    pass
                except aiohttp.ServerDisconnectedError as e:
                    pass
                except aiohttp.ClientResponseError as e:
                    pass
                except aiohttp.ServerTimeoutError as e:
                    pass
                except asyncio.TimeoutError as e :
                    pass

def main():
    loop = asyncio.get_event_loop()
    tasks = []
    sem = asyncio.Semaphore(500)  # 限制并发数量
    for i in range(100000):
        task = asyncio.ensure_future(send_request(sem, i))
        tasks.append(task)


    feature = asyncio.ensure_future(asyncio.gather(*tasks))
    loop.run_until_complete(feature)

if __name__ == "__main__":
    main()

```
The code will report an error after running for a while：
```
Traceback (most recent call last):
  File "2.py", line 31, in <module>
    main()
  File "2.py", line 28, in main
    loop.run_until_complete(feature)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "2.py", line 13, in hello
    async with session.get(f'http://127.0.0.1:80/{url}') as response:
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
```
But my code does catch the exception

💡 **To Reproduce**
This is my apache log information：
```
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6000 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6001 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6002 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6003 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6004 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6005 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6006 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6007 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6008 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6009 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6010 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6011 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6012 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6013 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6014 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6015 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6016 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6017 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6018 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6019 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6020 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6021 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6022 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6023 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6024 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6025 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6026 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6027 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6028 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6029 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6030 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6031 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6032 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6033 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6034 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6035 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6036 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6037 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6038 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6039 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6040 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6041 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6042 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"
127.0.0.1 - - [02/May/2020:11:51:47 +0800] "GET /6043 HTTP/1.1" 404 432 "-" "Python/3.7 aiohttp/3.6.2"

```
💡 **Expected behavior**

📋 **Your version of the Python**
my python version:
```
root@kali:/var/log/apache2# python3.7
Python 3.7.5 (default, Oct 27 2019, 15:43:29) 
[GCC 9.2.1 20191022] on linux
```
📋 **Your version of the aiohttp/yarl/multidict distributions**

my aiohttp version:
```
root@kali:/var/log/apache2# pip list|grep aiohttp
aiohttp                      3.6.2 
```
📋 **Additional context**

**Comment by heroanswer** [comment]
My problem has never been solved, please help me，please

**Comment by Zheaoli** [comment]
it doesn't look like an aiohttp bug. I can't reproduce it by causing the "Connection reset by peer" manually.

@asvetlov

**Comment by Dreamsorcerer** [comment]
Can you still reproduce this? It doesn't look like it should be possible..
