### ISSUE TITLE
Unclosed response

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#485]
master prints a lot of "Unclosed response" errors, 0.17.3 works fine

@asvetlov maybe `close()` related changes?

**Comment by asvetlov** [comment]
Perhaps yes. I'll take a look.

**Comment by asvetlov** [comment]
Fixed. 
Sorry, was my bad.

**Comment by amit151993** [comment]
while sending the hangout message through command line this type of errors, 
Anybody can identify the errors? 

root@amit:~/hangups# python3.4 /home/amit/hangups/examples/send_message.py --conversation-id "UgyqKlT2cb0xxJN1b-54AaABAagBwNKlAQ" --message-text " "
ERROR:asyncio:Unclosed response
client_response: <ClientResponse(https://0.client-channel.google.com/client-channel/channel/bind?VER=8&SID=825094D87141EEA7&RID=rpc&t=1&TYPE=xmlhttp&ctype=hangouts&gsessionid=UWOFGNfiA7mpXbl0jbMuIsGYBXdi58lh&CI=0) [200 OK]>
<CIMultiDictProxy('Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'Date': 'Wed, 03 May 2017 05:35:59 GMT', 'Content-Type': 'text/plain; charset=utf-8', 'Transfer-Encoding': 'chunked', 'X-Content-Type-Options': 'nosniff', 'X-Xss-Protection': '1; mode=block', 'Server': 'GSE', 'Alt-Svc': 'quic=":443"; ma=2592000; v="37,36,35"')>

Traceback (most recent call last):
  File "/home/amit/hangups/examples/send_message.py", line 30, in <module>
    run_example(send_message, '--conversation-id', '--message-text')
  File "/home/amit/hangups/examples/common.py", line 31, in run_example
    loop.run_until_complete(task)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 234, in _step
    result = coro.throw(exc)
  File "/home/amit/hangups/examples/common.py", line 76, in _async_main
    yield from example_coroutine(client, args)
  File "/home/amit/hangups/examples/send_message.py", line 26, in send_message
    yield from client.send_chat_message(request)
  File "/usr/local/lib/python3.4/dist-packages/hangups-0.4.2-py3.4.egg/hangups/client.py", line 568, in send_chat_message
  File "/usr/local/lib/python3.4/dist-packages/hangups-0.4.2-py3.4.egg/hangups/client.py", line 395, in _pb_request
hangups.exceptions.NetworkError: Request failed with status 0: ''
