### ISSUE TITLE
Yarl >= 1.5.0 breaks aiohttp

### ISSUE THREAD

**Issue by sarahfenway** [aio-libs/aiohttp#4880]
🐞 **Describe the bug**
Breaking change in yarl 1.5.0 breaks aiohttp.

💡 **To Reproduce**
Install aiohttp via pip, then `from aiohttp import web`

💡 **Expected behavior**
It should import `web`

📋 **Logs/tracebacks**

```python-traceback (paste your traceback in the next line)
 File "/usr/local/lib/python3.7/site-packages/myprojectnamehere/services/application/product_service.py", line 3, in <module>
    from aiohttp import web
  File "/usr/local/lib/python3.7/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import BaseConnector as BaseConnector
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 30, in <module>
    from yarl import URL
  File "/usr/local/lib/python3.7/site-packages/yarl/__init__.py", line 1, in <module>
    from ._url import URL, cache_clear, cache_configure, cache_info
  File "/usr/local/lib/python3.7/site-packages/yarl/_url.py", line 56, in <module>
    @rewrite_module
  File "/usr/local/lib/python3.7/site-packages/yarl/_url.py", line 132, in URL
    _QUERY_PART_QUOTER = _Quoter(safe="?/:@", qs=True, requote=False)
  File "yarl/_quoting.pyx", line 192, in yarl._quoting._Quoter.__init__
TypeError: __init__() got an unexpected keyword argument 'requote'
```

📋 **Your version of the Python**

```console
python 3.7.4
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
aiohttp==3.6.2
```
```console
$ python -m pip show multidict
multidict==4.5.2
```
```console
$ python -m pip show yarl
yarl==1.5.0
```

**Comment by Harmon758** [comment]
This was [an issue with yarl's MANIFEST.in](https://github.com/aio-libs/yarl/issues/485) that should now be fixed with v1.5.1 of yarl.

**Comment by sarahfenway** [comment]
Unfortunately, it's not fixed with v1.5.1 of yarl. (Exactly the same error. This is being built in a docker container, so I can see the pip install log from the docker build, and it installs yarl 1.5.1)

**Comment by webknjaz** [comment]
>  ```python-traceback
>  File "yarl/_quoting.pyx", line 192, in yarl._quoting._Quoter.__init__`
>  ```

Your traceback refers to `yarl/_quoting.pyx` that does not exist in YARL 1.5+ so I'm pretty sure there's some mixup in your env. Also, w/o a reproducer there's not much we can do.

**Comment by justinaustin** [comment]
I am running into this same error on a fresh installation of `aiohttp` (via `dephell`). Here's my traceback:

```python-traceback
$ python -m dephell --version
Traceback (most recent call last):
  File "/Users/austin/.pyenv/versions/3.6.10/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/austin/.pyenv/versions/3.6.10/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/austin/.local/lib/python3.6/site-packages/dephell/__main__.py", line 2, in <module>
    from .cli import entrypoint
  File "/Users/austin/.local/lib/python3.6/site-packages/dephell/cli.py", line 11, in <module>
    from .commands import COMMANDS
  File "/Users/austin/.local/lib/python3.6/site-packages/dephell/commands/__init__.py", line 2, in <module>
    from .discover import COMMANDS
  File "/Users/austin/.local/lib/python3.6/site-packages/dephell/commands/discover.py", line 86, in <module>
    module = import_module('.' + module_name, package=package)
  File "/Users/austin/.pyenv/versions/3.6.10/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/austin/.local/lib/python3.6/site-packages/dephell/commands/deps_add.py", line 7, in <module>
    from ..actions import get_resolver
  File "/Users/austin/.local/lib/python3.6/site-packages/dephell/actions/__init__.py", line 7, in <module>
    from ._converting import attach_deps
  File "/Users/austin/.local/lib/python3.6/site-packages/dephell/actions/_converting.py", line 7, in <module>
    from ..converters import CONVERTERS
  File "/Users/austin/.local/lib/python3.6/site-packages/dephell/converters/__init__.py", line 5, in <module>
    from .base import BaseConverter
  File "/Users/austin/.local/lib/python3.6/site-packages/dephell/converters/base.py", line 11, in <module>
    from ..controllers import Graph, Mutator, Resolver
  File "/Users/austin/.local/lib/python3.6/site-packages/dephell/controllers/__init__.py", line 3, in <module>
    from ._dependency import DependencyMaker
  File "/Users/austin/.local/lib/python3.6/site-packages/dephell/controllers/_dependency.py", line 18, in <module>
    from ..repositories import get_repo
  File "/Users/austin/.local/lib/python3.6/site-packages/dephell/repositories/__init__.py", line 2, in <module>
    from ._conda import CondaCloudRepo, CondaGitRepo, CondaRepo
  File "/Users/austin/.local/lib/python3.6/site-packages/dephell/repositories/_conda/__init__.py", line 2, in <module>
    from ._cloud import CondaCloudRepo
  File "/Users/austin/.local/lib/python3.6/site-packages/dephell/repositories/_conda/_cloud.py", line 24, in <module>
    from ...networking import requests_session
  File "/Users/austin/.local/lib/python3.6/site-packages/dephell/networking.py", line 10, in <module>
    from aiohttp import ClientError, ClientSession, TCPConnector
  File "/Users/austin/.local/lib/python3.6/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import BaseConnector as BaseConnector
  File "/Users/austin/.local/lib/python3.6/site-packages/aiohttp/client.py", line 30, in <module>
    from yarl import URL
  File "/Users/austin/.local/lib/python3.6/site-packages/yarl/__init__.py", line 1, in <module>
    from ._url import URL, cache_clear, cache_configure, cache_info
  File "/Users/austin/.local/lib/python3.6/site-packages/yarl/_url.py", line 56, in <module>
    @rewrite_module
  File "/Users/austin/.local/lib/python3.6/site-packages/yarl/_url.py", line 132, in URL
    _QUERY_PART_QUOTER = _Quoter(safe="?/:@", qs=True, requote=False)
  File "yarl/_quoting.pyx", line 192, in yarl._quoting._Quoter.__init__
TypeError: __init__() got an unexpected keyword argument 'requote'
```

My environment contains `aiohttp==3.6.2` and `yarl==1.5.1`.

I can also confirm that installing `yarl==1.4.2` fixes this issue for me

**Comment by webknjaz** [comment]
@justinaustin please post a complete reproducer to https://github.com/aio-libs/yarl/issues/485 and we'll try to take a look. Nobody's been able to reproduce it so far. Also, your traceback tells us almost nothing about your env, only that you use `pyenv` and used `--user` with `pip`.

**Comment by Harmon758** [comment]
This is late, but since there's still some discord.py users encountering this issue:

Since, it's possible that [force reinstalling v1.5.0 even without using the cache can fail](https://github.com/aio-libs/yarl/issues/485#issuecomment-666487279), I think it's plausible that this is because there are files that are mistakenly no longer associated with the library by pip that will not be uninstalled during the reinstall. This means that it's also possible that [upgrading from v1.5.0 to v1.5.1 will not fix the issue](https://github.com/aio-libs/yarl/issues/485#issuecomment-672279510), since those files will not be uninstalled during the upgrade process either.

Since yarl v1.4.2's MANIFEST.in is correct, **downgrading to yarl v1.4.2 fixes the issue.**
Additionally, **there should be no issue with upgrading to a version of yarl > 1.5.0 (e.g. v1.5.1) afterwards**, since the incorrect MANIFEST.in in v1.5.0 would be skipped.
