### ISSUE TITLE
Invalid exceptions handling or asyncio bug in Windows 10  [WinError 52] duplicate name in network

### ISSUE THREAD

**Issue by ChameleonRed** [aio-libs/aiohttp#4900]
🐞 **Describe the bug**

I wrote some program which setup 8-16 process with servers using aiohttp.web.Server all of then is sending heartbeats.

Maybe problem is with too many open connections but with reported as duplicate name in network what is wrong.

aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:8002 ssl:default [Połączenie nie zostało nawiązane, ponieważ w sieci istnieje duplikat nazwy. Jeśli przyłączasz się do domeny, przejdź do apletu System w Panelu sterowania, aby zmienić nazwę komputera, i spróbuj ponownie. Jeśli przyłączasz się do grupy roboczej, wybierz inną nazwę grupy]
9744:peer_2:ERROR:__mp_main__:Send heartbeat ServerAddress(host='127.0.0.1', port=8009).:s01_distributed_farm:212
Traceback (most recent call last):
  File "C:\Users\Cezary.Wagner\PycharmProjects\medptr2\venv\lib\site-packages\aiohttp\connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "C:\root\Python38\lib\asyncio\base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "C:\root\Python38\lib\asyncio\base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "C:\root\Python38\lib\asyncio\base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\root\Python38\lib\asyncio\proactor_events.py", line 702, in sock_connect
    return await self._proactor.connect(sock, address)
  File "C:\root\Python38\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\root\Python38\lib\asyncio\windows_events.py", line 595, in finish_connect
    ov.getresult()
OSError: [WinError 52] Połączenie nie zostało nawiązane, ponieważ w sieci istnieje duplikat nazwy. Jeśli przyłączasz się do domeny, przejdź do apletu System w Panelu sterowania, aby zmienić nazwę komputera, i spróbuj ponownie. Jeśli przyłączasz się do grupy roboczej, wybierz inną nazwę grupy

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Cezary.Wagner\PycharmProjects\medptr2\sandbox\distributed\s01_distributed_farm.py", line 196, in send_heartbeat
    async with session.get(f'http://{server_address.host}:{server_address.port}/heartbeat',
  File "C:\Users\Cezary.Wagner\PycharmProjects\medptr2\venv\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Cezary.Wagner\PycharmProjects\medptr2\venv\lib\site-packages\aiohttp\client.py", line 480, in _request
    conn = await self._connector.connect(
  File "C:\Users\Cezary.Wagner\PycharmProjects\medptr2\venv\lib\site-packages\aiohttp\connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Cezary.Wagner\PycharmProjects\medptr2\venv\lib\site-packages\aiohttp\connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "C:\Users\Cezary.Wagner\PycharmProjects\medptr2\venv\lib\site-packages\aiohttp\connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "C:\Users\Cezary.Wagner\PycharmProjects\medptr2\venv\lib\site-packages\aiohttp\connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\Cezary.Wagner\PycharmProjects\medptr2\venv\lib\site-packages\aiohttp\connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:8009 ssl:default [Połączenie nie zostało nawiązane, ponieważ w sieci istnieje duplikat nazwy. Jeśli przyłączasz się do domeny, przejdź do apletu System w Panelu sterowania, aby zmienić nazwę komputera, i spróbuj ponownie. Jeśli przyłączasz się do grupy roboczej, wybierz inną nazwę grupy]

💡 **To Reproduce**

Run this:
```
"""
Setup some distributed servers. Two of all are seed servers rest should be learned.
It uses multiprocessing to spawn servers.
"""

import abc
import asyncio
import logging
import multiprocessing
import random
from typing import Iterable, Set, List

import aiohttp.web
import aiohttp.client_exceptions

_logger = logging.getLogger(__name__)


class ServerAddress:
    def __init__(self, host, port):
        self.host = host
        self.port = port

    def __lt__(self, other: 'ServerAddress'):
        if type(self) is not type(other):
            raise TypeError()
        if self.host < other.host:
            return True
        if self.port < other.port:
            return True
        return False

    def __eq__(self, other: 'ServerAddress') -> bool:
        if type(self) is not type(other):
            raise TypeError()
        if self.host != other.host:
            return False
        if self.port != other.port:
            return False
        return True

    def __hash__(self):
        return hash(tuple(sorted(vars(self).items())))

    def __repr__(self):
        kwargs = ', '.join(f'{k}={v!r}' for k, v in vars(self).items())
        return f'{self.__class__.__qualname__}(' + kwargs + ')'


class BaseSend(abc.ABC):
    def __init__(self, target_server_address: ServerAddress):
        self.server_address = target_server_address
        self.retries = 0

    def add_retry(self):
        self.retries += 1


class SendHeartbeat(BaseSend):
    def __init__(self, target_server_address: ServerAddress, from_server_address: ServerAddress):
        super().__init__(target_server_address=target_server_address)

        self.from_server_address = from_server_address

    def __eq__(self, other: 'SendHeartbeat') -> bool:
        if type(self) is not type(other):
            raise TypeError()
        if self.server_address != other.server_address:
            return False
        if self.from_server_address != other.from_server_address:
            return False
        return True

    def __hash__(self):
        return hash((
            self.server_address,
            self.from_server_address,
        ))


class SendNewPeer(BaseSend):
    def __init__(self, target_server_address: ServerAddress, new_server_address: ServerAddress):
        super().__init__(target_server_address=target_server_address)

        self.new_server_address = new_server_address

    def __eq__(self, other: 'SendNewPeer') -> bool:
        if type(self) is not type(other):
            raise TypeError()
        if self.server_address != other.server_address:
            return False
        if self.new_server_address != other.new_server_address:
            return False
        return True

    def __hash__(self):
        return hash((
            self.server_address,
            self.new_server_address,
        ))


class DistributedServer:
    HEARTBEAT_SLEEP_SECONDS = 1.0
    HEARTBEAT_SLEEP_SECONDS_RANDOM = HEARTBEAT_SLEEP_SECONDS * 0.05
    HEARTBEAT_CONNECTION_TIMEOUT = 0.010

    NEW_PEER_CONNECTION_TIMEOUT = 0.010

    CLIENT_CONNECTION_LIMIT = 50

    def __init__(self, host: str, port: int, seed_server_addresses: Iterable[ServerAddress]):
        self.server_address = ServerAddress(host=host, port=port)
        self.seed_server_addresses: Set[ServerAddress] = set(seed_server_addresses)
        self.active_peer_server_addresses: Set[ServerAddress] = set()
        self.dead_peer_server_addresses: Set[ServerAddress] = set()

        self.client_session_new_peer = aiohttp.ClientSession(conn_timeout=self.NEW_PEER_CONNECTION_TIMEOUT)
        self.client_session_heartbeat = aiohttp.ClientSession(conn_timeout=self.HEARTBEAT_CONNECTION_TIMEOUT)

        self.retries = set()

        self.heartbeats_queue = asyncio.Queue()
        self.heartbeats_send = 0
        self.heartbeats_succeed = 0
        self.heartbeats_failed = 0
        self.heartbeats_timeout = 0

        self.new_peer_queue = asyncio.Queue()

        self.dead_peer_queue = asyncio.Queue()

    def other_servers(self) -> Set[ServerAddress]:
        server_addresses = set()
        server_addresses.update(self.seed_server_addresses)
        server_addresses.update(self.active_peer_server_addresses)
        server_addresses.update(self.dead_peer_server_addresses)
        server_addresses.discard(self.server_address)
        return server_addresses

    async def handle_new_peer(self, request: aiohttp.web.Request):
        host = request.query.get('host')
        port = request.query.get('port')
        server_address = ServerAddress(host=host, port=int(port))
        _logger.debug('Handle new peer %s.', server_address)
        if server_address != self.server_address:
            self.active_peer_server_addresses.add(server_address)

        return aiohttp.web.Response()

    async def send_new_peer(self, server_address: ServerAddress, new_server_address: ServerAddress):
        try:
            async with aiohttp.ClientSession(conn_timeout=self.NEW_PEER_CONNECTION_TIMEOUT) as session:
                async with session.get(f'http://{server_address.host}:{server_address.port}/new_peer',
                                       params={'host': new_server_address.host, 'port': new_server_address.port}) as response:
                    _logger.debug('Send new peer %s %s.', server_address, new_server_address)
                    if response.status != 200:
                        self.dead_peer_server_addresses.add(server_address)
                        self.active_peer_server_addresses.discard(server_address)
                        _logger.error('Error %s write new peer %s %s.', response.status, server_address, new_server_address)
                    else:
                        self.dead_peer_server_addresses.discard(server_address)
                        self.active_peer_server_addresses.add(server_address)
                    await response.read()
        except:
            _logger.exception('Send new peer %s %s.', response.status, server_address, new_server_address)
            self.retries.add(SendNewPeer(target_server_address=server_address, new_server_address=new_server_address))
        else:
            self.retries.discard(SendNewPeer(target_server_address=server_address, new_server_address=new_server_address))

    async def handle_heartbeat(self, request: aiohttp.web.Request):
        host = request.query.get('host')
        port = request.query.get('port')
        new_server_address = ServerAddress(host=host, port=int(port))

        if new_server_address != self.server_address:
            before_active_peer_servers = len(self.active_peer_server_addresses)
            self.active_peer_server_addresses.add(new_server_address)
            after_active_peer_servers = len(self.active_peer_server_addresses)

            # new peer
            if before_active_peer_servers != after_active_peer_servers:
                for server_address in self.other_servers():
                    await self.send_new_peer(server_address=server_address, new_server_address=new_server_address)
        else:
            retry = self.retries.pop()
            if type(retry) is SendNewPeer:
                await self.send_new_peer(server_address=retry.server_address,
                                         new_server_address=retry.new_server_address)

        return aiohttp.web.Response()

    async def send_heartbeat(self, server_address: ServerAddress):
        try:
            async with aiohttp.ClientSession(conn_timeout=self.HEARTBEAT_CONNECTION_TIMEOUT) as session:
                async with session.get(f'http://{server_address.host}:{server_address.port}/heartbeat',
                                       params={'host': self.server_address.host, 'port': self.server_address.port}) as response:
                    if response.status != 200:
                        self.dead_peer_server_addresses.add(server_address)
                        self.active_peer_server_addresses.discard(server_address)
                        self.heartbeats_failed += 1
                    else:
                        self.dead_peer_server_addresses.discard(server_address)
                        self.active_peer_server_addresses.add(server_address)
                        self.heartbeats_succeed += 1
                    await response.read()
        except aiohttp.client_exceptions.ServerTimeoutError:
            self.heartbeats_timeout += 1
            self.heartbeats_failed += 1
        except:
            self.heartbeats_failed += 1
            _logger.exception('Send heartbeat %s.', server_address)
        finally:
            self.heartbeats_send += 1

    async def heartbeat_send_task(self):
        try:
            while True:
                send_heartbeat: SendHeartbeat = await self.heartbeats_queue.get()
                await self.send_heartbeat(server_address=send_heartbeat.server_address)
                self.heartbeats_queue.task_done()
        except asyncio.CancelledError:
            pass

    async def heart_task(self):
        try:
            while True:
                if self.heartbeats_queue.empty():
                    for server_address in self.other_servers():
                        await self.heartbeats_queue.put(SendHeartbeat(
                            target_server_address=server_address,
                            from_server_address=self.server_address))
                else:
                    _logger.debug('Heartbeat queue is full.')
                await asyncio.sleep(self.HEARTBEAT_SLEEP_SECONDS
                                    + random.random() * self.HEARTBEAT_SLEEP_SECONDS_RANDOM)
        except asyncio.CancelledError:
            pass

    async def start_heart(self, app: aiohttp.web.Application):
        heart_task = asyncio.create_task(self.heart_task())
        app['heart_task'] = heart_task
        heartbeat_send_task = asyncio.create_task(self.heartbeat_send_task())
        app['heartbeat_send_task'] = heartbeat_send_task

    async def stop_heart(self, app: aiohttp.web.Application):
        heart_task = app['heart_task']
        heart_task.cancel()
        heartbeat_send_task = app['heartbeat_send_task']
        heartbeat_send_task.cancel()
        await heart_task

    async def handle_state(self, request: aiohttp.web.Request):
        lines = [
            f'{self.seed_server_addresses=}',
            f'{self.active_peer_server_addresses=}',
            f'{self.dead_peer_server_addresses=}',
            f'{self.heartbeats_send=}',
            f'{self.heartbeats_failed=}',
            f'{self.heartbeats_succeed=}',
        ]
        return aiohttp.web.Response(body='\n'.join(lines))

    async def handle_main(self, request: aiohttp.web.Request):
        body = f'''\
<html>
    <head>
        <title>Distributed Server</title>
    </head>
    <body>
        <pre style="max-width: 120em; white-space: pre-wrap; margin: auto">
{len(self.seed_server_addresses)=} {sorted(self.seed_server_addresses)=}
{len(self.active_peer_server_addresses)=} {sorted(self.active_peer_server_addresses)=}
{len(self.dead_peer_server_addresses)=} {sorted(self.dead_peer_server_addresses)=}

{self.heartbeats_send=}
{self.heartbeats_failed=}
{self.heartbeats_succeed=}
{self.heartbeats_timeout=}
        </pre>
    </body>
</html>
'''
        return aiohttp.web.Response(body=body, content_type='text/html')

    def run(self, debug: bool):
        logging.debug('run')
        app = aiohttp.web.Application()
        app.add_routes([
            aiohttp.web.get('/', self.handle_main),
            aiohttp.web.get('/state', self.handle_state),
            aiohttp.web.get('/heartbeat', self.handle_heartbeat),
            aiohttp.web.get('/new_peer', self.handle_new_peer),
        ])
        app.on_startup.append(self.start_heart)
        app.on_cleanup.append(self.stop_heart)
        asyncio.get_event_loop().set_debug(debug)
        aiohttp.web.run_app(app=app, host=self.server_address.host, port=self.server_address.port,
                            access_log=None)


def create_distributed_server_process(host: str, port: int, seed_server_addresses: Iterable[ServerAddress], debug: bool):
    server = DistributedServer(host=host, port=port, seed_server_addresses=seed_server_addresses)
    server.run(debug=debug)


class DistributedFarm:
    def __init__(self, seed_server_addresses: Iterable[ServerAddress],
                 worker_server_addresses: Iterable[ServerAddress]):
        self.seed_peer_server_addresses = seed_server_addresses
        self.peer_server_addresses = worker_server_addresses
        self.processes: List[multiprocessing.Process] = []

    def run(self, debug):
        server_addresses = []
        server_addresses.extend(self.seed_peer_server_addresses)
        server_addresses.extend(self.peer_server_addresses)
        for i, server_address in enumerate(server_addresses):
            p = multiprocessing.Process(name=f'peer_{i}',
                                        target=create_distributed_server_process,
                                        kwargs={
                                            'debug': debug,
                                            'host': server_address.host,
                                            'port': server_address.port,
                                            'seed_server_addresses': self.seed_peer_server_addresses
                                        })
            p.start()
            self.processes.append(p)

    def stop(self):
        for process in self.processes:
            process.terminate()
            process.join()


async def main():
    server_addresses = [ServerAddress(host='127.0.0.1', port=x) for x in range(8000, 8016)]
    seed_server_addresses = server_addresses[0:2]
    worker_server_addresses = server_addresses[2:]
    farm = DistributedFarm(seed_server_addresses=seed_server_addresses, worker_server_addresses=worker_server_addresses)
    farm.run(debug=False)
    try:
        while True:
            await asyncio.sleep(0.5)
    except KeyboardInterrupt:
        farm.stop()


if __name__ == '__main__':
    asyncio.run(main())


def mp_main():
    logging.basicConfig(
        level=logging.DEBUG,
        format='%(process)s:%(processName)s:%(levelname)s:%(name)s:%(message)s:%(module)s:%(lineno)s'
    )
    pass


if __name__ == '__mp_main__':
    mp_main()
```

💡 **Expected behavior**

 [WinError 52] duplicate name in network should not happen on closing connection.

📋 **Logs/tracebacks**

```python-traceback (paste your traceback in the next line)

```

📋 **Your version of the Python**

```console
$ python --version
3.8.5
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
3.6.3
```
```console
$ python -m pip show multidict
4.7.6
```
```console
$ python -m pip show yarl
1.4.2
```

📋 **Additional context**

both

**Comment by asvetlov** [comment]
Sorry, I cannot reproduce and cannot help.
The attached listing doesn't look like "minimal reproducible example" :)
