### ISSUE TITLE
Stuck while retriving data from Twitter in Ubuntu 20.04

### ISSUE THREAD

**Issue by hadisfr** [aio-libs/aiohttp#4926]
🐞 **Describe the bug**
While trying to send request to some URLs such as Twitter, the library gives `TimeoutError`.

This is happening only in Ubuntu 20.04, and only with Twitter URLs (such as https://twitter.com/), while everything is OK with e.g. https://google.com/, or with Twitter in Ubuntu 18.04.

This **may** be related to https://github.com/aio-libs/aiohttp/issues/3676.

Also, `curl` works good for the aforementioned URL.

💡 **To Reproduce**
Run the following code (_tw.py_) in the described environment:
```python
#!/usr/bin/env python3

import aiohttp
import asyncio


async def main():
    async with aiohttp.ClientSession() as session:
        async with session.get('https://twitter.com/') as resp:
            print(await resp.text())

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    loop.close()
```

💡 **Expected behavior**

Gets HTML of https://twitter.com/.

📋 **Logs/tracebacks**

```python-traceback (paste your traceback in the next line)
Traceback (most recent call last):
  File "./tw.py", line 14, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./tw.py", line 10, in main
    print(await resp.text())
  File "***/.env/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1009, in text
    await self.read()
  File "***/.env/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 973, in read
    self._body = await self.content.read()
  File "***/.env/lib/python3.8/site-packages/aiohttp/streams.py", line 358, in read
    block = await self.readany()
  File "***/.env/lib/python3.8/site-packages/aiohttp/streams.py", line 380, in readany
    await self._wait('readany')
  File "***/.env/lib/python3.8/site-packages/aiohttp/streams.py", line 296, in _wait
    await waiter
  File "***/.env/lib/python3.8/site-packages/aiohttp/helpers.py", line 596, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

📋 **Your version of the Python**

```console
$ python --version
Python 3.8.2
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.6.2
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: ***/.env/lib/python3.8/site-packages
Requires: chardet, yarl, async-timeout, multidict, attrs
Required-by: twint, aiohttp-socks
```
```console
$ python -m pip show multidict
Name: multidict
Version: 4.7.5
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: ***/.env/lib/python3.8/site-packages
Requires: 
Required-by: yarl, aiohttp
```
```console
$ python -m pip show yarl
Name: yarl
Version: 1.4.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: ***/.env/lib/python3.8/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

📋 **Additional context**

```console
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

**Comment by himanshudabas** [comment]
Hi, I was just rewriting some of twint's implementation and I too came across this issue. I can confirm that this does not happen on Python 3.6.8
It happens on Python 3.8+ (haven't tested for all the versions though)

**Comment by derlih** [comment]
Not reproduced on my machine.
When I ran the provided test I saw the HTML content in the output of the script.

```console
$ python --version
Python 3.8.5

$ python -m pip show aiohttp
Name: aiohttp
Version: 3.7.1
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: /tmp/twitter_aiohttp_test/venv/lib/python3.8/site-packages
Requires: chardet, multidict, async-timeout, typing-extensions, yarl, attrs
Required-by: 

$ python -m pip show multidict
Name: multidict
Version: 5.0.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /tmp/twitter_aiohttp_test/venv/lib/python3.8/site-packages
Requires: 
Required-by: yarl, aiohttp

$ python -m pip show yarl
Name: yarl
Version: 1.6.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /tmp/twitter_aiohttp_test/venv/lib/python3.8/site-packages
Requires: idna, multidict
Required-by: aiohttp

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

**Comment by hadisfr** [comment]
Hmm something seems to be changed and the bug seems to be fixed. I reproduced this on my machine and multiple VMs, then. But my script at the original issue seems to work fine for me, too, now.
```console
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
$ python --version
Python 3.8.5
$ pip list
Package           Version
----------------- -------
aiohttp           3.7.1  
async-timeout     3.0.1  
attrs             20.2.0 
chardet           3.0.4  
idna              2.10   
multidict         5.0.0  
pip               20.0.2 
pkg-resources     0.0.0  
setuptools        44.0.0 
typing-extensions 3.7.4.3
wheel             0.35.1 
yarl              1.6.2 
```
Also I was able to use `GNS3-gui` which uses `aiohttp` some days ago.

Thanks @himanshudabas and @derlih. Hope I can use `twint` on my local machine again. :D
