### ISSUE TITLE
aiohttp.client_exceptions.ClientPayloadError: 400, message='Can not decode content-encoding: deflate'

### ISSUE THREAD

**Issue by bouwew** [aio-libs/aiohttp#4930]
🐞 **Describe the bug**

This error-message is reported by a Home Assistant user that tries to use the Plugwise-beta custom_component:
```
2020-08-21 23:20:18 ERROR (MainThread) [custom_components.plugwise.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/plugwise/config_flow.py", line 130, in async_step_user
    api = await validate_input(self.hass, user_input)
  File "/config/custom_components/plugwise/config_flow.py", line 74, in validate_input
    await api.connect()
  File "/usr/local/lib/python3.8/site-packages/Plugwise_Smile/Smile.py", line 161, in connect
    result = await resp.text()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1009, in text
    await self.read()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 973, in read
    self._body = await self.content.read()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 358, in read
    block = await self.readany()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 380, in readany
    await self._wait('readany')
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 296, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: 400, message='Can not decode content-encoding: deflate'
```

💡 **To Reproduce**

Try to add the Plugwise Stretch integration in Home Assistant Core v0.114.3 (with aiohttp v3.6.2):
![image](https://user-images.githubusercontent.com/11290930/90962964-605a5380-e4b4-11ea-966b-193c22a78921.png)
When trying to troubleshoot the 'Unexpected Error' he found the above error-message in the HA Core Logs.

💡 **Expected behavior**

The integration should be added successfully.

📋 **Logs/tracebacks**

```python-traceback (paste your traceback in the next line)

```

📋 **Your version of the Python**

3.8.3

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
3.6.2
```
```console
$ python -m pip show multidict
4.7.6
```
```console
$ python -m pip show yarl
1.4.2
```

📋 **Additional context**

I've found this issue: https://github.com/aio-libs/aiohttp/issues/1918
I'm not sure whether the problem I'm reporting is a duplicate? If yes, please let me know, thanks!

The Home Assistant Core Plugwise-beta custom_component, as a client, tries to connect to a web-server that is running on a local connected device, using an `aiohttp.ClientSession`. The setup of the connection fails with the error as shown above as the result.

**Comment by bouwew** [comment]
Update: the user that has this problem has managed to install aiohttp v3.7 (via `pip3 install git+http://github.com/aio-libs/aiohttp@3.7`). After updating to v3.7, the reported problem is gone.

So, when will v3.7 be released? :)

**Comment by derlih** [comment]
@bouwew 
3.7 is already released.
