### ISSUE TITLE
Aiohttp Sniper Need Help Python noob

### ISSUE THREAD

**Issue by ImaDirt2** [aio-libs/aiohttp#4944]
## Long story short
Running a minecraft sniper and aiohttp is bugging.

my problem is aiohttp can't connect to namemc this is important because me being a helper I need to figure out how to resolve this with other people.
## Expected behaviour
It prints sniping name inxxx seconds and snipes a name

## Actual behaviour

```python-traceback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
    return await fut
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/selector_events.py", line 499, in _sock_connect
    sock.connect(address)
OSError: [Errno 65] No route to host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "snipe.py", line 287, in <module>
    session = session(target_username, accounts, block_snipe)
  File "snipe.py", line 224, in __init__
    self.drop_time = loop.run_until_complete(time_snipe(self.target_username, self.block_snipe))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "snipe.py", line 89, in time_snipe
    async with session.get(f"https://namemc.com/search?q={target}") as page:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host namemc.com:443 ssl:default [No route to host]
```

## Steps to reproduce
With all the requirements installed run the snipe.py  within the directory of https://github.com/Kqzz/MCsniperPY
 

With all the requirements installed run the snipe.py  within the directory of https://github.com/Kqzz/MCsniperPY
## Your environment
Mac OS 10.12.6 python 3.8

## The code
```python
import aiohttp
import logging
from colorama import Fore, init
from datetime import datetime, timedelta
import asyncio
from os import path
import time
from bs4 import BeautifulSoup
import json

init()

logging.basicConfig(level=logging.INFO, format='%(message)s')
times = []


def custom_info(message):
    logging.info(f"{Fore.BLUE}[info] {Fore.RESET}{message}")


def print_title():
    print(f"""

{Fore.CYAN}┌──────────────────────────────────────────────────────────────────────────────────────┐
{Fore.CYAN}│{Fore.RESET} ███╗   ███╗ ██████╗███████╗███╗   ██╗██╗██████╗ ███████╗██████╗ {Fore.BLUE}██████╗ ██╗   ██╗
{Fore.CYAN}│{Fore.RESET} ████╗ ████║██╔════╝██╔════╝████╗  ██║██║██╔══██╗██╔════╝██╔══██╗{Fore.BLUE}██╔══██╗╚██╗ ██╔╝
{Fore.CYAN}│{Fore.RESET} ██╔████╔██║██║     ███████╗██╔██╗ ██║██║██████╔╝█████╗  ██████╔╝{Fore.BLUE}██████╔╝ ╚████╔╝{Fore.CYAN}     |
|{Fore.RESET} ██║╚██╔╝██║██║     ╚════██║██║╚██╗██║██║██╔═══╝ ██╔══╝  ██╔══██╗{Fore.BLUE}██╔═══╝   ╚██╔╝     {Fore.CYAN} │
{Fore.RESET}  ██║ ╚═╝ ██║╚██████╗███████║██║ ╚████║██║██║     ███████╗██║  ██║{Fore.BLUE}██║        ██║      {Fore.CYAN} │
{Fore.RESET}  ╚═╝     ╚═╝ ╚═════╝╚══════╝╚═╝  ╚═══╝╚═╝╚═╝     ╚══════╝╚═╝  ╚═╝{Fore.BLUE}╚═╝        ╚═╝      {Fore.CYAN} │
{Fore.CYAN}└──────────────────────────────────────────────────────────────────────────────────────┘
{Fore.GREEN}Developed by @Kqzz#0001 on Discord {Fore.BLUE}| Discord server: https://discord.gg/jZm4qNF
{Fore.GREEN}THIS SNIPER IS 100% FREE ON GITHUB""", Fore.RESET)


def menu(options):
    i = 1
    # loop through options and print
    custom_info(f"select a number 1 - {len(options)}")
    for option in options:
        print(f"{i}). {option}")
        i += 1
    # main function loop
    # Doesn't end until a correct answer is given
    while True:
        try:
            # takes an input using readchar's readkey function
            choice = int(input("> "))
            options[choice - 1]
            # returns the option the user selected by list index
            return choice - 1
        except (ValueError, IndexError):
            print("please enter a valid option")


def custom_input(message):
    print(f"{Fore.BLUE}[input] {Fore.RESET}", end='')
    input_return = input(message)
    return input_return


def check_resp(status):
    if str(status)[0] == str(2):
        return True
    else:
        return False


def resp_error(message):
    print(f"{Fore.WHITE}[{Fore.RED}ERROR{Fore.WHITE}] {message}")


# def get_proxies():
#     with open("working.txt", "r") as f:
#         prox = f.readlines()
#         proxies = []
#         for proxy in prox:
#             proxies.append(proxy.strip())
#         return proxies


async def time_snipe(target, block_snipe):
    now = datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%S')
    now = datetime.strptime(now, '%Y-%m-%dT%H:%M:%S')
    block_snipe_words = ["snipe", "block"]
    async with aiohttp.ClientSession() as session:
        try:
            # namemc_url = f"https://namemc.com/search?q={target}"
            async with session.get(f"https://namemc.com/search?q={target}") as page:
                # page = requests.get(namemc_url)
                soup = BeautifulSoup(await page.text(), 'html.parser')
                snipe_time = soup.find("time", {"id": "availability-time"}).attrs["datetime"]
                snipe_time = datetime.strptime(snipe_time, '%Y-%m-%dT%H:%M:%S.000Z')
        except AttributeError:
            status_bar = soup.find(id="status-bar")
            info = status_bar.find_all("div", class_="col-sm-6 my-1")
            status = info[0].text.split("\n")[2]
            if status.lower().rstrip('*') == 'available':
                snipe_time = custom_input("At what time will this name be able to be turboed (month/day/yr, 24hrtime_hour:minute:second) (UTC)\nexample: 03/06/2020 01:06:45\n» ")
                snipe_time = datetime.strptime(snipe_time.strip(), "%m/%d/%Y %H:%M:%S")
                wait_time = snipe_time - now
                wait_time = wait_time.seconds / 60
                custom_info(f"{block_snipe_words[block_snipe].rstrip('e')}ing \"{target}\" in {wait_time} minutes | {block_snipe_words[block_snipe].rstrip('e')}ing at {snipe_time} (utc)")
                return snipe_time
            print(f"\"{target}\" is {status}. The sniper cannot claim names that are {status} so go claim it fast through https://my.minecraft.net if possible.")
            quit()

        wait_time = snipe_time - now
        wait_time = wait_time.seconds
        custom_info(f"{block_snipe_words[block_snipe].rstrip('e')}ing \"{target}\" in {wait_time} seconds | {block_snipe_words[block_snipe].rstrip('e')}ing at {snipe_time} (utc)")
        return snipe_time


class Account:
    def __init__(self, email, password, questions=[]):
        self.email = email
        self.password = password
        self.questions = questions
        self.authenticate_json = {"agent": {"name": "Minecraft", "version": 1}, "username": self.email, "password": self.password}
        self.headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.3", "Content-Type": "application/json"}

    async def authenticate(self, session):
        # logging.info(f"{Fore.WHITE}[{Fore.CYAN}INFO{Fore.WHITE}]{Fore.RESET} starting auth for {Fore.CYAN}{self.email}{Fore.RESET}")
        async with session.post("https://authserver.mojang.com/authenticate", json=self.authenticate_json, headers=self.headers) as r:
            if check_resp(r.status):
                resp_json = await r.json()
                try:
                    self.uuid = resp_json["selectedProfile"]["id"]
                except KeyError:
                    custom_info(f"{self.email} is unpaid and cannot snipe names. please make sure you are blocking.")
                self.auth = {"Authorization": "Bearer: " + resp_json["accessToken"]}
                self.access_token = resp_json["accessToken"]
            else:
                resp_error(f"invalid credentials | {self.email}")
                return
        async with session.get("https://api.mojang.com/user/security/challenges", headers=self.auth) as r:
            answers = []
            if check_resp(r.status):
                resp_json = await r.json()
                if resp_json == []:
                    logging.info(f"{Fore.WHITE}[{Fore.GREEN}success{Fore.WHITE}]{Fore.GREEN} signed in to {self.email}{Fore.RESET}")
                else:
                    try:
                        for x in range(3):
                            answers.append({"id": resp_json[x]["answer"]["id"], "answer": self.questions[x]})
                    except IndexError:
                        logging.info(f"{Fore.WHITE}[{Fore.RED}ERROR{Fore.WHITE}]{Fore.RESET} {self.email} has security questions and you did not provide any!")
                    async with session.post("https://api.mojang.com/user/security/location", json=answers, headers=self.auth) as r:
                        if check_resp(r.status):
                            logging.info(f"{Fore.WHITE}[{Fore.GREEN}success{Fore.WHITE}]{Fore.GREEN} signed in to {self.email}{Fore.RESET}")
                        else:
                            resp_error(f"security questions incorrect | {self.email}")

    async def block_req(self, session, ctarget_username):
        await asyncio.sleep(0)
        # logging.info(f'{Fore.WHITE}[{Fore.GREEN}SUCCESS{Fore.WHITE}] Sent Request @ {Fore.CYAN}{datetime.now()}')
        async with session.put(f"https://api.mojang.com/user/profile/agent/minecraft/name/{target_username}", headers=self.auth) as response:
            now = datetime.now()
            logging.info(f"{Fore.WHITE}[{f'{Fore.GREEN}SUCCESS' if response.status == 204 else f'{Fore.RED}FAIL'}{Fore.WHITE}]{Fore.RESET}{' ' + target_username + ' ' + Fore.GREEN + self.email if str(response.status)[0] == str(2) else Fore.RED} | {response.status}{Fore.RESET} @ {Fore.CYAN}{now}{Fore.RESET}")
            await response.read()

    async def snipe_req(self, session, target_username):
        await asyncio.sleep(0)
        # logging.info(f'{Fore.WHITE}[{Fore.GREEN}SUCCESS{Fore.WHITE}] Sent Request @ {Fore.CYAN}{datetime.now()}')
        try:
            async with session.post(f"https://api.mojang.com/user/profile/{self.uuid}/name", headers=self.auth, json={"name": target_username, "password": self.password}) as response:
                now = datetime.now()
                logging.info(f"{Fore.WHITE}[{f'{Fore.GREEN}SUCCESS' if response.status == 204 else f'{Fore.RED}FAIL'}{Fore.WHITE}]{Fore.RESET}{' ' + target_username + ' ' + Fore.GREEN + self.email if str(response.status)[0] == str(2) else Fore.RED} | {response.status}{Fore.RESET} @ {Fore.CYAN}{now}{Fore.RESET}")
                await response.read()
                if response.status == 204:
                    with open("success.txt", "a") as f:
                        f.write(f"{self.email}:{self.password} - {target_username}\n")
                    try:
                        files = {"model": "slim", "url": open("skin.txt", "r").read().strip()}
                        auth = self.auth
                        auth["Content-Type"] = "application/x-www-form-urlencoded"
                        async with session.post(f"https://api.mojang.com/user/profile/{self.uuid}/skin", headers=self.auth, data=files) as r:
                            if r.status == 204 or r.status == 200:
                                logging.info(f"{Fore.WHITE}[{Fore.GREEN}success{Fore.WHITE}]{Fore.RESET} changed skin of {self.email}")
                            else:
                                logging.info(f"{Fore.WHITE}[{Fore.RED}FAIL{Fore.WHITE}]{Fore.RESET} Failed to change skin {self.email} | {r.status}")
                                logging.info(await r.json())
                    except FileNotFoundError:
                        pass
                    except:
                        logging.info(f"{Fore.WHITE}[{Fore.RED}i have no idea{Fore.WHITE}]{Fore.RESET} i dont know what happend but it failed")
                    try:
                        webhooks = []
                        with open("webhook.txt", "r") as f:
                            unconverted_webhooks = f.readlines()
                        for hook in unconverted_webhooks:
                            webhooks.append(hook.strip())
                        for hook in webhooks:
                            async with session.post(hook, json={"embeds": [{"title": "New Snipe 🎉", "description": f"Sniped `{target_username}`!", "color": 65395}]}) as r:
                                if r.status == 200 or r.status == 204:
                                    logging.info(f"{Fore.WHITE}[{Fore.GREEN}success{Fore.WHITE}]{Fore.RESET} sent webhook of snipe!")
                                else:
                                    logging.info(r.status)
                                    logging.info(await r.json())
                    except FileNotFoundError:
                        pass
        except AttributeError:
            print(f'{Fore.WHITE}[{Fore.RED}error{Fore.WHITE}]{Fore.RESET} your account is unpaid and cannot snipe names. | {Fore.YELLOW}or ratelimit{Fore.RESET}')


def gather_info():
    block_snipe = menu(options=["Snipe name", "Block Name"])
    target_username = custom_input(f"What name you would you like to {['snipe', 'block'][block_snipe]}: ")
    return block_snipe, target_username


def load_accounts_file():
    accounts = []
    if not path.exists("accounts.txt"):
        print(f"{Fore.WHITE}[{Fore.RED}ERROR{Fore.WHITE}]{Fore.RESET} accounts.txt not found | creating one")
        open('accounts.txt', 'w+')
        input("Press any key to reload accounts. ")
        load_accounts_file()
    else:
        accounts = open('accounts.txt').readlines()
        if len(accounts) == 0:
            print(f"Accounts not found in accounts.txt file please add accounts with format (email:pass) or (email:pass:q1:q2:q3)")
            input("Press any key to reload accounts.")
            load_accounts_file()

    return accounts


def load_accounts():
    accounts = []
    for acc in load_accounts_file():
        acc = acc.rstrip().split(":")
        if acc == ['']:
            continue
        try:
            accounts.append(Account(acc[0], acc[1], [acc[2], acc[3], acc[4]]))
        except IndexError:
            accounts.append(Account(acc[0], acc[1]))
    return accounts


class session:
    block_snipe = ["Snipe", "block"]

    def __init__(self, target_username, accounts, block_snipe):
        self.target_username = target_username
        self.accounts = accounts
        self.block_snipe = block_snipe
        loop = asyncio.get_event_loop()
        self.drop_time = loop.run_until_complete(time_snipe(self.target_username, self.block_snipe))
        self.setup_time = self.drop_time - timedelta(seconds=50)
        self.setup = False
        self.ran = False
        settings_json = json.loads(open("settings.json", "r").read())
        if settings_json["custom_delay"]:
            self.drop_time = self.drop_time - timedelta(milliseconds=int(custom_input("Custom delay in ms: ")))
        else:
            if self.block_snipe == 0:
                self.drop_time = self.drop_time - timedelta(milliseconds=900)
            elif self.block_snipe == 1:
                self.drop_time = self.drop_time - timedelta(milliseconds=170)

    def run(self):
        loop = asyncio.get_event_loop()
        # input("press enter to run auth")
        # loop.run_until_complete(self.run_auth())
        # input("press enter to run requests")
        # loop.run_until_complete(self.send_requests())
        while True:
            now = datetime.utcnow()
            if now >= self.drop_time and not self.ran:
                loop.run_until_complete(self.send_requests())
                custom_input("press enter to quit: ")
                quit()
                self.ran = True
            elif now >= self.setup_time and not self.setup:
                loop.run_until_complete(self.run_auth())
                custom_info("setup complete")
                self.setup = True
            time.sleep(.00001)

    async def send_requests(self):
        async with aiohttp.ClientSession() as session:
            if self.block_snipe == 0:
                self.num_reqs = 20
                self.coros = [
                    acc.snipe_req(session, self.target_username) for acc in self.accounts for _ in range(self.num_reqs)
                ]
            elif self.block_snipe == 1:
                self.num_reqs = 3
                self.coros = [
                    acc.block_req(session, self.target_username) for acc in self.accounts for _ in range(self.num_reqs)
                ]
            start = time.time()
            await asyncio.wait(self.coros)
            end = time.time()
            elapsed_time = end - start
            rq_sec = self.num_reqs * len(accounts) / elapsed_time
            times.append(rq_sec)
            logging.info(f"{Fore.GREEN}{str(sum(times))[0:13]}{Fore.CYAN} rqs/sec {Fore.WHITE}|{Fore.CYAN} Took {Fore.WHITE}{str(elapsed_time)[0:8]}{Fore.CYAN} seconds{Fore.RESET} | {self.num_reqs * len(accounts)} requests")

    async def run_auth(self):
        async with aiohttp.ClientSession() as session:
            coros = [
                acc.authenticate(session) for acc in self.accounts
            ]
            await asyncio.wait(coros)


print_title()
accounts = load_accounts()
block_snipe, target_username = gather_info()
session = session(target_username, accounts, block_snipe)
session.run()
```

**Comment by webknjaz** [comment]
> OSError: [Errno 65] No route to host

Networking on your server computer is misconfigured. I'm pretty sure even `ping namemc.com` will show this. This sort of problem requires you to figure out how to make the host available to you according to your own network setup. This is in no way related to aiohttp.

**Comment by ImaDirt2** [comment]
Bruh ping namemc.com works and I can run it on Dif devices on this network
