### ISSUE TITLE
`GET` within a task raises SSL Error with TestClient/Server within docker

### ISSUE THREAD

**Issue by EricHorvat** [aio-libs/aiohttp#4945]
🐞 **Describe the bug**

Running a GET request to a TestServer with TestClient with SSL activated within docker fails. Without the task, works normally and the tests pass.

💡 **To Reproduce**

1. Wrap a session's get of `/` within a task, with a SSL configuration
2. Write a test for that code, which sets the same SSL self-signed certificates (for SSL testing), these certs should be used in the code too. 
3. You should use TestServer/TestClient, and pass the TestClient instance's session to the tested code. Be aware to add a handler for `/` in the TestServer
4. Run the tests within docker.

💡 **Expected behavior**

The test should pass, both in local enviroment as in docker enviroment.

📋 **Logs/tracebacks**

```python-traceback (paste your traceback in the next line)
ERROR    asyncio:base_events.py:1619 Exception in callback BaseSelectorEventLoop._sock_connect_done(11)(<Future finis... descriptor')>)
handle: <Handle BaseSelectorEventLoop._sock_connect_done(11)(<Future finis... descriptor')>)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 493, in _sock_connect_done
    self.remove_writer(fd)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 343, in remove_writer
    self._ensure_fd_no_transport(fd)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 249, in _ensure_fd_no_transport
    f'File descriptor {fd!r} is used by transport '
RuntimeError: File descriptor 11 is used by transport <_SelectorSocketTransport fd=11 read=idle write=<polling, bufsize=0>>
ERROR    asyncio:base_events.py:1619 Exception in callback _SelectorTransport._add_reader(11, <bound method..., bufsize=0>>>)
handle: <Handle _SelectorTransport._add_reader(11, <bound method..., bufsize=0>>>)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 718, in _add_reader
    self._loop._add_reader(fd, callback, *args)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 263, in _add_reader
    (handle, writer))
  File "/usr/local/lib/python3.7/selectors.py", line 389, in modify
    self._selector.modify(key.fd, selector_events)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x7f5a22913dd0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/sslproto.py", line 323, in __del__
    self.close()
  File "/usr/local/lib/python3.7/asyncio/sslproto.py", line 317, in close
    self._ssl_protocol._start_shutdown()
  File "/usr/local/lib/python3.7/asyncio/sslproto.py", line 588, in _start_shutdown
    self._abort()
  File "/usr/local/lib/python3.7/asyncio/sslproto.py", line 725, in _abort
    self._transport.abort()
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 643, in abort
    self._force_close(None)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 695, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 691, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

📋 **Your version of the Python**

```console
$ python --version
Python 3.7.9
```
```console
python --version
Python 3.8.5
```
```console
python --version
Python 3.9.0rc1
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

The same package version for each python version
```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.6.2
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: /builds/faradaysec/cloud/faraday_agent_dispatcher/faraday_venv/lib/python3.7/site-packages
Requires: yarl, multidict, chardet, attrs, async-timeout
Required-by: faraday-agent-dispatcher
$ python -m pip show multidict
Name: multidict
Version: 4.7.6
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /builds/faradaysec/cloud/faraday_agent_dispatcher/faraday_venv/lib/python3.7/site-packages
Requires: 
Required-by: yarl, aiohttp
$ python -m pip show yarl
Name: yarl
Version: 1.5.1
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /builds/faradaysec/cloud/faraday_agent_dispatcher/faraday_venv/lib/python3.7/site-packages
Requires: idna, typing-extensions, multidict
Required-by: aiohttp
```

📋 **Additional context**

1. Clone https://github.com/infobyte/faraday_agent_dispatcher.git
2. Run `git checkout feature_improve_signal_and_disconnection`
3. Run `pip install .[test]`
4. Run `pytest tests/unitests/` within a GitlabCI instance

You can see over [our public repo](https://github.com/infobyte/faraday_agent_dispatcher/tree/feature_improve_signal_and_disconnection/), if you want, [our code](
https://github.com/infobyte/faraday_agent_dispatcher/blob/feature_improve_signal_and_disconnection/faraday_agent_dispatcher/dispatcher.py#L529), this is the code working,; if you uncomment the task wrapping code, and comment the coroutine awaiting, the tests fails.

Sorry for not being available to share our private repo CI runs. However, I can bring the raw of the CI runs if you wants.

Thanks for the help in advance and for your work on the lib!

**Comment by asvetlov** [comment]
I guess you have different OpenSSL versions locally and inside a Docker container.
IIRC both Debian/Ubuntu and Fedora dropped TLS 1.0/1.1 from their distros.
See, for example, this discussion: https://bugs.python.org/issue41561

I doubt if aiohttp can do anything on the library side.
