### ISSUE TITLE
Server could not parse post nested dict data

### ISSUE THREAD

**Issue by tiantian1645** [aio-libs/aiohttp#5000]
🐞 **Describe the bug**

Client post a nested data like 
```python
data = dict(
    torrent=[
        dict(domain="AA", t_id=1222, title="title 1"),
        dict(domain="AB", t_id=23333, title="title 2"),
        dict(domain="AC", t_id=35555, title="title 3"),
        dict(domain="AD", t_id=488888),
    ]
)
```
But in server site will get data like this
```python
<MultiDictProxy('torrent': "{'domain': 'AA', 't_id': 1222, 'title': 'title 1'}", 'torrent': "{'domain': 'AB', 't_id': 23333, 'title': 'title 2'}", 'torrent': "{'domain': 'AC', 't_id': 35555, 'title': 'title 3'}", 'torrent': "{'domain': 'AD', 't_id': 488888}")>

# I must use this to parse data
data = await request.post()
for torrent_data in data.getall("torrent"):
    torrent_data = json.loads(torrent_data.replace("'", '"'))
```

💡 **To Reproduce**
```python

# Server
from aiohttp import web
import json

routes = web.RouteTableDef()


@routes.post("/new_hash")
async def new_hash(request):
    data = await request.post()
    for torrent_data in data.getall("torrent"):
        torrent_data = json.loads(torrent_data)
    return web.json_response(dict(result="success))

app = web.Application()
app.add_routes(routes)
web.run_app(app, port=5000)

# client
import httpx

data = dict(
    torrent=[
        dict(domain="AA", t_id=1222, title="title 1"),
        dict(domain="AB", t_id=23333, title="title 2"),
        dict(domain="AC", t_id=35555, title="title 3"),
        dict(domain="AD", t_id=488888),
    ]
)

resp = httpx.post("http://127.0.0.1:5000/new_hash", data=data)
print(resp.text)


```

💡 **Expected behavior**

Success Work

📋 **Logs/tracebacks**

```python-traceback (paste your traceback in the next line)
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\aiohttp\web_protocol.py", line 418, in start
    resp = await task
  File "C:\Program Files\Python37\lib\site-packages\aiohttp\web_app.py", line 458, in _handle
    resp = await handler(request)
  File "info_hash_server.py", line 44, in new_hash
    torrent_data = json.loads(torrent_data)
  File "C:\Program Files\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python37\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

```

📋 **Your version of the Python**

```console
Python 3.7.5
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.6.2
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: c:\program files\python37\lib\site-packages
Requires: attrs, multidict, yarl, chardet, async-timeout
Required-by:
```
```console
$ python -m pip show multidict
Name: multidict
Version: 4.7.6
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: c:\program files\python37\lib\site-packages
Requires:
Required-by: yarl, aiohttp
```
```console
$ python -m pip show yarl
Name: yarl
Version: 1.6.0
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: c:\program files\python37\lib\site-packages
Requires: typing-extensions, idna, multidict
Required-by: aiohttp
```

📋 **Additional context**

Windows 7 64

When server get post data , event it could not parse nested data to dict, but '"'  is better than "'".

**Comment by tiantian1645** [comment]
```
data = await request.json()

resp = httpx.post("http://127.0.0.1:5000/new_hash", json=data)
```
