### ISSUE TITLE
Could not build wheels for aiohttp which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by arudlandbynd** [aio-libs/aiohttp#5087]
🐞 **Describe the bug**
During installation of `aiohttp` I'm receiving the following error: 

```python-traceback
Building wheel for aiohttp (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/ashley.rudland/sources/test_aiohttp/venv/bin/python3 /Users/ashley.rudland/sources/test_aiohttp/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/2s/rk_qxkhx5zq15pw0fqd4h87h0000gw/T/tmptwkzghoz
       cwd: /private/var/folders/2s/rk_qxkhx5zq15pw0fqd4h87h0000gw/T/pip-install-w19g9gir/aiohttp
  ...
  running install_scripts
  [WARNING] This wheel needs a higher macOS version than the version your Python interpreter is compiled against.  To silence this warning, set MACOSX_DEPLOYMENT_TARGET to at least 11_0 or recreate these files with lower MACOSX_DEPLOYMENT_TARGET:
  build/bdist.macosx-10.14.6-x86_64/wheel/aiohttp/_websocket.cpython-38-darwin.so
  build/bdist.macosx-10.14.6-x86_64/wheel/aiohttp/_frozenlist.cpython-38-darwin.so
  build/bdist.macosx-10.14.6-x86_64/wheel/aiohttp/_http_parser.cpython-38-darwin.so
  build/bdist.macosx-10.14.6-x86_64/wheel/aiohttp/_http_writer.cpython-38-darwin.so
  build/bdist.macosx-10.14.6-x86_64/wheel/aiohttp/_helpers.cpython-38-darwin.soTraceback (most recent call last):
    File "/Users/ashley.rudland/sources/test_aiohttp/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/Users/ashley.rudland/sources/test_aiohttp/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/ashley.rudland/sources/test_aiohttp/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/private/var/folders/2s/rk_qxkhx5zq15pw0fqd4h87h0000gw/T/pip-build-env-i8itibap/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 216, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/private/var/folders/2s/rk_qxkhx5zq15pw0fqd4h87h0000gw/T/pip-build-env-i8itibap/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/2s/rk_qxkhx5zq15pw0fqd4h87h0000gw/T/pip-build-env-i8itibap/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 253, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/private/var/folders/2s/rk_qxkhx5zq15pw0fqd4h87h0000gw/T/pip-build-env-i8itibap/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 155, in <module>
      setup(**args)
    File "/private/var/folders/2s/rk_qxkhx5zq15pw0fqd4h87h0000gw/T/pip-build-env-i8itibap/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/2s/rk_qxkhx5zq15pw0fqd4h87h0000gw/T/pip-build-env-i8itibap/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 328, in run
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/private/var/folders/2s/rk_qxkhx5zq15pw0fqd4h87h0000gw/T/pip-build-env-i8itibap/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 278, in get_tag
      assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
  AssertionError: would build wheel with unsupported tag ('cp38', 'cp38', 'macosx_11_0_x86_64')
  ----------------------------------------
  ERROR: Failed building wheel for aiohttp
```

💡 **To Reproduce**
MacOS: Catalina - 10.15.7 (19H2)
Python: 3.8.2
Pip: 20.2.4

```
python3 -m venv venv/
source venv/bin/activate
pip install aiohttp
```

**Comment by webknjaz** [comment]
Mind answering the questions about aiohttp version from the issue template?

**Comment by webknjaz** [comment]
Also, I suppose you haven't followed this recommendation, have you?
>  [WARNING] This wheel needs a higher macOS version than the version your Python interpreter is compiled against.  To silence this warning, set MACOSX_DEPLOYMENT_TARGET to at least 11_0 or recreate these files with lower MACOSX_DEPLOYMENT_TARGET:

I'm almost sure that you haven't installed Python from python.org, right?

**Comment by arudlandbynd** [comment]
No specific version just `pip install aiohttp`. Setting `MACOSX_DEPLOYMENT_TARGET` to `11_0` fixes the issue. Thanks so much.
