### ISSUE TITLE
Aiohttp does not decode percentage url.

### ISSUE THREAD

**Issue by santasdi** [aio-libs/aiohttp#5103]
🐞 **Describe the bug**
Aiohttp under hood use YARL for URL processing. 12.10.2020 was released latest version of YARL 1.6.2. With this version of yarl aiohttp ignore encoded params in url that was passed to request.query

💡 **To Reproduce**

```
from aiohttp import web


async def handler(request):
    type_as_str = request.query['type__in']
    type_as_list = [int(v) for v in type_as_str.split(',')]
    return web.json_response({'result': type_as_list})


app = web.Application()
app.add_routes([
    web.get(r'/material', handler)
])


if __name__ == '__main__':
    web.run_app(app, host='127.0.0.1')
```

💡 **Expected behavior**

```
Request:
curl --location --request GET 'http://127.0.0.1:8080/material?type__in=1%2C2%2C3'

Response:
{"result": [1, 2, 3]}
```
📋 **Logs/tracebacks**

```
Error handling request
Traceback (most recent call last):
  File "/home/santasdi/.pyenv/versions/project/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/santasdi/.pyenv/versions/project/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/home/santasdi/bugs/url_error.py", line 6, in handler
    type_as_list = [int(v) for v in type_as_str.split(',')]
  File "/home/santasdi/bugs/url_error.py", line 6, in <listcomp>
    type_as_list = [int(v) for v in type_as_str.split(',')]
ValueError: invalid literal for int() with base 10: '1%2C2%2C3'

```

📋 **Your version of the Python**
python 3.6.4

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
Name: aiohttp
Version: 3.6.2
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: /home/santasdi/.pyenv/versions/3.6.4/envs/project/lib/python3.6/site-packages
Requires: yarl, chardet, async-timeout, attrs, typing-extensions, multidict, idna-ssl
...
```
```console
Name: multidict
Version: 4.7.6
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/santasdi/.pyenv/versions/3.6.4/envs/project/lib/python3.6/site-packages

...
```
```console
Name: yarl
Version: 1.6.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/santasdi/.pyenv/versions/3.6.4/envs/project/lib/python3.6/site-packages
Requires: multidict, idna, typing-extensions

...
```

**Comment by asvetlov** [comment]
Please upgrade aiohttp to 3.6.3 which pins yarl to 1.5.x line
Or wait for aiohttp 3.7 release which fixes compatibility with yarl 1.6.x
