### ISSUE TITLE
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 0.0.0.0:7000 ssl:default [Name or service not known]

### ISSUE THREAD

**Issue by lpkeates** [aio-libs/aiohttp#5155]
```python-traceback
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1017, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1002, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 916, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 485, in sock_connect
    return await fut
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 517, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('0.0.0.0', 7000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/wavelink/websocket.py", line 76, in _connect
    self._websocket = await self._node.session.ws_connect(uri, headers=self.headers, heartbeat=self._node.heartbeat)
  File "/home/container/.local/lib/python3.8/site-packages/aiohttp/client.py", line 721, in _ws_connect
    resp = await self.request(method, url,
  File "/home/container/.local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/home/container/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/container/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/home/container/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/home/container/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/container/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 0.0.0.0:7000 ssl:default [Connect call failed ('0.0.0.0', 7000)]
```

My Code (wavelink)
```python
        nodes = {'MAIN': {'host': '0.0.0.0',
                          'port': 7000,
                          'rest_uri': 'http://0.0.0.0:7000',
                          'password': 'testing',
                          'identifier': 'REST',
                          'region': 'us_central'
                          }}
```
My Code (application.yml)
```yaml
server: # REST and WS server
  port: 7000
  address: 0.0.0.0
lavalink:
  server:
    password: "testing"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/

  level:
   root: INFO
    lavalink: INFO
```

### My environment
Python: `3.8.6`
Aiohttp: `3.6.2`
OS: N/A

**Comment by lpkeates** [comment]
This is with wavelink (a discord.py module) for your information.

**Comment by asvetlov** [comment]
Try aiohttp 3.6.3 please

**Comment by lpkeates** [comment]
> Try aiohttp 3.6.3 please

Still happening, regardless
```console
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 0.0.0.0:7000 ssl:default [Connect call failed ('0.0.0.0', 7000)]
```
^ Error

```python-traceback
WEBSOCKET | Connection Failure:: Cannot connect to host 0.0.0.0:7000 ssl:default [Connect call failed ('0.0.0.0', 7000)]
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1017, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1002, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 916, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 485, in sock_connect
    return await fut
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 517, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('0.0.0.0', 7000)
```
^ Traceback

**Comment by asvetlov** [comment]
Sorry, I still have no idea how to reproduce your problem.
I have no idea how to setup discord.py and wavelink.
I'm curious: do you really want to connect to `0.0.0.0:7000` instead of, e.g., `127.0.0.1:7000`?

**Comment by lpkeates** [comment]
> Sorry, I still have no idea how to reproduce your problem.
> I have no idea how to setup discord.py and wavelink.
> I'm curious: do you really want to connect to `0.0.0.0:7000` instead of, e.g., `127.0.0.1:7000`?

If you want to setup discord.py, just use pip install discord.py and for wavelink, same thing but do wavelink instead of discord.py

**Comment by asvetlov** [comment]
Looks like we have a misunderstanding.
I need a simple reproducible code example that demonstrates the error; otherwise, I cannot debug and fix the problem.
Ideally, the script is short and self-contained; it uses aiohttp only without third-party dependencies.

If the reproducer will not be provided I should close the issue.

**Comment by rushuang** [comment]
Same question...

**Comment by lpkeates** [comment]
This was 2 years ago at least, so I guess the issue has to be closed
