### ISSUE TITLE
ConnectionResetError Supression Regression in 3.7.x

### ISSUE THREAD

**Issue by shauneccles** [aio-libs/aiohttp#5212]
🐞 **Describe the bug**
Appears to be a regression in 3.7 branch that no longer supresses the connectionreset errors fixed by this commit
https://github.com/aio-libs/aiohttp/pull/3699

💡 **To Reproduce**

Using 3.7.x and python3.8 initiate an aiohttp listen server.
Present dynamic content.
Exit browser.

💡 **Expected behaviour**

ConnectionResetError: Cannot write to closing transport error is suppressed.

📋 **Logs/tracebacks**

```console
[2020-11-09 10:49:12] ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "C:\Users\shaun\ledfx-3.8\lib\site-packages\aiohttp\web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "C:\Users\shaun\ledfx-3.8\lib\site-packages\aiohttp\web_app.py", line 499, in _handle
    resp = await handler(request)
  File "c:\users\shaun\ledfx-3.8\ledfx\ledfx\api\__init__.py", line 26, in handler
    return await method(**{arg_name: available_args[arg_name] for arg_name in wanted_args})
  File "c:\users\shaun\ledfx-3.8\ledfx\ledfx\api\websocket.py", line 34, in get
    return await WebsocketConnection(self._ledfx).handle(request)
  File "c:\users\shaun\ledfx-3.8\ledfx\ledfx\api\websocket.py", line 157, in handle
    await self._sender_task
  File "c:\users\shaun\ledfx-3.8\ledfx\ledfx\api\websocket.py", line 98, in _sender
    await self._socket.send_json(message, dumps=json.dumps)
  File "C:\Users\shaun\ledfx-3.8\lib\site-packages\aiohttp\web_ws.py", line 316, in send_json
    await self.send_str(dumps(data), compress=compress)
  File "C:\Users\shaun\ledfx-3.8\lib\site-packages\aiohttp\web_ws.py", line 300, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "C:\Users\shaun\ledfx-3.8\lib\site-packages\aiohttp\http_websocket.py", line 687, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "C:\Users\shaun\ledfx-3.8\lib\site-packages\aiohttp\http_websocket.py", line 598, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
Stopping LedFx.
(ledfx-3.8) PS C:\Users\shaun\ledfx-3.8\LedFx> python
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import aiohttp
>>> print(aiohttp.__version__)
3.7.2
```

📋 **Your version of the Python**

```console
$ python --version
Python 3.8.0
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
Bug in
Version: 3.7.2
Working in
Version: 3.6.3
```
```console
$ python -m pip show multidict
Bug in
Version: 5.0.0
Working in
Version: 4.7.6
```
```console
$ python -m pip show yarl
Bug in
Version: 1.6.0
Working in
Version: 1.5.1
```

📋 **Additional context**

Windows 10, aiohttp version 3.7 release branch (from 3.7.0 to latest)

**Comment by asvetlov** [comment]
I think the behavior is *technically* still ok (cannot write to the closed socket, terminate the web-handler).
I also agree that traceback in logs can scare.
Just logging the fact that a peer has dropped connection should be enough.

**Comment by shauneccles** [comment]
Investigating a bit further, this commit https://github.com/aio-libs/aiohttp/commit/21b062199ff8da1a8d48b262f3d75fb616cc275f might be the culprit.

At line 470 it captures errors and funnels them to a debug log to ignore client disconnections.
```console
except (asyncio.CancelledError, ConnectionError):

self.log_debug('Ignored premature client disconnection')
```


Would
```console
except (asyncio.CancelledError, ConnectionError, ConnectionResetError):

self.log_debug('Ignored premature client disconnection')
```
Fix this?

**Comment by Dreamsorcerer** [comment]
Is there an actual reproducer? It's not too clear what's wrong here.
