### ISSUE TITLE
ClientSession timeout issue

### ISSUE THREAD

**Issue by levsh** [aio-libs/aiohttp#5226]
Hi!
Is this a bug or i am doing something wrong?
```python
import asyncio
import aiohttp

print(aiohttp.__version__)

async def main():
    async with aiohttp.ClientSession(timeout=1) as s:
        await s.get("http://example.com")

if __name__ == '__main__':
    asyncio.run(main())
```

```
3.7.2
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    asyncio.run(main())
  File "/Users/levsh/.pyenv/versions/3.8.6/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/levsh/.pyenv/versions/3.8.6/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test.py", line 11, in main
    await s.get("http://example.com")
  File "/Users/levsh/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiohttp/client.py", line 435, in _request
    tm = TimeoutHandle(self._loop, real_timeout.total)
AttributeError: 'int' object has no attribute 'total'
```

python version - 3.8.6
aiohttp version - 3.7.2

I think the problem is here  https://github.com/aio-libs/aiohttp/blob/v3.7.2/aiohttp/client.py#L274 and here https://github.com/aio-libs/aiohttp/blob/v3.7.2/aiohttp/client.py#L427

Thank you!

**Comment by webknjaz** [comment]
Sounds like a regression indeed. Have you checked if any of the older versions behave better?

**Comment by levsh** [comment]
3.3.0 - same behaviour
```python
3.3.0
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    asyncio.run(main())
  File "/Users/levsh/.pyenv/versions/3.8.6/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/levsh/.pyenv/versions/3.8.6/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test.py", line 11, in main
    await s.get("http://example.com")
  File "/Users/levsh/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiohttp/client.py", line 295, in _request
    tm = TimeoutHandle(self._loop, timeout.total)
AttributeError: 'int' object has no attribute 'total'
```

**Comment by derlih** [comment]
@webknjaz Looks like the timeout parameter never had an int type.
In this PR #2972 it was introduced.

According to 
https://github.com/aio-libs/aiohttp/blob/021668ad4e2ac4eba1693bd5c5b952911426d908/aiohttp/client.py#L380-L386
https://github.com/aio-libs/aiohttp/blob/021668ad4e2ac4eba1693bd5c5b952911426d908/aiohttp/client.py#L874-L880

it should be possible to write
```python
async def main():
    async with aiohttp.ClientSession() as s:
        await s.get("http://example.com", timeout=1)
```
@levsh can you check it?

**Comment by levsh** [comment]
@derlih yes it works.

According to documentations ClientSession `request` method supports int/float `timeout` for sake of backward compatibility, but ClientSession constructor doesn't. Only `ClientTimeout`instance.
My carelessness, thanks all

**Comment by asvetlov** [comment]
Could you please send a link on docs where the timeout is `float`?
I want to fix this.

**Comment by derlih** [comment]
@asvetlov 
https://github.com/aio-libs/aiohttp/blob/021668ad4e2ac4eba1693bd5c5b952911426d908/docs/client_reference.rst#L441-L450
