### ISSUE TITLE
HTTP/1.0 Keep-Alive behaviour

### ISSUE THREAD

**Issue by jashandeep-sohi** [aio-libs/aiohttp#526]
While running some benchmarks with `ab` Apache HTTP server benchmarking tool, I've encountered a bug where the `-k` (keep-alive) option causes errors.

I'm not sure if this is a bug in `ab` or `aiohttp`'s implementation of `keep-alive` when the HTTP version is `HTTP/1.0`.

**Comment by asvetlov** [comment]
Would you elaborate?
What kind of errors have you observed?

**Comment by jashandeep-sohi** [comment]
When SSL is enabled, `ab` just seems to hang after making the first request. There are no exceptions raised on the `aiohttp` end.

```
$ python app.py localhost 8888 cert.pem static
DEBUG:asyncio:Using selector: EpollSelector
Serving on: ('::1', 8888, 0, 0)
Serving on: ('127.0.0.1', 8888)
```

```
$ ab -v 4 -k -n 2 https://localhost:8888/static/file.bin
This is ApacheBench, Version 2.3 <$Revision: 1663405 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)...INFO: GET header == 
---
GET /static/file.bin HTTP/1.0
Connection: Keep-Alive
Host: localhost:8888
User-Agent: ApacheBench/2.3
Accept: */*


---
SSL/TLS Handshake [Start] before/connect initialization
SSL/TLS State [connect] before/connect initialization
write to 0x1f9cf80 [0x1f9d3f0] (517 bytes => 517 (0x205))
0000 - 16 03 01 02 00 01 00 01-fc 03 03 dc 88 87 82 82   ................
0010 - a6 93 81 7f 6c c8 53 96-ec 7d 79 77 9a c5 da 91   ....l.S..}yw....
0020 - d8 88 42 7b 59 e7 d3 40-ef 32 87 00 00 b6 c0 30   ..B{Y..@.2.....0
0030 - c0 2c c0 28 c0 24 c0 14-c0 0a 00 a5 00 a3 00 a1   .,.(.$..........
0040 - 00 9f 00 6b 00 6a 00 69-00 68 00 39 00 38 00 37   ...k.j.i.h.9.8.7
0050 - 00 36 00 88 00 87 00 86-00 85 c0 32 c0 2e c0 2a   .6.........2...*
0060 - c0 26 c0 0f c0 05 00 9d-00 3d 00 35 00 84 c0 2f   .&.......=.5.../
0070 - c0 2b c0 27 c0 23 c0 13-c0 09 00 a4 00 a2 00 a0   .+.'.#..........
0080 - 00 9e 00 67 00 40 00 3f-00 3e 00 33 00 32 00 31   ...g.@.?.>.3.2.1
0090 - 00 30 00 9a 00 99 00 98-00 97 00 45 00 44 00 43   .0.........E.D.C
00a0 - 00 42 c0 31 c0 2d c0 29-c0 25 c0 0e c0 04 00 9c   .B.1.-.).%......
00b0 - 00 3c 00 2f 00 96 00 41-00 07 c0 11 c0 07 c0 0c   .<./...A........
00c0 - c0 02 00 05 00 04 c0 12-c0 08 00 16 00 13 00 10   ................
00d0 - 00 0d c0 0d c0 03 00 0a-00 15 00 12 00 0f 00 0c   ................
00e0 - 00 09 00 ff 02 01 00 01-1c 00 0b 00 04 03 00 01   ................
00f0 - 02 00 0a 00 1c 00 1a 00-17 00 19 00 1c 00 1b 00   ................
0100 - 18 00 1a 00 16 00 0e 00-0d 00 0b 00 0c 00 09 00   ................
0110 - 0a 00 23 00 00 00 0d 00-20 00 1e 06 01 06 02 06   ..#..... .......
0120 - 03 05 01 05 02 05 03 04-01 04 02 04 03 03 01 03   ................
0130 - 02 03 03 02 01 02 02 02-03 00 0f 00 01 01 00 15   ................
0140 - 00 c3                                             ..
0205 - <SPACES/NULS>
SSL/TLS State [connect] SSLv2/v3 write client hello A
read from 0x1f9cf80 [0x1fa2950] (7 bytes => -1 (0xFFFFFFFFFFFFFFFF))
read from 0x1f9cf80 [0x1fa2950] (7 bytes => 7 (0x7))
0000 - 16 03 03 00 42 02                                 ....B.
0007 - <SPACES/NULS>
read from 0x1f9cf80 [0x1fa295a] (64 bytes => 64 (0x40))
0000 - 00 3e 03 03 f3 a2 4f 83-88 a9 79 72 9d 96 c3 e3   .>....O...yr....
0010 - 9c c8 13 03 d7 ad 4c 98-30 02 e1 38 f0 3e 82 7d   ......L.0..8.>.}
0020 - 1e 1a c7 dd 00 c0 30 00-00 16 ff 01 00 01 00 00   ......0.........
0030 - 0b 00 04 03 00 01 02 00-23 00 00 00 0f 00 01 01   ........#.......
SSL/TLS State [connect] SSLv3 read server hello A
read from 0x1f9cf80 [0x1fa2953] (5 bytes => 5 (0x5))
0000 - 16 03 03 03 8d                                    .....
read from 0x1f9cf80 [0x1fa2958] (909 bytes => 909 (0x38D))
0000 - 0b 00 03 89 00 03 86 00-03 83 30 82 03 7f 30 82   ..........0...0.
0010 - 02 67 a0 03 02 01 02 02-09 00 80 e7 24 b3 db d2   .g..........$...
0020 - 7c 82 30 0d 06 09 2a 86-48 86 f7 0d 01 01 0b 05   |.0...*.H.......
0030 - 00 30 56 31 0b 30 09 06-03 55 04 06 13 02 44 45   .0V1.0...U....DE
0040 - 31 0d 30 0b 06 03 55 04-08 0c 04 4e 6f 6e 65 31   1.0...U....None1
0050 - 0f 30 0d 06 03 55 04 07-0c 06 42 65 72 6c 69 6e   .0...U....Berlin
0060 - 31 0d 30 0b 06 03 55 04-0a 0c 04 77 68 61 74 31   1.0...U....what1
0070 - 18 30 16 06 03 55 04 03-0c 0f 77 77 77 2e 65 78   .0...U....www.ex
0080 - 61 6d 70 6c 65 2e 63 6f-6d 30 1e 17 0d 31 35 30   ample.com0...150
0090 - 39 32 33 30 35 30 34 35-34 5a 17 0d 31 36 30 39   923050454Z..1609
00a0 - 32 32 30 35 30 34 35 34-5a 30 56 31 0b 30 09 06   22050454Z0V1.0..
00b0 - 03 55 04 06 13 02 44 45-31 0d 30 0b 06 03 55 04   .U....DE1.0...U.
00c0 - 08 0c 04 4e 6f 6e 65 31-0f 30 0d 06 03 55 04 07   ...None1.0...U..
00d0 - 0c 06 42 65 72 6c 69 6e-31 0d 30 0b 06 03 55 04   ..Berlin1.0...U.
00e0 - 0a 0c 04 77 68 61 74 31-18 30 16 06 03 55 04 03   ...what1.0...U..
00f0 - 0c 0f 77 77 77 2e 65 78-61 6d 70 6c 65 2e 63 6f   ..www.example.co
0100 - 6d 30 82 01 22 30 0d 06-09 2a 86 48 86 f7 0d 01   m0.."0...*.H....
0110 - 01 01 05 00 03 82 01 0f-00 30 82 01 0a 02 82 01   .........0......
0120 - 01 00 9e 44 80 47 52 a3-2a 30 09 77 bf ec f8 11   ...D.GR.*0.w....
0130 - d5 b7 0b 89 ca 62 a0 f5-be a6 b6 f1 99 82 a8 b4   .....b..........
0140 - c2 69 7a 1f e6 a4 cc 30-5e ef 80 55 3e ca f1 2b   .iz....0^..U>..+
0150 - 31 9d d3 af b7 fa d2 20-61 21 82 d0 a8 09 52 8b   1...... a!....R.
0160 - b3 1f 11 03 43 76 51 22-7a 4d a7 d2 9f 7d 08 19   ....CvQ"zM...}..
0170 - 43 26 11 19 59 eb f2 9b-2f cd 59 b2 9e 79 01 2a   C&..Y.../.Y..y.*
0180 - 0e e3 9b 67 18 54 7b 26-6c 20 94 84 88 6f 81 64   ...g.T{&l ...o.d
0190 - 5f 77 c7 84 8b 02 9e 9e-96 4a 91 b0 46 1c db c8   _w.......J..F...
01a0 - 0a b7 68 db f2 ca 3b 69-9c 98 8d 8b b2 d8 43 d3   ..h...;i......C.
01b0 - 52 26 f1 24 3f c5 da 19-a5 d8 b8 e3 cf 72 52 c1   R&.$?........rR.
01c0 - 32 a3 0a ff 77 00 98 2a-72 e2 97 bf e4 90 ff 13   2...w..*r.......
01d0 - a8 cc 12 96 e8 65 08 fb-05 a6 53 a3 54 82 85 da   .....e....S.T...
01e0 - 16 2c 29 11 93 b3 3e 67-20 b5 e7 36 eb e3 d9 0a   .,)...>g ..6....
01f0 - 21 f7 21 ba 00 8a 91 22-d7 77 08 5e 29 c4 7a 6d   !.!....".w.^).zm
0200 - 78 60 1f 7f 77 0b 2c d2-6b 67 45 33 be 35 d6 df   x`..w.,.kgE3.5..
0210 - f7 36 8b a0 ac f6 6e 07-4c 85 04 31 f8 c6 c5 74   .6....n.L..1...t
0220 - 38 39 02 03 01 00 01 a3-50 30 4e 30 1d 06 03 55   89......P0N0...U
0230 - 1d 0e 04 16 04 14 56 bc-bf d8 c3 b8 fa bc d0 3d   ......V........=
0240 - 31 8e 10 04 c7 1b 0b 67-3b 4d 30 1f 06 03 55 1d   1......g;M0...U.
0250 - 23 04 18 30 16 80 14 56-bc bf d8 c3 b8 fa bc d0   #..0...V........
0260 - 3d 31 8e 10 04 c7 1b 0b-67 3b 4d 30 0c 06 03 55   =1......g;M0...U
0270 - 1d 13 04 05 30 03 01 01-ff 30 0d 06 09 2a 86 48   ....0....0...*.H
0280 - 86 f7 0d 01 01 0b 05 00-03 82 01 01 00 4e dd 37   .............N.7
0290 - c9 9d 8f e5 92 6b 22 56-4e b6 84 f1 5f ad c7 25   .....k"VN..._..%
02a0 - 10 24 cb 12 5b 25 4e 19-8b b8 2d 15 10 99 df 70   .$..[%N...-....p
02b0 - 02 1a cf c9 9f c5 dd 03-2d 53 90 e7 a2 f0 b1 0e   ........-S......
02c0 - bc f3 d0 db 9c ee 87 2d-0a 17 82 91 3e 22 4f cf   .......-....>"O.
02d0 - d4 38 e9 a2 8e 97 cc b2-13 ff 7f dc 87 85 e8 98   .8..............
02e0 - 67 94 42 46 39 fd 4c 50-7e 88 d1 b7 32 3e 5f b6   g.BF9.LP~...2>_.
02f0 - 4d 9d cb d3 0f 3f cb 9b-ef 53 b6 b3 d4 1b f6 7a   M....?...S.....z
0300 - bb 69 4c 2c 0c 61 89 ec-26 d4 95 34 c1 11 06 89   .iL,.a..&..4....
0310 - 16 35 ad 69 5d e6 b2 8f-0b 84 a9 11 cb 69 12 ee   .5.i]........i..
0320 - 7d be 95 dc ca 10 12 53-35 45 ca d4 c6 36 14 93   }......S5E...6..
0330 - 1c a3 da 0c f9 33 fc 78-26 8e 1c 91 5c 7d bf 99   .....3.x&...\}..
0340 - 3f 05 10 28 7a 59 83 d2-20 b9 14 a3 e3 54 57 cf   ?..(zY.. ....TW.
0350 - ef fb f2 ee 97 dd 79 28-d9 ae b0 9a 2d ea 15 f2   ......y(....-...
0360 - a0 77 40 74 b4 6b b9 be-4a 10 48 ac 72 97 4d 34   .w@t.k..J.H.r.M4
0370 - 14 d5 3d b6 66 dd 0a 89-c1 4d 00 66 6b 93 c2 25   ..=.f....M.fk..%
0380 - 41 a7 7a 25 2a 83 7b c4-6e eb 61 82 73            A.z%*.{.n.a.s
SSL/TLS State [connect] SSLv3 read server certificate A
read from 0x1f9cf80 [0x1fa2953] (5 bytes => 5 (0x5))
0000 - 16 03 03 01 4d                                    ....M
read from 0x1f9cf80 [0x1fa2958] (333 bytes => 333 (0x14D))
0000 - 0c 00 01 49 03 00 17 41-04 60 e9 c4 30 05 c1 0f   ...I...A.`..0...
0010 - c3 72 9b 89 b8 f3 6c 65-30 2d 57 19 75 34 49 df   .r....le0-W.u4I.
0020 - b7 8d 8f ab c7 b0 31 42-c7 04 b6 50 5e 4f 6f 2e   ......1B...P^Oo.
0030 - 70 67 26 5c 0e c5 6c d2-41 40 33 43 07 43 bb 6d   pg&\..l.A@3C.C.m
0040 - fb d4 d6 0c c6 51 f4 cd-dc 06 01 01 00 95 ec fa   .....Q..........
0050 - f5 f8 84 de e0 33 6b de-d9 52 94 36 52 64 47 6c   .....3k..R.6RdGl
0060 - 32 21 60 16 dd d0 34 73-6e be 6e 73 5a 9c 84 16   2!`...4sn.nsZ...
0070 - b9 2e f0 bd 8e 8e ba dd-d6 df 1b 28 b0 0d dc 78   ...........(...x
0080 - 04 97 de 3b c3 cc e2 5a-0b 42 f6 3b 5c 83 40 19   ...;...Z.B.;\.@.
0090 - a4 ef 61 ef ad ca b8 e0-66 5a 84 21 57 1d 57 a6   ..a.....fZ.!W.W.
00a0 - 23 81 1d e6 8c c6 e3 7c-ae 79 40 0a ff 92 42 bd   #......|.y@...B.
00b0 - 0b 82 f2 8b e6 1a f0 0f-a0 fa a6 db 2d dc 78 e3   ............-.x.
00c0 - b9 d7 c7 01 cf 3d 3d fd-41 c5 0e 6e ab 0d c3 00   .....==.A..n....
00d0 - f1 41 db 8a fb 80 a8 37-09 ef 89 88 2d 0b 00 61   .A.....7....-..a
00e0 - 75 c9 91 65 1d 0a 2c ee-a9 83 c9 dc fb 2f 26 7b   u..e..,....../&{
00f0 - 90 ac 46 4d 3b 71 15 7d-ea 69 b2 84 ad de 08 91   ..FM;q.}.i......
0100 - ed 57 be e0 ae 90 f4 9c-3f f7 fd bd de e6 ff a9   .W......?.......
0110 - 62 58 9f dd 1d 90 44 e6-d8 fa 34 ad 5a 6b 63 d0   bX....D...4.Zkc.
0120 - b9 7f 9c 0a 80 2b ab 1d-37 16 6f 1f c5 93 32 13   .....+..7.o...2.
0130 - ac 98 f8 15 3e 67 d2 a9-fe 44 0e 2f f9 61 7d 79   ....>g...D./.a}y
0140 - b6 5b e1 80 a5 fa c3 e1-43 b4 3b 71 14            .[......C.;q.
SSL/TLS State [connect] SSLv3 read server key exchange A
read from 0x1f9cf80 [0x1fa2953] (5 bytes => 5 (0x5))
0000 - 16 03 03 00 04                                    .....
read from 0x1f9cf80 [0x1fa2958] (4 bytes => 4 (0x4))
0000 - 0e                                                .
0004 - <SPACES/NULS>
SSL/TLS State [connect] SSLv3 read server done A
SSL/TLS State [connect] SSLv3 write client key exchange A
SSL/TLS State [connect] SSLv3 write change cipher spec A
SSL/TLS State [connect] SSLv3 write finished A
write to 0x1f9cf80 [0x1fb0740] (126 bytes => 126 (0x7E))
0000 - 16 03 03 00 46 10 00 00-42 41 04 e5 35 7f 99 8e   ....F...BA..5...
0010 - ba 53 cf 7d 17 3d 7a f2-93 aa 62 f2 b5 b7 ee cd   .S.}.=z...b.....
0020 - a4 c0 c3 0a 75 6b e4 8c-85 59 b3 7b 3e 15 6f e9   ....uk...Y.{>.o.
0030 - 16 0d 7a f5 f7 22 cb 75-a1 b3 52 72 1a 35 da 49   ..z..".u..Rr.5.I
0040 - 2a 20 81 8f cd e3 c1 2a-21 a7 96 14 03 03 00 01   * .....*!.......
0050 - 01 16 03 03 00 28 04 ee-94 31 fa 78 5a 97 2d 0a   .....(...1.xZ.-.
0060 - 0d 3a 2d c7 c7 95 6c ae-c8 e1 17 40 22 61 cc 9b   .:-...l....@"a..
0070 - 53 b9 7d 7f ab 37 e0 b2-6e 20 ca 58 82 be         S.}..7..n .X..
SSL/TLS State [connect] SSLv3 flush data
read from 0x1f9cf80 [0x1fa2953] (5 bytes => -1 (0xFFFFFFFFFFFFFFFF))
read from 0x1f9cf80 [0x1fa2953] (5 bytes => 5 (0x5))
0000 - 16 03 03 00 aa                                    .....
read from 0x1f9cf80 [0x1fa2958] (170 bytes => 170 (0xAA))
0000 - 04 00 00 a6 00 00 01 2c-00 a0 0b 52 a7 d0 11 e8   .......,...R....
0010 - 97 13 a8 0a a5 1f 76 ed-94 35 3f c6 1a 33 d9 31   ......v..5?..3.1
0020 - 80 dd bc 22 bd 8a 5f 99-7b 6f 3d 5d b0 78 68 ed   ...".._.{o=].xh.
0030 - 21 eb e8 84 45 1e a4 16-78 d4 0f 35 62 f2 19 c1   !...E...x..5b...
0040 - 4c 6b d2 43 3f 67 bc e8-dc 27 ab 81 8c 0f d1 ad   Lk.C?g...'......
0050 - 1b de 07 bb 70 29 a0 d3-41 fc 41 6f 01 dc c2 f0   ....p)..A.Ao....
0060 - 9d 71 15 f5 80 04 d6 af-41 86 3b 4c 7a 0b bc 88   .q......A.;Lz...
0070 - 53 f6 97 39 f9 13 c8 79-f8 92 e2 70 38 1b 73 3b   S..9...y...p8.s;
0080 - d1 84 d0 17 8e ce 06 42-69 b6 e8 61 f1 7c 08 7c   .......Bi..a.|.|
0090 - c7 87 51 76 07 d6 d4 36-b0 52 d6 6c 67 6c 94 00   ..Qv...6.R.lgl..
00a0 - 12 b3 75 02 78 1b d3 0d-32 5f                     ..u.x...2_
SSL/TLS State [connect] SSLv3 read server session ticket A
read from 0x1f9cf80 [0x1fa2953] (5 bytes => 5 (0x5))
0000 - 14 03 03 00 01                                    .....
read from 0x1f9cf80 [0x1fa2958] (1 bytes => 1 (0x1))
0000 - 01                                                .
read from 0x1f9cf80 [0x1fa2953] (5 bytes => 5 (0x5))
0000 - 16 03 03 00 28                                    ....(
read from 0x1f9cf80 [0x1fa2958] (40 bytes => 40 (0x28))
0000 - d3 16 f4 23 d2 6d 3b fa-97 b8 e5 40 b1 67 87 1a   ...#.m;....@.g..
0010 - 98 3e 53 a2 7b 7e 12 d1-0c a7 f0 1a 61 da d7 6c   .>S.{~......a..l
0020 - 60 d9 d6 96 e3 09 e4 17-                          `.......
SSL/TLS State [connect] SSLv3 read finished A
SSL/TLS Handshake [Done] SSL negotiation finished successfully

Peer certificate
Certificate version: 3
Valid from: Sep 23 05:04:54 2015 GMT
Valid to  : Sep 22 05:04:54 2016 GMT
Public key is 2048 bits
The issuer name is /C=DE/ST=None/L=Berlin/O=what/CN=www.example.com
The subject name is /C=DE/ST=None/L=Berlin/O=what/CN=www.example.com
Extension Count: 3
Transport Protocol      :TLSv1.2
Cipher Suite Protocol   :TLSv1/SSLv3
Cipher Suite Name       :ECDHE-RSA-AES256-GCM-SHA384
Cipher Suite Cipher Bits:256 (256)
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 28C1ECCAAA1C5FD0B90DE4D6290D77FF464E384C0E3028024D570E4DD84D53BD
    Session-ID-ctx: 
    Master-Key: D0818D4C5B30A41DC3C24DA257893D0F86C118F767F8719DCE135AC7C433B379E4B605F0D20D200F91940DDDCCB29989
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 0b 52 a7 d0 11 e8 97 13-a8 0a a5 1f 76 ed 94 35   .R..........v..5
    0010 - 3f c6 1a 33 d9 31 80 dd-bc 22 bd 8a 5f 99 7b 6f   ?..3.1...".._.{o
    0020 - 3d 5d b0 78 68 ed 21 eb-e8 84 45 1e a4 16 78 d4   =].xh.!...E...x.
    0030 - 0f 35 62 f2 19 c1 4c 6b-d2 43 3f 67 bc e8 dc 27   .5b...Lk.C?g...'
    0040 - ab 81 8c 0f d1 ad 1b de-07 bb 70 29 a0 d3 41 fc   ..........p)..A.
    0050 - 41 6f 01 dc c2 f0 9d 71-15 f5 80 04 d6 af 41 86   Ao.....q......A.
    0060 - 3b 4c 7a 0b bc 88 53 f6-97 39 f9 13 c8 79 f8 92   ;Lz...S..9...y..
    0070 - e2 70 38 1b 73 3b d1 84-d0 17 8e ce 06 42 69 b6   .p8.s;.......Bi.
    0080 - e8 61 f1 7c 08 7c c7 87-51 76 07 d6 d4 36 b0 52   .a.|.|..Qv...6.R
    0090 - d6 6c 67 6c 94 00 12 b3-75 02 78 1b d3 0d 32 5f   .lgl....u.x...2_

    Start Time: 1443115349
    Timeout   : 300 (sec)
    Verify return code: 18 (self signed certificate)
write to 0x1f9cf80 [0x1faaea3] (150 bytes => 150 (0x96))
0000 - 17 03 03 00 91 04 ee 94-31 fa 78 5a 98 27 31 e8   ........1.xZ.'1.
0010 - 80 72 d0 a4 28 b9 72 a7-9b 18 07 9e f9 e0 2f 7c   .r..(.r......./|
0020 - 0c 3e ac f1 f3 0b 41 10-a3 77 44 83 57 de a1 3d   .>....A..wD.W..=
0030 - 1e e6 20 fd b7 14 fb 90-f4 8f f4 60 4e 2d f9 4a   .. ........`N-.J
0040 - d8 66 f6 ac 04 17 c2 9c-ac b8 17 14 2b 7b 7e 01   .f..........+{~.
0050 - 69 29 4f bb 7e be 4f 0b-09 f3 18 a5 cf e4 77 87   i)O.~.O.......w.
0060 - ad 69 ab d1 9c b2 64 ad-66 98 80 2a d6 bf b1 33   .i....d.f..*...3
0070 - 5c 1e fa 2b 00 6e 87 8a-23 40 8e 93 a0 d2 8b 24   \..+.n..#@.....$
0080 - 18 ff be 56 09 e5 0c 46-ec 67 25 82 d0 b8 90 84   ...V...F.g%.....
0090 - 24 6f 53 bd 02 27                                 $oS..'
read from 0x1f9cf80 [0x1fa2953] (5 bytes => 5 (0x5))
0000 - 17 03 03 40 18                                    ...@.
read from 0x1f9cf80 [0x1fa2958] (16408 bytes => 16408 (0x4018))
0000 - d3 16 f4 23 d2 6d 3b fb-7a 60 0e 6a f6 03 55 a8   ...#.m;.z`.j..U.
0010 - e7 0c af 04 6e a6 f0 45-d1 a3 d6 fc 31 45 c5 31   ....n..E....1E.1
0020 - 31 2c e6 e6 a0 6d ec 61-73 e7 6d fc f4 02 f7 e8   1,...m.as.m.....
0030 - 29 29 bd 8c 98 e4 a3 4a-9b be 1f 01 e4 af d2 bd   )).....J........
0040 - 24 b9 9d ba 9d f6 4f b4-85 8b 9d b3 40 9f 3e 28   $.....O.....@.>(
0050 - 19 52 94 d0 bc b2 1d 8e-2d 98 b2 b4 b5 73 74 68   .R......-....sth
0060 - a4 d6 d2 71 36 19 66 83-d7 96 63 fe 21 ce 72 c2   ...q6.f...c.!.r.
0070 - e2 eb d5 8c 5d 0c 93 76-87 06 e8 ec 67 21 7e aa   ....]..v....g!~.
0080 - 46 9e 36 3c 32 be 42 db-dd c1 3f 8c c9 54 d1 23   F.6<2.B...?..T.#
0090 - 50 23 73 ef 21 03 de e9-ca 78 41 83 3e 4e c7 6a   P#s.!....xA.>N.j
00a0 - 13 87 49 28 f8 b4 eb b3-af 3b bd bc 33 1a 82 6f   ..I(.....;..3..o
00b0 - f7 bc e9 a3 af 73 a2 59-ca d3 24 e1 34 b2 70 db   .....s.Y..$.4.p.
.
.
.
3fe0 - 2a 16 44 03 43 03 f3 24-1c bf 58 8b ba 69 5e 25   *.D.C..$..X..i^%
3ff0 - 1b 67 1c ba c4 8a 4a aa-af 2f 0d cb 0a 74 e8 21   .g....J../...t.!
4000 - 19 59 69 b3 ac 23 34 e8-a7 01 bc d6 b6 af 0f 30   .Yi..#4........0
4010 - 48 8b a5 c7 a4 dc 80 25-                          H......%
LOG: header received:
HTTP/1.0 200 OK
CONTENT-TYPE: application/octet-stream
LAST-MODIFIED: Wed, 23 Sep 2015 07:07:18 GMT
CONTENT-LENGTH: 500000
CONNECTION: keep-alive
DATE: Thu, 24 Sep 2015 17:22:29 GMT
SERVER: Python/3.4 aiohttp/0.18.0a0


LOG: Response code = 200
write to 0x1f9cf80 [0x1faaea3] (150 bytes => 150 (0x96))
0000 - 17 03 03 00 91 04 ee 94-31 fa 78 5a 99 08 ce f4   ........1.xZ....
0010 - 41 3d 24 13 2e cf 15 4c-af ff c0 e5 d9 31 38 7c   A=$....L.....18|
0020 - 62 d5 0c af 74 eb 4b 74-37 e3 05 50 0f 2a 47 82   b...t.Kt7..P.*G.
0030 - d9 55 8a 17 63 43 5a d1-c4 6a 2c 04 d9 5a 80 77   .U..cCZ..j,..Z.w
0040 - f8 3f 98 2a 66 44 55 aa-7b bf a7 1e ec ba f2 2a   .?.*fDU.{......*
0050 - ba c4 0e 2b 81 ed 18 5c-67 ef bf 03 b7 09 14 a3   ...+...\g.......
0060 - fd 25 20 a6 18 0e 5e bd-bf 7f cd 62 2c 3b 77 61   .% ...^....b,;wa
0070 - af f3 65 99 c7 be 8f 0b-e5 99 96 26 72 da 6b 3d   ..e........&r.k=
0080 - 32 b5 84 b5 44 3b e7 62-d6 95 43 c2 4f 71 46 ae   2...D;.b..C.OqF.
0090 - da 6d 10 fc 82 a6                                 .m....
LOG: header received:

apr_pollset_poll: The timeout specified has expired (70007)
Total of 1 requests completed
```

When SSL is disabled, you get the same behaviour on `ab`, but on the `aiohttp` end you also get a
`BrokenPipeError` raised this time.

```
$ python app.py localhost 8888 - static
DEBUG:asyncio:Using selector: EpollSelector
failed to load SSL certificate; fallback to unencrypted transport
Serving on: ('::1', 8888, 0, 0)
Serving on: ('127.0.0.1', 8888)
ERROR:aiohttp.web:Error handling request
Traceback (most recent call last):
  File "/home/user/code/aiohttp/aiohttp/server.py", line 272, in start
    yield from self.handle_request(message, payload)
  File "/home/user/code/aiohttp/aiohttp/web.py", line 86, in handle_request
    resp = yield from handler(request)
  File "/home/user/code/aiohttp/aiohttp/web_urldispatcher.py", line 287, in handle
    yield from self._sendfile(request, resp, f, file_size)
  File "/home/user/code/aiohttp/aiohttp/web_urldispatcher.py", line 225, in _sendfile_system
    yield from fut
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    return self.result()  # May raise too.
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/home/user/code/aiohttp/aiohttp/web_urldispatcher.py", line 179, in _sendfile_cb
    n = os.sendfile(out_fd, in_fd, offset, count)
BrokenPipeError: [Errno 32] Broken pipe
```

```
$ ab -v 4 -k -n 2 http://localhost:8888/static/file.bin
This is ApacheBench, Version 2.3 <$Revision: 1663405 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)...INFO: GET header == 
---
GET /static/file.bin HTTP/1.0
Connection: Keep-Alive
Host: localhost:8888
User-Agent: ApacheBench/2.3
Accept: */*


---
LOG: header received:
HTTP/1.0 200 OK
CONTENT-TYPE: application/octet-stream
LAST-MODIFIED: Wed, 23 Sep 2015 07:07:18 GMT
CONTENT-LENGTH: 500000
CONNECTION: keep-alive
DATE: Thu, 24 Sep 2015 17:42:05 GMT
SERVER: Python/3.4 aiohttp/0.18.0a0


LOG: Response code = 200
LOG: header received:

apr_pollset_poll: The timeout specified has expired (70007)
Total of 1 requests completed
```

**Comment by asvetlov** [comment]
Check again please: after ffc7982a76ad59865444604261cf9af44343a3e1 sendfile is disabled for SSL mode.

**Comment by jashandeep-sohi** [comment]
I am testing with ffc7982. I think you misunderstood what I was saying.
The problem isn't with sendfile, it's something to do with `keep-alive` on `http/1.0` requests.

For example, making `keep-alive` requests using `http/1.1` clients like `httperf` doesn't cause any problems.

**Comment by asvetlov** [comment]
The problem maybe related to keepalive support in HTTP/1.0
But I definitely see `os.sendfile()` in your traceback, it should never happen with SSL enabled.

**Comment by jashandeep-sohi** [comment]
Look at it again, please. There are two sets of logs. One where SSL is enabled, and one where it is disabled.

**Comment by asvetlov** [comment]
Ahh, got it. Sorry.

I think we should add `Connection: keep-alive` header in https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/protocol.py#L834 if `not self.closing and self.version == HttpVersion10`.

@jashandeep-sohi would you make a PR with a test?

**Comment by jashandeep-sohi** [comment]
`aiohttp` is already responding with `connection: keep-alive` headers for `http/1.0` requests that have `connection: keep-alive` in their headers.

Maybe this is a problem with `ab`? Do you know of any other `http/1.0` clients that I could test with?

**Comment by jashandeep-sohi** [comment]
Okay, it is a problem with `ab`. Running `ab` on `https://www.python.org/` leads to the same problem::

```
$ ab -k -n 2 "https://www.python.org/"
This is ApacheBench, Version 2.3 <$Revision: 1663405 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking www.python.org (be patient)...apr_pollset_poll: The timeout specified has expired (70007)
```

Probably should have done this earlier and saved ourselves some time :-<
