### ISSUE TITLE
AssertionError in _sendfile_system: assert transport is not None

### ISSUE THREAD

**Issue by bitnom** [aio-libs/aiohttp#5373]
aiohttp 4.0.0a1
python 3.9.0
Linux x64

I think this is just a basic demo setup with a route using jinja2. Upon visiting the page/route, I see:

```
Unhandled exception
Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/website--1hV_kTf-py3.9/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 480, in start
    resp, reset = await task
  File "/home/user/.cache/pypoetry/virtualenvs/website--1hV_kTf-py3.9/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "/home/user/.cache/pypoetry/virtualenvs/website--1hV_kTf-py3.9/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 580, in finish_response
    await prepare_meth(request)
  File "/home/user/.cache/pypoetry/virtualenvs/website--1hV_kTf-py3.9/lib/python3.9/site-packages/aiohttp/web_fileresponse.py", line 344, in prepare
    return await self._sendfile(request, fobj, count)
  File "/home/user/.cache/pypoetry/virtualenvs/website--1hV_kTf-py3.9/lib/python3.9/site-packages/aiohttp/web_fileresponse.py", line 155, in _sendfile_system
    assert transport is not None
AssertionError
```

This does not happen in stable version

**Comment by Dreamsorcerer** [comment]
Given that the last aiohttp 4 alpha release was over a year ago, I'd suggest running against master if you want to use v4 (and confirm if the issue is still present).

master seems to get most of the improvements being made for the 3.x releases, so that old alpha release is probably missing a huge amount of changes.

**Comment by bitnom** [comment]
> Given that the last aiohttp 4 alpha release was over a year ago, I'd suggest running against master if you want to use v4 (and confirm if the issue is still present).
> 
> master seems to get most of the improvements being made for the 3.x releases, so that old alpha release is probably missing a huge amount of changes.

my bad. I hadn't checked the date. Thanks
