### ISSUE TITLE
Logger: aiohttp.server Source: /usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py:393 First occurred: 7:45:22 (1 occurrences) Last logged: 7:45:22  Error handling request Traceback (most recent call last):   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 314, in data_received     messages, upgraded, tail = self._request_parser.feed_data(data)   File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"

### ISSUE THREAD

**Issue by viannale** [aio-libs/aiohttp#5544]

**Comment by webknjaz** [comment]
Looks like you received an invalid request.
