### ISSUE TITLE
AttributeError: 'ClientSession' object has no attribute '_connector' on Google Dataproc

### ISSUE THREAD

**Issue by gndumbri** [aio-libs/aiohttp#5658]
🐞 **Describe the bug**

AttributeError: 'ClientSession' object has no attribute '_connector' 

💡 **To Reproduce**

```
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import scipy
from scipy.sparse import csr_matrix
import pyspark
from pyspark.sql import SparkSession
import sys
import time
from datetime import datetime, date

def tfidf(path):
    if '.csv' in path:
        diags = pd.read_csv(path)
    else:
        diags = pd.read_parquet(path)

    diags.dropna(inplace=True)

    hicnos = diags['hicno'].unique().tolist()

    diags['diags'] = (diags['diag']+' ')*diags['clm_cnt']
    diags = pd.DataFrame(diags.groupby('hicno', sort=False)['diags'].apply(lambda x: x.tolist()))
    diags.reset_index(inplace=True)
    diags['diags'] = diags['diags'].apply(lambda x: ''.join(x).rstrip())

    vectorizer = TfidfVectorizer(dtype=np.float32)
    return hicnos, vectorizer.fit_transform(diags['diags'].tolist())

path = sys.argv[1] # a gs://google-storage-bucket/file.csv link is what is given as sys.argv[1] in the pyspark jobs submit 

df = tfidf(path)

```

💡 **Expected behavior**

As of 4/20/21 my csv file would load as expected and there was no error. I have run this same code in a Google Colab notebook without error. The python version in the Colab notebook is  3.7. The python version is the only difference I see between the code that causes and error and the code that works as expected. The code I provided above causes the error whether my csv file is from an s3 or google storage bucket on Google Dataproc.  Python version is 3.8.8 on Google Compute Engine VM instance.

📋 **Logs/tracebacks**

```python-traceback (paste your traceback in the next line)
Job [6282a0c4e4be42ac87d678d43a2e520c] submitted.
Waiting for job output...
Exception ignored in: <function ClientSession.__del__ at 0x7f6880aef550>
Traceback (most recent call last):
  File "/opt/conda/default/lib/python3.8/site-packages/aiohttp/client.py", line 326, in __del__
    if not self.closed:
  File "/opt/conda/default/lib/python3.8/site-packages/aiohttp/client.py", line 963, in closed
    return self._connector is None or self._connector.closed
AttributeError: 'ClientSession' object has no attribute '_connector'
Traceback (most recent call last):
  File "/tmp/6282a0c4e4be42ac87d678d43a2e520c/rap5.py", line 221, in <module>
    hicnos, x = tfidf(path)
  File "/tmp/6282a0c4e4be42ac87d678d43a2e520c/rap5.py", line 21, in tfidf
    diags = pd.read_csv(path).dropna()
  File "/opt/conda/default/lib/python3.8/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/default/lib/python3.8/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/default/lib/python3.8/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/opt/conda/default/lib/python3.8/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/opt/conda/default/lib/python3.8/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/opt/conda/default/lib/python3.8/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/opt/conda/default/lib/python3.8/site-packages/pandas/io/common.py", line 558, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/opt/conda/default/lib/python3.8/site-packages/pandas/io/common.py", line 333, in _get_filepath_or_buffer
    file_obj = fsspec.open(
  File "/opt/conda/default/lib/python3.8/site-packages/fsspec/core.py", line 428, in open
    return open_files(
  File "/opt/conda/default/lib/python3.8/site-packages/fsspec/core.py", line 280, in open_files
    fs, fs_token, paths = get_fs_token_paths(
  File "/opt/conda/default/lib/python3.8/site-packages/fsspec/core.py", line 608, in get_fs_token_paths
    fs = cls(**options)
  File "/opt/conda/default/lib/python3.8/site-packages/fsspec/spec.py", line 69, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/opt/conda/default/lib/python3.8/site-packages/gcsfs/core.py", line 269, in __init__
    self._session = sync(
  File "/opt/conda/default/lib/python3.8/site-packages/fsspec/asyn.py", line 53, in sync
    raise result[0]
  File "/opt/conda/default/lib/python3.8/site-packages/fsspec/asyn.py", line 20, in _runner
    result[0] = await coro
  File "/opt/conda/default/lib/python3.8/site-packages/fsspec/implementations/http.py", line 25, in get_client
    return aiohttp.ClientSession(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'callback_timeout'
```

📋 **Your version of the Python**

```console
Python 3.8.8
$ python --version
...
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
3.7.4
$ python -m pip show aiohttp
...
```
```console
5.1.0
$ python -m pip show multidict
...
```
```console
1.6.3
$ python -m pip show yarl
...
```

📋 **Additional context**

Python 3.8.8
Pyspark 3.1.1
fsspec 0.9.0
gcsfs 0.7.2
2.0.9-debian10 master node for cluster

**Comment by gndumbri** [comment]
The issue only appears to happen with gcsfs version 0.7.2. It looks like gcsfs 2021.4.0 was just released 4/21/21. Perhaps I am seeing the error now because the bug only occurs when gcsfs is version 0.7.2. I played around with changing aiohttp versions and the error only occurs when gcsfs is 0.7.2. Any idea why the error with this version alone? It looks like errors are caused in aiohttp and fsspec due to this gcsfs version 0.7.2.

**Comment by Dreamsorcerer** [comment]
Are you looking at the right error though?

> TypeError: __init__() got an unexpected keyword argument 'callback_timeout'

This suggests a problem somewhere else, this parameter does not exist.

I suspect the other error is caused by this one, given that it is coming form `__del__()`. i.e. `ClientSession()` is created, but then `__init__()` errors without setting up the object, then the session object is deleted which errors again as it expects the object to have been setup successfully.

**Comment by gndumbri** [comment]
The issue was with gcsfs 0.7.2 being incompatible with fsspec 0.9.0. For whatever reason Dataproc preinstalls those versions on the Dataproc image 2.0 that comes with Debian 10. So either the Google Dataproc team doesn't know they're incompatible or it is mistake, but either way it is not caused by aiohttp.
