### ISSUE TITLE
Error occurs when Content-Type is not specified in the response header.

### ISSUE THREAD

**Issue by grarich** [aio-libs/aiohttp#5667]
🐞 **Describe the bug**
Error occurs when Content-Type is not specified in the response header.

💡 **To Reproduce**
1. Open the REPL for asyncio
2. Execute the following code
3. See some behavior described

```python
>>>import asyncio
>>>import aiohttp
# JSON is returned, but Content-Type application/json is not specified in the response header.
>>>url = 'https://example.com'
>>>async with aiohttp.request('POST', url) as resp:
...    data = await resp.json()
...

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "<console>", line 2, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\client_reqrep.py", line 1026, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://example.com')
```

📋 **Logs/tracebacks**
See the traceback above.

📋 **Your version of the Python**
```console
$ python --version
Python 3.8.6
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
Location: c:\users\user\appdata\local\programs\python\python38\lib\site-packages
Requires: async-timeout, chardet, attrs, multidict, yarl
```
```console
$ python -m pip show multidict
Name: multidict
Version: 4.7.6
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: c:\users\user\appdata\local\programs\python\python38\lib\site-packages
Requires:
Required-by: yarl, aiohttp
```
```console
$ python -m pip show yarl
Name: yarl
Version: 1.5.1
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: c:\users\user\appdata\local\programs\python\python38\lib\site-packages
Requires: multidict, idna
Required-by: aiohttp
```

**Comment by mshandrovskiy** [comment]
This is documented behavior https://docs.aiohttp.org/en/stable/client_advanced.html#disabling-content-type-validation-for-json-responses
You have a few options, depending on how you want to handle it.

**Comment by grarich** [comment]
I see. I understand. Thank you.
