### ISSUE TITLE
Unable to Stream Proxy Data

### ISSUE THREAD

**Issue by tebanep** [aio-libs/aiohttp#5693]
🐞 **Describe the bug**

I'm trying to serve a stream of data downloaded from an external url. For that purpouse, I'm using aiohttp's server and client in combination. In my server handler, I'm returning a StreamResponse, writing to it in chunks. The response is correctly streamed when using static bytes data. However, if the data comes from ClientResponse.content (i.e. an aiohttp.StreamReader instance) an error is raised.

💡 **To Reproduce**

You might run the following server:

```python
from aiohttp import web, ClientSession


# Proxy Streaming Download

async def _proxy_chunked_data() -> None:
    url = ('https://images.unsplash.com/photo-1620330270596-0c559cb32a68?'
        'ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&'
        'cs=tinysrgb&w=1080&fit=max')

    size = 512 * 1024
    
    async with ClientSession() as session:
        async with session.get(url) as response:
            chunk = await response.content.read(size)
            while chunk:
                yield chunk
                await response.content.read(size)

async def proxy_stream_download(request):
    response = web.StreamResponse()
    await response.prepare(request)

    async for chunk in _proxy_chunked_data():
        await response.write(chunk)

    print('Proxy Stream Response Finished!')

    return response


# Bytes Streaming Download

async def _bytes_chunked_data() -> None:
    size = 1
    offset = 0
    data = b'abracadabra\n'
    chunk = data[offset:offset + size]
    while chunk:
        yield chunk
        offset += size
        chunk = data[offset:offset + size]

async def bytes_stream_download(request):
    response = web.StreamResponse()
    await response.prepare(request)

    async for chunk in _bytes_chunked_data():
        await response.write(chunk)

    print('Bytes Stream Response Finished!')

    return response


app = web.Application()
app.add_routes([web.get('/proxy_download', proxy_stream_download)])
app.add_routes([web.get('/bytes_download', bytes_stream_download)])


if __name__ == '__main__':
    web.run_app(app, port=7777)
```

Then, with **curl** you can perform requests to both endpoints, realizing that the **"/proxy_download"** raises an error.

In **client console (bytes_download):**
```console
(env) mediark@mediark:~$ curl localhost:7777/bytes_download
abracadabra
```

In **server console (bytes_download):**
```console
(env) mediark@mediark:~$ python read_wait_aiohttp_error.py
======== Running on http://0.0.0.0:7777 ========
(Press CTRL+C to quit)
Bytes Stream Response Finished!
```

In **client console (proxy_download):**
```console
(env) mediark@mediark:~$ curl localhost:7777/proxy_download
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.

(env) mediark@mediark:~$ curl localhost:7777/proxy_download --output /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                                     Dload  Upload   Total   Spent    Left  Speed
100 25.2M    0 25.2M    0     0  3273k      0 --:--:--  0:00:07 --:--:-- 3406k^C
```

In **server console (proxy_download):**
```console
(env) mediark@mediark:~$ python read_wait_aiohttp_error.py 
======== Running on http://0.0.0.0:7777 ========
(Press CTRL+C to quit)
Multiple access to StreamReader in eof state, might be infinite loop.
Stack (most recent call last):
File "read_wait_aiohttp_error.py", line 62, in <module>
web.run_app(app, port=7777)
File "/opt/mediark/env/lib/python3.8/site-packages/aiohttp/web.py", line 508, in run_app
loop.run_until_complete(main_task)
File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
self.run_forever()
File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
self._run_once()
File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
handle._run()
File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
self._context.run(self._callback, *self._args)
File "/opt/mediark/env/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/opt/mediark/env/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "read_wait_aiohttp_error.py", line 24, in proxy_stream_download
async for chunk in _proxy_chunked_data():
File "read_wait_aiohttp_error.py", line 18, in _proxy_chunked_data
await response.content.read(size)
File "/opt/mediark/env/lib/python3.8/site-packages/aiohttp/streams.py", line 354, in read
internal_logger.warning(
Multiple access to StreamReader in eof state, might be infinite loop.
...
```

For example:
1. Have certain environment
2. Run given code snippet in a certain way
3. See some behavior described

Add these steps below this comment: -->

💡 **Expected behavior**

The remote binary resource should be able to be downloaded and proxied by the server through streaming.

📋 **Logs/tracebacks**

```python-traceback (paste your traceback in the next line)
Multiple access to StreamReader in eof state, might be infinite loop.
Stack (most recent call last):
File "read_wait_aiohttp_error.py", line 62, in <module>
web.run_app(app, port=7777)
File "/opt/mediark/env/lib/python3.8/site-packages/aiohttp/web.py", line 508, in run_app
loop.run_until_complete(main_task)
File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
self.run_forever()
File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
self._run_once()
File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
handle._run()
File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
self._context.run(self._callback, *self._args)
File "/opt/mediark/env/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/opt/mediark/env/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "read_wait_aiohttp_error.py", line 24, in proxy_stream_download
async for chunk in _proxy_chunked_data():
File "read_wait_aiohttp_error.py", line 18, in _proxy_chunked_data
await response.content.read(size)
File "/opt/mediark/env/lib/python3.8/site-packages/aiohttp/streams.py", line 354, in read
internal_logger.warning(
Error handling request
Traceback (most recent call last):
File "/opt/mediark/env/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/opt/mediark/env/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "read_wait_aiohttp_error.py", line 25, in proxy_stream_download
await response.write(chunk)
File "/opt/mediark/env/lib/python3.8/site-packages/aiohttp/web_response.py", line 470, in write
await self._payload_writer.write(data)
File "/opt/mediark/env/lib/python3.8/site-packages/aiohttp/http_writer.py", line 107, in write
self._write(chunk)
File "/opt/mediark/env/lib/python3.8/site-packages/aiohttp/http_writer.py", line 67, in _write
raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```

📋 **Your version of the Python**

```console
$ python --version
Python 3.8.5
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.7.4.post0
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: /opt/mediark/env/lib/python3.8/site-packages
Requires: chardet, multidict, async-timeout, typing-extensions, attrs, yarl
Required-by: pytest-aiohttp, aiohttp-jinja2
```
```console
$ python -m pip show multidict
Name: multidict
Version: 5.1.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /opt/mediark/env/lib/python3.8/site-packages
Requires:
Required-by: yarl, aiohttp
```
```console
$ python -m pip show yarl
Name: yarl
Version: 1.6.3
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /opt/mediark/env/lib/python3.8/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

📋 **Additional context**

Using **Ubuntu 20.04**

Thank you! :smiley:

**Comment by paulefoe** [comment]
Hey, thanks for submitting it!

There seems to be a problem with your code tho. As server logs say you have an infinite loop

Change this and everything should work well
```python
async with ClientSession() as session:
        async with session.get(url) as response:
            chunk = await response.content.read(size)
            while chunk:
                yield chunk
                chunk = await response.content.read(size)
```

Let me know if you still have an issue

**Comment by tebanep** [comment]
Thank you @paulefoe! You are completely right, I missed the assignment to chunk inside the while loop in this example. This is not the actual error I'm experiencing in production, as you might have guessed. However, I confirm that in this case, assigning to chunk fixes the problem. This gives me some clues about what might be happening with our server, so I'll review again our implementation. If the problem persists, I'll get back to you again if you don't mind. Thanks a lot!

**Comment by tebanep** [comment]
@paulefoe, I guess I know what is happening. If the client (in this case **curl**) terminates before the file has been completely downloaded, then the server gets stuck and doesn't get to the print statement line **print('Proxy Stream Response Finished!')**. Is this the normal behaviour of aiohttp, and if so, which would be the proper way to handle this kind of situations?

**Comment by paulefoe** [comment]
I think that is the proper way for handling things in aiohttp.

Let me know if this part of docs is solving your problem

https://docs.aiohttp.org/en/stable/web_advanced.html#peer-disconnection

**Comment by tebanep** [comment]
Hello @paulefoe and thanks a lot for your help. Unfortunately, the server is still getting stuck when the client disconnects abruptly. I've modified my example to demonstrate the situation:

```python
import asyncio
from aiohttp import web, ClientSession


# Proxy Streaming Download

async def _proxy_chunked_data() -> None:
    url = ('https://file-examples-com.github.io/uploads'
            '/2017/04/file_example_MP4_1920_18MG.mp4')
    
    size = 16 * 1024
    
    async with ClientSession() as session:
        async with session.get(url) as response:
            chunk = await response.content.read(size)
            while chunk:
                print('Yielding chunk:', len(chunk))
                yield chunk
            
                print('Reading next chunk...')
                try:
                    chunk = await response.content.read(size)
                except Exception as error:
                    print(error)
                    raise

            print('*** New chunk read:', len(chunk))


async def proxy_stream_download(request):
    print('Start Proxy')
    response = web.StreamResponse()
    await response.prepare(request)
    
    async for chunk in _proxy_chunked_data():
        try:
            print('Writting chunk:', len(chunk))
            await response.write(chunk)
            print('Chunk written!')
        except Exception as error:
            print(error)
            raise
            
    print('Proxy Stream Response Finished!')
    
    return response


app = web.Application()
app.add_routes([web.get('/proxy_download', proxy_stream_download)])


if __name__ == '__main__':
    web.run_app(app, port=7777)

```
If the server is started and a request is made with **curl** the file begins to be streamed.

```console
root@mediark:~# curl localhost:7777/proxy_download --output /dev/null
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 7582k    0 7582k    0     0  2901k      0 --:--:--  0:00:02 --:--:-- 2900k^C
```

However, if we terminate curl's process (in this case after 2 seconds), the server gets stuck, without raising any errors. It halts on reading from the upstream source, and not when writting to the response.

```console
(env) mediark@mediark:~$ python proxy_read_wait_aiohttp_error.py 
======== Running on http://0.0.0.0:7777 ========
(Press CTRL+C to quit)
Start Proxy
Yielding chunk: 1378
Writting chunk: 1378
Chunk written!
Reading next chunk...
*** New chunk read: 1378

...

Yielding chunk: 16384
Writting chunk: 16384
Chunk written!
Reading next chunk...
*** New chunk read: 16384
Yielding chunk: 16384
Writting chunk: 16384
Chunk written!
Reading next chunk...
*** New chunk read: 16384
Yielding chunk: 16384
Writting chunk: 16384
Chunk written!
Reading next chunk...
*** New chunk read: 16384
Yielding chunk: 16384
Writting chunk: 16384
Chunk written!
Reading next chunk...
```

Upon deeper investigation, I noticed that the process halts in line **310 of the streams.py** file, inside the **_wait()** method that is called by **read() (in line 377)**:

```python
# streams.py
...
    async def read(self, n: int = -1) -> bytes:
        if self._exception is not None:
            raise self._exception

        if not n:
            return b""

        if n < 0:
            # This used to just loop creating a new waiter hoping to
            # collect everything in self._buffer, but that would
            # deadlock if the subprocess sends more than self.limit
            # bytes.  So just call self.readany() until EOF.
            blocks = []
            while True:
                block = await self.readany()
                if not block:
                    break
                blocks.append(block)
            return b"".join(blocks)

        # TODO: should be `if` instead of `while`
        # because waiter maybe triggered on chunk end,
        # without feeding any data
        while not self._buffer and not self._eof:
            await self._wait("read")

        return self._read_nowait(n)
...
```

```python
# streams.py
...
    async def _wait(self, func_name: str) -> None:
        # StreamReader uses a future to link the protocol feed_data() method
        # to a read coroutine. Running two read coroutines at the same time
        # would have an unexpected behaviour. It would not possible to know
        # which coroutine would get the next data.
        if self._waiter is not None:
            raise RuntimeError(
                "%s() called while another coroutine is "
                "already waiting for incoming data" % func_name
            )

        waiter = self._waiter = self._loop.create_future()
        try:
            if self._timer:
                with self._timer:
                    await waiter
            else:
                await waiter
        finally:
            self._waiter = None
...
```

Can you guess what might be causing this problem? Any workarounds to prevent the server from halting when the client disconnects?

**Comment by paulefoe** [comment]
This is interesting, but your code behaving differently on my machine.

Here's the output that I observe:

```
Chunk written!
Reading next chunk...
Connection closed
Yielding chunk: 4134
Writting chunk: 4134
Cannot write to closing transport
Error handling request
Traceback (most recent call last):
  File "/home/paulefou/other_projects/httpx/venv/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/home/paulefou/other_projects/httpx/venv/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/home/paulefou/other_projects/unauth/stre.py", line 37, in proxy_stream_download
    await response.write(chunk)
  File "/home/paulefou/other_projects/httpx/venv/lib/python3.9/site-packages/aiohttp/web_response.py", line 470, in write
    await self._payload_writer.write(data)
  File "/home/paulefou/other_projects/httpx/venv/lib/python3.9/site-packages/aiohttp/http_writer.py", line 107, in write
    self._write(chunk)
  File "/home/paulefou/other_projects/httpx/venv/lib/python3.9/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```

What you described happen to me only if I remove the `raise` here:

```python
try:
        print('Writting chunk:', len(chunk))
        await response.write(chunk)
        print('Chunk written!')
except Exception as error:
        print(error)
        raise
```
And I'm using the same `3.7.4.post0` version.

I'll try tomorrow to do a little bit more research, but I can't really promise anything

**Comment by tebanep** [comment]
Thank you very much @paulefoe. I'm closing this issue as I have solved my problem already. Notwithstanding I could reproduce the issue in a smaller example, I believe this is a rare case that occurs only when proper exception handling is not applied in code involving the performance of network requests. So, at least for me, this whole situation can be marked as solved!
