### ISSUE TITLE
 kerberos authentication header is not supported 

### ISSUE THREAD

**Issue by lavkush-qu** [aio-libs/aiohttp#5755]
🐞 **Describe the bug**

There is a use case where we need to set auth header as kerberos authentication like `auth=HTTPKerberosAuth(force_preemptive=True, mutual_authentication=OPTIONAL, delegate=True))` in `ClientSession(auth=auth)`. It is raising error (mention below) because auth type is define BasicAuth only.
`in update_auth
    raise TypeError("BasicAuth() tuple is required instead")
TypeError: BasicAuth() tuple is required instead
`
is there any suggestion or help for setting up auth as kerberos authentication?

Thanks in advance 

💡 **To Reproduce**

💡 **Expected behavior**

📋 **Logs/tracebacks**

```python-traceback (paste your traceback in the next line)
Traceback (most recent call last):
  File "edge_sdk/connectors/osipi/test.py", line 40, in <module>
    asyncio.run(check())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "edge_sdk/connectors/osipi/test.py", line 28, in check
    resp = await session.get(url)
  File "/home/dev/local_env/c_ser/lib/python3.8/site-packages/aiohttp/client.py", line 492, in _request
    req = self._request_class(
  File "/home/dev/local_env/c_ser/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 310, in __init__
    self.update_auth(auth)
  File "/home/dev/local_env/c_ser/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 497, in update_auth
    raise TypeError("BasicAuth() tuple is required instead")
TypeError: BasicAuth() tuple is required instead

```

📋 **Your version of the Python**

```console
$ python --version
Python 3.8.5
...
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
...
Version: 3.7.4
```
```console
$ python -m pip show multidict
...
Version: 5.1.0
```
```console
$ python -m pip show yarl
...
Version: 1.6.3
```

📋 **Additional context**

**Comment by webknjaz** [comment]
> `HTTPKerberosAuth`

There's no such thing in aiohttp. Please consult with the library you're importing this from.
