### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'send'

### ISSUE THREAD

**Issue by justanotherbyte** [aio-libs/aiohttp#5941]
### Describe the bug

When trying to send data through a websocket, the following error occurs:

```sh
Traceback (most recent call last):
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Websites\bbdash\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Websites\bbdash\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Websites\bbdash\lib\site-packages\asgiref\sync.py", line 223, in __call__
    return call_result.result()
  File "c:\users\happy\appdata\local\programs\python\python38\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "c:\users\happy\appdata\local\programs\python\python38\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Websites\bbdash\lib\site-packages\asgiref\sync.py", line 292, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Websites\bbdash\core\views.py", line 110, in dashboard_welcoming
    await WEBSOCKET.send_json({
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Websites\bbdash\bbdash\websocket.py", line 42, in send_json
    return await self.ws.send_str(string_data)
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Websites\bbdash\lib\site-packages\aiohttp\client_ws.py", line 150, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Websites\bbdash\lib\site-packages\aiohttp\http_websocket.py", line 687, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Websites\bbdash\lib\site-packages\aiohttp\http_websocket.py", line 643, in _send_frame
    self._write(header + mask + message)
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Websites\bbdash\lib\site-packages\aiohttp\http_websocket.py", line 661, in _write
    self.transport.write(data)
  File "c:\users\happy\appdata\local\programs\python\python38\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "c:\users\happy\appdata\local\programs\python\python38\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
```

### To Reproduce

1. Create a django project
2. Create a websocket class that handles websockets. Mine is shown below;
```py
class WebsocketIO:
    def __init__(self, ws: aiohttp.ClientWebSocketResponse, session: aiohttp.ClientSession):
        self.ws = ws
        self.session = session

        self.initial_connect = False
        self.failed_connect = False

    
    @property
    def can_connect(self) -> bool:
        if self.ws is None or self.ws.closed is True:
            if self.failed_connect is False:
                return True
            
        return False


    async def send_json(self, data: dict):
        string_data = json.dumps(data)
        return await self.ws.send_str(string_data)

    async def receive_json(self) -> dict:
        string_data = await self.ws.receive_str()
        data = json.loads(string_data)
        return data

    
    @classmethod
    def from_none(cls):
        io = cls(None, None)
        return io

    async def ws_connect(self) -> Tuple[aiohttp.ClientWebSocketResponse, aiohttp.ClientSession]:
        ws, session = await _ws_connect(WEBSOCKET_URL, headers = {"Authorization": WEBSOCKET_AUTH})
        self.ws = ws
        self.session = session
        return (ws, session)
```
3. Try and send data through a websocket in an async django view.

### Expected behavior

The library actually sends the data through the websocket instead of failing.

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Websites\bbdash\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Websites\bbdash\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Websites\bbdash\lib\site-packages\asgiref\sync.py", line 223, in __call__
    return call_result.result()
  File "c:\users\happy\appdata\local\programs\python\python38\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "c:\users\happy\appdata\local\programs\python\python38\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Websites\bbdash\lib\site-packages\asgiref\sync.py", line 292, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Websites\bbdash\core\views.py", line 110, in dashboard_welcoming
    await WEBSOCKET.send_json({
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Websites\bbdash\bbdash\websocket.py", line 42, in send_json
    return await self.ws.send_str(string_data)
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Websites\bbdash\lib\site-packages\aiohttp\client_ws.py", line 150, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Websites\bbdash\lib\site-packages\aiohttp\http_websocket.py", line 687, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Websites\bbdash\lib\site-packages\aiohttp\http_websocket.py", line 643, in _send_frame
    self._write(header + mask + message)
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Websites\bbdash\lib\site-packages\aiohttp\http_websocket.py", line 661, in _write
    self.transport.write(data)
  File "c:\users\happy\appdata\local\programs\python\python38\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "c:\users\happy\appdata\local\programs\python\python38\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
```

### Python Version

```console
$ python --version
Python 3.8.7
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.7.4.post0
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: c:\users\happy\onedrive\documents\coding projects\websites\bbdash\lib\site-packages
Requires: yarl, async-timeout, multidict, typing-extensions, attrs, chardet
Required-by: discord-ext-oauth
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 5.1.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: c:\users\happy\onedrive\documents\coding projects\websites\bbdash\lib\site-packages
Requires:
Required-by: yarl, aiohttp
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.6.3
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: c:\users\happy\onedrive\documents\coding projects\websites\bbdash\lib\site-packages
Requires: multidict, idna
Required-by: aiohttp
```

### OS

Windows

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by justanotherbyte** [comment]
Just to add, my `_ws_connect` function is as so:
```py
async def _ws_connect(url: str, session: aiohttp.ClientSession = None, **connect_kwargs) -> Tuple[aiohttp.ClientWebSocketResponse, aiohttp.ClientSession]:
    if session is not None and session.closed is True:
        session = None
    session = session or aiohttp.ClientSession(raise_for_status = True)
    ws = await session.ws_connect(url, **connect_kwargs)
    return (ws, session)
```

**Comment by Hanaasagi** [comment]
I tested above code in my local laptop. I could not reproduce this error. I used the `https://echo.websocket.org/` as the test url.


```Python
import json
import asyncio
import aiohttp
from typing import Tuple

WEBSOCKET_URL = "https://echo.websocket.org/"
WEBSOCKET_AUTH = ""


async def _ws_connect(url: str, session: aiohttp.ClientSession = None, **connect_kwargs) -> Tuple[aiohttp.ClientWebSocketResponse, aiohttp.ClientSession]:
    if session is not None and session.closed is True:
        session = None
    session = session or aiohttp.ClientSession(raise_for_status = True)
    ws = await session.ws_connect(url, **connect_kwargs)
    return (ws, session)


class WebsocketIO:
    def __init__(self):

        self.initial_connect = False
        self.failed_connect = False


    @property
    def can_connect(self) -> bool:
        if self.ws is None or self.ws.closed is True:
            if self.failed_connect is False:
                return True

        return False


    async def send_json(self, data: dict):
        string_data = json.dumps(data)
        return await self.ws.send_str(string_data)

    async def receive_json(self) -> dict:
        string_data = await self.ws.receive_str()
        data = json.loads(string_data)
        return data


    @classmethod
    def from_none(cls):
        io = cls(None, None)
        return io

    async def ws_connect(self) -> Tuple[aiohttp.ClientWebSocketResponse, aiohttp.ClientSession]:
        ws, session = await _ws_connect(WEBSOCKET_URL, headers = {"Authorization": WEBSOCKET_AUTH})
        self.ws = ws
        self.session = session
        return (ws, session)



async def test():
    wio = WebsocketIO()
    await wio.ws_connect()
    print("sending ...")
    await wio.send_json({'a': 1})
    print("waiting ...")
    data = await wio.receive_json()
    print("Got data:")
    print(data)


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(test())

```

Environment:
- Python 3.8.5
- aiohttp: 3.7.4.post0
- Linux

**Comment by Hanaasagi** [comment]
I see that it used the `IOCP` policy from the traceback message. Could you try:

```Python
policy = asyncio.WindowsSelectorEventLoopPolicy()
asyncio.set_event_loop_policy(policy)
```

**Comment by justanotherbyte** [comment]
> 
> 
> I see that it used the `IOCP` policy from the traceback message. Could you try:
> 
> ```python
> policy = asyncio.WindowsSelectorEventLoopPolicy()
> asyncio.set_event_loop_policy(policy)
> ```

I have tried this. I still get a similar error.

**Comment by asvetlov** [comment]
`loop._proactor` is `None` means `loop.close()` was called before `session.close()` call.
This is incorrect; and not aiohttp problem.
