### ISSUE TITLE
Asyncronious DNS not working

### ISSUE THREAD

**Issue by ghost** [aio-libs/aiohttp#5966]
### Describe the bug

aiodns is not working. I checked my Internet connection and DNS settings (by using `socket` and `aiodns` 
 related functions). 

I tried to get a json file, but got: `OSError: [Errno 101] Network is unreachable`.

### To Reproduce

```python
import aiohttp
from aiohttp.resolver import AsyncResolver

async def main():
    resolver = AsyncResolver()
    conn = aiohttp.TCPConnector(resolver=resolver)

    async with aiohttp.ClientSession(connector=conn) as session:
        inst_url = 'https://api.invidious.io/instances.json'
        async with session.get(inst_url) as resp:
            json = await resp.json()
            print(json)
```

### Expected behavior

The content of https://api.invidious.io/instances.json

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
  File "/path/to/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 970, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 507, in _sock_connect
    sock.connect(address)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "<stdin>", line 6, in main
  File "/path/to/venv/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/path/to/venv/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/path/to/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/path/to/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 893, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/path/to/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1052, in _create_direct_connection
    raise last_exc
  File "/path/to/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1021, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/path/to/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 976, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.invidious.io:443 ssl:default [Network is unreachable]
```

### Python Version

```console
(venv) $ python --version
Python 3.9.6
```

### aiohttp Version

```console
(venv) $ python -m pip show aiohttp
Name: aiohttp
Version: 3.7.4.post0
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: /path/to/venv/lib/python3.9/site-packages
Requires: typing-extensions, yarl, attrs, async-timeout, chardet, multidict
Required-by:
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 5.1.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /path/to/venv/lib/python3.9/site-packages
Requires: 
Required-by: yarl, aiohttp
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.6.3
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /path/to/venv/lib/python3.9/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

Distribution: Arch Linux
```
$ uname -srmo
Linux 5.12.19-hardened1-1-hardened x86_64 GNU/Linux
```

### Related component

Client

### Additional context

Virtual environment

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by anesabml** [comment]
`TCPConnector` process both IPv4 and IPv6 since this [PR](https://github.com/aio-libs/aiohttp/pull/561), the issue you are facing probably is due to not having an IPv6 route set up yet, a quick fix is to tell TCPConnector to only process IPv4 by specifying the address family `AF_INET` when constructing TCPConnector: `aiohttp.TCPConnector(resolver=resolver, family=socket.AF_INET)`

**Comment by Dreamsorcerer** [comment]
Yes, I was able to reproduce this on my machine. aiodns is returning an IPv6 address, if I replaced this with an IPv4 address, it worked fine.

**Comment by ghost** [comment]
> a quick fix is to tell TCPConnector to only process IPv4

Yes, it's working now. Thanks. It seems like that IPv6 is preferred more than IPv4. Will this behavior be changed in future?

**Comment by Dreamsorcerer** [comment]
Or alternatively, can we autodetect if IPv6 is not supported and fallback to IPv4 without needing the user to workaround the problem?
