### ISSUE TITLE
wsgi not supported

### ISSUE THREAD

**Issue by pylover** [aio-libs/aiohttp#604]
As the document says: 

```
from aiohttp import web

def index(request):
    return web.Response(text="Welcome home!")

my_web_app = web.Application()
my_web_app.router.add_route('GET', '/', index)
```

the WSGI application is not interfaced correctly:

```
gunicorn example:app


Traceback (most recent call last):
  File "/home/vahid/.virtualenvs/falcon/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/vahid/.virtualenvs/falcon/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 171, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() takes 1 positional argument but 3 were given
```

**Comment by pylover** [comment]
My bad , i forget to add `--worker-class aiohttp.worker.GunicornWebWorker` .

Sorry
