### ISSUE TITLE
Gzipped 204 responses raises ContentEncodingError

### ISSUE THREAD

**Issue by C4ptainCrunch** [aio-libs/aiohttp#609]
When querying an HTTP endpoint that returns a 204 with a `content-encoding: gzip`, aiohttp raises a `aiohttp.errors.ContentEncodingError: 400, message='deflate'`.
(Note that aiohttp claims it's a error 400 but the server sends a 204 : `127.0.0.1 - - [30/Oct/2015 13:01:37] "POST / HTTP/1.1" 204 -`)

I made a small repo with a minimal example : https://github.com/C4ptainCrunch/aiohttp-204-gzip-bug

Here is the full stacktrace : 

```
content-encoding: gzip

Traceback (most recent call last):
  File "client.py", line 14, in <module>
    fetch(url)
  File "/usr/lib64/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib64/python3.4/asyncio/tasks.py", line 236, in _step
    result = coro.send(value)
  File "client.py", line 11, in fetch
    return (yield from response.release())
  File "/home/C4/sandbox/aiohttp/ve3/lib64/python3.4/site-packages/aiohttp/client_reqrep.py", line 648, in release
    chunk = yield from content.readany()
  File "/home/C4/sandbox/aiohttp/ve3/lib64/python3.4/site-packages/aiohttp/streams.py", line 472, in wrapper
    result = yield from func(self, *args, **kw)
  File "/home/C4/sandbox/aiohttp/ve3/lib64/python3.4/site-packages/aiohttp/streams.py", line 535, in readany
    return (yield from super().readany())
  File "/home/C4/sandbox/aiohttp/ve3/lib64/python3.4/site-packages/aiohttp/streams.py", line 265, in readany
    raise self._exception
  File "/home/C4/sandbox/aiohttp/ve3/lib64/python3.4/site-packages/aiohttp/parsers.py", line 181, in set_parser
    next(p)
  File "/home/C4/sandbox/aiohttp/ve3/lib64/python3.4/site-packages/aiohttp/protocol.py", line 312, in __call__
    out.feed_eof()
  File "/home/C4/sandbox/aiohttp/ve3/lib64/python3.4/site-packages/aiohttp/protocol.py", line 386, in feed_eof
    raise errors.ContentEncodingError('deflate')
aiohttp.errors.ContentEncodingError: 400, message='deflate'
```

**Comment by kxepal** [comment]
Looks familiar https://github.com/KeepSafe/aiohttp/pull/154

**Comment by carlcarl** [comment]
What the expected result should be?

**Comment by C4ptainCrunch** [comment]
It should a least not declare an error 400 (it's not a "Bad request").
I think it should also not fail because of an empty response (especially with a 204 code)

Edit: Requests does not fail and returns a normal response object with an empty body

``` python
In [1]: import requests
In [2]: response = requests.post('http://localhost:5000')
In [3]: response
Out[3]: <Response [204]>
In [4]: response.text
Out[4]: u''
```

**Comment by asvetlov** [comment]
204 with body is forbidden combination from my perspective.
I have no clean idea what to do with malformed server response but perhaps we don't want to process it.

**Comment by C4ptainCrunch** [comment]
I think you misunderstood, in my example, there _is no_ body, the response seems well-formed :)

**Comment by C4ptainCrunch** [comment]
Any updates on this ?

**Comment by mark-rushakoff** [comment]
I just ran into this same problem with aiohttp version 0.21.6 (and filed an upstream bug at https://github.com/influxdata/influxdb/issues/6624).

In my use case, I'm expecting the 204 up front, and if I don't get a 204, I don't mind if the response is not compressed – so I can set the header `Accept-Encoding: identity` and aiohttp does not crash.

FWIW there is precedent for the client to gracefully accept a 204 with `Content-Encoding: gzip` in https://github.com/visionmedia/superagent/pull/898.

**Comment by khazhyk** [comment]
Ditto, any empty response causes `release()` to raise if the content-encoding is gzip. This causes all HEAD requests to raise if the content encoding is gzip, which is quite annoying.

**Comment by khazhyk** [comment]
Using the latest `master` code, I no longer get this error when using HEAD, fwiw.

**Comment by fafhrd91** [comment]
fixed in master
