### ISSUE TITLE
Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8

### ISSUE THREAD

**Issue by InvalidAccount69** [aio-libs/aiohttp#6735]
### Describe the bug

Trying Get Json Data

### To Reproduce

` async with aiohttp.ClientSession() as session:
        async with session.get(f"https://loader.to/ajax/download.php?format={str(Quality)}&url={str(YoutubeLink)}", data=data) as req:
            await aprint(await req.json())
`
and getting this error:

### Expected behavior

...

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\Desk\Coding\Tools\YoutubeDownloader.py", line 72, in <module>
    asyncio.run(main())
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\admin\Desktop\Desk\Coding\Tools\YoutubeDownloader.py", line 46, in main
    await aprint(await req.json())
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://loader.to/ajax/download.php?format=720&url=https://www.youtube.com/watch?v=PcGwSgok3D0')
```

### Python Version

```console
$ python --version
Python 3.9.6
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.1
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author:
Author-email:
License: Apache 2
Location: c:\users\admin\appdata\local\programs\python\python39\lib\site-packages
Requires: aiosignal, async-timeout, attrs, charset-normalizer, frozenlist, multidict, yarl
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 5.2.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: c:\users\admin\appdata\local\programs\python\python39\lib\site-packages
Requires:
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.7.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: c:\users\admin\appdata\local\programs\python\python39\lib\site-packages
Requires: idna, multidict
```

### OS

Windows

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
The server is obviously incorrect, as the error says it is sending a content-type of text/html.
You can customise the check with content_type: https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientResponse.json
