### ISSUE TITLE
Some exceptions are not raised in the correct stack

### ISSUE THREAD

**Issue by Insoleet** [aio-libs/aiohttp#674]
Hello,

Following an issue opened on quamash, but maybe this is more about aiohttp : 
https://github.com/harvimt/quamash/issues/42

I'm having troubles with my application, sakia. When connection is lost (wifi down or mobile network for example), some gaierrors are raised but not catched by aiohttp nor by my application , thus crashing the application : 

```
DEBUG:main:Exception handler executing
ERROR:main:Future exception was never retrieved
future: <Future finished exception=gaierror(-2, 'Name or service unknown')>
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/quamash/__init__.py", line 89, in run
    r = callback(*args, **kwargs)
  File "/usr/lib/python3.4/socket.py", line 533, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service unknown
```

I mocked `socket.getaddrinfo` to be able to test a bad connection ( https://gist.github.com/Insoleet/7f9bec7fa6e66590bf3b )

At first, I thought it was because of the `run_in_executor`, so with some analysis, thanks to @harvimt , I created a custom synchronized getaddrinfo in the event loop :  

``` python
def getaddrinfo(self, host, port, *, family=0, type=0, proto=0, flags=0):
    future = asyncio.Future()
    try:
        if self._debug:
            result = self._getaddrinfo_debug(host, port, family, type, proto, flags) 
        else:
            result = socket.getaddrinfo(host, port, family, type, proto, flags)
        future.set_result(result) 
    except Exception as e: 
        future.set_exception(result) 
return future
```

The exception is still raised outside my application stack, and I get the following stacktrace : 

```
DEBUG:main:async_exception_handler:Exception handler executing
ERROR:main:async_exception_handler:Task exception was never retrieved
future: <Task finished coro=<__iter__() done, defined at /home/inso/.pyenv/versions/cutecoin/lib/python3.4/site-packages/aiohttp/client.py:454> exception=ClientOSError(None, 'Cannot connect to host moul.re:8999 ssl:False [Can not connect to moul.re:8999 [None]]')>
Traceback (most recent call last):
  File "/home/inso/.pyenv/versions/cutecoin/lib/python3.4/site-packages/aiohttp/connector.py", line 557, in _create_connection
    server_hostname=hinfo['hostname'] if sslcontext else None)
  File "/home/inso/.pyenv/versions/3.4.3/lib/python3.4/asyncio/base_events.py", line 581, in create_connection
    infos = f1.result()
  File "/home/inso/.pyenv/versions/3.4.3/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/home/inso/code/quamash/quamash/__init__.py", line 482, in getaddrinfo
    result = socket.getaddrinfo(host, port, family, type, proto, flags)
socket.gaierror: [Errno -2] Nom ou service inconnu

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/inso/.pyenv/versions/cutecoin/lib/python3.4/site-packages/aiohttp/connector.py", line 289, in connect
    transport, proto = yield from self._create_connection(req)
  File "/home/inso/.pyenv/versions/cutecoin/lib/python3.4/site-packages/aiohttp/connector.py", line 580, in _create_connection
    (req.host, req.port, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno None] Can not connect to moul.re:8999 [None]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/inso/.pyenv/versions/3.4.3/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/home/inso/.pyenv/versions/cutecoin/lib/python3.4/site-packages/aiohttp/client.py", line 456, in __iter__
    resp = yield from self._coro
  File "/home/inso/.pyenv/versions/cutecoin/lib/python3.4/site-packages/aiohttp/client.py", line 173, in _request
    conn = yield from self._connector.connect(req)
  File "/home/inso/.pyenv/versions/cutecoin/lib/python3.4/site-packages/aiohttp/connector.py", line 299, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno None] Cannot connect to host moul.re:8999 ssl:False [Can not connect to moul.re:8999 [None]]
```

I need some help to push the analysis further.

**Comment by moden-py** [comment]
Also see the same problem with Celery workers time to time.

``` code
[2016-02-17 10:51:58,498: WARNING/Worker-8] http://votb.org/wordpress1/comments/feed/
[2016-02-17 10:51:58,499: ERROR/Worker-8] Future exception was never retrieved
future: <Future finished exception=gaierror(-2, 'Name or service not known')>
Traceback (most recent call last):
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.4/socket.py", line 533, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

My usage example:

``` code
with aiohttp.ClientSession(loop=loop) as session:
        with aiohttp.Timeout(timeout):
            try:
                response = yield from session.get(url,
                                                  allow_redirects=False,
                                                  max_redirects=1)
                text = yield from response.text()
            except:
                pass
            else:
                return text
            finally:
                if response is not None:
                    response.close()
```

Expect all the request exceptions will be handled.

**Comment by ivan-is** [comment]
got  the same problem:

```


 with aiohttp.ClientSession(loop=loop) as session:
                response = None
                with aiohttp.Timeout(CONNECTION_TIMEOUT):
                    try:
                        response = yield from session.get(url,
                                                          headers=HEADERS,
                                                          allow_redirects=REDIRECTS,
                                                          max_redirects=MAX_REDIRECTS)
                    except Exception as e:
                        pass

                with aiohttp.Timeout(READ_TIMEOUT):
                    if response:
                        try:
                            text = yield from response.read()
                        except asyncio.TimeoutError:
                            pass
                        except Exception as e:
                            pass
                        else:
                            RESULTS.append(text)
                        finally:
                            if response is not None:
                                response.close()

```

**Comment by asvetlov** [comment]
I recommend to catch `OSError` too
