### ISSUE TITLE
Websockets in variables

### ISSUE THREAD

**Issue by Insoleet** [aio-libs/aiohttp#753]
Hello,

I'm trying to run the following : 

``` python

async def connect():
    the_ws = aiohttp.ws_connect('ws://metab.ucoin.io:9201/ws/block')
    async with the_ws:

        async for msg in the_ws:
            if msg.tp == aiohttp.MsgType.text:
                print(msg.data)
            elif msg.tp == aiohttp.MsgType.closed:
                break
            elif msg.tp == aiohttp.MsgType.error:
                break
```

It fails with the following error : 

```
Traceback (most recent call last):
  File "/home/inso/code/ucoin/sakia/test.py", line 22, in <module>
    loop.run_until_complete(connect())
  File "/home/inso/.pyenv/versions/sakia-env/lib/python3.5/site-packages/quamash/__init__.py", line 243, in run_until_complete
    return future.result()
  File "/home/inso/.pyenv/versions/3.5.0/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/inso/.pyenv/versions/3.5.0/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/home/inso/code/ucoin/sakia/test.py", line 10, in connect
    async for msg in the_ws:
TypeError: 'async for' requires an object with __aiter__ method, got _DetachedWSRequestContextManager
```

Is it a bug or am I supposed to do it differently ?

**Comment by Insoleet** [comment]
Oh, sorry, I found my mistake. The correct code should be the following : 

``` python
async def connect():
    the_ws = aiohttp.ws_connect('ws://metab.ucoin.io:9201/ws/block')
    async with the_ws as ws:

        async for msg in ws:
            if msg.tp == aiohttp.MsgType.text:
                print(msg.data)
            elif msg.tp == aiohttp.MsgType.closed:
                break
            elif msg.tp == aiohttp.MsgType.error:
                break
```
