### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by ecerulm** [aio-libs/aiohttp#764]
I have script that continuously fetches an URL. After a couple of thousand request it starts failing with "too many open files".

```
 async def get_report(self):
  with aiohttp.Timeout(3):
    async with aiohttp.get(URL) as resp:
      content = await rest.text()
      resp.close()
   return content
```

Am I doing something wrong? or is it leaking file descriptors?

**Comment by ecerulm** [comment]
The traceback
Traceback (most recent call last):

```
  File "/home/ecerulm/.pyenv/versions/tm500ws/lib/python3.5/site-packages/aiohttp/connector.py", line 310, in connect
  File "/home/ecerulm/.pyenv/versions/tm500ws/lib/python3.5/site-packages/aiohttp/connector.py", line 604, in _create_connection
aiohttp.errors.ClientOSError: [Errno 24] Can not connect to 10.68.83.112:5002 [Too many open files]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "xxxxxx.py", line 128, in send_report
  File "xxxxxx.py", line 214, in get_report
  File "/home/ecerulm/.pyenv/versions/tm500ws/lib/python3.5/site-packages/aiohttp/client.py", line 538, in __aenter__
  File "/home/ecerulm/.pyenv/versions/tm500ws/lib/python3.5/site-packages/aiohttp/client.py", line 183, in _request
  File "/home/ecerulm/.pyenv/versions/tm500ws/lib/python3.5/site-packages/aiohttp/connector.py", line 320, in connect
aiohttp.errors.ClientOSError: [Errno 24] Cannot connect to host 10.68.83.112:5002 ssl:False [Can not connect to 10.68.83.112:5002 [Too many open files]]
```

**Comment by ecerulm** [comment]
Nevermind the files descriptors are leaked in another part of the script unrelated with aiohttp is just that is always aiohttp the one that notices it.
