### ISSUE TITLE
AsyncStreamReaderMixin conditional methods

### ISSUE THREAD

**Issue by jashandeep-sohi** [aio-libs/aiohttp#772]
Do the methods defined in `AsyncStreamReaderMixin` have to be dependent on having Python 3.5? That is, is [this](https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/streams.py#L46) `if` statement necessary?

Considering none of the methods are using the `async/await` syntax, I think having them in Python 3.4 would be fine. Obviously you couldn't use them in 3.4.

Removing the `if` statement should fix the errors when generating docs w/ Python 3.4.

**Comment by asvetlov** [comment]
These methods doesn't make sense in 3.4, that's why `if` statement exists.
Removing it is interesting question: what's more important -- python code correctness or doc warnings?
I'm inclining to don't change python code right now.

**Comment by jashandeep-sohi** [comment]
Yeah, it doesn't make much sense, but it doesn't hurt either. You might also have to add it in other places. i.e. [here](https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/streams.py#L29)

**Comment by rutsky** [comment]
Why Sphinx tries to access these attributes?

Here is an error that occur in my environment:

```
/home/bob/stuff/aio/aiohttp/docs/api.rst:29: WARNING: autodoc: failed to import method 'AsyncStreamReaderMixin.iter_chunked' from module 'aiohttp.streams'; the following exception was raised:
Traceback (most recent call last):
  File "/home/bob/stuff/aio/aiohttp_cors/env/lib/python3.4/site-packages/sphinx/util/inspect.py", line 109, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: type object 'AsyncStreamReaderMixin' has no attribute 'iter_chunked'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bob/stuff/aio/aiohttp_cors/env/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 392, in import_object
    obj = self.get_attr(obj, part)
  File "/home/bob/stuff/aio/aiohttp_cors/env/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 288, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/home/bob/stuff/aio/aiohttp_cors/env/lib/python3.4/site-packages/sphinx/util/inspect.py", line 115, in safe_getattr
    raise AttributeError(name)
AttributeError: iter_chunked
/home/bob/stuff/aio/aiohttp/docs/api.rst:30: WARNING: autodoc: failed to import method 'AsyncStreamReaderMixin.iter_any' from module 'aiohttp.streams'; the following exception was raised:
Traceback (most recent call last):
  File "/home/bob/stuff/aio/aiohttp_cors/env/lib/python3.4/site-packages/sphinx/util/inspect.py", line 109, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: type object 'AsyncStreamReaderMixin' has no attribute 'iter_any'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bob/stuff/aio/aiohttp_cors/env/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 392, in import_object
    obj = self.get_attr(obj, part)
  File "/home/bob/stuff/aio/aiohttp_cors/env/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 288, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/home/bob/stuff/aio/aiohttp_cors/env/lib/python3.4/site-packages/sphinx/util/inspect.py", line 115, in safe_getattr
    raise AttributeError(name)
AttributeError: iter_any
```

**Comment by asvetlov** [comment]
autodocs are sucks. Perhaps we need hand-written doc for streams, like we have it for client and server api.

**Comment by jashandeep-sohi** [comment]
@rutsky [Here](https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/streams.py#L79) Sphinx tries to auto generate the docs for those methods.

Getting rid of autodocs might be the best solution. I'll close this for now.
