### ISSUE TITLE
UnicodeEncodeError in BodyPartWriter

### ISSUE THREAD

**Issue by TigorC** [aio-libs/aiohttp#818]
## Long story short

I tried to upload a file with unicode characters inside and it doesn't work.
## Expected behaviour

A file with Unicode characters should be encoded correctly.
## Actual behaviour

Get the encoding error:

```
Traceback (most recent call last):
  File "/home/tigorc/.virtualenvs/aiotest/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 386, in write_bytes
    result = stream.send(value)
  File "/home/tigorc/.virtualenvs/aiotest/lib/python3.5/site-packages/aiohttp/helpers.py", line 147, in _gen_form_data
    part = self._writer.append(value, headers)
  File "/home/tigorc/.virtualenvs/aiotest/lib/python3.5/site-packages/aiohttp/multipart.py", line 911, in append
    self.parts.append(self.part_writer_cls(obj, headers))
  File "/home/tigorc/.virtualenvs/aiotest/lib/python3.5/site-packages/aiohttp/multipart.py", line 653, in __init__
    self._fill_headers_with_defaults()
  File "/home/tigorc/.virtualenvs/aiotest/lib/python3.5/site-packages/aiohttp/multipart.py", line 671, in _fill_headers_with_defaults
    content_length = self._guess_content_length(self.obj)
  File "/home/tigorc/.virtualenvs/aiotest/lib/python3.5/site-packages/aiohttp/multipart.py", line 690, in _guess_content_length
    return len(obj.getvalue().encode(charset)) - obj.tell()
UnicodeEncodeError: 'ascii' codec can't encode character '\u2603' in position 108: ordinal not in range(128)
```
## Steps to reproduce

``` python
from io import StringIO
import asyncio
import aiohttp


@asyncio.coroutine
def test():
    fake_f = StringIO("""
        <html>
            <head>
                <meta charset="utf-8">
                <title>Test Title ☃&#x2603;</title>
            </head>
                <body>foobar</body>
        </html>""")
    fake_f.name = "test.html"
    form_data = aiohttp.helpers.FormData()
    form_data.add_field(fake_f.name, fake_f)
    session = aiohttp.ClientSession()
    try:
        resp = yield from session.post('http://requestb.in/uq9euyuq', data=form_data)
    finally:
        session.close()
    return resp


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    resp = loop.run_until_complete(test())
    resp.close()
    loop.close()
```
## Your environment

Ubuntu 14.04
Python 3.5.1
aiohttp==0.21.2

**Comment by kxepal** [comment]
Two problems here:
1. Default charset per RFC is us-ascii
2. StringIO is a blob of unicode data. On the wire it should be bytes, so we have to encode it into something. 

So you need either explicitly specify content-type like `form_data.add_field(fake_f.name, fake_f, headers={"Content-Type": "text/html;charset=utf-8"})` or provide BytesIO with the correctly encoded bytes sequence. However, you still better pass charset into content type header to avoid any issues on the other side.
