### ISSUE TITLE
Http client HEAD request failed to release

### ISSUE THREAD

**Issue by enzoliao** [aio-libs/aiohttp#852]
My code is as followed:

``` Python
import aiohttp
import asyncio

async def head(url):
    with aiohttp.ClientSession() as session:
        async with session.head(url) as ret:
            print(ret.status)

loop = asyncio.get_event_loop()
loop.run_until_complete(head("https://www.mongodb.org"))
```

What I got is as followed

```
200
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "<stdin>", line 4, in head
  File "/usr/local/lib/python3.5/site-packages/aiohttp/client.py", line 557, in __aexit__
    yield from self._resp.release()
  File "/usr/local/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 668, in release
    chunk = yield from content.readany()
  File "/usr/local/lib/python3.5/site-packages/aiohttp/streams.py", line 485, in wrapper
    result = yield from func(self, *args, **kw)
  File "/usr/local/lib/python3.5/site-packages/aiohttp/streams.py", line 548, in readany
    return (yield from super().readany())
  File "/usr/local/lib/python3.5/site-packages/aiohttp/streams.py", line 278, in readany
    raise self._exception
  File "/usr/local/lib/python3.5/site-packages/aiohttp/parsers.py", line 189, in set_parser
    next(p)
  File "/usr/local/lib/python3.5/site-packages/aiohttp/protocol.py", line 318, in __call__
    out.feed_eof()
  File "/usr/local/lib/python3.5/site-packages/aiohttp/protocol.py", line 392, in feed_eof
    raise errors.ContentEncodingError('deflate')
aiohttp.errors.ContentEncodingError: 400, message='deflate'
```

When I change the url to "https://www.python.org", the error disappear. 
I notice that there is a "Content-Encoding: gzip" in the response header when I request "https://www.mongodb.org", while the response of "https://www.python.org" doesn't have the same header. I guess this is what matters.
Could anybody give me some help on this? Thanks.

PS. I'm using Python 3.5.1, aiohttp 0.21.5.

**Comment by asvetlov** [comment]
Fixed by #758
Will be available in aiohttp 0.22 release.
