### ISSUE TITLE
3.10.0 regression: AttributeError: module 'asyncio.futures' has no attribute 'TimeoutError' with python older than 3.8.2

### ISSUE THREAD

**Issue by homm** [aio-libs/aiohttp#8556]
### Describe the bug

`AttributeError` while connecting.

### To Reproduce

```python
import aiohttp
s = await aiohttp.ClientSession().__aenter__()
await s.get('http://python.org')
```

### Expected behavior

Yes

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
     File "/usr/local/lib/python3.8/dist-packages/aiobotocore/httpsession.py", line 222, in send
       response = await session.request(
     File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 648, in _request
       conn = await self._connector.connect(
     File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 546, in connect
       proto = await self._create_connection(req, traces, timeout)
     File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 954, in _create_connection
       _, proto = await self._create_direct_connection(req, traces, timeout)
     File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 1282, in _create_direct_connection
       transp, proto = await self._wrap_create_connection(
     File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 1036, in _wrap_create_connection
       sock = await aiohappyeyeballs.start_connection(
     File "/usr/local/lib/python3.8/dist-packages/aiohappyeyeballs/impl.py", line 76, in start_connection
       sock, _, _ = await staggered.staggered_race(
     File "/usr/lib/python3.8/asyncio/staggered.py", line 144, in staggered_race
       raise d.exception()
     File "/usr/lib/python3.8/asyncio/staggered.py", line 86, in run_one_coro
       with contextlib.suppress(futures.TimeoutError):
   AttributeError: module 'asyncio.futures' has no attribute 'TimeoutError'
```

### Python Version

```console
$ python --version
Python 3.8.0
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.10.0
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: None
Author-email: None
License: Apache 2
Location: /usr/local/lib/python3.8/dist-packages
Requires: aiosignal, multidict, async-timeout, aiohappyeyeballs, attrs, yarl, frozenlist
Required-by: aiobotocore
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.5
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /usr/local/lib/python3.8/dist-packages
Requires: 
Required-by: yarl, aiohttp
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.9.4
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Location: /usr/local/lib/python3.8/dist-packages
Requires: multidict, idna
Required-by: aiohttp
```

### OS

ubuntu 18.04

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by bdraco** [comment]
This looks like either a bug in cpython 3.8 or you have cpython asyncio replaced with one that isn’t stdlib

**Comment by homm** [comment]
> looks like a bug in cpython 3.8

Is it supported by aiohttp?

> you have cpython asyncio replaced with one that isn’t stdlib

No, I haven't:

```Dockefile
FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install --no-install-recommends -y \
        python3.8 python3-pip
RUN ln -s python3.8 /usr/bin/python
RUN python -m pip install -U pip setuptools
RUN pip install aiohttp==3.10.0 ipython

CMD ipython
```

```
$ docker run --rm -it $(docker build -q .)
```

**Comment by bdraco** [comment]
It looks like it is broken in cpython 3.8 https://github.com/python/cpython/issues/83310

**Comment by bdraco** [comment]
I’m not really sure what to do about this one since it’s python itself that’s broken and it looks like there is no plan to ever fix cpython 3.8

**Comment by bdraco** [comment]
Actually it does look like it was fixed in a later release of cpython 3.8 https://github.com/python/cpython/pull/17693 so the solution is like to upgrade the cpython 3.8 version

**Comment by homm** [comment]
So actual minimal python version is 3.8.2, [not 3.8](https://github.com/aio-libs/aiohttp/blob/master/setup.cfg#L45C1-L45C16). Could you fix it to avoid latest aiohttp installation?

**Comment by homm** [comment]
Dockerfile to test this:

```dockerfile
FROM python:3.8.2-slim

RUN python -m pip install -U pip setuptools
RUN pip install aiohttp==3.10.0 ipython

CMD ipython
```

**Comment by bdraco** [comment]
> So actual minimal python version is 3.8.2, [not 3.8](https://github.com/aio-libs/aiohttp/blob/master/setup.cfg#L45C1-L45C16). Could you fix it to avoid latest aiohttp installation?

We can change it for new versions but since 3.10.0 is already released, it’s too late to change it

**Comment by homm** [comment]
As a solution, `asyncio.futures.TimeoutError` could be monkeypatched:

```python
import asyncio.futures
asyncio.futures.TimeoutError = asyncio.TimeoutError
```
```python
In [4]: import aiohttp
   ...: s = await aiohttp.ClientSession().__aenter__()
   ...: await s.get('http://python.org')
Out[4]: 
<ClientResponse(https://www.python.org/) [200 OK]>
<CIMultiDictProxy('Connection': 'keep-alive', 'Content-Length': '51154', 'Content-Type': 'text/html; charset=utf-8', 'X-Frame-Options': 'SAMEORIGIN', 'Via': '1.1 varnish, 1.1 varnish', 'Accept-Ranges': 'bytes', 'Date': 'Wed, 31 Jul 2024 12:28:25 GMT', 'Age': '1956', 'X-Served-By': 'cache-iad-kiad7000025-IAD, cache-mxp6939-MXP', 'X-Cache': 'HIT, HIT', 'X-Cache-Hits': '39, 4', 'X-Timer': 'S1722428906.943085,VS0,VE0', 'Vary': 'Cookie', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload')>
```
