### ISSUE TITLE
ReferenceError: weakly-referenced object no longer exists

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#86]
@asvetlov could you look at this exception, ClientReponse.**del**?

```
ERROR [asyncio] Exception in default exception handler
Traceback (most recent call last):
 File "/usr/lib/python3.4/asyncio/base_events.py", line 719, in call_exception_handler
   self.default_exception_handler(context)
 File "/usr/lib/python3.4/asyncio/base_events.py", line 696, in default_exception_handler
   log_lines.append('{}: {!r}'.format(key, context[key]))
 File "/usr/lib/python3.4/asyncio/tasks.py", line 164, in __repr__
   res = super().__repr__()
 File "/usr/lib/python3.4/asyncio/futures.py", line 157, in __repr__
   res += '<exception={!r}>'.format(self._exception)
 File "/opt/files/lib/python3.4/site-packages/aiohttp/client.py", line 576, in __repr__
   print(self.headers, file=out)
 File "/opt/files/lib/python3.4/site-packages/aiohttp/multidict.py", line 88, in __repr__
   return '<{} {!r}>'.format(self.__class__.__name__, self._items)
 File "/usr/lib/python3.4/reprlib.py", line 24, in wrapper
   result = user_function(self)
 File "/usr/lib/python3.4/collections/__init__.py", line 198, in __repr__
   return '%s(%r)' % (self.__class__.__name__, list(self.items()))
 File "/usr/lib/python3.4/_collections_abc.py", line 484, in __iter__
   for key in self._mapping:
 File "/usr/lib/python3.4/collections/__init__.py", line 87, in __iter__
   curr = root.next
ReferenceError: weakly-referenced object no longer exists
```

**Comment by fafhrd91** [comment]
seems problem is resolved with new asyncio

**Comment by asvetlov** [comment]
Sounds good
