### ISSUE TITLE
weighttp benchmark fail - OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by walkr** [aio-libs/aiohttp#860]
## Long story short

aiohttp fails when benchmarking with `weighttp`

``` python
  File "/Users/walkr/.virtualenvs/main3/lib/python3.5/site-packages/aiohttp/parsers.py", line 256, in set_tcp_nodelay
    self._socket.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, value)
OSError: [Errno 22] Invalid argument
```
## Actual behavior

It should not fail
## Steps to reproduce

I'm benchmarking the following code:

``` python
from aiohttp import web


async def handle(request):
    name = request.match_info.get('name', "Anonymous")
    text = "Hello, " + name
    return web.Response(body=text.encode('utf-8'))


app = web.Application()
app.router.add_route('GET', '/{name}', handle)

web.run_app(app)
```

Then while benchmarking it with `weighttp`

``` shell
$ weighttp -t 2 -c 10 -n 1000 localhost:8080/name
```

... I get the following error:

``` python
Error handling request
Traceback (most recent call last):
  File "/Users/walkr/.virtualenvs/main3/lib/python3.5/site-packages/aiohttp/server.py", line 266, in start
    yield from self.handle_request(message, payload)
  File "/Users/walkr/.virtualenvs/main3/lib/python3.5/site-packages/aiohttp/web.py", line 100, in handle_request
    yield from resp.write_eof()
  File "/Users/walkr/.virtualenvs/main3/lib/python3.5/site-packages/aiohttp/web_reqrep.py", line 857, in write_eof
    self.set_tcp_nodelay(True)
  File "/Users/walkr/.virtualenvs/main3/lib/python3.5/site-packages/aiohttp/web_reqrep.py", line 624, in set_tcp_nodelay
    self._resp_impl.transport.set_tcp_nodelay(value)
  File "/Users/walkr/.virtualenvs/main3/lib/python3.5/site-packages/aiohttp/parsers.py", line 256, in set_tcp_nodelay
    self._socket.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, value)
OSError: [Errno 22] Invalid argument
```

Any thoughts?
## Your environment

Python: 3.5
Platform: OS X El Capitan

**Comment by asvetlov** [comment]
Wow! I believe MacOSX has `TCP_NODELAY` support.
Could you run the following snippet?

```
import socket
s = socket.socket()
s.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, True)
s.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, False)
```

**Comment by walkr** [comment]
No errors when I run the code.

**Comment by sseg** [comment]
I'm not able to reproduce this on either OSX 10.10.5 or 10.11.5.

**Comment by mpeg** [comment]
@asvetlov @sseg 

I'm seeing the same issue with a similar repro, on OSX 10.10.5 and Python 3.5

I can see errors even if I run the benchmarks as:

`weighttp -k -t 1 -c 1 -n 10 localhost:8080/`

It's more intermittent than when I'm doing more requests / higher concurrency, but I still get lots of errors on average

It seems when the `setsockopt` call fails the raddr of the socket is not set, and trying to call `socket.getpeername()` on that socket also results in `OSError: [Errno 22] Invalid Argument`

Also, if I use wrk instead of weighttp I don't get any errors on a concurrency of 1, but as I increase concurrency I get n-1 errors at the end of a run, for instance:

`wrk -t1 -c7 -d3s http://localhost:8080/`

would give me exactly 6 OSError exceptions at the end of the 3 seconds run, or however long I make it

I'm not familiar enough with UNIX sockets but I'll see if I can diagnose it better

**Comment by IlyaSemenov** [comment]
@asvetlov I concur the problem. I ran the same app on two different Macs with OS X 10.10.5 and 10.11.5 in a fresh virtualenv with Homebrewed Python 3.5.1 (only adjusted the port to 8889) and benchmarked it with `wrk`.

It stopped to reproduce on 10.11.5 after a while, but it never stopped on 10.10.5.

### OS X 10.11.5

``` console
$ uname -a
Darwin daedra15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64 i386 MacBookPro12,1 Darwin
$ wrk -t1 -c7 -d3s http://localhost:8889/name
Running 3s test @ http://localhost:8889/name
  1 threads and 7 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.37ms    1.17ms  19.11ms   94.64%
    Req/Sec     2.12k   295.00     2.34k    90.32%
  6550 requests in 3.10s, 780.48KB read
Requests/sec:   2112.34
Transfer/sec:    251.70KB
```

``` console
$ python3 app.py
======== Running on http://127.0.0.1:8889/ ========
(Press CTRL+C to quit)
Error handling request
Traceback (most recent call last):
  File "/Users/semenov/work/socketerr/lib/python3.5/site-packages/aiohttp/server.py", line 266, in start
    yield from self.handle_request(message, payload)
  File "/Users/semenov/work/socketerr/lib/python3.5/site-packages/aiohttp/web.py", line 100, in handle_request
    yield from resp.write_eof()
  File "/Users/semenov/work/socketerr/lib/python3.5/site-packages/aiohttp/web_reqrep.py", line 857, in write_eof
    self.set_tcp_nodelay(True)
  File "/Users/semenov/work/socketerr/lib/python3.5/site-packages/aiohttp/web_reqrep.py", line 624, in set_tcp_nodelay
    self._resp_impl.transport.set_tcp_nodelay(value)
  File "/Users/semenov/work/socketerr/lib/python3.5/site-packages/aiohttp/parsers.py", line 256, in set_tcp_nodelay
    self._socket.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, value)
OSError: [Errno 22] Invalid argument
Error handling request
```

(the error repeated two times)

### OS X 10.10.5

``` console
$ uname -a
Darwin eerie 14.5.0 Darwin Kernel Version 14.5.0: Mon Jan 11 18:48:35 PST 2016; root:xnu-2782.50.2~1/RELEASE_X86_64 x86_64
$ wrk -t1 -c7 -d3s http://localhost:8889/
Running 3s test @ http://localhost:8889/
  1 threads and 7 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.40ms    0.88ms  15.03ms   96.30%
    Req/Sec     1.60k    98.95     1.69k    90.32%
  4944 requests in 3.10s, 835.42KB read
  Non-2xx or 3xx responses: 4944
Requests/sec:   1594.70
Transfer/sec:    269.47KB
```

``` console
$ python3 app.py
======== Running on http://127.0.0.1:8889/ ========
(Press CTRL+C to quit)
Error handling request
Traceback (most recent call last):
  File "/Users/vadim/socketerr/lib/python3.5/site-packages/aiohttp/server.py", line 266, in start
    yield from self.handle_request(message, payload)
  File "/Users/vadim/socketerr/lib/python3.5/site-packages/aiohttp/web.py", line 100, in handle_request
    yield from resp.write_eof()
  File "/Users/vadim/socketerr/lib/python3.5/site-packages/aiohttp/web_reqrep.py", line 857, in write_eof
    self.set_tcp_nodelay(True)
  File "/Users/vadim/socketerr/lib/python3.5/site-packages/aiohttp/web_reqrep.py", line 624, in set_tcp_nodelay
    self._resp_impl.transport.set_tcp_nodelay(value)
  File "/Users/vadim/socketerr/lib/python3.5/site-packages/aiohttp/parsers.py", line 256, in set_tcp_nodelay
    self._socket.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, value)
OSError: [Errno 22] Invalid argument
```

(the error repeated 4 times)

#### Another more rare error on OS X 10.10.5

I got this a few times on 10.10.5:

``` console
======== Running on http://127.0.0.1:8889/ ========
(Press CTRL+C to quit)
Fatal write error on socket transport
protocol: <RequestHandler GET:/ connected>
transport: <_SelectorSocketTransport fd=13 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/selector_events.py", line 702, in write
    n = self._sock.send(data)
OSError: [Errno 41] Protocol wrong type for socket
```

which then was followed by the above "Invalid argument" errors.

**Comment by IlyaSemenov** [comment]
On my 10.10.5 it even happens in non-benchmark use, simply when the browser loads page images via `router.add_static`

**Comment by IlyaSemenov** [comment]
Interestingly enough, when I benchmark 10.10.5 from different computers (Macs and Linuxes), it never spits a single error, even though the load is similar (>1K req/s).

**Comment by IlyaSemenov** [comment]
## Monkey patch for whoever needs it

``` python
from aiohttp.web_reqrep import StreamResponse
StreamResponse.set_tcp_nodelay = lambda self, value: None
```

This consistently removed all benchmarking errors on my Macs without degrading performance (actually performance even slightly increased).

Sorry for spamming, guys, that would be it.
