### ISSUE TITLE
Empty CancelledError while parsing request body (question)

### ISSUE THREAD

**Issue by tumb1er** [aio-libs/aiohttp#918]
I have periodically troubles with `CancelledError(args=())` while parsing multipart/form-data request.
python3.4, aiohttp=0.21.0, under gunicorn==0.19.3
After collecting some statistics, this view issues several errors:
- ClientDisconnectedError (bad http connection) (80%)
- errors with duplicate requests (browsers re-send POST requests if got no response from server in a minute) (10%)
- this CancelledError, and a reason for it is unknown. (10%)

``` python
Traceback (most recent call last):
  File "/data/uploader-13.2.0-01/uploader/views.py", line 207, in post
    **kwargs)
  File "/data/uploader-13.2.0-01/uploader/views.py", line 161, in _process_post_request
    fields, files = yield from self.parser.parse_payload()
  File "/data/uploader-13.2.0-01/uploader/parser.py", line 75, in parse_payload
    buffer = yield from field.read_chunk()
  File "/data/uploader/virtualenv/lib/python3.4/site-packages/aiohttp/multipart.py", line 273, in read_chunk
    chunk = yield from self._read_chunk_from_stream(size)
  File "/data/uploader/virtualenv/lib/python3.4/site-packages/aiohttp/multipart.py", line 313, in _read_chunk_from_stream
    chunk = yield from self._content.read(size)
  File "/data/uploader/virtualenv/lib/python3.4/site-packages/aiohttp/streams.py", line 485, in wrapper
    result = yield from func(self, *args, **kw)
  File "/data/uploader/virtualenv/lib/python3.4/site-packages/aiohttp/streams.py", line 540, in read
    return (yield from super().read(n))
  File "/data/uploader/virtualenv/lib/python3.4/site-packages/aiohttp/streams.py", line 269, in read
    yield from self._waiter
  File "/data/uploader/virtualenv/lib/python3.4/site-packages/asyncio/futures.py", line 348, in __iter__
    yield self  # This tells Task to wait for completion.
concurrent.futures._base.CancelledError
```

Process is alive and serving after this error.

Is it possible to diagnose and eliminate the reason of this error? Or may be somebody solved it already?

Thanks for any suggestions.

**Comment by asvetlov** [comment]
I believe in your case `CancelledError` is synonym for `ClientDisconnectedError`

**Comment by tumb1er** [comment]
Thank you for reply. Looks like a bug somewhere in aio*, but I'll handle it like a disconnected error.
