### ISSUE TITLE
Error: reserved fields must be empty 

### ISSUE THREAD

**Issue by vladyslav2** [aio-libs/aiohttp#923]
## Error: reserved fields must be empty

Not sure, if that a bug, but maybe my report will help you
I was looking for async solution on python found you and decide to make some quick tests.
By quick googling if found that chat solution base on aiohttp https://github.com/intellilab/chat
Looks like pretty simple and good solution.

Since past few years i was using nodejs i used 10 lines js script for generate 1000 users online in one char room, here is a script:

```
var WebSocket = require('ws' );


for(var i = 0; i < 1000; i ++) {
    (function(i) {
        var ws = new WebSocket('ws://localhost:2222/chat.ws');
            ws.on('open', function open() {
                    //this.send(JSON.stringify({ type: 'init', data: {back: 0, nick: 'Name' + i}}));
                    //this.send(JSON.stringify({ type: 'message', data: "hello " + i}));
            }).
            on('message', function(data, flags) {
                //console.log('new message ', data, flags);
            }).
            on('error', function(error, data) {
                console.log('err ', error, data);
            }).
            on('close', function(err, d) {
                console.log('close connection', err, d);
            })
    })(i);
};
```

After 100 iteration i got bunch of errors. It looks like there is a bug somewhere in a system when aiohttp send not the correct information (but again i'm not sure)

```
Error: reserved fields must be empty
    at Receiver.error (/Users/admin/projects/pchat/node_modules/ws/lib/Receiver.js:322:18)
    at Receiver.processPacket (/Users/admin/projects/pchat/node_modules/ws/lib/Receiver.js:204:12)
    at Receiver.add (/Users/admin/projects/pchat/node_modules/ws/lib/Receiver.js:103:24)
    at realHandler (/Users/admin/projects/pchat/node_modules/ws/lib/WebSocket.js:825:20)
    at firstHandler (/Users/admin/projects/pchat/node_modules/ws/lib/WebSocket.js:815:7)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9) undefined
```

For websocket i'm using protocolVersion: 13
For a few days i tried to resolve issue by myself but looks like problem somewhere deeper.

**Comment by asvetlov** [comment]
Cannot reproduce
